<?php

declare(strict_types=1);

use Carbon\CarbonImmutable;
use Fisharebest\Webtrees\I18N;

/**
 * @var CarbonImmutable $timestamp
 */
?>

<?php if ($timestamp->getTimestamp() === 0) : ?>
    <span class="wt-timestamp">
        <?= I18N::translate('Never') ?>
    </span>
<?php else : ?>
    <span class="wt-timestamp" title="<?= e($timestamp->diffForHumans()) ?>" dir="auto">
        <?= e($timestamp->isoFormat('LLLL')) ?>
    </span>
<?php endif ?>
