<?php

use Fisharebest\Webtrees\Carbon;
use Fisharebest\Webtrees\I18N;

/** @var Carbon $timestamp */
?>

<?php if ($timestamp->unix() === 0) : ?>
    <span class="wt-timestamp">
        <?= I18N::translate('Never') ?>
    </span>
<?php else : ?>
    <span class="wt-timestamp" title="<?= e($timestamp->local()->diffForHumans()) ?>" dir="auto">
        <?= e($timestamp->local()->isoFormat('LLLL')) ?>
    </span>
<?php endif ?>
