<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var float $progress
 */

?>

<div class="progress">
    <div
    class="progress-bar"
    role="progressbar"
    aria-valuenow="<?= $progress * 100 ?>"
    aria-valuemin="0"
    aria-valuemax="100"
    style="width: <?= $progress * 100 ?>%; min-width: 2.5rem;"
    >
        <?= I18N::percentage($progress, 1) ?>
    </div>
</div>
