<?php

/**
 * @var bool|null   $checked
 * @var bool|null   $disabled
 * @var string|null $id
 * @var string      $label
 * @var string      $name
 * @var string      $value
 */

?>

<div class="form-check">
    <input type="radio" class="form-check-input"
        name="<?= e($name) ?>"
        id="<?= e($id ?? $name . '-' . $value) ?>"
        value="<?= e($value) ?>"
        <?= $checked ?? false ? 'checked' : '' ?>
        <?= $disabled ?? false ? 'disabled' : '' ?>
    >
    <label class="form-check-label" for="<?= e($id ?? $name . '-' . $value) ?>">
        <?= $label ?>
    </label>
</div>
