<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\TomSelectLocation;
use Fisharebest\Webtrees\Location;
use Fisharebest\Webtrees\Tree;

/**
 * @var string        $at "@" or "" (or unset).
 * @var Location|null $location
 * @var string|null   $class
 * @var string|null   $id
 * @var string        $name
 * @var Tree          $tree
 */

$at = $at ?? '';

?>

<select
    autocomplete="off"
    class="form-select tom-select <?= $class ?? '' ?>"
    data-url="<?= e(route(TomSelectLocation::class, ['tree' => $tree->name(), 'at' => $at])) ?>"
    id="<?= e($id ?? $name) ?>"
    name="<?= e($name) ?>"
    <?= ($disabled ?? false) ? 'disabled="disabled"' : '' ?>
    <?= ($required ?? false) ? 'required="required"' : '' ?>
>
    <?php if (($location ?? null) instanceof Location) : ?>
        <option value="<?= e($at . $location->xref() . $at) ?>">
            <?= view('selects/location', ['location' => $location]) ?>
        </option>
    <?php else : ?>
        <option value="">&nbsp;</option>
    <?php endif ?>
</select>
