<?php

declare(strict_types=1);

/**
 * @var string|null             $class
 * @var string|null             $id
 * @var string                  $name
 * @var \BackedEnum|array-key|array<string> $selected
 * @var array<string>           $options
 * @var string|null             $aria_label
 */

$selected_value = $selected instanceof BackedEnum ? $selected->value : $selected;

?>

<select
    class="form-select <?= $class ?? '' ?>"
    name="<?= e($name) ?>"
    id="<?= e($id ?? $name) ?>"
    <?= is_array($selected_value) ? 'multiple="multiple"' : '' ?>
    aria-label="<?= e($aria_label ?? '') ?>"

>
    <?php foreach ($options as $key => $value) : ?>
        <option value="<?= e((string) $key) ?>"<?= (is_array($selected_value) ? in_array((string) $key, $selected_value, true) : (string) $key === (string) $selected_value) ?  ' selected="selected"' : '' ?>>
            <?= $value === '' ? '&nbsp;' : e($value) ?>
        </option>
    <?php endforeach ?>
</select>
