<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\TomSelectPlace;
use Fisharebest\Webtrees\Place;
use Fisharebest\Webtrees\Tree;

/**
 * @var Place|null  $place
 * @var string|null $class
 * @var string|null $id
 * @var string      $name
 * @var Tree        $tree
 */

?>

<select
    autocomplete="off"
    class="form-select tom-select <?= $class ?? '' ?>"
    data-wt-url="<?= e(route(TomSelectPlace::class, ['tree' => $tree->name(), 'at' => ''])) ?>"
    id="<?= e($id ?? $name) ?>"
    name="<?= e($name) ?>"
    <?= ($disabled ?? false) ? 'disabled="disabled"' : '' ?>
    <?= ($required ?? false) ? 'required="required"' : '' ?>
>
    <?php if (($place ?? null) instanceof Place && $place->id() !== 0) : ?>
        <?php $option_html = view('selects/place', ['place' => $place]); ?>
        <option
            value="<?= $place->id() ?>" 
            data-ts-option="<?= e(json_encode(['text' => $option_html])) ?>"
        >
            <?= strip_tags($option_html) ?>
        </option>
    <?php else : ?>
        <option value="">&nbsp;</option>
    <?php endif ?>
</select>
