<?php

use Fisharebest\Webtrees\Http\RequestHandlers\AbstractSelect2Handler;
use Fisharebest\Webtrees\Http\RequestHandlers\Select2Submission;
use Fisharebest\Webtrees\Submission;
use Fisharebest\Webtrees\Tree;

/**
 * @var string          $at "@" or "" (or unset).
 * @var Submission|null $submission
 * @var string|null     $class
 * @var string|null     $id
 * @var string          $name
 * @var Tree            $tree
 */

$at = $at ?? '';

?>

<select
    autocomplete="off"
    class="form-select select2 <?= $class ?? '' ?>"
    data-ajax--delay="<?= e(AbstractSelect2Handler::AJAX_DELAY) ?>"
    data-minimum-input-length="<?= e(AbstractSelect2Handler::MINIMUM_INPUT_LENGTH) ?>"
    data-ajax--type="POST"
    data-ajax--url="<?= e(route(Select2Submission::class, ['tree' => $tree->name(), 'at' => $at])) ?>"
    data-allow-clear="true"
    data-placeholder=""
    id="<?= e($id ?? $name) ?>"
    name="<?= e($name) ?>"
    <?= ($disabled ?? false) ? 'disabled' : '' ?>
    <?= ($required ?? false) ? 'required' : '' ?>
    style="width:100%"
>
    <?php if (($submission ?? null) instanceof Submission) : ?>
        <option value="<?= e($at . $submission->xref() . $at) ?>">
            <?= view('selects/submission', ['submission' => $submission]) ?>
        </option>
    <?php else : ?>
        <option value="">&nbsp;</option>
    <?php endif ?>
</select>
