<?php

use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;

/**
 * @var Individual|null $individual
 * @var string|null     $class
 * @var string|null     $id
 * @var string          $name
 * @var Tree            $tree
 */

?>

<select
    autocomplete="off"
    class="form-control select2 <?= $class ?? '' ?>"
    data-ajax--delay="350"
    data-minimum-input-length="2"
    data-ajax--type="POST"
    data-ajax--url="<?= e(route('select2-individual', ['tree' => $tree->name()])) ?>"
    data-allow-clear="true"
    data-placeholder=""
    id="<?= e($id ?? $name) ?>"
    name="<?= e($name) ?>"
    <?= ($disabled ?? false) ? 'disabled' : '' ?>
    <?= ($required ?? false) ? 'required' : '' ?>
>
    <?php if (($individual ?? null) instanceof Individual): ?>
        <option value="<?= e($individual->xref()) ?>">
            <?= view('selects/individual', ['individual' => $individual]) ?>
        </option>
    <?php else: ?>
        <option></option>
    <?php endif ?>
</select>
