<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\TomSelectMediaObject;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Tree;

/**
 * @var string      $at     "@" or "" (or unset).
 * @var Media|null  $media
 * @var string|null $class
 * @var string|null $id
 * @var string      $name
 * @var Tree        $tree
 */

$at = $at ?? '';

?>

<select
    autocomplete="off"
    class="form-select tom-select <?= $class ?? '' ?>"
    data-url="<?= e(route(TomSelectMediaObject::class, ['tree' => $tree->name(), 'at' => $at])) ?>"
    id="<?= e($id ?? $name) ?>"
    name="<?= e($name) ?>"
    <?= ($disabled ?? false) ? 'disabled="disabled"' : '' ?>
    <?= ($required ?? false) ? 'required="required"' : '' ?>
>
    <?php if (($media ?? null) instanceof Media) : ?>
        <option value="<?= e($at . $media->xref() . $at) ?>">
            <?= view('selects/media', ['media' => $media]) ?>
        </option>
    <?php else : ?>
        <option value="">&nbsp;</option>
    <?php endif ?>
</select>
