<?php

use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\Tree;

/**
 * @var GedcomRecord|null $submitter
 * @var string|null       $id
 * @var string            $name
 * @var Tree              $tree
 */

?>

<select
autocomplete="off"
class="form-control select2"
data-ajax--delay="350"
data-ajax--minimum-input-length="2"
data-ajax--type="POST"
data-ajax--url="<?= e(route('select2-submitter', ['ged' => $tree->name()])) ?>"
data-allow-clear="true"
id="<?= e($id ?? $name) ?>"
name="<?= e($name) ?>"
    <?= ($disabled ?? false) ? 'disabled' : '' ?>
    <?= ($required ?? false) ? 'required' : '' ?>
>
    <?php if (($submitter ?? null) instanceof GedcomRecord): ?>
        <option value="<?= e($submitter->xref()) ?>" selected>
            <?= view('selects/submitter', ['submitter' => $submitter]) ?>
        </option>
    <?php else: ?>
        <option></option>
    <?php endif ?>
</select>
