<?php

/**
 * @var string|null $class
 * @var string|null $id
 * @var string      $name
 * @var mixed       $selected
 * @var string[]    $values
 */

?>

<select
    class="form-control <?= $class ?? '' ?>"
    name="<?= e($name) ?>"
    id="<?= e($id ?? $name) ?>"
    <?= is_array($selected) ? 'multiple' : '' ?>
>
    <?php foreach ($values as $key => $value) : ?>
        <option value="<?= e((string) $key) ?>" <?= is_array($selected) && in_array($key, $selected, true) || $key === $selected ?  'selected' : '' ?>>
            <?= e($value) ?>
        </option>
    <?php endforeach ?>
</select>
