<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\TomSelectRepository;
use Fisharebest\Webtrees\Repository;
use Fisharebest\Webtrees\Tree;

/**
 * @var string      $at     "@" or "" (or unset).
 * @var Repository|null $repository
 * @var string|null     $class
 * @var string|null     $id
 * @var string          $name
 * @var Tree            $tree
 */

$at = $at ?? '';

?>

<select
    autocomplete="off"
    class="form-select tom-select <?= $class ?? '' ?>"
    data-wt-url="<?= e(route(TomSelectRepository::class, ['tree' => $tree->name(), 'at' => $at])) ?>"
    id="<?= e($id ?? $name) ?>"
    name="<?= e($name) ?>"
    <?= ($disabled ?? false) ? 'disabled="disabled"' : '' ?>
    <?= ($required ?? false) ? 'required="required"' : '' ?>
>
    <?php if (($repository ?? null) instanceof Repository) : ?>
        <?php $option_html = view('selects/repository', ['repository' => $repository]); ?>
        <option
            value="<?= e($at . $repository->xref() . $at) ?>"
            data-ts-option="<?= e(json_encode(['text' => $option_html])) ?>"
        >
            <?= strip_tags($option_html) ?>
        </option>
    <?php else : ?>
        <option value="">&nbsp;</option>
    <?php endif ?>
</select>
