<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Http\RequestHandlers\TomSelectFamily;
use Fisharebest\Webtrees\Tree;

/**
 * @var string      $at     "@" or "" (or unset).
 * @var Family|null $family
 * @var string|null $class
 * @var string|null $id
 * @var string      $name
 * @var Tree        $tree
 */

$at = $at ?? '';

?>

<select
    autocomplete="off"
    class="form-select tom-select <?= $class ?? '' ?>"
    data-url="<?= e(route(TomSelectFamily::class, ['tree' => $tree->name(), 'at' => $at])) ?>"
    id="<?= e($id ?? $name) ?>"
    name="<?= e($name) ?>"
    <?= ($disabled ?? false) ? 'disabled="disabled"' : '' ?>
    <?= ($required ?? false) ? 'required="required"' : '' ?>
>
    <?php if (($family ?? null) instanceof Family) : ?>
        <option value="<?= e($at . $family->xref() . $at) ?>">
            <?= view('selects/family', ['family' => $family]) ?>
        </option>
    <?php else : ?>
        <option value="">&nbsp;</option>
    <?php endif ?>
</select>
