<?php

use Fisharebest\Webtrees\Http\RequestHandlers\AbstractSelect2Handler;
use Fisharebest\Webtrees\Http\RequestHandlers\Select2Note;
use Fisharebest\Webtrees\Note;
use Fisharebest\Webtrees\Tree;

/**
 * @var string      $at     "@" or "" (or unset).
 * @var Note|null   $note
 * @var string|null $class
 * @var string|null $id
 * @var string      $name
 * @var Tree        $tree
 */

$at = $at ?? '';

?>

<select
    autocomplete="off"
    class="form-select select2 <?= $class ?? '' ?>"
    data-ajax--delay="<?= e(AbstractSelect2Handler::AJAX_DELAY) ?>"
    data-minimum-input-length="<?= e(AbstractSelect2Handler::MINIMUM_INPUT_LENGTH) ?>"
    data-ajax--type="POST"
    data-ajax--url="<?= e(route(Select2Note::class, ['tree' => $tree->name(), 'at' => $at])) ?>"
    data-allow-clear="true"
    data-placeholder=""
    id="<?= e($id ?? $name) ?>"
    name="<?= e($name) ?>"
    <?= ($disabled ?? false) ? 'disabled' : '' ?>
    <?= ($required ?? false) ? 'required' : '' ?>
    style="width:100%"
>
    <?php if (($note ?? null) instanceof Note) : ?>
        <option value="<?= e($at . $note->xref() . $at) ?>">
            <?= view('selects/note', ['note' => $note]) ?>
        </option>
    <?php else : ?>
        <option value="">&nbsp;</option>
    <?php endif ?>
</select>
