<?php

use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Tree;

/**
 * @var Media|null  $media
 * @var string|null $class
 * @var string|null $id
 * @var string      $name
 * @var Tree        $tree
 */

?>

<select
    autocomplete="off"
    class="form-control select2 <?= $class ?? '' ?>"
    data-ajax--delay="350"
    data-ajax--minimum-input-length="2"
    data-ajax--type="POST"
    data-ajax--url="<?= e(route('select2-media', ['ged' => $tree->name()])) ?>"
    data-allow-clear="true"
    data-placeholder=""
    id="<?= e($id ?? $name) ?>"
    name="<?= e($name) ?>"
    <?= ($disabled ?? false) ? 'disabled' : '' ?>
    <?= ($required ?? false) ? 'required' : '' ?>
>
    <?php if (($media ?? null) instanceof Media): ?>
        <option value="<?= e($media->xref()) ?>">
            <?= view('selects/media', ['media' => $media]) ?>
        </option>
    <?php else: ?>
        <option></option>
    <?php endif ?>
</select>
