<?php use Fisharebest\Webtrees\I18N; ?>

<div class="wt-footer wt-footer-cookies text-center py-2">
    <?= I18N::translate('Cookies') ?>
    -
    <?= I18N::translate('This website uses cookies to learn about visitor behaviour.') ?>

    <button class="btn btn-secondary" onclick="document.cookie='cookie=1'; this.parentNode.classList.add('d-none');">
        <?= I18N::translate('close') ?>
    </button>
</div>

