<?php use Fisharebest\Webtrees\I18N; ?>

<div class="wt-footer-cookie-warning">
    <div class="wt-cookie-warning">
        <?= I18N::translate('Cookies') ?>
        -
        <?= I18N::translate('This website uses cookies to learn about visitor behaviour.') ?>

        <button onclick="document.cookie='cookie=1'; this.parentNode.classList.add('d-none');">
            <?= I18N::translate('continue') ?>
        </button>
    </div>
</div>
