<?php

use Fisharebest\Webtrees\I18N;

?>

<div class="form-group row">
    <label class="col-sm-3 col-form-label" for="filter">
        <?= I18N::translate('Show only events of living individuals') ?>
    </label>
    <div class="col-sm-9">
        <?= view('components/radios-inline', ['name' => 'filter', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int) $filter]) ?>
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-3 col-form-label" for="events">
        <?= I18N::translate('Events') ?>
    </label>
    <div class="col-sm-9">
        <?= view('components/select', ['name' => 'events[]', 'id' => 'events', 'selected' => $event_array, 'options' => $all_events, 'class' => 'select2']) ?>
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-3 col-form-label" for="infoStyle">
        <?= /* I18N: Label for a configuration option */ I18N::translate('Presentation style') ?>
    </label>
    <div class="col-sm-9">
        <?= view('components/select', ['name' => 'infoStyle', 'selected' => $infoStyle, 'options' => $info_styles]) ?>
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-3 col-form-label" for="sortStyle">
        <?= /* I18N: Label for a configuration option */ I18N::translate('Sort order') ?>
    </label>
    <div class="col-sm-9">
        <?= view('components/select', ['name' => 'sortStyle', 'selected' => $sortStyle, 'options' => $sort_styles]) ?>
    </div>
</div>
