<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var array<string,string> $all_events
 * @var array<string,string> $event_array
 * @var string               $filter
 * @var string               $info_style
 * @var array<string,string> $info_styles
 * @var string               $sort_style
 * @var array<string,string> $sort_styles
 */

?>

<div class="row mb-3">
    <label class="col-sm-3 col-form-label" for="filter">
        <?= I18N::translate('Show only events of living individuals') ?>
    </label>
    <div class="col-sm-9">
        <?= view('components/radios-inline', ['name' => 'filter', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int) $filter]) ?>
    </div>
</div>

<div class="row mb-3">
    <label class="col-sm-3 col-form-label" for="events">
        <?= I18N::translate('Events') ?>
    </label>
    <div class="col-sm-9">
        <?= view('components/select', ['name' => 'events[]', 'id' => 'events', 'selected' => $event_array, 'options' => $all_events, 'class' => 'tom-select']) ?>
    </div>
</div>

<div class="row mb-3">
    <label class="col-sm-3 col-form-label" for="infoStyle">
        <?= I18N::translate('Layout') ?>
    </label>
    <div class="col-sm-9">
        <?= view('components/select', ['name' => 'infoStyle', 'selected' => $info_style, 'options' => $info_styles]) ?>
    </div>
</div>

<div class="row mb-3">
    <label class="col-sm-3 col-form-label" for="sortStyle">
        <?= /* I18N: Label for a configuration option */ I18N::translate('Sort order') ?>
    </label>
    <div class="col-sm-9">
        <?= view('components/select', ['name' => 'sortStyle', 'selected' => $sort_style, 'options' => $sort_styles]) ?>
    </div>
</div>
