<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\Http\RequestHandlers\AccountDelete;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;

/**
 * @var array<string,string> $contact_methods
 * @var Individual|null      $default_individual
 * @var array<string,string> $languages
 * @var Individual|null      $my_individual_record
 * @var bool                 $show_delete_option
 * @var bool                 $show_2fa
 * @var array<string,string> $timezones
 * @var string               $title
 * @var Tree|null            $tree
 * @var UserInterface        $user
 * @var array<string,string> $qrcode
 */

?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<form method="post" class="wt-page-options wt-page-options-my-account">
    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="user-name">
            <?= I18N::translate('Username') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input type="text" class="form-control" id="user-name" name="user_name" value="<?= e($user->userName()) ?>" dir="auto" aria-describedby="username-description" required="required">
            <div class="form-text" id="username-description">
                <?= I18N::translate('Usernames are case-insensitive and ignore accented letters, so that “chloe”, “chloë”, and “Chloe” are considered to be the same.') ?>
            </div>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="real-name">
            <?= I18N::translate('Real name') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input type="text" class="form-control" id="real-name" name="real_name" value="<?= e($user->realName()) ?>" dir="auto" aria-describedby="real-name-description" required="required">
            <div class="form-text" id="real-name-description">
                <?= I18N::translate('This is your real name, as you would like it displayed on screen.') ?>
            </div>
        </div>
    </div>

    <?php if ($tree instanceof Tree) : ?>
        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="gedcom-id">
                <?= I18N::translate('Individual record') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <select class="form-select" id="gedcom-id" aria-describedby="gedcom-id-description" disabled>
                    <?php if ($my_individual_record !== null) : ?>
                        <option value=""><?= $my_individual_record->fullName() ?></option>
                    <?php else : ?>
                        <option value=""><?= I18N::translateContext('unknown people', 'Unknown') ?></option>
                    <?php endif ?>
                </select>
                <div class="form-text" id="gedcom-id-description">
                    <?= I18N::translate('This is a link to your own record in the family tree. If this is the wrong individual, contact an administrator.') ?>
                </div>
            </div>
        </div>

        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="default-xref">
                <?= I18N::translate('Default individual') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?= view('components/select-individual', ['name' => 'default-xref', 'id' => 'default-xref', 'individual' => $default_individual, 'tree' => $tree]) ?>
                <div class="form-text" id="default-xref-description">
                    <?= I18N::translate('This individual will be selected by default when viewing charts and reports.') ?>
                </div>
            </div>
        </div>
    <?php endif ?>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="password">
            <?= I18N::translate('Password') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="password" id="password" name="password" aria-describedby="password-description" autocomplete="new-password" data-wt-show-password-text="<?= e(I18N::translate('show')) ?>" data-wt-show-password-title="<?= e(I18N::translate('Show password')) ?>" data-wt-hide-password-text="<?= e(I18N::translate('hide')) ?>" data-wt-hide-password-title="<?= e(I18N::translate('Hide password')) ?>">
            <div class="form-text" id="password-description">
                <?= I18N::translate('Passwords must be at least 8 characters long and are case-sensitive, so that “secret” is different from “SECRET”.') ?>
                <br>
                <?= I18N::translate('Leave the password blank if you want to keep the current password.') ?>
            </div>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="language">
            <?= I18N::translate('Language') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select', ['name' => 'language', 'selected' => $user->getPreference(UserInterface::PREF_LANGUAGE, 'en-US'), 'options' => $languages]) ?>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="timezone">
            <?= I18N::translate('Time zone') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select', ['name' => 'timezone', 'selected' => $user->getPreference(UserInterface::PREF_TIME_ZONE, 'UTC'), 'options' => $timezones]) ?>
            <div class="form-text" id="timezone-description">
                <?= I18N::translate('The time zone is required for date calculations, such as knowing today’s date.') ?>
            </div>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="email">
            <?= I18N::translate('Email address') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="email" id="email" name="email" value="<?= e($user->email()) ?>" aria-describedby="email-description">
            <div class="form-text" id="email-description">
                <?= I18N::translate('This email address will be used to send password reminders, website notifications, and messages from other family members who are registered on the website.') ?>
            </div>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="contact-method">
            <?= I18N::translate('Contact method') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select', ['name' => 'contact-method', 'id' => 'contact-method', 'selected' => $user->getPreference(UserInterface::PREF_CONTACT_METHOD), 'options' => $contact_methods]) ?>
            <div class="form-text" id="contact-method-description">
            <?= I18N::translate('Site members can send each other messages. You can choose to how these messages are sent to you, or choose not receive them at all.') ?>
            </div>
        </div>
    </div>

    <fieldset class="row">
        <legend class="col-sm-3 col-form-label wt-page-options-label">
            <?= I18N::translate('Visible online') ?>
        </legend>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/checkbox', ['label' => I18N::translate('Visible to other users when online'), 'name' => 'visible-online', 'checked' => (bool) $user->getPreference(UserInterface::PREF_IS_VISIBLE_ONLINE)]) ?>
            <div class="form-text" id="visible-online-description">
                <?= I18N::translate('You can choose whether to appear in the list of users who are currently signed-in.') ?>
            </div>
        </div>
    </fieldset>
<?php if ($show_2fa) : ?>
    <fieldset class="row">
        <legend class="col-sm-3 col-form-label wt-page-options-label">
            <?= I18N::translate('MFA status') ?>
        </legend>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/checkbox', ['label' => I18N::translate('Enable or disable 2FA status'), 'name' => 'status-mfa', 'checked' => (bool) $user->getPreference(UserInterface::PREF_IS_STATUS_MFA)]) ?>
            <div class="form-text" id="status-mfa-description">
                <?= I18N::translate('You can choose whether to use 2FA for extra security.') ?>
            </div>
        </div>
    </fieldset>
<?php endif ?>
    <div class="row"  id="qrcode">
        <?php $qrc = $qrcode; ?>
        <input type="hidden" name="secret" id="secret" value="">
        <input type="hidden" id="newsecret" value="<?= e($qrc['secret']) ?>">
        <img src="<?= e($qrc['qrcode']) ?>" alt="QR Code" id="qrcode" />
    </div>
    <div class="row mb-3">
        <div class="col-sm-3 wt-page-options-label"></div>
        <div class="col-sm-9 wt-page-options-value">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= I18N::translate('save') ?>
            </button>
        </div>
    </div>

    <?= csrf_field() ?>
</form>

<?php if ($show_delete_option) : ?>
    <div class="row mb-3">
        <div class="col-sm-3 wt-page-options-label"></div>
        <div class="col-sm-9 wt-page-options-value">
            <a href="#" class="btn btn-danger" data-wt-confirm="<?= I18N::translate('Are you sure you want to delete “%s”?', e($user->userName())) ?>" data-wt-post-url="<?= e(route(AccountDelete::class)) ?>">
                <?= view('icons/delete') ?>
                <?= I18N::translate('Delete your account') ?>
            </a>
        </div>
    </div>
<?php endif ?>
