<?php

use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Functions\FunctionsPrint;
use Fisharebest\Webtrees\Functions\FunctionsPrintFacts;
use Fisharebest\Webtrees\Http\RequestHandlers\AddNewFact;
use Fisharebest\Webtrees\I18N;
use Illuminate\Support\Collection;

/**
 * @var Collection<Fact> $clipboard_facts
 * @var Collection<Fact> $facts
 * @var Family           $record
 */

?>

<?= view('family-page-pending', ['record' => $record]) ?>

<div class="d-flex mb-4">
    <h2 class="wt-page-title mx-auto">
        <?= $record->fullName() ?>
    </h2>
    <?php if ($record->canEdit()) : ?>
        <?= view('family-page-menu', ['clipboard_facts' => $clipboard_facts, 'record' => $record]) ?>
    <?php endif ?>
</div>

<div class="wt-page-content">
    <div class="wt-family-members d-flex">
        <?= view('family-page-children', ['family' => $record]) ?>
        <?= view('family-page-parents', ['family' => $record]) ?>
    </div>

    <h3 class="mt-4"><?= I18N::translate('Facts and events') ?></h3>
    <table class="table wt-facts-table">
        <?php if ($facts->isEmpty()) : ?>
            <tr>
                <td colspan="2">
                    <?= I18N::translate('No facts exist for this family.') ?>
                </td>
            </tr>
        <?php else : ?>
            <?php foreach ($facts as $fact) : ?>
                <?php FunctionsPrintFacts::printFact($fact, $record) ?>
            <?php endforeach ?>
        <?php endif ?>

        <?php if (Auth::isEditor($record->tree())) : ?>
            <?php FunctionsPrint::printAddNewFact($record) ?>
            <tr>
                <th scope="row">
                    <?= I18N::translate('Note') ?>
                </th>
                <td>
                    <a href="<?= e(route(AddNewFact::class, ['tree' => $record->tree()->name(), 'xref' => $record->xref(), 'fact' => 'NOTE'])) ?>">
                        <?= I18N::translate('Add a note') ?>
                    </a>
                </td>
            </tr>

            <?php if ($record->tree()->getPreference('MEDIA_UPLOAD') >= Auth::accessLevel($record->tree())) : ?>
                <tr>
                    <th scope="row">
                        <?= I18N::translate('Media object') ?>
                    </th>
                    <td>
                        <a href="<?= e(route(AddNewFact::class, ['tree' => $record->tree()->name(), 'xref' => $record->xref(), 'fact' => 'OBJE'])) ?>">
                            <?= I18N::translate('Add a media object') ?>
                        </a>
                    </td>
                </tr>
            <?php endif ?>

            <tr>
                <th scope="row">
                    <?= I18N::translate('Source') ?>
                </th>
                <td>
                    <a href="<?= e(route(AddNewFact::class, ['tree' => $record->tree()->name(), 'xref' => $record->xref(), 'fact' => 'SOUR'])) ?>">
                        <?= I18N::translate('Add a source citation') ?>
                    </a>
                </td>
            </tr>
        <?php endif ?>
    </table>
</div>

<?= view('modals/ajax') ?>
