<?php

use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Functions\FunctionsPrint;
use Fisharebest\Webtrees\Functions\FunctionsPrintFacts;
use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\Http\RequestHandlers\PendingChangesAcceptRecord;
use Fisharebest\Webtrees\Http\RequestHandlers\PendingChangesRejectRecord;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Note;
use Fisharebest\Webtrees\Source;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var Collection<Fact>       $facts
 * @var Collection<Family>     $families
 * @var Collection<Individual> $individuals
 * @var Collection<Media>      $media_objects
 * @var Collection<Note>       $notes
 * @var GedcomRecord           $record
 * @var Collection<Source>     $sources
 * @var Tree                   $tree
 */

?>

<?php if ($record->isPendingDeletion()) : ?>
    <?php if (Auth::isModerator($record->tree())) : ?>
        <?= view('components/alert-warning-dismissible', ['alert' => /* I18N: %1$s is “accept”, %2$s is “reject”. These are links. */ I18N::translate('This record has been deleted. You should review the deletion and then %1$s or %2$s it.', '<a href="#" class="alert-link" data-post-url="' . e(route(PendingChangesAcceptRecord::class, ['tree' => $record->tree()->name(), 'xref' => $record->xref()])) . '">' . I18N::translateContext('You should review the deletion and then accept or reject it.', 'accept') . '</a>', '<a href="#" class="alert-link" data-post-url="' . e(route(PendingChangesRejectRecord::class, ['tree' => $record->tree()->name(), 'xref' => $record->xref()])) . '">' . I18N::translateContext('You should review the deletion and then accept or reject it.', 'reject') . '</a>') . ' ' . view('help/link', ['topic' => 'pending_changes'])]) ?>
    <?php elseif (Auth::isEditor($record->tree())) : ?>
        <?= view('components/alert-warning-dismissible', ['alert' => I18N::translate('This record has been deleted. The deletion will need to be reviewed by a moderator.') . ' ' . view('help/link', ['topic' => 'pending_changes'])]) ?>
    <?php endif ?>
<?php elseif ($record->isPendingAddition()) : ?>
    <?php if (Auth::isModerator($record->tree())) : ?>
        <?= view('components/alert-warning-dismissible', ['alert' => /* I18N: %1$s is “accept”, %2$s is “reject”. These are links. */ I18N::translate('This record has been edited. You should review the changes and then %1$s or %2$s them.', '<a href="#" class="alert-link" data-post-url="' . e(route(PendingChangesAcceptRecord::class, ['tree' => $record->tree()->name(), 'xref' => $record->xref()])) . '">' . I18N::translateContext('You should review the changes and then accept or reject them.', 'accept') . '</a>', '<a href="#" class="alert-link" data-post-url="' . e(route(PendingChangesRejectRecord::class, ['tree' => $record->tree()->name(), 'xref' => $record->xref()])) . '">' . I18N::translateContext('You should review the changes and then accept or reject them.', 'reject') . '</a>') . ' ' . view('help/link', ['topic' => 'pending_changes'])]) ?>
    <?php elseif (Auth::isEditor($record->tree())) : ?>
        <?= view('components/alert-warning-dismissible', ['alert' => I18N::translate('This record has been edited. The changes need to be reviewed by a moderator.') . ' ' . view('help/link', ['topic' => 'pending_changes'])]) ?>
    <?php endif ?>
<?php endif ?>

<div class="d-flex mb-4">
    <h2 class="wt-page-title mx-auto">
        <?= $record->fullName() ?>
    </h2>
    <?php if ($record->canEdit()) : ?>
        <?= view('gedcom-record-page-menu', ['record' => $record]) ?>
    <?php endif ?>
</div>

<div class="wt-page-content">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item" role="presentation">
            <a class="nav-link active" data-toggle="tab" role="tab" href="#details">
                <?= I18N::translate('Details') ?>
            </a>
        </li>

        <?php if ($individuals->isNotEmpty()) : ?>
            <li class="nav-item" role="presentation">
                <a class="nav-link" data-toggle="tab" role="tab" href="#individuals">
                    <?= I18N::translate('Individuals') ?>
                    <?= view('components/badge', ['count' => $individuals->count()]) ?>
                </a>
            </li>
        <?php endif ?>

        <?php if ($families->isNotEmpty()) : ?>
            <li class="nav-item" role="presentation">
                <a class="nav-link" data-toggle="tab" role="tab" href="#families">
                    <?= I18N::translate('Families') ?>
                    <?= view('components/badge', ['count' => $families->count()]) ?>
                </a>
            </li>
        <?php endif ?>

        <?php if ($media_objects->isNotEmpty()) : ?>
            <li class="nav-item" role="presentation">
                <a class="nav-link" data-toggle="tab" role="tab" href="#media">
                    <?= I18N::translate('Media objects') ?>
                    <?= view('components/badge', ['count' => $media_objects->count()]) ?>
                </a>
            </li>
        <?php endif ?>

        <?php if ($sources->isNotEmpty()) : ?>
            <li class="nav-item" role="presentation">
                <a class="nav-link" data-toggle="tab" role="tab" href="#sources">
                    <?= I18N::translate('Sources') ?>
                    <?= view('components/badge', ['count' => $sources->count()]) ?>
                </a>
            </li>
        <?php endif ?>

        <?php if ($notes->isNotEmpty()) : ?>
            <li class="nav-item" role="presentation">
                <a class="nav-link" data-toggle="tab" role="tab" href="#notes">
                    <?= I18N::translate('Notes') ?>
                    <?= view('components/badge', ['count' => $notes->count()]) ?>
                </a>
            </li>
        <?php endif ?>
    </ul>

    <div class="tab-content">
        <div class="tab-pane active fade show" role="tabpanel" id="details">
            <table class="table wt-facts-table">
                <?php foreach ($facts as $fact) : ?>
                    <?php FunctionsPrintFacts::printFact($fact, $record) ?>
                <?php endforeach ?>

                <?php if ($record->canEdit()) : ?>
                    <?php FunctionsPrint::printAddNewFact($record, $facts, $record::RECORD_TYPE) ?>
                <?php endif ?>
            </table>
        </div>

        <?php if ($individuals->isNotEmpty()) : ?>
            <div class="tab-pane fade" role="tabpanel" id="individuals">
                <?= view('lists/individuals-table', ['individuals' => $individuals, 'sosa' => false, 'tree' => $tree]) ?>
            </div>
        <?php endif ?>

        <?php if ($families->isNotEmpty()) : ?>
            <div class="tab-pane fade" role="tabpanel" id="families">
                <?= view('lists/families-table', ['families' => $families, 'tree' => $tree]) ?>
            </div>
        <?php endif ?>

        <?php if ($media_objects->isNotEmpty()) : ?>
            <div class="tab-pane fade" role="tabpanel" id="media">
                <?= view('lists/media-table', ['media_objects' => $media_objects, 'tree' => $tree]) ?>
            </div>
        <?php endif ?>

        <?php if ($sources->isNotEmpty()) : ?>
            <div class="tab-pane fade" role="tabpanel" id="sources">
                <?= view('lists/sources-table', ['sources' => $sources, 'tree' => $tree]) ?>
            </div>
        <?php endif ?>

        <?php if ($notes->isNotEmpty()) : ?>
            <div class="tab-pane fade" role="tabpanel" id="notes">
                <?= view('lists/notes-table', ['notes' => $notes, 'tree' => $tree]) ?>
            </div>
        <?php endif ?>
    </div>
</div>

<?= view('modals/ajax') ?>
