<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Individual;

/**
 * @var Individual $record
 */
?>

<!-- Name accordion -->
<div class="col-sm accordion" id="individual-names">
    <?php foreach ($record->facts(['NAME']) as $fact) : ?>
        <?= view('individual-page-name', ['fact' => $fact]) ?>
    <?php endforeach ?>

    <?php foreach ($record->facts(['SEX']) as $fact) : ?>
        <?= view('individual-page-sex', ['fact' => $fact]) ?>
    <?php endforeach ?>
</div>
