<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Module\ModuleTabInterface;
use Illuminate\Support\Collection;

/**
 * @var Individual                         $record
 * @var Collection<int,ModuleTabInterface> $tabs
 */
?>

<div class="wt-tabs-individual" id="individual-tabs">
    <ul class="nav nav-tabs flex-wrap" role="tablist">
        <?php foreach ($tabs as $tab) : ?>
            <li class="nav-item" role="presentation">
                <a class="nav-link<?= $tab->isGrayedOut($record) ? ' text-muted' : '' ?>" id="<?= $tab->name() ?>-tab" data-bs-toggle="tab" role="tab" aria-controls="<?= $tab->name() ?>" aria-selected="false" data-wt-href="<?= e(route('module', ['module' => $tab->name(), 'action' => 'Tab', 'tree' => $record->tree()->name(), 'xref' => $record->xref()])) ?>" href="#<?= $tab->name() ?>">
                    <?= $tab->tabTitle() ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>

    <div class="tab-content">
        <?php foreach ($tabs as $tab) : ?>
            <div id="<?= $tab->name() ?>" class="tab-pane mt-2 fade" role="tabpanel" aria-labelledby="<?= $tab->name() ?>-tab"><?php if (!$tab->canLoadAjax()) : ?><?= $tab->getTabContent($record) ?><?php endif ?></div>
        <?php endforeach ?>
    </div>
</div>
