<?php

use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Factory;
use Fisharebest\Webtrees\Functions\FunctionsPrint;
use Fisharebest\Webtrees\Functions\FunctionsPrintFacts;
use Fisharebest\Webtrees\GedcomCode\GedcomCodeName;
use Fisharebest\Webtrees\GedcomTag;
use Fisharebest\Webtrees\Http\RequestHandlers\DeleteFact;
use Fisharebest\Webtrees\Http\RequestHandlers\EditName;
use Fisharebest\Webtrees\I18N;

/**
 * @var Fact $fact
 * @var int  $n
 */

$individual = $fact->record();
$tree       = $individual->tree();

// Create a dummy record, so we can extract the formatted NAME value from it.
$dummy = Factory::individual()->new(
    'xref',
    "0 @xref@ INDI\n1 DEAT Y\n" . $fact->gedcom(),
    null,
    $tree
);
$dummy->setPrimaryName(0); // Make sure we use the name from "1 NAME"

$container_class = '';
$content_class   = 'collapse';
$aria            = 'false';

if ($n === $individual->getPrimaryName()) {
    $content_class = 'collapse show';
    $aria          = 'true';
}
if ($fact->isPendingDeletion()) {
    $container_class = 'wt-old';
} elseif ($fact->isPendingAddition()) {
    $container_class = 'wt-new';
}

?>
<div class="card <?= $container_class ?>">
    <div class="card-header" role="tab" id="name-header-<?= $n ?>">
        <a data-toggle="collapse" href="#name-content-<?= $n ?>" aria-expanded="<?= $aria ?>"
           aria-controls="name-content-<?= $n ?>">
            <!--
            <?= view('icons/expand') ?>
            <?= view('icons/collapse') ?>
            -->
            <span class="label"><?= I18N::translate('Name') ?></span>
            <?= $dummy->fullName() ?>
        </a>

        <?php if ($fact->canEdit()) : ?>
            <a class="btn btn-link" href="#"
               data-confirm="<?= I18N::translate('Are you sure you want to delete this fact?') ?>"
               data-post-url="<?= e(route(DeleteFact::class, ['tree' => $individual->tree()->name(), 'xref' => $individual->xref(), 'fact_id' => $fact->id()])) ?>"
               title="<?= I18N::translate('Delete this name') ?>">
                <?= view('icons/delete') ?>
                <span class="sr-only"><?= I18N::translate('Delete this name') ?></span>
            </a>

            <a class="btn btn-link"
               href="<?= e(route(EditName::class, ['xref' => $individual->xref(), 'fact_id' => $fact->id(), 'tree' => $individual->tree()->name()])) ?>"
               title="<?= I18N::translate('Edit the name') ?>">
                <?= view('icons/edit') ?>
                <span class="sr-only"><?= I18N::translate('Edit the name') ?></span>
            </a>
        <?php endif ?>
    </div>

    <div id="name-content-<?= $n ?>" class="<?= $content_class ?>" data-parent="#individual-names"
         aria-labelledby="name-header-<?= $n ?>">
        <div class="card-body">
            <dl class="row mb-0">
                <dt class="col-md-4 col-lg-3"><?= I18N::translate('Name') ?></dt>
                <dd class="col-md-8 col-lg-9"><?= $dummy->fullName() ?></dd>

                <?php preg_match_all('/\n2 (\w+) (.+)/', $fact->gedcom(), $matches, PREG_SET_ORDER) ?>

                <?php foreach ($matches as $key => $match) : ?>
                    <?php [, $tag, $value] = $match ?>
                    <?php if ($tag !== 'SOUR' && $tag !== 'NOTE' && $tag !== 'SPFX') : ?>
                        <dt class="col-md-4 col-lg-3">
                            <?= GedcomTag::getLabel($tag) ?>
                        </dt>
                        <dd class="col-md-8 col-lg-9">
                            <?php
                            switch ($tag) {
                                case 'TYPE':
                                    echo GedcomCodeName::getValue(e($value), $individual);
                                    break;
                                case 'GIVN':
                                    echo '<span dir="auto">' . preg_replace('/(\S*)\*/', '<span class="starredname">\\1</span>', e($value)) . '</span>';
                                    break;
                                case 'SURN':
                                    // The SURN field is not necessarily the surname.
                                    // Where it is not a substring of the real surname, show it after the real surname.
                                    $surname = $dummy->getAllNames()[0]['surname'];
                                    $surns   = preg_replace('/, */', ' ', $value);
                                    if (strpos($dummy->getAllNames()[0]['surname'], $surns) !== false) {
                                        echo '<span dir="auto">' . e($surname) . '</span>';
                                    } else {
                                        echo I18N::translate('%1$s (%2$s)', '<span dir="auto">' . e($surname) . '</span>', '<span dir="auto">' . e($value) . '</span>');
                                    }
                                    break;
                                default:
                                    echo '<span dir="auto">' . e($value) . '</span>';
                                    break;
                            }
                            ?>
                        </dd>
                    <?php endif ?>
                <?php endforeach ?>
            </dl>

            <?php if (strpos($fact->gedcom(), "\n2 SOUR") !== false) : ?>
                <div id="indi_sour">
                    <?= FunctionsPrintFacts::printFactSources($tree, $fact->gedcom(), 2) ?>
                </div>
            <?php endif ?>

            <?php if (strpos($fact->gedcom(), "\n2 NOTE") !== false) : ?>
                <div id="indi_note">
                    <?= FunctionsPrint::printFactNotes($tree, $fact->gedcom(), 2) ?>
                </div>
            <?php endif ?>
        </div>
    </div>
</div>
