<?php

use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;
use League\Flysystem\FilesystemOperator;

/**
 * @var Collection         $clipboard_facts
 * @var FilesystemOperator $data_filesystem
 * @var Collection         $linked_families
 * @var Collection         $linked_individuals
 * @var Collection         $linked_notes
 * @var Collection         $linked_sources
 * @var Media              $record
 * @var Tree               $tree
 */

?>

<?= view('media-page-pending', ['record' => $record]) ?>

<div class="d-flex mb-4">
    <h2 class="wt-page-title mx-auto">
        <?= $record->fullName() ?>
    </h2>
    <?php if ($record->canEdit()) : ?>
        <?= view('media-page-menu', ['clipboard_facts' => $clipboard_facts, 'record' => $record]) ?>
    <?php endif ?>
</div>

<div class="wt-page-content">
        <?= view('record-page-links', [
            'details'              => view('media-page-details', ['clipboard_facts' => $clipboard_facts, 'data_filesystem' => $data_filesystem, 'record' => $record]),
            'linked_families'      => $linked_families,
            'linked_individuals'   => $linked_individuals,
            'linked_media_objects' => null,
            'linked_notes'         => $linked_notes,
            'linked_sources'       => $linked_sources,
            'tree'                 => $tree,
        ]) ?>
</div>

<?= view('modals/ajax') ?>
