<?php
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
?>

<?php if ($one_line_only): ?>
  <div class="fact_NOTE">
    <span class="label">
      <?= I18N::translate($label) ?>
    </span>
    <span dir="auto">
      <?= $title ?>
    </span>
  </div>
<?php else: ?>
  <div class="fact_NOTE">
    <a
      href="#<?= e($id) ?>"
      role="button"
      data-bs-toggle="collapse"
      aria-controls="<?= e($id) ?>"
      aria-expanded="<?= ($expanded ? 'true' : 'false') ?>">
      <?= view('icons/expand') ?>
      <?= view('icons/collapse') ?>
    </a>
    <span class="label">
      <?= $label ?>:
    </span>
    <span dir = "auto" data-id="<?= e($id) ?>">
      <?= $title ?>
    </span>
  </div>
  <div id="<?= e($id) ?>" class="collapse <?= $expanded ?>">
      <?= $content ?>
  </div>
<?php endif; ?>
