<?php

use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Note;
use Fisharebest\Webtrees\Source;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var Note                   $record
 * @var Collection<Fact>       $clipboard_facts
 * @var Collection<Family>     $linked_families
 * @var Collection<Individual> $linked_individuals
 * @var Collection<Media>      $linked_media_objects
 * @var Collection<Source>     $linked_sources
 * @var Tree                   $tree
 */

?>

<?= view('note-page-pending', ['record' => $record]) ?>

<div class="d-flex mb-4">
    <h2 class="wt-page-title mx-auto">
        <?= $record->fullName() ?>
    </h2>
    <?php if ($record->canEdit()) : ?>
        <?= view('record-page-menu', ['clipboard_facts' => $clipboard_facts, 'record' => $record]) ?>
    <?php endif ?>
</div>

<div class="wt-page-content">
    <?= view('record-page-links', [
        'details'              => view('note-page-details', ['clipboard_facts' => $clipboard_facts, 'record' => $record]),
        'linked_families'      => $linked_families,
        'linked_individuals'   => $linked_individuals,
        'linked_media_objects' => $linked_media_objects,
        'linked_notes'         => null,
        'linked_sources'       => $linked_sources,
        'tree'                 => $tree,
    ]) ?>
</div>

<?= view('modals/ajax') ?>
