<?php

use Fisharebest\Webtrees\Http\RequestHandlers\PasswordRequestAction;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var string $title
 */
?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<form method="post" action="<?= e(route(PasswordRequestAction::class, ['tree' => $tree instanceof Tree ? $tree->name() : null])) ?>" class="wt-page-options wt-page-options-login">
    <?= csrf_field() ?>

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="email">
            <?= I18N::translate('Email') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="email" id="email" name="email" autocomplete="email" required>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-3 col-form-label wt-page-options-label">
        </div>
        <div class="col-sm-9 wt-page-options-value">
            <button class="btn btn-primary" type="submit">
                <?= /* I18N: A button label. */
                I18N::translate('continue') ?>
            </button>

        </div>
    </div>
</form>
