<?php
use Fisharebest\Webtrees\I18N;
use \Fisharebest\Webtrees\Place;

/**
 * @var bool $showlink
 * @var Place $place
 * @var string $flag
 * @var array $stats
 *
 */
?>

<div class="row">
    <span class="offset-sm-1 col-sm-7 label">
        <?php if ($showlink) : ?>
            <a href="<?= e($place->url()) ?>">
                <?= $place->placeName() ?>
            </a>
        <?php else : ?>
            <?= $place->placeName() ?>
        <?php endif ?>
    </span>
    <?php if ($flag) : ?>
    <span class="col-sm-3 align-digits">
            <img class="flag" alt = "<?=strip_tags($place->placeName()) ?>" title = "<?=strip_tags($place->placeName()) ?>" src='<?= $flag ?>'>
    </span>
    <?php endif ?>
    <span class="offset-sm-1 col-sm-7"><?= I18N::translate('Individuals') ?></span>
    <span class="col-sm-3 align-digits"><?= $stats['INDI'] ?></span>
    <span class="offset-sm-1 col-sm-7"><?= I18N::translate('Families') ?></span>
    <span class="col-sm-3 align-digits"><?= $stats['FAM'] ?></span>
</div>
