<?php

declare(strict_types=1);

/**
 * @var array<string> $bad_user_agents
 * @var string        $base_path
 * @var string        $base_url
 * @var string        $sitemap_url
 */

?>
# robots.txt for <?= $base_url ?>

<?php if ($base_path !== '') : ?>
# CAUTION!  This robots.txt needs to be copied to the root folder.
<?php endif ?>

<?php foreach ($bad_user_agents as $bad_user_agent) : ?>
User-agent: <?= $bad_user_agent ?>

<?php endforeach ?>
Disallow: /

User-agent: *
Disallow: <?= $base_path ?>/admin
Disallow: <?= $base_path ?>/manager
Disallow: <?= $base_path ?>/editor
Disallow: <?= $base_path ?>/account
Crawl-delay: 1

Disallow: <?= $base_path ?>/login   
Disallow: <?= $base_path ?>/module 

Disallow: /*/*-list
Disallow: /*/*-map
Disallow: /*/*-tree
Disallow: /*/branches/
Disallow: /*/calendar/
Disallow: /*/Chart/
Disallow: /*/compact/
Disallow: /*/contact
Disallow: /*/family-book 
Disallow: /*/fan-chart-
Disallow: /*/hourglass
Disallow: /*/media-thumbnail
Disallow: /*/pedigree-
Disallow: /*/relationships-
Disallow: /*/report/
Disallow: /*/timeline-

<?php if ($sitemap_url !== '') : ?>
Sitemap: <?= $sitemap_url ?>
<?php endif ?>
