# robots.txt for <?= $base_url ?>

<?php if ($base_path !== '') : ?>
# CAUTION!  This robots.txt needs to be copied to the root folder.
<?php endif ?>

User-agent: *
Disallow: <?= $base_path ?>/admin
Disallow: <?= $base_path ?>/manager
Disallow: <?= $base_path ?>/editor
Disallow: <?= $base_path ?>/account
Crawl-delay: 10

<?php if ($sitemap_url !== '') : ?>
Sitemap: <?= $sitemap_url ?>
<?php endif ?>
