<?php

use Fisharebest\Webtrees\Http\RequestHandlers\SearchReplaceAction;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var string $context
 * @var string $replace
 * @var string $search
 * @var string $title
 * @var Tree $tree
 */

?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<form method="post" action="<?= e(route(SearchReplaceAction::class, ['tree' => $tree->name()])) ?>" class="wt-page-options wt-page-options-ancestors-chart hidden-print">
    <?= csrf_field() ?>

    <div class="row form-group">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="search">
            <?= I18N::translate('Search for') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" id="search" name="search" value="<?= e($search) ?>" type="text" autofocus>
        </div>
    </div>

    <div class="row form-group">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="replace">
            <?= I18N::translate('Replace with') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" id="replace" name="replace" value="<?= e($replace) ?>" type="text">
        </div>
    </div>

    <div class="row form-group">
        <label class="col-sm-3 col-form-label wt-page-options-label">
            <?= /* I18N: A button label. */ I18N::translate('Search') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/radios-inline', ['name' => 'context', 'options' => ['all' => I18N::translate('Entire record'), 'name' => I18N::translate('Names'), 'place' => I18N::translate('Places')], 'selected' => $context]) ?>
        </div>
    </div>
    <div class="row form-group">
        <label class="col-sm-3 col-form-label wt-page-options-label"></label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="btn btn-primary" type="submit" value="<?= /* I18N: A button label. */ I18N::translate('replace') ?>">
        </div>
    </div>
</form>
