<?php

use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Functions\FunctionsPrintFacts;
use Fisharebest\Webtrees\Http\RequestHandlers\PendingChangesAcceptRecord;
use Fisharebest\Webtrees\Http\RequestHandlers\PendingChangesRejectRecord;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Submitter;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var Collection<Fact>       $facts
 * @var Collection<Family>     $families
 * @var Collection<Individual> $individuals
 * @var Submitter              $submitter
 * @var Tree                   $tree
 */

?>

<?php if ($submitter->isPendingDeletion()) : ?>
    <?php if (Auth::isModerator($submitter->tree())) : ?>
        <?= view('components/alert-warning-dismissible', ['alert' => /* I18N: %1$s is “accept”, %2$s is “reject”. These are links. */ I18N::translate('This record has been deleted. You should review the deletion and then %1$s or %2$s it.', '<a href="#" class="alert-link" data-post-url="' . e(route(PendingChangesAcceptRecord::class, ['tree' => $submitter->tree()->name(), 'xref' => $submitter->xref()])) . '">' . I18N::translateContext('You should review the deletion and then accept or reject it.', 'accept') . '</a>', '<a href="#" class="alert-link" data-post-url="' . e(route(PendingChangesRejectRecord::class, ['tree' => $submitter->tree()->name(), 'xref' => $submitter->xref()])) . '">' . I18N::translateContext('You should review the deletion and then accept or reject it.', 'reject') . '</a>') . ' ' . view('help/link', ['topic' => 'pending_changes'])]) ?>
    <?php elseif (Auth::isEditor($submitter->tree())) : ?>
        <?= view('components/alert-warning-dismissible', ['alert' => I18N::translate('This record has been deleted. The deletion will need to be reviewed by a moderator.') . ' ' . view('help/link', ['topic' => 'pending_changes'])]) ?>
    <?php endif ?>
<?php elseif ($submitter->isPendingAddition()) : ?>
    <?php if (Auth::isModerator($submitter->tree())) : ?>
        <?= view('components/alert-warning-dismissible', ['alert' => /* I18N: %1$s is “accept”, %2$s is “reject”. These are links. */ I18N::translate('This record has been edited. You should review the changes and then %1$s or %2$s them.', '<a href="#" class="alert-link" data-post-url="' . e(route(PendingChangesAcceptRecord::class, ['tree' => $submitter->tree()->name(), 'xref' => $submitter->xref()])) . '">' . I18N::translateContext('You should review the changes and then accept or reject them.', 'accept') . '</a>', '<a href="#" class="alert-link" data-post-url="' . e(route(PendingChangesRejectRecord::class, ['tree' => $submitter->tree()->name(), 'xref' => $submitter->xref()])) . '">' . I18N::translateContext('You should review the changes and then accept or reject them.', 'reject') . '</a>') . ' ' . view('help/link', ['topic' => 'pending_changes'])]) ?>
    <?php elseif (Auth::isEditor($submitter->tree())) : ?>
        <?= view('components/alert-warning-dismissible', ['alert' => I18N::translate('This record has been edited. The changes need to be reviewed by a moderator.') . ' ' . view('help/link', ['topic' => 'pending_changes'])]) ?>
    <?php endif ?>
<?php endif ?>

<div class="d-flex mb-4">
    <h2 class="wt-page-title mx-auto">
        <?= $submitter->fullName() ?>
    </h2>
    <?php if ($submitter->canEdit()) : ?>
        <?= view('submitter-page-menu', ['record' => $submitter]) ?>
    <?php endif ?>
</div>

<div class="wt-page-content">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item" role="presentation">
            <a class="nav-link active" data-toggle="tab" role="tab" href="#details">
                <?= I18N::translate('Details') ?>
            </a>
        </li>

        <li class="nav-item" role="presentation">
            <a class="nav-link<?= $individuals->isEmpty() ? ' text-muted' : '' ?>" data-toggle="tab" role="tab" href="#individuals">
                <?= I18N::translate('Individuals') ?>
                <?= view('components/badge', ['count' => $individuals->count()]) ?>
            </a>
        </li>

        <li class="nav-item" role="presentation">
            <a class="nav-link<?= $families->isEmpty() ? ' text-muted' : '' ?>" data-toggle="tab" role="tab" href="#families">
                <?= I18N::translate('Families') ?>
                <?= view('components/badge', ['count' => $families->count()]) ?>
            </a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane active fade show" role="tabpanel" id="details">
            <table class="table wt-facts-table">
                <?php foreach ($facts as $fact) : ?>
                    <?php FunctionsPrintFacts::printFact($fact, $submitter) ?>
                <?php endforeach ?>
            </table>
        </div>

        <div class="tab-pane fade" role="tabpanel" id="individuals">
            <?= view('lists/individuals-table', ['individuals' => $individuals, 'sosa' => false, 'tree' => $tree]) ?>
        </div>

        <div class="tab-pane fade" role="tabpanel" id="families">
            <?= view('lists/families-table', ['families' => $families, 'tree' => $tree]) ?>
        </div>
    </div>
</div>

<?= view('modals/ajax') ?>
