<?php

use Fisharebest\Webtrees\Http\RequestHandlers\UserPageBlock;
use Fisharebest\Webtrees\Module\ModuleBlockInterface;
use Fisharebest\Webtrees\Tree;

/**
 * @var ModuleBlockInterface $block
 * @var int                  $block_id
 * @var Tree                 $tree
 */

?>

<?php if ($block->loadAjax()) : ?>
    <div class="wt-ajax-load" data-ajax-url="<?= e(route(UserPageBlock::class, ['tree' => $tree->name(), 'block_id' => $block_id])) ?>"></div>
<?php else : ?>
    <?= $block->getBlock($tree, $block_id, ModuleBlockInterface::CONTEXT_USER_PAGE) ?>
<?php endif ?>
