<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var string $title
 */

?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<div class="wt-page-content">
    <p>
        <?= I18N::translate('You have confirmed your request to become a registered user.') ?>
    </p>
    <p>
        <?= I18N::translate('The administrator has been informed. As soon as they give you permission to sign in, you can sign in with your username and password.') ?>
    </p>
</div>
