<?php

/**
 * webtrees: online genealogy
 * Copyright (C) 2026 webtrees development team
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace Fisharebest\Webtrees\Http\Middleware;

use Fisharebest\Webtrees\Enums\HttpStatusCode;
use Fisharebest\Webtrees\Services\PhpService;
use Fisharebest\Webtrees\Webtrees;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Throwable;

use function e;
use function error_get_last;
use function get_class;
use function register_shutdown_function;
use function response;
use function str_replace;
use function view;

use const E_ERROR;
use const PHP_EXTRA_VERSION;
use const PHP_OS;
use const PHP_SAPI;
use const PHP_VERSION;

/**
 * Low-level exception handler. Catches errors early in the bootstrap process,
 * or generated by a higher-level exception handler.
 */
final readonly class HandleBootstrapExceptions extends AbstractExceptionHandler implements MiddlewareInterface
{
    public function __construct(
        private PhpService $php_service
    ) {
    }

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        register_shutdown_function($this->shutdownHandler(...));

        try {
            return $handler->handle($request);
        } catch (Throwable $exception) {
            $this->closeOutputBuffers();

            $trace    = $this->stackTrace($exception);
            $server   = $request->getServerParams()['SERVER_SOFTWARE'] ?? 'unknown';
            $php      = PHP_VERSION . PHP_EXTRA_VERSION . ' (' . PHP_OS . ', ' . PHP_SAPI . ', ' . $server . ')';

            // Redact the host name
            $host    = $request->getUri()->getHost();
            $referer = str_replace('//' . $host . '/', '//[REDACTED]/', $request->getHeaderLine('referer'));
            $url     = str_replace('//' . $host . '/', '//[REDACTED]/', (string) $request->getUri());

            if ($this->isAjaxRequest($request)) {
                $html = view('components/alert-danger', ['alert' => $trace]);

                return response($html, HttpStatusCode::InternalServerError);
            }

            $html = view('layouts/exception', [
                'method'   => $request->getMethod(),
                'php'      => $php,
                'referer'  => $referer,
                'title'    => Webtrees::NAME . ' ' . Webtrees::VERSION . ': ' . get_class($exception),
                'trace'    => $trace,
                'url'      => $url,
            ]);

            return response($html, HttpStatusCode::InternalServerError);
        }
    }

    /**
     * Fatal errors. If PHP didn't display it, then we need to.
     * We could be out of memory, so don't create any temporary variables.
     */
    private function shutdownHandler(): void
    {
        if (((error_get_last()['type'] ?? 0) & E_ERROR) !== 0 && !$this->php_service->displayErrors()) {
            echo
                '<pre>' .
                (error_get_last()['message'] ?? 'unknown') . '<br>' .
                (error_get_last()['file'] ?? 'unknown') . ': ' .
                (error_get_last()['line'] ?? 'unknown') .
                '</pre>';
        }
    }
}
