<?php

/**
 * webtrees: online genealogy
 * Copyright (C) 2021 webtrees development team
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace Fisharebest\Webtrees\Module;

use Illuminate\Support\Collection;

/**
 * Class HistoryMonarchsFrench
 */
class HistoryMonarchsFrench extends AbstractModule implements ModuleHistoricEventsInterface
{
    use ModuleHistoricEventsTrait;

    /**
     * How should this module be identified in the control panel, etc.?
     *
     * @return string
     */
    public function title(): string
    {
        return 'Les Monarques des Francs et de France 🇫🇷';
    }

    /**
     * Should this module be enabled when it is first installed?
     *
     * @return bool
     */
    public function isEnabledByDefault(): bool
    {
        return false;
    }

    /**
     * All events provided by this module.
     *
     * @return Collection<string>
     */
    public function historicEventsAll(): Collection
    {
        return new Collection([
            "1 EVEN Clovis Ier (vers 446 —  511)\n2 TYPE Roi des Francs d'Orléans\n2 DATE FROM @#DJULIAN@ 481 TO @#DJULIAN@ 511\n2 NOTE Mérovingiens (481 — 751): fils de Childéric Ier et de Basine de Thuringe.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Clovis_Ier)",
            "1 EVEN Clodomir (vers 495 —  524)\n2 TYPE Roi des Francs d'Orléans\n2 DATE FROM @#DJULIAN@ 511 TO @#DJULIAN@ 524\n2 NOTE Mérovingiens (481 — 751): aîné des fils survivants de Clovis Ier et de Clotilde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Clodomir)",
            "1 EVEN Thierry Ier (vers 485/490 —  534)\n2 TYPE Roi des Francs de Metz et Roi des Francs d'Orléans\n2 DATE FROM @#DJULIAN@ 511 TO @#DJULIAN@ 534\n2 NOTE Mérovingiens (481 — 751): aîné des fils survivants de Clovis Ier et de Evochilde, princesse franque.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Thierry_Ier)",
            "1 EVEN Thibert Ier (vers 504 —  548)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 534 TO @#DJULIAN@ 548\n2 NOTE Mérovingiens (481 — 751): fils du roi Thierry.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Thibert_Ier)",
            "1 EVEN Thibaut (vers 535 —  555)\n2 TYPE Roi des Francs de Metz\n2 DATE FROM @#DJULIAN@ 548 TO @#DJULIAN@ 555\n2 NOTE Mérovingiens (481 — 751): fils de Thibert Ier et de Deoteria.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Thibaut_(roi_des_Francs))",
            "1 EVEN Childebert Ier (vers 497 —  558)\n2 TYPE Roi de Francs des Paris\n2 DATE FROM @#DJULIAN@ 511 TO @#DJULIAN@ 558\n2 NOTE Mérovingiens (481 — 751): quatrième fils de Clovis et le troisième des quatre que ce dernier eut avec Clotilde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Childebert_Ier)",
            "1 EVEN Clotaire Ier «le Vieux» (vers 498 —  561)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 511 TO @#DJULIAN@ 561\n2 NOTE Mérovingiens (481 — 751): benjamin des fils survivants de Clovis Ier et Clotilde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Clotaire_Ier)",
            "1 EVEN Caribert Ier (vers 521 —  567)\n2 TYPE Roi de Paris\n2 DATE FROM @#DJULIAN@ 561 TO @#DJULIAN@ 567\n2 NOTE Mérovingiens (481 — 751): aîné des fils survivants de Clotaire Ier et d'Ingonde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Caribert_Ier)",
            "1 EVEN Sigebert Ier (535 —  575)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 561 TO @#DJULIAN@ 575\n2 NOTE Mérovingiens (481 — 751): fils de Clotaire Ier et d’Ingonde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Sigebert_Ier)",
            "1 EVEN Chilpéric Ier (vers 526 —  584)\n2 TYPE Roi des Soissons\n2 DATE FROM @#DJULIAN@ 561 TO @#DJULIAN@ 584\n2 NOTE Mérovingiens (481 — 751): deuxième des fils survivants de Clotaire Ier et d'Ingonde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Chilpéric_Ier_(roi_des_Francs))",
            "1 EVEN Gontran (vers 533 —  592)\n2 TYPE Roi des Orléanais\n2 DATE FROM @#DJULIAN@ 561 TO @#DJULIAN@ 592\n2 NOTE Mérovingiens (481 — 751): troisième  des fils survivants de Clotaire Ier et d'Ingonde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Gontran_(roi))",
            "1 EVEN Childebert II (570 —  596)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 575 TO @#DJULIAN@ 596\n2 NOTE Mérovingiens (481 — 751): fils de Sigebert Ier et de Brunehaut.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Childebert_II)",
            "1 EVEN Thibert II (585  —   612)\n2 TYPE Roi des Francs d'Austrasie\n2 DATE FROM @#DJULIAN@ 595 TO @#DJULIAN@ 612\n2 NOTE Mérovingiens (481 — 751): fils de  Childebert II et de Faileube.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Thibert_II)",
            "1 EVEN Thierry II (587  —   613)\n2 TYPE Roi des Francs d'Austrasie et des Burgondes\n2 DATE FROM @#DJULIAN@ 595 TO @#DJULIAN@ 613\n2 NOTE Mérovingiens (481 — 751): fils de  Childebert II et de Faileube.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Thierry_II_(roi))",
            "1 EVEN Sigebert II (vers 601 —  613)\n2 TYPE Roi des Francs d'Austrasie et des Burgondes\n2 DATE FROM @#DJULIAN@ 613 TO @#DJULIAN@ 613\n2 NOTE Mérovingiens (481 — 751): fils de Thierry II et d'Ermenberge.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Sigebert_II)",
            "1 EVEN Clotaire II «le Jeune» (587  —   613)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 584 TO @#DJULIAN@ 629\n2 NOTE Mérovingiens (481 — 751): fils de Chilpéric Ier et de Frédégonde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Clotaire_II)",
            "1 EVEN Dagobert Ier (vers 602/605 —   639)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 623 TO @#DJULIAN@ 639\n2 NOTE Mérovingiens (481 — 751): fils aîné de Clotaire II et de Bertrude.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Dagobert_Ier)",
            "1 EVEN Caribert II (vers 606/610 —  632)\n2 TYPE Roi d'Aquitaine\n2 DATE FROM @#DJULIAN@ 629 TO @#DJULIAN@ 632\n2 NOTE Mérovingiens (481 — 751): fils cadet de Clotaire II et de Sichilde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Caribert_II)",
            "1 EVEN Sigebert III (vers (631 — 656)\n2 TYPE Roi des Francs d'Austrasie\n2 DATE FROM @#DJULIAN@ 639 TO @#DJULIAN@ 656\n2 NOTE Mérovingiens (481 — 751): fils de Dagobert Ier et de Ragnétrude.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Sigebert_III)",
            "1 EVEN Clovis II «le Fainéant» (633 — 657)\n2 TYPE Roi des Francs de Neustrie et des Burgondes\n2 DATE FROM @#DJULIAN@ 639 TO @#DJULIAN@ 657\n2 NOTE Mérovingiens (481 — 751): fils de Dagobert Ier et de Nantilde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Clovis_II)",
            "1 EVEN Childebert III «l'Adopté» (vers 650 — 662)\n2 TYPE Roi des Francs d'Austrasie\n2 DATE FROM @#DJULIAN@ 656 TO @#DJULIAN@ 662\n2 NOTE Mérovingiens (481 — 751): les deux thèses quant à son identité véritable: 1) fils de Grimoald adopté par Sigebert III selon le Liber Historiae Francorum, 2) fils de Sigebert III adopté par Grimoald selon plusieurs historiens.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Childebert_III_l'Adopté)",
            "1 EVEN Clotaire III (vers 652 — 673)\n2 TYPE Roi des Francs de Neustrie et des Burgondes\n2 DATE FROM @#DJULIAN@ 657 TO @#DJULIAN@ 673\n2 NOTE Mérovingiens (481 — 751): fils de Clovis II et de Bathilde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Clotaire_III)",
            "1 EVEN Childéric II (vers 655 — 675)\n2 TYPE Roi des Francs d'Austrasie\n2 DATE FROM @#DJULIAN@ 662 TO @#DJULIAN@ 675\n2 NOTE Mérovingiens (481 — 751): fils cadet de Clovis II et de Bathilde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Childéric_II)",
            "1 EVEN Thierry III (vers 657 — 691)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 675 TO @#DJULIAN@ 691\n2 NOTE Mérovingiens (481 — 751): dernier fils cadet de Clovis II et de Bathilde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Thierry_III)",
            "1 EVEN Clovis III (vers 670 — 676)\n2 TYPE Roi des Francs d'Austrasie\n2 DATE FROM @#DJULIAN@ 675 TO @#DJULIAN@ 676\n2 NOTE Mérovingiens (481 — 751): fils prétendu du roi Clotaire III, mais en fait un imposteur produit le maire du palais Ébroïn.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Clovis_III)",
            "1 EVEN Dagobert II (vers 652 — 679)\n2 TYPE Roi des Francs d'Austrasie\n2 DATE FROM @#DJULIAN@ 676 TO @#DJULIAN@ 679\n2 NOTE Mérovingiens (481 — 751): fils de Sigebert III et de Chimnechilde (possible).\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Dagobert_II)",
            "1 EVEN Clovis IV (vers 680 — 695)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 691 TO @#DJULIAN@ 695\n2 NOTE Mérovingiens (481 — 751): fils ainé de Thierry III et de Clotilde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Clovis_IV)",
            "1 EVEN Childebert IV (vers 683 — 711)\n2 TYPE Roi des Francs de Neustrie\n2 DATE FROM @#DJULIAN@ 695 TO @#DJULIAN@ 711\n2 NOTE Mérovingiens (481 — 751): fils cadet de Thierry III et de Clotilde.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Childebert_IV)",
            "1 EVEN Dagobert III (vers 699 — 715)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 711 TO @#DJULIAN@ 715\n2 NOTE Mérovingiens (481 — 751): fils probable de Childebert IV.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Dagobert_III)",
            "1 EVEN Chilpéric II (vers 670 — 721)\n2 TYPE Roi des Francs d'Austrasie\n2 DATE FROM @#DJULIAN@ 715 TO @#DJULIAN@ 721\n2 NOTE Mérovingiens (481 — 751): fils probable de Thierry III.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Clotaire_IV)",
            "1 EVEN Thierry IV (vers 713 — 737)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 721 TO @#DJULIAN@ 737\n2 NOTE Mérovingiens (481 — 751): fils de Dagobert III.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Thierry_IV)",
            "1 EVEN Interrègne\n2 DATE FROM @#DJULIAN@ 737 TO @#DJULIAN@ 743",
            "1 EVEN Childéric III «le Fainéant» (vers 714 — vers 754/755)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 743 TO @#DJULIAN@ 751\n2 NOTE Mérovingiens (481 — 751): d'ascendance incertaine. Placé sur le trône par le maire du palais Pépin le Bref.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Childéric_III)",
            "1 EVEN Pépin III «le Bref» (vers 715 — 768)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ NOV 751 TO @#DJULIAN@ 24 SEP 768\n2 NOTE Carolingiens (751 — 987): fils cadet de Charles Martel et de Rotrude.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Pépin_le_Bref)",
            "1 EVEN Carloman Ier (vers 751 — 771)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 24 SEP 768 TO @#DJULIAN@ 04 DEC 771\n2 NOTE Carolingiens (751 — 987): fils cadet de Pépin le Bref et de Bertrade de Laon.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Carloman_Ier)",
            "1 EVEN Charlemagne ou Charles Ier « le Grand » (742 — 814)\n2 TYPE Roi des Francs et Empereur d'Occident\n2 DATE FROM @#DJULIAN@ 24 SEP 768 TO @#DJULIAN@ 28 JAN 814\n2 NOTE Carolingiens (751 — 987): fils aîné de Pépin le Bref et de Bertrade de Laon.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Charlemagne)",
            "1 EVEN Louis Ier «le Pieux» ou «le Débonnaire» (778 — 840)\n2 TYPE Roi des Francs et Empereur d'Occident\n2 DATE FROM @#DJULIAN@ 28 JAN 814 TO @#DJULIAN@ 20 JUN 840\n2 NOTE Carolingiens (751 — 987): fils de Charlemagne et d'Hildegarde de Vintzgau. \n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_le_Pieux)",
            "1 EVEN Charles II «le Chauve» (823 — 877)\n2 TYPE Roi des Francs et Empereur d'Occident\n2 DATE FROM @#DJULIAN@ AUG 843 TO @#DJULIAN@ 06 OCT 877\n2 NOTE Carolingiens (751 — 987): benjamin des fils de Louis le Pieux, le seul par sa deuxième femme Judith de Bavière.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Charles_II_le_Chauve)",
            "1 EVEN Louis II «le Bègue» (846 — 879)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 06 OCT 877 TO @#DJULIAN@ 11 APR 879\n2 NOTE Carolingiens (751 — 987): fils aîné de Charles II et d'Ermentrude d'Orléans.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_II_le_Bègue)",
            "1 EVEN Louis III (vers 864 — 882)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 11 APR 879 TO @#DJULIAN@ 05 AUG 882\n2 NOTE Carolingiens (751 — 987): fils aîné  de Louis II et d'Ansgarde de Bourgogne.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_III_(roi_des_Francs))",
            "1 EVEN Carloman II (vers 867 — 884)\n2 TYPE Roi des Francs associé\n2 DATE FROM @#DJULIAN@ 11 APR 879 TO @#DJULIAN@ 06 DEC 884\n2 NOTE Carolingiens (751 — 987): fils de Louis II et d'Ansgarde de Bourgogne.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Carloman_II)",
            "1 EVEN Charles III «le Gros» (839— 888)\n2 TYPE Roi des Francs et Empereur d'Occident\n2 DATE FROM @#DJULIAN@ JUN 885 TO @#DJULIAN@ NOV 887\n2 NOTE Carolingiens (751 — 987): troisième fils de Louis le Germanique et d'Emma de Bavière. Incapable de faire face aux Normands, il est déposé en novembre 887.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Charles_III_le_Gros)",
            "1 EVEN Eudes Ier (852— 898)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 29 FEB 888 TO @#DJULIAN@ 03 JAN 898\n2 NOTE Carolingiens (751 — 987): fils aîné de Robert le Fort et d'Adélaïde de Tours.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Eudes_(roi_des_Francs))",
            "1 EVEN Charles III «le Simple» (879— 929)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 03 JAN 898 TO @#DJULIAN@ 29 JUN 922\n2 NOTE Carolingiens (751 — 987): troisième fils de Louis II, le seul par sa deuxième femme Adélaïde de Frioul.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Charles_III_le_Simple)",
            "1 EVEN Robert Ier (860— 923)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@  29 JUN 922 TO @#DJULIAN@ 15 JUN 923\n2 NOTE Carolingiens (751 — 987): fils de Robert le Fort et d'Adélaïde de Tours  frère d'Eudes Ier.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Robert_Ier_(roi_des_Francs))",
            "1 EVEN Raoul (890— 936)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 15 JUN 923 TO @#DJULIAN@ 15 JAN 936\n2 NOTE Carolingiens (751 — 987): fils de Richard II de Bourgogne et d'Adélaïde de Bourgogne.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Raoul_(roi_des_Francs))",
            "1 EVEN Louis IV «d'Outremer» (920 ou 921— 954)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 19 JUN 936 TO @#DJULIAN@ 10 SEP 954\n2 NOTE Carolingiens (751 — 987): seul fils de Charles III le Simple et d'Edwige de Wessex.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_IV_d'Outremer)",
            "1 EVEN Lothaire (941— 986)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 10 SEP 954 TO @#DJULIAN@ 02 MAR 986\n2 NOTE Carolingiens (751 — 987): fils de Louis IV et de Gerberge de Saxe.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Lothaire_(roi_des_Francs))",
            "1 EVEN Louis V «le Fainéant» (ver 967 — 987)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 2 MAR 986 TO @#DJULIAN@ 21 MAY 987\n2 NOTE Carolingiens (751 — 987): fils de Lothaire et d'Emma d'Italie\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_V_le_Fainéant)",
            "1 EVEN Hugues Ier «Capet» (vers 940 —  996)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 03 JUN 987 TO @#DJULIAN@ 24 OCT 996\n2 NOTE Capétiens directs (987 — 1328): fils de Hugues le Grand et de Hedwige de Saxe.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Hugues_Capet)",
            "1 EVEN Robert II «le Pieux» (972 —  1031)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 24 OCT 996 TO @#DJULIAN@ 20 JUL 1031\n2 NOTE Capétiens directs (987 — 1328): fils d’Hugues Capet et de Adélaïde d'Aquitaine.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Robert_II_le_Pieux)",
            "1 EVEN Hugues (1007 —  1025)\n2 TYPE Roi des Francs associé\n2 DATE FROM @#DJULIAN@ 19 JUN 1017 TO @#DJULIAN@ 17 SEP 1025\n2 NOTE Capétiens directs (987 — 1328): fils de Robert II le Pieux et de Constance d'Arles. Sacré à Compiègne, il règne conjointement avec son père, mais meurt avant lui.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Hugues_de_France_(1007-1025))",
            "1 EVEN Henri Ier (1008 —  1060)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 20 JUL 1031 TO @#DJULIAN@ 04 AUG 1060\n2 NOTE Capétiens directs (987 — 1328): deuxième fils de Robert II et de Constance d'Arles.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Henri_Ier_(roi_des_Francs))",
            "1 EVEN Philippe Ier (1052 —  1108)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@ 04 AUG 1060 TO @#DJULIAN@ 29 JUL 1108\n2 NOTE Capétiens directs (987 — 1328): fils aîné d'Henri Ier et d'Anne de Kiev.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Philippe_Ier_(roi_des_Francs))",
            "1 EVEN Louis VI «le Gros» ou «le Batailleur» (1081 —  1137)\n2 TYPE Roi des Francs\n2 DATE FROM @#DJULIAN@  29 JUL 1109 TO @#DJULIAN@ 01 AUG 1137\n2 NOTE Capétiens directs (987 — 1328): fils aîné de Philippe Ier et de Berthe de Hollande.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_VI_le_Gros)",
            "1 EVEN Philippe (1116 —  1131)\n2 TYPE Roi des Francs associé\n2 DATE FROM @#DJULIAN@  14 APR 1129 TO @#DJULIAN@ 14 OCT 1131\n2 NOTE Capétiens directs (987 — 1328): premier fils de Louis VI et Adélaïde de Savoie. Sacré en 1129, il règne conjointement avec son père avant de mourir prématurément en 1131.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Philippe_de_France_(1116-1131))",
            "1 EVEN Louis VII «le Jeune» ou «le Pieux» (1120 —  1180\n2 TYPE Roi de Francs\n2 DATE FROM @#DJULIAN@ 01 AUG 1137 TO @#DJULIAN@ 18 SEP 1180\n2 NOTE Capétiens directs (987 — 1328): deuxième fils de Louis VI et d'Adélaïde de Savoie. \n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_VII_le_Jeune)",
            "1 EVEN Philippe II «Auguste» (1165 —  1123)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 18 SEP 1180 TO @#DJULIAN@ 14 JUL 1223\n2 NOTE Capétiens directs (987 — 1328): fils de Louis VII et d'Adèle de Champagne. Premier roi à utiliser le titre de „Roi de France‟ .\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Philippe_II_Auguste)",
            "1 EVEN Louis VIII «le Lion» (1187 —  1226)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 14 JUL 1223 TO @#DJULIAN@ 08 NOV 1226\n2 NOTE Capétiens directs (987 — 1328): fils aîné de Philippe II et d'Isabelle de Hainaut.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_VIII_le_Lion)",
            "1 EVEN Louis IX «le Prudhomme» ou «Saint Louis» (1214 —  1270)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 08 NOV 1226 TO @#DJULIAN@ 25 AUG 1270\n2 NOTE Capétiens directs (987 — 1328): quatrième fils de Louis VIII et de Blanche de Castille.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_IX)",
            "1 EVEN Philippe III «le Hardi» (1245 —  1285)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 25 AUG 1270 TO @#DJULIAN@ 05 OCT 1285\n2 NOTE Capétiens directs (987 — 1328): deuxième fils de Louis IX et de Marguerite de Provence.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Philippe_III_le_Hardi)",
            "1 EVEN Philippe IV «le Bel» (1268 —  1314\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 05 OCT 1285 TO @#DJULIAN@ 29 NOV 1314\n2 NOTE Capétiens directs (987 — 1328): deuxième fils de Philippe III et d'Isabelle d'Aragon. \n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Philippe_IV_le_Bel)",
            "1 EVEN Louis X «le Hutin» (1289 —  1316)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 29 NOV 1314 TO @#DJULIAN@ 05 JUN 1315\n2 NOTE Capétiens directs (987 — 1328): fils aîné de Philippe IV et de Jeanne de Navarre. \n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_X)",
            "1 EVEN Jean Ier «le Posthume» (1316 —  1316)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 15 NOV 1315 TO @#DJULIAN@ 19 NOV 1315\n2 NOTE Capétiens directs (987 — 1328): fils de Louis X et de Clémence de Hongrie. Il est le seul roi de France à avoir régné de sa naissance à sa mort.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Jean_Ier_le_Posthume)",
            "1 EVEN Philippe V «le Long» (1293 —  1322)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 19 NOV 1316 TO @#DJULIAN@ 03 JAN 1322\n2 NOTE Capétiens directs (987 — 1328): deuxième fils de Philippe IV et de Jeanne de Navarre. \n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Philippe_V_le_Long)",
            "1 EVEN Charles IV «le Bel» (1294 —  1328)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 03 JAN 1322 TO @#DJULIAN@ 01 FEB 1328\n2 NOTE Capétiens directs (987 — 1328): troisième fils de Philippe IV et de Jeanne de Navarre\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Charles_IV_le_Bel)",
            "1 EVEN Philippe VI de Valois (1293 —  1350)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 01 FEB 1328 TO @#DJULIAN@ 22 AUG 1350\n2 NOTE Valois (1328 — 1589): fils aîné de Charles de Valois, frère cadet du roi Philippe IV «le Bel», et de Marguerite d'Anjou.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Philippe_VI_de_Valois)",
            "1 EVEN Jean II «le Bon» (1319 —  1364)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 22 AUG 1350 TO @#DJULIAN@ 08 APR 1364\n2 NOTE Valois (1328 — 1589): fils aîné de Philippe VI et de Jeanne de Bourgogne.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Jean_II_le_Bon)",
            "1 EVEN Charles V «le Sage» (1338 —  1380)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 08 APR 1364 TO @#DJULIAN@ 16 SEP 1380\n2 NOTE Valois (1328 — 1589): fils aîné de Jean II et de Bonne de Luxembourg.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Charles_V_le_Sage)",
            "1 EVEN Charles VI «le Bien-Aimé» ou «le Fol» (1368 —  1422)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 16 SEP 1380 TO @#DJULIAN@ 22 OCT 1422\n2 NOTE Valois (1328 — 1589): aîné des fils survivants de Charles V et de Jeanne de Bourbon. \n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Charles_VI_(roi_de_France))",
            "1 EVEN Charles VII «le Victorieux» ou «le Bien Servi» (1403 —  1461)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 22 OCT 1422 TO @#DJULIAN@ 22 JUL 1461\n2 NOTE Valois (1328 — 1589): dernier fils survivant de Charles VI et d'Isabeau de Bavière.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Charles_VII_(roi_de_France))",
            "1 EVEN Louis XI «le Prudent»  ou «Universelle Aragne»  (1423 —  1483)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 22 JUL 1461 TO @#DJULIAN@ 30 AUG 1483\n2 NOTE Valois (1328 — 1589): fils aîné de Charles VII et de Marie d'Anjou.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_XI)",
            "1 EVEN Charles VIII «l’Affable» (1470 —  1498)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 30 AUG 1483 TO @#DJULIAN@ 07 APR 1498\n2 NOTE Valois (1328 — 1589): seul fils de Louis XI et de Charlotte de Savoie\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Charles_VIII_(roi_de_France))",
            "1 EVEN Louis XII «le Père du Peuple» (1462 —  1515)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 07 APR 1498 TO @#DJULIAN@ 01 JAN 1515\n2 NOTE Valois (1328 — 1589): fils de Charles d'Orléans, le prince poète, et de Marie de Clèves.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_XII)",
            "1 EVEN François Ier «le Père et Restaurateur des Lettres» (1494 —  1547)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 01 JAN 1515 TO @#DJULIAN@ 01 MAR 1547\n2 NOTE Valois (1328 — 1589): gils de Charles d'Orléans et de Louise de Savoie\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/François_Ier_(roi_de_France))",
            "1 EVEN Henri II (1519 —  1559)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 01 MAR 1547 TO @#DJULIAN@ 10 JUL 1559\n2 NOTE Valois (1328 — 1589): deuxième fils de François Ier et de Claude de France.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Henri_II_(roi_de_France))",
            "1 EVEN François II (1544 —  1560)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 10 JUL 1559 TO @#DJULIAN@ 05 DEC 1560\n2 NOTE Valois (1328 — 1589): fils aîné d'Henri II et de Catherine de Médicis.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Fran%C3%A7ois_II_(roi_de_France))",
            "1 EVEN Charles IX (1550 —  1574)\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 05 DEC 1560 TO @#DJULIAN@ 30 MAY 1574\n2 NOTE Valois (1328 — 1589): troisième fils d'Henri II et de Catherine de Médicis.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Charles_IX_(roi_de_France))",
            "1 EVEN Henri III (1551 —  1589\n2 TYPE Roi de France\n2 DATE FROM @#DJULIAN@ 30 MAY 1574 TO 02 AUG 1589\n2 NOTE Valois (1328 — 1589): quatrième fils d'Henri II et de Catherine de Médicis.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Henri_III_(roi_de_France))",
            "1 EVEN Henri IV «le Grand»  ou «le Vert-Galant» (1553 —  1610)\n2 TYPE Roi de France\n2 DATE FROM 02 AUG 1589 TO 14 MAY 1610\n2 NOTE Bourbons (1589 — 1792): fils de Jeanne d'Albret, reine de Navarre et d'Antoine de Bourbon.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Henri_IV_(roi_de_France))",
            "1 EVEN Louis XIII «le Juste» (1610 —  1643)\n2 TYPE Roi de France et de Navarre\n2 DATE FROM 14 MAY 1610 TO 14 MAY 1643\n2 NOTE Bourbons (1589 — 1792): fils aîné d'Henri IV et de Marie de Médicis.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_XIII)",
            "1 EVEN Louis XIV «le Grand» ou  le Roi-Soleil» (1638 —  1715)\n2 TYPE Roi de France et de Navarre\n2 DATE FROM 14 MAY 1643 TO 01 SEP 1715\n2 NOTE Bourbons (1589 — 1792): fils aîné de Louis XIII et d'Anne d'Autriche.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_XIV)",
            "1 EVEN Louis XV «le Bien -Aimé» (1710 —  1774)\n2 TYPE Roi de France et de Navarre\n2 DATE FROM 01 SEP 1715 TO 10 MAY 1774\n2 NOTE Bourbons (1589 — 1792): troisième fils de Louis de France et de Marie — Adélaïde de Savoie.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_XV)",
            "1 EVEN Louis XVI (1754 —  1793)\n2 TYPE Roi des Français\n2 DATE FROM 10 MAY 1774 TO 21 JAN 1793\n2 NOTE Bourbons (1589 — 1792): fils de Louis de France et de Marie — Josèphe de Saxe.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_XVI)",
            "1 EVEN Louis XVII (1785 —  1795)\n2 TYPE Prétendant aux trônes de France et de Navarre\n2 DATE FROM 21 JAN 1793 TO 08 JUN 1795\n2 NOTE Bourbons (1589 — 1792): deuxième fils de Louis XVI et de Marie — Antoinette.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_XVII)",
            "1 EVEN Napoléon Ier (1769 —  1821)\n2 TYPE Empereur des Français\n2 DATE FROM 02 DEC 1804 TO 06 APR 1814\n2 NOTE Bonaparte (1804 — 1814): deuxième fils de Charles Bonaparte et Letizia Ramolino.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Napoléon_Ier)",
            "1 EVEN Louis XVIII (1755 —  1824)\n2 TYPE Roi de France et de Navarre\n2 DATE FROM 06 APR 1814 TO 20 MAR 1815\n2 NOTE Bourbons (1814 — 1815): quatrième fils de Louis de France et de sa seconde épouse Marie — Josèphe de Saxe.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_XVIII)",
            "1 EVEN Napoléon Ier (1769 —  1821)\n2 TYPE Empereur des Français\n2 DATE FROM 20 MAR 1815 TO 22 JUN 1815\n2 NOTE Bonaparte (1815): deuxième fils de Charles Bonaparte et Letizia Ramolino.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Napoléon_Ier)",
            "1 EVEN Napoléon II (1811 —  1832)\n2 TYPE Empereur des Français\n2 DATE FROM 22 JUN 1815 TO 07 JUL 1815\n2 NOTE Bonaparte (1815): le fils de Napoléon Ier et de sa seconde épouse, Marie — Louise d'Autriche.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Napoléon_II)",
            "1 EVEN Louis XVIII (1755 —  1824)\n2 TYPE Roi de France et de Navarre\n2 DATE FROM 08 JUL 1817 TO 16 SEP 1824\n2 NOTE Bourbons (1815 — 1830): quatrième fils de Louis de France et de sa seconde épouse Marie — Josèphe de Saxe.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis_XVIII)",
            "1 EVEN Charles X (1757 —  1836)\n2 TYPE Roi de France et de Navarre\n2 DATE FROM 16 SEP 1824 TO 02 AUG 1830\n2 NOTE Bourbons (1815 — 1830): cinquième fils de Louis de France et de sa seconde épouse Marie — Josèphe de Saxe.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Charles_X)",
            "1 EVEN Louis-Philippe Ier «Roi-Citoyen» ou le «Roi bourgeois» ou le «Roi des barricades» (1773 —  1850)\n2 TYPE Roi des Français\n2 DATE FROM 09 AUG 1830 TO 24 FEB 1848\n2 NOTE Orléans (1830 — 1848): fils de Louis Philippe Joseph d'Orléans et de Louise Marie — Adélaïde de Bourbon. Il est le dernière Roi de Français.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/Louis-Philippe_Ier)",
            "1 EVEN Napoléon III (1808 —  1873)\n2 TYPE Empereur des Français\n2 DATE FROM 02 DEC 1852 TO 04 SEP 1870\n2 NOTE Bonaparte (1852 — 1870): troisième fils de Louis Bonaparte et d'Hortense de Beauharnais. Il est le dernière Monarque de France.\n2 SOUR [Wikipedia: Liste des monarques de France](https://fr.wikipedia.org/wiki/https://fr.wikipedia.org/wiki/Napoléon_III)",
        ]);
    }
}
