<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\I18N;
use Illuminate\Support\Collection;

/**
 * @var int                  $limit_high
 * @var int                  $limit_low
 * @var Collection<int,Fact> $tasks
 */

?>

<table
    class="table table-bordered table-sm wt-table-tasks datatables d-none"
    style="table-layout: fixed"
    <?= view('lists/datatables-attributes') ?>
    data-paging="<?= $tasks->count() >= $limit_high ? 'true' : 'false' ?>"
    data-filter="false"
    data-info="false"
    data-length-change="false"
    data-page-length="<?= e($limit_low) ?>"
>
    <thead>
        <tr>
            <th class="w-50 d-none d-md-table-cell wt-side-block-optional">
                <?= I18N::translate('Date') ?>
            </th>
            <th class="w-50">
                <?= I18N::translate('Record') ?>
            </th>
            <th class="w-50 d-none d-md-table-cell wt-side-block-optional">
                <?= I18N::translate('Username') ?>
            </th>
            <th class="w-50">
                <?= I18N::translate('Research task') ?>
            </th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($tasks as $task) : ?>
            <tr>
                <td data-sort="<?= sprintf('x%07d', $task->date()->julianDay()) ?>" class="d-none d-md-table-cell wt-side-block-optional">
                    <?= $task->date()->display() ?>
                </td>
                <td data-sort="<?= e($task->record()->sortName()) ?>">
                    <a href="<?= e($task->record()->url()) ?>">
                        <?= $task->record()->fullName() ?>
                    </a>
                </td>
                <td class="d-none d-md-table-cell wt-side-block-optional">
                    <?= e($task->attribute('_WT_USER')) ?>
                </td>
                <td class="ut" dir="auto">
                    <?= e($task->value()) ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
