<?php

use Fisharebest\Webtrees\I18N;

?>

<p>
    <?= I18N::translate('Data fixes can require lots of slow calculations, so it is not possible to create an exact list of records that need to be updated.') ?>
</p>

<p>
    <?= I18N::translate('For example, we can quickly find individuals that do not have a death event, but it is much slower to calculate if the individual is dead.') ?>
</p>

<p>
    <?= I18N::translate('This list is created using a simple (but fast) search, and therefore includes records that will not be updated.') ?>
</p>
