<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\HelpText;
use Fisharebest\Webtrees\I18N;

/**
 * @var string $topic
 */

?>
<a href="#" data-bs-toggle="modal" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e(route(HelpText::class, ['topic' => $topic])) ?>" title="<?= I18N::translate('Help') ?>">
    <?= view('icons/help') ?>
    <span class="visually-hidden"><?= I18N::translate('Help') ?></span>
</a>
