<?php

use Fisharebest\Webtrees\I18N;

?>

<p>
    <?= I18N::translate('A media object is a record in the family tree which contains information about a media file. This information may include a title, a copyright notice, a transcript, privacy restrictions, etc. The media file, such as the photo or video, can be stored locally (on this webserver) or remotely (on a different webserver).') ?>
</p>
