<?php

use Fisharebest\Webtrees\I18N;

?>

<p>
    <?= I18N::translate('Place names should be entered as a comma-separated list, starting with the smallest place and ending with the country. For example, “Westminster, London, England”.') ?>
</p>

<p>
    <?= I18N::translate('Place names can change over time.  In genealogy, it is customary to use the current name for a town or country. The historic name can be shown in sources, notes, etc.') ?>
</p>
