<?php
use Fisharebest\Webtrees\I18N;
?>

<div id="google_charts" class="center">
    <p><?= $chart_title ?></p>
    <div>
        <img src="<?= $chart_url ?>" alt="<?= $chart_title ?>" title="<?= $chart_title ?>" class="gchart" />
        <br>
        <table class="center">
            <tr>
                <td bgcolor="#<?= $WT_STATS_CHART_COLOR2 ?>" width="12"></td><td><?= I18N::translate('Highest population') ?></td>
                <td bgcolor="#<?= $WT_STATS_CHART_COLOR3 ?>" width="12"></td><td><?= I18N::translate('Lowest population') ?></td>
                <td bgcolor="#<?= $WT_STATS_CHART_COLOR1 ?>" width="12"></td><td><?= I18N::translate('Nobody at all') ?></td>
            </tr>
        </table>
    </div>
</div>
