<?php
use Fisharebest\Webtrees\I18N;

/** @var \Fisharebest\Webtrees\Stats $stats */
?>

<h3>
    <?= I18N::translate('Places'), ': ', $stats->totalPlaces() ?>
</h3>
<table>
    <tr>
        <td><?= I18N::translate('Birth places') ?></td>
        <td><?= I18N::translate('Death places') ?></td>
    </tr>
    <tr>
        <td><?= $stats->commonBirthPlacesList() ?></td>
        <td><?= $stats->commonDeathPlacesList() ?></td>
    </tr>
    <tr>
        <td><?= I18N::translate('Marriage places') ?></td>
        <td><?= I18N::translate('Events in countries') ?></td>
    </tr>
    <tr>
        <td><?= $stats->commonMarriagePlacesList() ?></td>
        <td><?= $stats->commonCountriesList() ?></td>
    </tr>
    <tr>
        <td colspan="2"><?= $stats->chartDistribution() ?></td>
    </tr>
</table>
