<?php
use Fisharebest\Webtrees\I18N;

/** @var \Fisharebest\Webtrees\Stats $stats */
?>

<div class="row">
    <div class="col-md-12">
        <h2>
            <?= I18N::translate('Sources'), ': ', $stats->totalSources() ?>
        </h2>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-sm-12 col-xs-12">
        <span><?= I18N::translate('Individuals with sources'), ': ', $stats->totalIndisWithSources() ?></span>
        <?= $stats->chartIndisWithSources() ?>
    </div>
    <div class="col-md-6 col-sm-12 col-xs-12">
        <span><?= I18N::translate('Families with sources'), ': ', $stats->totalFamsWithSources() ?></span>
        <?= $stats->chartFamsWithSources() ?>
    </div>
</div>
