<?php
use Fisharebest\Webtrees\I18N;

/** @var \Fisharebest\Webtrees\Stats $stats */
?>

<div class="row">
    <div class="col-md-12">
        <h2>
            <?= I18N::translate('Records') ?>: <?= $stats->totalRecords() ?>
        </h2>
    </div>
</div>
<div class="row">
    <div class="col-md-3 col-sm-3 col-xs-6">
        <span><?= I18N::translate('Media objects') ?></span>
        <h2><?= $stats->totalMedia() ?></h2>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-6">
        <span><?= I18N::translate('Sources') ?></span>
        <h2><?= $stats->totalSources() ?></h2>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-6">
        <span><?= I18N::translate('Notes') ?></span>
        <h2><?= $stats->totalNotes() ?></h2>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-6">
        <span><?= I18N::translate('Repositories') ?></span>
        <h2><?= $stats->totalRepositories() ?></h2>
    </div>
</div>
