<?php
use Fisharebest\Webtrees\I18N;

/** @var \Fisharebest\Webtrees\Stats $stats */
?>

<div class="row">
    <div class="col-md-12">
        <h2>
            <?= I18N::translate('Total events'), ': ', $stats->totalEvents() ?>
        </h2>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <span><?= I18N::translate('First event'), ' - ', $stats->firstEventType() ?></span>
        <h2><?= $stats->firstEvent() ?></h2>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <span><?= I18N::translate('Last event'), ' - ', $stats->lastEventType() ?></span>
        <h2><?= $stats->lastEvent() ?></h2>
    </div>
</div>
