<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Place;

/**
 * @var array<array<Place>> $columns
 */

?>

<div class="row">
    <span class="col list_label mr-1">
        <?= I18N::translate('Place list') ?>
    </span>
</div>
<div class="row">
    <?php foreach ($columns as $column) : ?>
        <ul class="col list_value_wrap mr-1 list-unstyled">
            <?php foreach ($column as $place) : ?>
                <li>
                    <a href="<?= e($place->url()) ?>"><?= $place->fullName() ?></a>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endforeach ?>
</div>

