<?php

use Fig\Http\Message\StatusCodeInterface;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;

/**
 * @var string $breadcrumbs
 * @var string $content
 * @var string $title
 * @var Tree   $tree
 */

?>

<div id="place-hierarchy">
  <h4><?= $title ?></h4>
  <h5 class="breadcrumbs text-center"><?= $breadcrumbs ?? '&nbsp' ?></h5>

  <div class="row wt-place-hierarchy-content">
    <?= $content ?>
  </div>

  <div class="invisible place_link text-center my-2">
    <a role="button" class=""></a>
    <div>
      <span role="alert" class="alert alert-warning px-2 py-0">
        <?= I18N::translate('Places with a large number of events may take a long time to load.') ?>
      </span>
    </div>
  </div>

  <div class="row text-content"></div>
</div>

<?php View::push('javascript') ?>
<script>
  'use strict';

  const wt_place_list = (function () {
    const use_map = <?= json_encode($use_map, JSON_THROW_ON_ERROR) ?>;
    const place_summary = <?= json_encode($place_summary, JSON_THROW_ON_ERROR) ?>;
    const events_target = document.querySelector('.text-content');
    const body_target = document.querySelector('.wt-place-hierarchy-content');

    /**
     * @private
     *
     * @param {boolean} showloading
     */
    const _clearText = (showloading) => {
      events_target.innerHTML = '';
      if (showloading) {
        events_target.classList.add('wt-ajax-load');
      } else {
        events_target.classList.remove('wt-ajax-load');
      }
    }

    /**
     * @private
     *
     * @param {object} data
     */
    const _updateLinks = (data) => {
      document.querySelector('.breadcrumbs').innerHTML = data.breadcrumbs;
      const link = document.querySelector('.place_link');
      if (data.place_summary.id === 0) {
        link.classList.add('invisible');
      } else {
        const target = link.querySelector('a');
        target.dataset.id = data.place_summary.id;
        target.innerHTML = data.place_summary.link;
        link.classList.remove('invisible');
      }
      _clearText(false);
    }

    /**
     * @private
     *
     * @param {string}   type
     * @param {integer}  id
     * @param {boolean}  clear
     * @param {function} callback
     */
    const _getData = (type, id, clear, callback) => {
      _clearText(clear);

      const formData = new FormData();

      formData.append('_csrf', document.querySelector('meta[name=csrf]').content);
      formData.append('placeId', id || place_summary.id);
      formData.append('type', type);
      fetch(<?= json_encode(route('module', ['module' => 'places_list', 'action' => 'updateData', 'tree' => $tree->name()]), JSON_THROW_ON_ERROR) ?>, {
          credentials: 'same-origin',
          body: formData,
          method: 'POST',
        })
        .then((response) => {
          if (response.status === <?= json_encode(StatusCodeInterface::STATUS_OK) ?>) {
            return response.text();
          } else {
            throw response;
          }
        })
        .then(callback)
        .catch(error => {
          error.text()
          .then(errorMessage => alert(errorMessage));
        });
    }

    const _getTabularData = (id) => {
      _getData('hierarchy', id, false, function (text) {
        const result = JSON.parse(text);
        body_target.innerHTML = result.data;
        _updateLinks(result);
      });
    }

    // Request for events table
    document.querySelector('.place_link').addEventListener('click', (evt) => {
      evt.stopPropagation();
      _getData('events', evt.target.closest('a').dataset.id, true, function (text) {
        const result = JSON.parse(text);
        events_target.innerHTML = result.data;
      });
    });

    if (!use_map) {
      // act on breadcrumb click
      document.querySelector('.breadcrumbs').addEventListener('click', (evt) => {
        _getTabularData(evt.target.closest('a').dataset.id);
      });

      // Get tabular data
      body_target.addEventListener('click', (evt) => {
        _getTabularData(evt.target.closest('a').dataset.id);
      });

      // load initial data
      _getTabularData(null);
    }

    return {
      updateLinks: _updateLinks,
      getData: _getData,
    }

  })();
</script>
<?php View::endpush() ?>
