<?php

use Fisharebest\Webtrees\Place;
use Fisharebest\Webtrees\I18N;

/**
 * @var Place  $place
 * @var string $latitude
 * @var string $longitude
 */
?>
<div dir="auto" class="label">
    <a role="button" class="map-place" data-id="<?= $place->id() ?>" ><?= $place->placeName() ?></a>
</div>

<table class="table table-borderless">
  <tr>
    <th scope="row" class="p-0"><?= I18N::translate('Latitude') ?></th>
    <td class="p-0 align-digits"><?= $latitude ?></td>
  </tr>
  <tr>
    <th scope="row" class="p-0"><?= I18N::translate('Longitude') ?></th>
    <td class="p-0 align-digits"><?= $longitude ?></td>
  </tr>
</table>
