<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Place;

/**
 * @var bool   $showlink
 * @var Place  $place
 * @var string $flag
 * @var int    $id
 * @var string $sidebar_class
 * @var string $sidebar_title
 * @var array  $stats
 */
?>

<li title="<?= $sidebar_title ?>" class="gchart <?= $sidebar_class ?>" data-id="<?= $id ?>">
    <div class="row">
        <div class="offset-sm-1 col-sm-7 label">
            <?php if ($showlink) : ?>
                <a href="<?= e($place->url()) ?>">
                    <?= $place->placeName() ?>
                </a>
            <?php else : ?>
                <?= $place->placeName() ?>
            <?php endif ?>
        </div>
        <?php if ($flag) : ?>
            <div class="col-sm-3 align-digits">
                <img class="flag" alt="<?= strip_tags($place->placeName()) ?>" title="<?= strip_tags($place->placeName()) ?>" src='<?= $flag ?>'>
            </div>
        <?php endif ?>
        <div class="offset-sm-1 col-sm-7"><?= I18N::translate('Individuals') ?></div>
        <div class="col-sm-3 align-digits"><?= $stats['INDI'] ?></div>
        <div class="offset-sm-1 col-sm-7"><?= I18N::translate('Families') ?></div>
        <div class="col-sm-3 align-digits"><?= $stats['FAM'] ?></div>
    </div>
</li>
