<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Date;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Illuminate\Support\Collection;

/**
 * @var int                                                                                       $limit_high
 * @var int                                                                                       $limit_low
 * @var Collection<int,object{individual:Individual,yahrzeit_date:Date,fact_date:Date,fact:Fact}> $yahrzeits
 */

?>

<div class="table-responsive">
    <table
        class="table table-sm datatable wt-table-yahrzeits"
        <?= view('lists/datatables-attributes') ?>
        data-paging="<?= $yahrzeits->count() >= $limit_high ? 'true' : 'false' ?>"
        data-filter="false"
        data-info="false"
        data-length-change="false"
        data-page-length="<?= e($limit_low) ?>"
    >
        <thead>
            <tr>
                <th><?= I18N::translate('Name') ?></th>
                <th><?= I18N::translate('Death') ?></th>
                <th>
                <span title="<?= I18N::translate('Anniversary') ?>">
                    <?= view('icons/anniversary') ?>
                </span>

                </th>
                <th><?= I18N::translate('Yahrzeit') ?></th>
            </tr>
        </thead>
        <tbody>

            <?php foreach ($yahrzeits as $yahrzeit) : ?>
                <tr>
                    <td data-sort="<?= e($yahrzeit->individual->sortName()) ?>">
                        <a href="<?= e($yahrzeit->individual->url()) ?>">
                            <?= $yahrzeit->individual->fullName() ?>
                            <?php if ($yahrzeit->individual->alternateName() !== null) : ?>
                                <br>
                                <?= $yahrzeit->individual->alternateName() ?>
                            <?php endif ?>
                        </a>
                    </td>
                    <td data-sort="<?= sprintf('x%07d', $yahrzeit->yahrzeit_date->julianDay()) ?>">
                        <?= $yahrzeit->fact_date->display($yahrzeit->individual->tree()) ?>
                    </td>
                    <td data-sort="<?= sprintf('x%07d', $yahrzeit->fact->anniv) ?>">
                        <?= I18N::number($yahrzeit->fact->anniv) ?>
                    </td>
                    <td data-sort="<?= sprintf('x%07d', $yahrzeit->yahrzeit_date->julianDay()) ?>">
                        <?= $yahrzeit->yahrzeit_date->display($yahrzeit->individual->tree()) ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>

<script>
  $(".wt-table-yahrzeits").dataTable();
</script>
