<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Illuminate\Support\Collection;

/**
 * @var bool                 $can_edit
 * @var Collection<int,Fact> $clipboard_facts
 * @var Collection<int,Fact> $facts
 * @var Individual           $individual
 */

?>
<div class="container py-4 wt-facts-table">

    <div class="row wt-fact-content py-1">
        <div class="col-sm-auto">
            <input id="show-level-2-media" class="form-check-input" type="checkbox"
                data-bs-toggle="collapse"
                data-bs-target=".wt-level-two-media"
                data-wt-persist="level-two-media"
                autocomplete="off"
                <?= $facts->isEmpty() ? 'disabled="disabled"' : '' ?>
            >
            <label class="form-check-label" for="show-level-2-media">
                <?= I18N::translate('Show all media') ?>
            </label>
        </div>
    </div>

    <?php foreach ($facts as $fact) : ?>
        <?php if (str_ends_with($fact->tag(), ':OBJE')) : ?>
            <?= view('fact', ['fact' => $fact, 'record' => $individual]) ?>
        <?php else : ?>
            <?php
            if ($fact->isPendingAddition()) {
                $styleadd = 'wt-new ';
            } elseif ($fact->isPendingDeletion()) {
                $styleadd = 'wt-old ';
            } else {
                $styleadd = '';
            }
            ?>


            <div class="row wt-level-two-media collapse pt-1">
                <div class="col-sm-2 pe-1 ps-0 rela wt-fact-controls <?= $styleadd ?>">
                    <?= $fact->label() ?>
                    <?= view('fact-edit-links', ['fact' => $fact, 'url' => $fact->record()->url() . '#tab-media']) ?>
                </div>

                <div class="col-sm-10 wt-fact-content <?= $styleadd ?>">
                    <?php if (preg_match_all('/\n([2-4] OBJE .*)/', $fact->gedcom(), $matches, PREG_SET_ORDER) > 0) : ?>
                        <?php foreach ($matches as $match) : ?>
                            <?= view('fact-gedcom-fields', ['gedcom' => $match[1], 'parent' => $fact->tag(), 'tree' => $fact->record()->tree()]) ?>
                        <?php endforeach ?>
                    <?php endif ?>
                </div>
            </div>
        <?php endif ?>
    <?php endforeach ?>

    <?php if ($facts->isEmpty()) : ?>
        <div class="row wt-fact-content my-3">
            <div class="col-sm-auto py-2">
                <?= I18N::translate('There are no media objects for this individual.') ?>
            </div>
        </div>
    <?php endif ?>
</div>
