<?php

declare(strict_types=1);

/**
 * @var string $areas
 * @var int    $fanh
 * @var int    $fanw
 * @var string $html
 * @var string $png
 * @var string $title
 */

?>
<?= $html ?>

<map id="fan-chart-map" name="fan-chart-map" data-wt-fanchart-map>
    <?= $areas ?>
</map>

<div class="text-center">
    <img class="wt-chart-fan-img" src="data:image/png;base64,<?= base64_encode($png) ?>" width="<?= $fanw ?>" height="<?= $fanh ?>" alt="<?= strip_tags($title) ?>" usemap="#fan-chart-map">
</div>


