<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

?>

<div class="row mb-3">
    <label class="col-sm-3 col-form-label" for="search-for">
        <?= I18N::translate('Search') ?>
    </label>

    <div class="col-sm-9">
        <input class="form-control" id="search-for" name="search-for">
    </div>
</div>

<div class="row mb-3">
    <label class="col-sm-3 col-form-label" for="replace-with">
        <?= I18N::translate('Replace') ?>
    </label>

    <div class="col-sm-9">
        <input class="form-control" id="replace-with" name="replace-with">
    </div>
</div>
