<?php
use Fisharebest\Webtrees\I18N;

/** @var \Fisharebest\Webtrees\Stats $stats */
?>

<div class="card-deck mb-3">
    <div class="col-lg-6 col-md-12 mb-3">
        <div class="card m-0">
            <h5 class="card-header">
                <?= I18N::translate('Marriages by century') ?>
            </h5>
            <div class="card-body">
                <?= $stats->statsMarr() ?>
            </div>
        </div>
    </div>

    <div class="col-lg-6 col-md-12 mb-3">
        <div class="card m-0">
            <h5 class="card-header">
                <?= I18N::translate('Divorces by century') ?>
            </h5>
            <div class="card-body">
                <?= $stats->statsDiv() ?>
            </div>
        </div>
    </div>
</div>
