<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Statistics;

/** @var Statistics $stats */
?>

<h4 class="border-bottom p-2 mb-4">
    <?= I18N::translate('Age in year of marriage') ?>
</h4>

<div class="d-grid gap-3 mb-3">
    <div class="row row-cols-1 row-cols-md-2 g-3">
        <div class="col">
            <div class="card">
                <?php $age    = $stats->youngestMarriageMaleAge('1') ?>
                <?php $result = $stats->youngestMarriageMale() ?>
                <h5 class="card-header">
                    <?= I18N::translate('Youngest male') ?>
                    <?php if ($age) :
                        ?><?= ' - ', $age ?><?php
                    endif; ?>
                </h5>
                <div class="card-body">
                    <?php if ($result) : ?>
                        <?= $result ?>
                    <?php else : ?>
                        <?= I18N::translate('This information is not available.') ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <?php $age    = $stats->youngestMarriageFemaleAge('1') ?>
                <?php $result = $stats->youngestMarriageFemale() ?>
                <h5 class="card-header">
                    <?= I18N::translate('Youngest female') ?>
                    <?php if ($age) :
                        ?><?= ' - ', $age ?><?php
                    endif; ?>
                </h5>
                <div class="card-body">
                    <?php if ($result) : ?>
                        <?= $result ?>
                    <?php else : ?>
                        <?= I18N::translate('This information is not available.') ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        
        <div class="col">
            <div class="card">
                <?php $age    = $stats->oldestMarriageMaleAge('1') ?>
                <?php $result = $stats->oldestMarriageMale() ?>
                <h5 class="card-header">
                    <?= I18N::translate('Oldest male') ?>
                    <?php if ($age) :
                        ?><?= ' - ', $age ?><?php
                    endif; ?>
                </h5>
                <div class="card-body">
                    <?php if ($result) : ?>
                        <?= $result ?>
                    <?php else : ?>
                        <?= I18N::translate('This information is not available.') ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    
        <div class="col">
            <div class="card">
                <?php $age    = $stats->oldestMarriageFemaleAge('1') ?>
                <?php $result = $stats->oldestMarriageFemale() ?>
                <h5 class="card-header">
                    <?= I18N::translate('Oldest female') ?>
                    <?php if ($age) :
                        ?><?= ' - ', $age ?><?php
                    endif; ?>
                </h5>
                <div class="card-body">
                    <?php if ($result) : ?>
                        <?= $result ?>
                    <?php else : ?>
                        <?= I18N::translate('This information is not available.') ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    
    <div class="card m-0">
        <div class="card-body">
            <?= $stats->statsMarrAge() ?>
        </div>
    </div>
</div>
