<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;

/**
 * @var array<array{family:Family,count:int}> $records
 */

?>

<?php foreach ($records as $record) : ?>
    <?php $family = $record['family']; ?>
    <a href="<?= e($family->url()) ?>"><?= $family->fullName() ?></a>
    - <?= I18N::plural('%s child', '%s children', $record['count'], I18N::number($record['count'])) ?>
<?php endforeach; ?>
