<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;

/* @var array  $records */
/* @var Family $family */
?>

<?php foreach ($records as $record) : ?>
    <?php $family = $record['family']; ?>
    <a href="<?= e($family->url()) ?>"><?= $family->fullName() ?></a>
    - <?= I18N::plural('%s grandchild', '%s grandchildren', $record['count'], I18N::number($record['count'])) ?>
<?php endforeach; ?>
