<?php
declare(strict_types=1);

use Fisharebest\Webtrees\Family;

/* @var array  $records */
/* @var Family $family */
?>

<ul class="list-group list-group-flush">
    <?php foreach ($records as $record): ?>
        <?php $family = $record['family']; ?>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="<?= e($family->url()) ?>"><?= $family->getFullName() ?></a>
            <span class="badge badge-secondary badge-pill ml-3"><?= $record['age'] ?></span>
        </li>
    <?php endforeach; ?>
</ul>
