<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var array<array> $records
 */

?>

<?php if ($records) : ?>
    <ul class="list-group list-group-flush">
        <?php foreach ($records as $record) : ?>
            <?php $family = $record['family']; ?>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="<?= e($family->url()) ?>"><?= $family->fullName() ?></a>
                <span class="badge badge-secondary badge-pill ml-3"><?= $record['age'] ?></span>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else : ?>
    <div class="card-body">
        <?= I18N::translate('This information is not available.') ?>
    </div>
<?php endif; ?>
