<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;

/**
 * @var array<array{family:Family,count:int}> $records
 */

?>

<?php if ($records === []) : ?>
    <div class="card-body">
        <?= I18N::translate('This information is not available.') ?>
    </div>
<?php else : ?>
    <ul class="list-group list-group-flush">
        <?php foreach ($records as $record) : ?>
            <?php $family = $record['family']; ?>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="<?= e($family->url()) ?>"><?= $family->fullName() ?></a>
                <span class="badge bg-secondary rounded-pill ms-3">
                    <?= I18N::plural('%s grandchild', '%s grandchildren', $record['count'], I18N::number($record['count'])) ?>
                </span>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
