<?php
declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/** @var \Fisharebest\Webtrees\Stats $stats */
?>

<div class="card-deck mb-3">
    <div class="col-lg-6 col-md-6 mb-3">
        <div class="card m-0">
            <h5 class="card-header">
                <?= I18N::translate('Earliest marriage') ?>
            </h5>
            <div class="card-body">
                <?= $stats->firstMarriage() ?>
            </div>
        </div>
    </div>

    <div class="col-lg-6 col-md-6 mb-3">
        <div class="card m-0">
            <h5 class="card-header">
                <?= I18N::translate('Earliest divorce') ?>
            </h5>
            <div class="card-body">
                <?= $stats->firstDivorce() ?>
            </div>
        </div>
    </div>

    <div class="col-lg-6 col-md-6 mb-3">
        <div class="card m-0">
            <h5 class="card-header">
                <?= I18N::translate('Latest marriage') ?>
            </h5>
            <div class="card-body">
                <?= $stats->lastMarriage() ?>
            </div>
        </div>
    </div>

    <div class="col-lg-6 col-md-6 mb-3">
        <div class="card m-0">
            <h5 class="card-header">
                <?= I18N::translate('Latest divorce') ?>
            </h5>
            <div class="card-body">
                <?= $stats->lastDivorce() ?>
            </div>
        </div>
    </div>
</div>

<h4 class="border-bottom p-2 mb-4">
    <?= I18N::translate('Length of marriage') ?>
</h4>

<div class="card-deck mb-3">
    <div class="col-lg-6 col-md-6 mb-3">
        <div class="card m-0">
            <h5 class="card-header">
                <?= I18N::translate('Longest marriage'), ' - ', $stats->topAgeOfMarriage() ?>
            </h5>
            <div class="card-body">
                <?= $stats->topAgeOfMarriageFamily() ?>
            </div>
        </div>
    </div>

    <div class="col-lg-6 col-md-6 mb-3">
        <div class="card m-0">
            <h5 class="card-header">
                <?= I18N::translate('Shortest marriage'), ' - ', $stats->minAgeOfMarriage() ?>
            </h5>
            <div class="card-body">
                <?= $stats->minAgeOfMarriageFamily() ?>
            </div>
        </div>
    </div>
</div>
