<?php use Fisharebest\Webtrees\I18N; ?>

<?php if ($individual === null) : ?>
    <?= view('icons/arrow-right') ?>
<?php else : ?>
    <a href="<?= e(route('compact-tree', ['xref' => $individual->xref(), 'ged' => $individual->tree()->name()])) ?>" title="<?= I18N::translate('Compact tree of %s', strip_tags($individual->getFullName())) ?>">
        <?= view('icons/arrow-right') ?>
    </a>
<?php endif;
