<?php

use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Module\CompactTreeChartModule;

/**
 * @var Individual|null        $individual
 * @var CompactTreeChartModule $module
 */

?>
<?php if ($individual instanceof Individual) : ?>
    <a href="<?= e($module->chartUrl($individual)) ?>" title="<?= strip_tags($module->chartTitle($individual)) ?>">
        <?= view('icons/arrow-up') ?>
    </a>
<?php else : ?>
    <?= view('icons/arrow-up') ?>
<?php endif;
