<?php if ($individual === null) : ?>
    <div class="h-100 wt-chart-box">&nbsp;</div>
<?php else : ?>
    <?= view('chart-box', ['individual' => $individual]) ?>
<!--
    <div class="h-100 person_box<?= ['M' => '', 'F' => 'F', 'U' => 'NN'][$individual->sex()]?> person_box_template">
        <a href="<?= e($individual->url()) ?>">
            <?= $individual->fullName() ?>
        </a>
        <div class="small">
            <?= $individual->lifespan() ?>
        </div>
    </div>
-->
<?php endif ?>
