<?php

use Fisharebest\Webtrees\I18N;

?>

<div class="wt-custom-module-info">
    <?= view('icons/warning') ?>
    <?= I18N::translate('Custom module') ?>
    <?php if ($module::CUSTOM_VERSION) : ?>
        - <?= I18N::translate('Version') ?> <?= $module::CUSTOM_VERSION ?>
    <?php endif ?>
    <?php if ($module::CUSTOM_WEBSITE) : ?>
        -
        <a href="<?= $module::CUSTOM_WEBSITE ?>">
            <?= $module::CUSTOM_WEBSITE ?>
        </a>
    <?php endif ?>
</div>
