<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\DataFixData;
use Fisharebest\Webtrees\Http\RequestHandlers\DataFixPage;
use Fisharebest\Webtrees\Http\RequestHandlers\DataFixUpdateAll;
use Fisharebest\Webtrees\Http\RequestHandlers\HelpText;
use Fisharebest\Webtrees\Http\RequestHandlers\ManageTrees;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Module\ModuleDataFixInterface;
use Fisharebest\Webtrees\Tree;

/**
 * @var ModuleDataFixInterface $data_fix
 * @var string                 $latest_version
 * @var string                 $title
 * @var Tree                   $tree
 * @var string                 $pending_url
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ManageTrees::class, ['tree' => $tree->name()]) => I18N::translate('Manage family trees'), route(DataFixPage::class, ['tree' => $tree->name()]) => view('icons/data-fix') . I18N::translate('Data fixes'), $title]]) ?>

<h1><?= $title ?></h1>

<div id="admin-data-fix-page">
    <form
        action="#"
        id="data-fix-options"
        data-wt-data-fix-url="<?= e(route(DataFixData::class, ['tree' => $tree->name(), 'data_fix' => $data_fix->name()])) ?>"
        data-wt-update-all-url="<?= e(route(DataFixUpdateAll::class, ['tree' => $tree->name(), 'data_fix' => $data_fix->name()])) ?>"
    >
        <p>
            <?= $data_fix->description() ?>
        </p>

        <?= $data_fix->fixOptions($tree) ?>

        <div class="row mb-3">
            <div class="col-sm-3">
            </div>

            <div class="col-sm-9">
                <button class="btn btn-primary" type="button" id="btn-search">
                    <?= view('icons/search') ?>
                    <?= I18N::translate('Search') ?>
                </button>

                <button class="btn btn-primary" type="button" id="btn-update-all">
                    <?= view('icons/data-fix') ?>
                    <?= I18N::translate('Update all') ?>
                </button>
            </div>
        </div>
    </form>

    <div id="data-fix-table-container" class="d-none">
        <table
            id="data-fix-table"
            class="table table-bordered table-sm table-hover wt-data-fix-table"
            <?= view('lists/datatables-attributes') ?>
            data-server-side="true"
            data-filter="false"
            data-processing="true"
            data-sort="false"
        >
            <thead>
                <tr>
                    <th class="w-75">
                        <?= I18N::translate('Record') ?>
                    </th>
                    <th class="w-25">
                        <?= view('icons/data-fix') ?>
                        <?= I18N::translate('Data fix') ?>
                    </th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

        <hr>

        <a href="#" data-bs-toggle="modal" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e(route(HelpText::class, ['topic' => 'data-fixes'])) ?>">
            <?= view('icons/help') ?>
            <?= I18N::translate('Why does this list include records that do not need to be updated?') ?>
        </a>
    </div>

    <div id="data-fix-progress" class="d-none">
        <div class="progress" role="progressbar">
            <div class="progress-bar"></div>
        </div>
    </div>
</div>

<?= view('modals/ajax') ?>

