<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Media;

/**
 * @var Fact       $fact
 * @var Individual $individual
 * @var Media      $media
 */
?>

<button
class="btn btn-primary btn-small mb-1 wt-fix-button"
data-wt-confirm="<?= I18N::translate('Move the media object?') ?>"
data-fact-id="<?= e($fact->id()) ?>"
data-tree-id="<?= e($individual->tree()->id()) ?>"
data-individual-xref="<?= e($individual->xref()) ?>"
data-media-xref="<?= e($media->xref()) ?>"
type="button"
>
    <?= $fact->label() ?>
    <?= $fact->value() ?>
    <?= $fact->date()->display(null, '%Y') ?>
</button>
