<?php use Fisharebest\Webtrees\I18N; ?>

<button
    class="btn btn-primary btn-small mb-1 wt-fix-button"
    data-confirm="<?= I18N::translate('Move the media object?') ?>"
    data-fact-id="<?= e($fact->id()) ?>"
    data-tree-id="<?= e($tree->id()) ?>"
    data-individual-xref="<?= e($individual->xref()) ?>"
    data-media-xref="<?= e($media->xref()) ?>"
    type="button"
>
    <?= $fact->label() ?>
    <?= $fact->date()->display(false, '%Y', false) ?>
</button>
