<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\FixLevel0MediaAction;
use Fisharebest\Webtrees\Http\RequestHandlers\FixLevel0MediaData;
use Fisharebest\Webtrees\I18N;

/**
 * @var string $title
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<div id="admin-fix-level-0-media-page">
    <p>
        <?= I18N::translate('If a media object is linked to an individual, when it should be linked to a fact or event, then you can move it to the correct location.') ?>
    </p>

    <table
        id="wt-datatables-fix-level-0-media"
        class="table table-bordered table-sm table-hover wt-fix-table wt-datatables d-none"
        <?= view('lists/datatables-attributes') ?>
        data-ajax="<?= e(json_encode(['url' => route(FixLevel0MediaData::class), 'type' => 'POST'], JSON_THROW_ON_ERROR)) ?>"
        data-wt-fix-action-url="<?= e(route(FixLevel0MediaAction::class)) ?>"
        data-server-side="true"
    >
        <caption class="visually-hidden">
            <?= I18N::translate('Media objects') ?>
        </caption>
        <thead class="thead-dark">
            <tr>
                <th data-sortable="false"><?= I18N::translate('Family tree') ?></th>
                <th data-sortable="false"><?= I18N::translate('Media object') ?></th>
                <th data-sortable="false"><?= I18N::translate('Title') ?></th>
                <th data-sortable="false"><?= I18N::translate('Individual') ?></th>
                <th data-sortable="false"><?= I18N::translate('Facts and events') ?></th>
            </tr>
        </thead>
    </table>
</div>

