<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\GedcomLoad;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var string $errors
 * @var float  $progress
 * @var string $status
 * @var Tree   $tree
 */

?>

<div class="progress" id="progress<?= e($tree->id()) ?>"
     role="progressbar"
     aria-valuenow="<?= $progress * 100 ?>"
     aria-valuemin="0"
     aria-valuemax="100"
>
    <div class="progress-bar" style="min-width: <?= $progress * 100 ?>%;">
        <?= $status ?: I18N::percentage($progress, 1) ?>
    </div>
</div>

<?php if ($errors === '') : ?>
    <script>
        $("#import<?= e($tree->id()) ?>")
            .load("<?= route(GedcomLoad::class, ['tree' => $tree->name()]) ?>", {});
    </script>
<?php else : ?>
    <div class="alert alert-danger">
        <?= $errors ?>
    </div>

    <button class="btn btn-primary" onclick="" id="error-button-<?= $tree->id() ?>">
        <?= I18N::translate('continue') ?>
    </button>

    <script>
        $("#error-button-<?= $tree->id() ?>").click(function () {
            $("#import<?= e($tree->id()) ?>")
                .load("<?= route(GedcomLoad::class, ['tree' => $tree->name()]) ?>", {});
        });
    </script>
<?php endif ?>
