<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\GedcomLoad;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var string $errors
 * @var float  $progress
 * @var string $status
 * @var Tree   $tree
 */

?>

<div class="progress" id="progress<?= e($tree->id()) ?>"
     role="progressbar"
     aria-valuenow="<?= $progress * 100 ?>"
     aria-valuemin="0"
     aria-valuemax="100"
>
    <div class="progress-bar" style="min-width: <?= $progress * 100 ?>%;">
        <?= $status ?: I18N::percentage($progress, 1) ?>
    </div>
</div>

<?php if ($errors === '') : ?>
    <div class="d-none" data-wt-import-autoload-url="<?= e(route(GedcomLoad::class, ['tree' => $tree->name()])) ?>"></div>
<?php else : ?>
    <div class="alert alert-danger">
        <?= $errors ?>
    </div>

    <button class="btn btn-primary" type="button" data-wt-import-continue-url="<?= e(route(GedcomLoad::class, ['tree' => $tree->name()])) ?>">
        <?= I18N::translate('continue') ?>
    </button>
<?php endif ?>
