<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\MapDataSave;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\PlaceLocation;

/**
 * @var array<string,string> $breadcrumbs
 * @var string               $latitude
 * @var object               $leaflet_config
 * @var string               $longitude
 * @var PlaceLocation        $location
 * @var array<array<float>>  $map_bounds
 * @var array<float>         $marker_position
 * @var PlaceLocation        $parent
 * @var string               $title
 * @var string               $url
 */

?>

<?= view('components/breadcrumbs', ['links' => $breadcrumbs]) ?>

<h1><?= $title ?></h1>

<div
    id="admin-location-edit-page"
    data-wt-leaflet-config="<?= e(json_encode($leaflet_config, JSON_THROW_ON_ERROR)) ?>"
    data-wt-add-place="<?= $location->id() === null ? '1' : '0' ?>"
    data-wt-marker-position="<?= e(json_encode($marker_position, JSON_THROW_ON_ERROR)) ?>"
    data-wt-map-bounds="<?= e(json_encode($map_bounds, JSON_THROW_ON_ERROR)) ?>"
    data-wt-location-name="<?= e($location->locationName()) ?>"
    data-wt-search-label="<?= e(I18N::translate('Search')) ?>"
    data-wt-nothing-found="<?= e(I18N::translate('Nothing found.')) ?>"
    data-wt-icon-image-path="<?= e(asset('css/images/')) ?>"
>
    <div class="row wt-location-edit-wrapper wt-fullscreen-container">
        <div id="wt-map" class="col-sm-9 wt-map" dir="ltr"></div>

        <div class="col-sm-3 wt-map-sidebar">
            <form method="post" action="<?= e(route(MapDataSave::class)) ?>">
                <input type="hidden" name="parent_id" value="<?= $parent->id() ?>">
                <input type="hidden" name="place_id" value="<?= $location->id() ?>">
                <input type="hidden" name="url" value="<?= e($url) ?>">

            <label class="col-form-label col-sm-6" for="new_place_name">
                <?= I18N::translate('Place') ?>
            </label>
            <input type="text" id="new_place_name" name="new_place_name" value="<?= e($location->locationName()) ?>" class="form-control" required="required" maxlength="120" pattern="[^,]+" dir="auto">

            <label class="col-form-label col-sm-6" for="new_place_lati">
                <?= I18N::translate('Latitude') ?>
            </label>
            <div class="input-group">
                <input type="text" dir="ltr" id="new_place_lati" class="editable form-control" name="new_place_lati" placeholder="<?= I18N::translate('degrees') ?>" value="<?= e($latitude) ?>">
            </div>

            <label class="col-form-label" for="new_place_long">
                <?= I18N::translate('Longitude') ?>
            </label>
            <div class="input-group">
                <input type="text" dir="ltr" id="new_place_long" class="editable form-control" name="new_place_long" placeholder="<?= I18N::translate('degrees') ?>" value="<?= e($longitude) ?>">
            </div>

            <div class="mt-3">
                <button class="btn btn-primary" type="submit">
                    <?= /* I18N: A button label. */
                    I18N::translate('save')
                    ?>
                </button>
                <a class="btn btn-secondary" href="<?= e($url) ?>">
                    <?= I18N::translate('cancel') ?>
                </a>
            </div>

                <?= csrf_field() ?>
            </form>
        </div>
    </div>
</div>

