<?php

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<form method="post">
    <?= csrf_field() ?>

    <div class="form-group">
        <div class="form-row">
            <label class="col-form-label col-sm-3" for="provider-default">
                <?= I18N::translate('Map provider') ?>
            </label>
            <div class="col-sm-9">
                <?= view('components/radios', ['name' => 'provider', 'selected' => $provider, 'options' => [
                ''    => I18N::translate('Do not use maps'),
                'osm' => I18N::translate('OpenStreetMap™'),
                ]]) ?>
            </div>
        </div>
    </div>

    <hr>

        <div class="form-group">
          <div class="form-row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Use a gazetteer to provide autocomplete suggestions for places') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'use_gazetteer', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int) $use_gazetteer]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Use a gazetteer to provide autocomplete suggestions for places” configuration setting */
                    I18N::translate('This option controls whether or not to use a gazetteer to provide autocomplete suggestions for places. When this is enabled, the default is Nominatim the free search engine provided by OpenStreetMap, however if a key for OpenCage is provided then that is used instead.') ?>
                </p>
            </div>
          </div>
        </div>

    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="opencage">
            <?= I18N::translate('OpenCage key') ?>
        </label>
        <div class="col-sm-9">
            <input
            class="form-control"
            dir="ltr"
            id="opencage"
            maxlength="255"
            name="opencage"
            type="text"
            value="<?= e($opencage) ?>"
            >
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Use OpenCage database for autocomplete on places” configuration setting */ I18N::translate('The OpenCage geocoder searches a number of databases (including Geonames and Nominatim) in order to provide autocomplete options for new places. To use this feature, you must register for an account at %s and obtain a key. A free account allows 2500 searches per day.', '<a href="https://opencagedata.com/users/sign_up">OpenCage</a>') ?>
            </p>
        </div>
    </div>

    <hr>

    <div class="form-group row">
        <div class="offset-sm-3 col-sm-9">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= I18N::translate('save') ?>
            </button>
        </div>
    </div>
</form>
