<?php use Fisharebest\Webtrees\I18N; ?>

<?= view('components/breadcrumbs', ['links' => [route('admin-control-panel') => I18N::translate('Control panel'), $title]]) ?>

<form method="POST">
    <?= csrf_field() ?>

    <div class="form-group">
        <div class="form-row">
            <div class="col-form-label col-sm-3">
                <?= I18N::translate('Map provider') ?>
            </div>
            <div class="col-sm-9">
                <?= view('components/radio', ['id' => 'provider-default', 'name' => 'provider', 'value' => '', 'checked' => $provider === '', 'text' => 'Do not use maps']) ?>
                <hr>
                <?= view('components/radio', ['id' => 'provider-openstreetmap', 'name' => 'provider', 'value' => 'OpenStreetMap.Mapnik', 'checked' => $provider === 'OpenStreetMap.Mapnik', 'text' => 'OpenStreetMap']) ?>
                <hr>
                <!-- @TODO - other mapping providers (may need API keys, etc.) -->
            </div>
        </div>
    </div>

    <!-- SAVE BUTTON -->
    <div class="form-group row">
        <div class="offset-sm-3 col-sm-9">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= I18N::translate('save') ?>
            </button>
        </div>
    </div>
</form>
