<?php use Fisharebest\Webtrees\Bootstrap4; ?>
<?php use Fisharebest\Webtrees\I18N; ?>
<?php use Fisharebest\Webtrees\Module\ModuleBlockInterface; ?>
<?php use Fisharebest\Webtrees\Module\ModuleChartInterface; ?>
<?php use Fisharebest\Webtrees\Module\ModuleConfigInterface; ?>
<?php use Fisharebest\Webtrees\Module\ModuleCustomInterface; ?>
<?php use Fisharebest\Webtrees\Module\ModuleMenuInterface; ?>
<?php use Fisharebest\Webtrees\Module\ModuleReportInterface; ?>
<?php use Fisharebest\Webtrees\Module\ModuleSidebarInterface; ?>
<?php use Fisharebest\Webtrees\Module\ModuleTabInterface; ?>
<?php use Fisharebest\Webtrees\Module\ModuleThemeInterface; ?>
<?php use Fisharebest\Webtrees\View; ?>

<?= view('components/breadcrumbs', ['links' => [route('admin-control-panel') => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<?php foreach ($deleted_modules as $module_name) : ?>
    <div class="alert alert-warning" role="alert">
        <form action="<?= e(route('admin-delete-module-settings')) ?>" class="form-inline" method="POST">
            <?= csrf_field() ?>
            <input type="hidden" name="module_name" value="<?= $module_name ?>">
            <?= I18N::translate('Preferences exist for the module “%s”, but this module no longer exists.', $module_name) ?>
            <button type="submit" class="btn btn-secondary text-wrap">
                <?= I18N::translate('Delete the preferences for this module.') ?>
            </button>
            </form>
    </div>
<?php endforeach ?>

<form method="POST">
    <input type="hidden" name="route" value="admin-update-module-status">
    <?= csrf_field() ?>
    <table class="table table-bordered table-hover table-sm table-module-administration" data-info="false" data-paging="false" data-state-save="true">
        <caption class="sr-only">
            <?= I18N::translate('Module administration') ?>
        </caption>
        <thead>
            <tr>
                <th>
                    <?= I18N::translate('Module') ?>
                </th>
                <th>
                    <?= I18N::translate('Enabled') ?>
                </th>
                <th data-orderable="false">
                    <?= I18N::translate('Description') ?>
                </th>
                <th title="<?= I18N::translate('Preferences') ?>">
                    <?= view('icons/preferences') ?>
                    <span class="sr-only"><?= I18N::translate('Preferences') ?></span>
                </th>
                <th title="<?= I18N::translate('Menus') ?>">
                    <?= view('icons/menu') ?>
                    <span class="sr-only"><?= I18N::translate('Menus') ?></span>
                </th>
                <th title="<?= I18N::translate('Tabs') ?>">
                    <?= view('icons/tab') ?>
                    <span class="sr-only"><?= I18N::translate('Tabs') ?></span>
                </th>
                <th title="<?= I18N::translate('Sidebars') ?>">
                    <?= view('icons/sidebar') ?>
                    <span class="sr-only"><?= I18N::translate('Sidebars') ?></span>
                </th>
                <th title="<?= I18N::translate('Blocks') ?>">
                    <?= view('icons/block') ?>
                    <span class="sr-only"><?= I18N::translate('Blocks') ?></span>
                </th>
                <th title="<?= I18N::translate('Charts') ?>">
                    <?= view('icons/chart') ?>
                    <span class="sr-only"><?= I18N::translate('Charts') ?></span>
                </th>
                <th title="<?= I18N::translate('Reports') ?>">
                    <?= view('icons/report') ?>
                    <span class="sr-only"><?= I18N::translate('Reports') ?></span>
                </th>
                <th class="d-none" title="<?= I18N::translate('Themes') ?>">
                    <?= view('icons/theme') ?>
                    <span class="sr-only"><?= I18N::translate('Themes') ?></span>
                </th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($modules as $module) : ?>
                <tr>
                    <th scope="row" dir="auto">
                        <?= $module->title() ?>
                    </th>
                    <td class="text-center" data-sort="<?= $module->isEnabled() ?>">
                        <?= Bootstrap4::checkbox('', false, ['name' => 'status-' . $module->name(), 'checked' => $module->isEnabled()]) ?>
                    </td>
                    <td>
                        <?= $module->description() ?>
                        <?php if ($module instanceof ModuleCustomInterface) : ?>
                            <br>
                            <?= view('icons/warning') ?>
                            <?= I18N::translate('Custom module') ?>
                            <?php if ($module::CUSTOM_VERSION) : ?>
                                - <?= I18N::translate('Version') ?> <?= $module::CUSTOM_VERSION ?>
                            <?php endif ?>
                            <?php if ($module::CUSTOM_WEBSITE) : ?>
                                - <a href="<?= $module::CUSTOM_WEBSITE ?>">
                                    <?= $module::CUSTOM_WEBSITE ?>
                                </a>
                            <?php endif ?>
                        <?php endif ?>
                    </td>
                    <td class="text-center text-muted" title="<?= I18N::translate('Preferences') ?>">
                        <?php if ($module instanceof ModuleConfigInterface) : ?>
                            <a href="<?= e($module->getConfigLink()) ?>" title="<?= I18N::translate('Preferences') ?>">
                                <?= view('icons/preferences') ?>
                                <span class="sr-only">
                                    <?= I18N::translate('Preferences') ?>
                                </span>
                            </a>
                        <?php endif ?>
                    </td>
                    <td class="text-center text-muted" title="<?= I18N::translate('Menu') ?>">
                        <?php if ($module instanceof ModuleMenuInterface) : ?>
                            <?= view('icons/menu') ?>
                            <span class="sr-only"><?= I18N::translate('Menu') ?></span>
                        <?php else : ?>
                            -
                        <?php endif ?>
                    </td>
                    <td class="text-center text-muted" title="<?= I18N::translate('Tab') ?>">
                        <?php if ($module instanceof ModuleTabInterface) : ?>
                            <?= view('icons/tab') ?>
                            <span class="sr-only"><?= I18N::translate('Tab') ?></span>
                        <?php else : ?>
                            -
                        <?php endif ?>
                    </td>
                    <td class="text-center text-muted" title="<?= I18N::translate('Sidebar') ?>">
                        <?php if ($module instanceof ModuleSidebarInterface) : ?>
                            <?= view('icons/sidebar') ?>
                            <span class="sr-only"><?= I18N::translate('Sidebar') ?></span>
                        <?php else : ?>
                            -
                        <?php endif ?>
                    </td>
                    <td class="text-center text-muted">
                        <?php if ($module instanceof ModuleBlockInterface) : ?>
                            <?php if ($module->isUserBlock()) : ?>
                                <span title="<?= I18N::translate('My page') ?>">
                                    <?= view('icons/block-user') ?>
                                </span>
                                <span class="sr-only">
                                    <?= I18N::translate('My page') ?>
                                </span>
                            <?php endif ?>

                            <?php if ($module->isTreeBlock()) : ?>
                                <span title="<?= I18N::translate('Home page') ?>">
                                    <?= view('icons/block-tree') ?>
                                </span>
                                <span class="sr-only">
                                    <?= I18N::translate('Home page') ?>
                                </span>
                            <?php endif ?>
                        <?php else : ?>
                            -
                        <?php endif ?>
                    </td>
                    <td class="text-center text-muted" title="<?= I18N::translate('Chart') ?>">
                        <?php if ($module instanceof ModuleChartInterface) : ?>
                            <?= view('icons/chart') ?>
                            <span class="sr-only"><?= I18N::translate('Chart') ?></span>
                        <?php else : ?>
                            -
                        <?php endif ?>
                    </td>
                    <td class="text-center text-muted" title="<?= I18N::translate('Report') ?>">
                        <?php if ($module instanceof ModuleReportInterface) : ?>
                            <?= view('icons/report') ?>
                            <span class="sr-only"><?= I18N::translate('Report') ?></span>
                        <?php else : ?>
                            -
                        <?php endif ?>
                    </td>
                    <td class="text-center text-muted d-none" title="<?= I18N::translate('Theme') ?>">
                        <?php if ($module instanceof ModuleThemeInterface) : ?>
                            <?= view('icons/theme') ?>
                            <span class="sr-only"><?= I18N::translate('Theme') ?></span>
                        <?php else : ?>
                            -
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <button class="btn btn-primary" type="submit">
        <?= view('icons/save') ?>
        <?= I18N::translate('save') ?></button>
</form>

<?php View::push('javascript') ?>
<script>
  'use strict';

  $(".table-module-administration").dataTable({<?= I18N::datatablesI18N() ?>});
</script>
<?php View::endpush() ?>
