<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;

/**
 * @var string $phpinfo
 * @var string $title
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<h2>
    <?= I18N::translate('PHP information') ?>
</h2>

<div class="php-info" dir="ltr">
    <?= $phpinfo ?>
</div>
