<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\TelemetrySubmitAction;
use Fisharebest\Webtrees\I18N;

/**
 * @var string $title
 * @var string $payload
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<p class="alert alert-info">
    <?= I18N::translate('Please review the telemetry data below. Click "Confirm" to send this data, or "Cancel" to return to the control panel.') ?>
</p>

<div class="card mb-4">
    <div class="card-body">
        <pre><code><?= e($payload) ?></code></pre>
    </div>
</div>

<form method="post" action="<?= e(route(TelemetrySubmitAction::class)) ?>">
    <?= csrf_field() ?>

    <div class="row mb-3">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= I18N::translate('Confirm') ?>
            </button>

            <a href="<?= e(route(ControlPanel::class)) ?>" class="btn btn-secondary">
                <?= view('icons/cancel') ?>
                <?= I18N::translate('cancel') ?>
            </a>
        </div>
    </div>
</form>
