<?php

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ExportGedcomClient;
use Fisharebest\Webtrees\Http\RequestHandlers\ExportGedcomServer;
use Fisharebest\Webtrees\Http\RequestHandlers\ManageTrees;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var array<string> $download_filenames
 * @var string        $filename
 * @var string        $title
 * @var Tree          $tree
 * @var bool          $zip_available
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ManageTrees::class, ['tree' => $tree->name()]) => I18N::translate('Manage family trees'), $title]]) ?>

<h1><?= $title ?></h1>

<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
                <?= I18N::translate('A file on the server') ?>
            </div>
            <div class="card-body">
                <form method="post" action="<?= e(route(ExportGedcomServer::class, ['tree' => $tree->name()])) ?>" class="form form-horizontal">
                    <div class="mb-3">
                        <label for="filename"><?= I18N::translate('Filename') ?></label>
                        <input type="text" class="form-control" id="filename" name="filename" value="<?= e($filename) ?>">
                    </div>

                    <button type="submit" class="btn btn-primary">
                        <?= view('icons/save') ?>
                        <?= /* I18N: A button label. */
                        I18N::translate('save') ?>
                    </button>

                    <?= csrf_field() ?>
                </form>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
                <?= I18N::translate('A file on your computer') ?>
            </div>

            <div class="card-body">
                <form method="post" action="<?= e(route(ExportGedcomClient::class, ['tree' => $tree->name()])) ?>" class="form form-horizontal">
                    <p class="card-title">
                        <?= I18N::translate('Export preferences') ?>
                    </p>

                    <?= view('admin/gedcom-export-options', ['download_filenames' => $download_filenames, 'tree' => $tree, 'zip_available' => $zip_available]) ?>

                    <button type="submit" class="btn btn-primary">
                        <?= view('icons/download') ?>
                        <?= /* I18N: A button label. */
                        I18N::translate('download') ?>
                    </button>

                    <?= csrf_field() ?>
                </form>
            </div>
        </div>
    </div>
</div>

<?= view('modals/ajax') ?>
