<?php

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ManageTrees;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var array<string> $errors
 * @var array<string> $infos
 * @var string        $more_url
 * @var string        $title
 * @var Tree          $tree
 * @var array<string> $warnings
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ManageTrees::class, ['tree' => $tree->name()]) => I18N::translate('Manage family trees'), $title]]) ?>

<h1><?= $title ?></h1>

<h2>
    <?= I18N::translate('GEDCOM errors') ?>
</h2>

<ul class="list-group">
    <?php foreach ($errors as $error) : ?>
        <li class="list-group-item list-group-item-danger"><?= $error ?></li>
    <?php endforeach ?>

    <?php foreach ($warnings as $warning) : ?>
        <li class="list-group-item list-group-item-warning"><?= $warning ?></li>
    <?php endforeach ?>

    <?php foreach ($infos as $info) : ?>
        <li class="list-group-item list-group-item-info"><?= $info ?></li>
    <?php endforeach ?>

    <?php if ($errors === [] && $warnings === []) : ?>
        <li class="list-group-item"><?= I18N::translate('No errors have been found.') ?></li>
    <?php endif ?>
</ul>

<?php if ($more_url !== '') : ?>
    <p>
        <?= I18N::translate('The server’s time limit has been reached.') ?>
        <a class="btn btn-primary" href="<?= e($more_url) ?>">
            <?= I18N::translate('show more') ?>
        </a>
    </p>
<?php endif ?>
