<?php

use Fisharebest\Webtrees\Functions\FunctionsEdit;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route('manage-trees', ['tree' => $tree->name()]) => I18N::translate('Manage family trees'), $title]]) ?>

<h1><?= $title ?></h1>

<form method="post" action="<?= e(route('admin-trees-preferences-update', ['tree' => $tree->name()])) ?>" class="form-horizontal">
    <?= csrf_field() ?>

    <h3><?= I18N::translate('General') ?></h3>

    <!-- TREE TITLE -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="title">
            <?= I18N::translate('Family tree title') ?>
        </label>
        <div class="col-sm-9">
            <input
                class="form-control"
                dir="auto"
                id="title"
                maxlength="255"
                name="title"
                required
                type="text"
                value="<?= e($tree->getPreference('title')) ?>"
            >
        </div>
    </div>

    <!-- TREE URL / FILENAME -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="gedcom">
            <?= I18N::translate('URL') ?>
        </label>
        <div class="col-sm-9">
            <div class="input-group" dir="ltr">
                <div class="input-group-prepend">
                    <span class="input-group-text" dir="ltr">
                        <?= e(explode('{tree}', rawurldecode(route('example')))[0]) ?>
                    </span>
                </div>
                <input class="form-control" dir="ltr" id="gedcom" maxlength="255" name="gedcom" required type="text" value="<?= e($tree->name()) ?>">
                <div class="input-group-append">
                    <span class="input-group-text" dir="ltr">
                        <?= e(explode('{tree}', rawurldecode(route('example')))[1]) ?>
                    </span>
                </div>
            </div>
            <p class="small text-muted">
                <?= /* I18N: help text for family tree / GEDCOM file names */ I18N::translate('Avoid spaces and punctuation. A family name might be a good choice.') ?>
            </p>
        </div>
    </div>

    <!-- PEDIGREE_ROOT_ID -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="PEDIGREE_ROOT_ID">
            <?= /* I18N: A configuration setting */ I18N::translate('Default individual') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select-individual', ['name' => 'PEDIGREE_ROOT_ID', 'individual' => $pedigree_individual, 'tree' => $tree]) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Default individual” configuration setting */ I18N::translate('This individual will be selected by default when viewing charts and reports.') ?>
            </p>
        </div>
    </div>

    <!-- CALENDAR_FORMAT -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Calendar conversion') ?>
                <label class="sr-only" for="CALENDAR_FORMAT0">
                    <?= /* I18N: A configuration setting */ I18N::translate('Calendar conversion') ?> 1
                </label>
                <label class="sr-only" for="CALENDAR_FORMAT1">
                    <?= /* I18N: A configuration setting */ I18N::translate('Calendar conversion') ?> 2
                </label>
            </legend>
            <div class="col-sm-9">
                <div class="row">
                    <div class="col-sm-6" style="padding-left: 0;">
                        <?= view('components/select', ['name' => 'CALENDAR_FORMAT0', 'selected' => $calendar_formats[0], 'options' => FunctionsEdit::optionsCalendarConversions()]) ?>
                    </div>
                    <div class="col-sm-6" style="padding-right: 0;">
                        <?= view('components/select', ['name' => 'CALENDAR_FORMAT1', 'selected' => $calendar_formats[1], 'options' => FunctionsEdit::optionsCalendarConversions()]) ?>
                    </div>
                </div>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Calendar conversion” configuration setting */ I18N::translate('Different calendar systems are used in different parts of the world, and many other calendar systems have been used in the past. Where possible, you should enter dates using the calendar in which the event was originally recorded. You can then specify a conversion, to show these dates in a more familiar calendar. If you regularly use two calendars, you can specify two conversions and dates will be converted to both the selected calendars.') ?>
                </p>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Calendar conversion” configuration setting */ I18N::translate('Dates are only converted if they are valid for the calendar. For example, only dates between %1$s and %2$s will be converted to the French calendar and only dates after %3$s will be converted to the Gregorian calendar.', $french_calendar_start->display(false, null, false), $french_calendar_end->display(false, null, false), $gregorian_calendar_start->display(false, null, false)) ?>
                </p>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Calendar conversion” configuration setting */ I18N::translate('In some calendars, days start at midnight. In other calendars, days start at sunset. The conversion process does not take account of the time, so for any event that occurs between sunset and midnight, the conversion between these types of calendar will be one day out.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <!-- GENERATE_UIDS -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Add unique identifiers') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'GENERATE_UIDS', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int) $tree->getPreference('GENERATE_UIDS')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Add unique identifiers” configuration setting */ I18N::translate('Unique identifiers allow the same record to be found in different family trees and in different systems. They will be added whenever records are created or updated. If you do not want unique identifiers to be displayed, you can hide them using the privacy rules.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <h3><?= I18N::translate('Contact information') ?></h3>

    <!-- CONTACT_USER_ID -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="CONTACT_USER_ID">
            <?= /* I18N: A configuration setting */ I18N::translate('Genealogy contact') ?>
        </label>
        <div class="col-sm-9">
            <select id="CONTACT_USER_ID" name="CONTACT_USER_ID" class="form-control">
                <option value="">&nbsp;</option>
                <?php foreach ($members as $member) : ?>
                    <option value="<?= $member->id() ?>" <?= (int) $tree->getPreference('CONTACT_USER_ID') === $member->id() ? 'selected' : '' ?>>
                        <?= e($member->realName()) ?> - <?= e($member->userName()) ?>
                    </option>
                <?php endforeach ?>
            </select>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Genealogy contact” configuration setting */ I18N::translate('The individual to contact about the genealogy data on this website.') ?>
            </p>
        </div>
    </div>

    <!-- WEBMASTER_USER_ID -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="WEBMASTER_USER_ID">
            <?= /* I18N: A configuration setting */ I18N::translate('Technical help contact') ?>
        </label>
        <div class="col-sm-9">
            <select id="WEBMASTER_USER_ID" name="WEBMASTER_USER_ID" class="form-control">
                <option value="">&nbsp;</option>
                <?php foreach ($members as $member) : ?>
                    <option value="<?= $member->id() ?>" <?= (int) $tree->getPreference('WEBMASTER_USER_ID') === $member->id() ? 'selected' : '' ?>>
                        <?= e($member->realName()) ?> - <?= e($member->userName()) ?>
                    </option>
                <?php endforeach ?>
            </select>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Technical help contact” configuration setting */ I18N::translate('The individual to be contacted about technical questions or errors encountered on your website.') ?>
            </p>
        </div>
    </div>

    <h3><?= I18N::translate('Website') ?></h3>

    <!-- META_TITLE -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="META_TITLE">
            <?= /* I18N: A configuration setting */ I18N::translate('Add to TITLE header tag') ?>
        </label>
        <div class="col-sm-9">
            <input
                class="form-control"
                id="META_TITLE"
                maxlength="255"
                name="META_TITLE"
                type="text"
                value="<?= e($tree->getPreference('META_TITLE')) ?>"
            >
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Add to TITLE header tag” configuration setting */ I18N::translate('This text will be appended to each page title. It will be shown in the browser’s title bar, bookmarks, etc.') ?>
            </p>
        </div>
    </div>

    <!-- META_DESCRIPTION -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="META_DESCRIPTION">
            <?= /* I18N: A configuration setting */ I18N::translate('Description META tag') ?>
        </label>
        <div class="col-sm-9">
            <input
                class="form-control"
                id="META_DESCRIPTION"
                maxlength="255"
                name="META_DESCRIPTION"
                type="text"
                value="<?= e($tree->getPreference('META_DESCRIPTION')) ?>"
            >
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Description META tag” configuration setting */ I18N::translate('Search engines may use this description of your site in their search results.') ?>
            </p>
        </div>
    </div>

    <h3><?= I18N::translate('Media folders') ?></h3>

    <!-- MEDIA_DIRECTORY -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="MEDIA_DIRECTORY">
            <?= /* I18N: A configuration setting */ I18N::translate('Media folder') ?>
        </label>
        <div class="col-sm-9">
            <div class="input-group" dir="ltr">
                <div class="input-group-prepend">
                    <span class="input-group-text" dir="ltr">
                        <?= e($data_folder) ?>
                    </span>
                </div>
                <input class="form-control" dir="ltr" id="MEDIA_DIRECTORY" maxlength="255" name="MEDIA_DIRECTORY" type="text" value="<?= e($tree->getPreference('MEDIA_DIRECTORY')) ?>">
            </div>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Media folder” configuration setting */ I18N::translate('This folder will be used to store the media files for this family tree.') ?>
                <?= /* I18N: Help text for the “Media folder” configuration setting */ I18N::translate('If you select a different folder, you must also move any media files from the existing folder to the new one.') ?>
                <?= /* I18N: Help text for the “Media folder” configuration setting */ I18N::translate('If two family trees use the same media folder, then they will be able to share media files. If they use different media folders, then their media files will be kept separate.') ?>
            </p>
        </div>
    </div>

    <h3><?= I18N::translate('Media files') ?></h3>

    <!-- MEDIA_UPLOAD -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="MEDIA_UPLOAD">
            <?= /* I18N: A configuration setting */ I18N::translate('Who can upload new media files') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'MEDIA_UPLOAD', 'selected' => $tree->getPreference('MEDIA_UPLOAD'), 'options' => $privacy_options]) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Who can upload new media files” configuration setting */ I18N::translate('If you are concerned that users might upload inappropriate images, you can restrict media uploads to managers only.') ?>
            </p>
        </div>
    </div>

    <!-- SHOW_MEDIA_DOWNLOAD -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Show a download link in the media viewer') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/select', ['name' => 'SHOW_MEDIA_DOWNLOAD', 'selected' => $tree->getPreference('SHOW_MEDIA_DOWNLOAD'), 'options' => FunctionsEdit::optionsAccessLevels()]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Show a download link in the media viewer” configuration setting */ I18N::translate('This option will make it easier for users to download images.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <h3><?= I18N::translate('Thumbnail images') ?></h3>

    <!-- SHOW_HIGHLIGHT_IMAGES -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= I18N::translate('Thumbnail images') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'SHOW_HIGHLIGHT_IMAGES', 'options' => [I18N::translate('hide'), I18N::translate('show')], 'selected' => (int) $tree->getPreference('SHOW_HIGHLIGHT_IMAGES')]) ?>
                <p class="small text-muted">
                    <?= I18N::translate('Show thumbnail images in charts and family groups.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <!-- USE_SILHOUETTE -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Use silhouettes') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'USE_SILHOUETTE', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int) $tree->getPreference('USE_SILHOUETTE')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Use silhouettes” configuration setting */ I18N::translate('Use silhouette images when no highlighted image for that individual has been specified. The images used are specific to the gender of the individual in question.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <h3><?= I18N::translate('Watermarks') ?></h3>

    <!-- SHOW_NO_WATERMARK -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="SHOW_NO_WATERMARK">
            <?= I18N::translate('Images without watermarks') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'SHOW_NO_WATERMARK', 'selected' => $tree->getPreference('SHOW_NO_WATERMARK'), 'options' => FunctionsEdit::optionsAccessLevels()]) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Images without watermarks” configuration setting */ I18N::translate('Watermarks are optional and normally shown just to visitors.') ?>
            </p>
        </div>
    </div>

    <h3><?= I18N::translate('Lists') ?></h3>

    <!-- SURNAME_LIST_STYLE -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="SURNAME_LIST_STYLE">
            <?= I18N::translate('Surname list style') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'SURNAME_LIST_STYLE', 'selected' => $tree->getPreference('SURNAME_LIST_STYLE'), 'options' => $surname_list_styles]) ?>
            <p class="small text-muted">
            </p>
        </div>
    </div>

    <!-- SUBLIST_TRIGGER_I -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="SUBLIST_TRIGGER_I">
            <?= /* I18N: A configuration setting */ I18N::translate('Maximum number of surnames on individual list') ?>
        </label>
        <div class="col-sm-9">
            <input
                class="form-control"
                id="SUBLIST_TRIGGER_I"
                maxlength="5"
                name="SUBLIST_TRIGGER_I"
                required
                type="text"
                value="<?= e($tree->getPreference('SUBLIST_TRIGGER_I')) ?>"
            >
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Maximum number of surnames on individual list” configuration setting */ I18N::translate('Long lists of individuals with the same surname can be broken into smaller sub-lists according to the first letter of the individual’s given name.<br><br>This option determines when sub-listing of surnames will occur. To disable sub-listing completely, set this option to zero.') ?>
            </p>
        </div>
    </div>

    <!-- SHOW_EST_LIST_DATES -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Estimated dates for birth and death') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'SHOW_EST_LIST_DATES', 'options' => [I18N::translate('hide'), I18N::translate('show')], 'selected' => (int) $tree->getPreference('SHOW_EST_LIST_DATES')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Estimated dates for birth and death” configuration setting */ I18N::translate('This option controls whether or not to show estimated dates for birth and death instead of leaving blanks on individual lists and charts for individuals whose dates are not known.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <!-- SHOW_LAST_CHANGE -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= I18N::translate('The date and time of the last update') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'SHOW_LAST_CHANGE', 'options' => [I18N::translate('hide'), I18N::translate('show')], 'selected' => (int) $tree->getPreference('SHOW_LAST_CHANGE')]) ?>
                <p class="small text-muted">
                </p>
            </div>
        </div>
    </fieldset>

    <h3><?= I18N::translate('Charts') ?></h3>

    <!-- SHOW_PARENTS_AGE -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Age of parents next to child’s birthdate') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'SHOW_PARENTS_AGE', 'options' => [I18N::translate('hide'), I18N::translate('show')], 'selected' => (int) $tree->getPreference('SHOW_PARENTS_AGE')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Age of parents next to child’s birthdate” configuration setting */ I18N::translate('This option controls whether or not to show age of father and mother next to child’s birthdate on charts.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <!-- CHART_BOX_TAGS -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="CHART_BOX_TAGS">
            <?= I18N::translate('Other facts to show in charts') ?>
        </label>
        <div class="col-sm-9">
            <div class="input-group">
                <?= view('components/select', ['name' => 'CHART_BOX_TAGS[]', 'id' => 'CHART_BOX_TAGS', 'selected' => explode(',', $tree->getPreference('CHART_BOX_TAGS')), 'options' => $all_indi_facts, 'class' => 'select2']) ?>
            </div>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Other facts to show in charts” configuration setting */ I18N::translate('This should be a comma or space separated list of facts, in addition to birth and death, that you want to appear in chart boxes such as the pedigree chart. This list requires you to use fact tags as defined in the GEDCOM 5.5.1 standard. For example, if you wanted the occupation to show up in the box, you would add “OCCU” to this field.') ?>
            </p>
        </div>
    </div>

    <h3><?= I18N::translate('Individual pages') ?></h3>

    <!-- SHOW_RELATIVES_EVENTS -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= I18N::translate('Show the events of close relatives on the individual page') ?>
            </legend>
            <div class="col-sm-3">
                <div class="form-check">
                    <label for="_BIRT_GCHI">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_BIRT_GCHI" value="_BIRT_GCHI" <?= in_array('_BIRT_GCHI', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Birth of a grandchild') ?>
                    </label>
                </div>
                <div class="form-check">
                    <label for="_BIRT_CHIL">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_BIRT_CHIL" value="_BIRT_CHIL" <?= in_array('_BIRT_CHIL', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Birth of a child') ?>
                    </label>
                </div>
                <div class="form-check">
                    <label for="_BIRT_SIBL">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_BIRT_SIBL" value="_BIRT_SIBL" <?= in_array('_BIRT_SIBL', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Birth of a sibling') ?>
                    </label>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="form-check">
                    <label for="_MARR_GCHI">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_MARR_GCHI" value="_MARR_GCHI" <?= in_array('_MARR_GCHI', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Marriage of a grandchild') ?>
                    </label>
                </div>
                <div class="form-check">
                    <label for="_MARR_CHIL">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_MARR_CHIL" value="_MARR_CHIL" <?= in_array('_MARR_CHIL', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Marriage of a child') ?>
                    </label>
                </div>
                <div class="form-check">
                    <label for="_MARR_SIBL">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_MARR_SIBL" value="_MARR_SIBL" <?= in_array('_MARR_SIBL', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Marriage of a sibling') ?>
                    </label>
                </div>
                <div class="form-check">
                    <label for="_MARR_PARE">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_MARR_PARE" value="_MARR_PARE" <?= in_array('_MARR_PARE', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Marriage of a parent') ?>
                    </label>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="form-check">
                    <label for="_DEAT_GCHI">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_DEAT_GCHI" value="_DEAT_GCHI" <?= in_array('_DEAT_GCHI', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Death of a grandchild') ?>
                    </label>
                </div>
                <div class="form-check">
                    <label for="_DEAT_CHIL">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_DEAT_CHIL" value="_DEAT_CHIL" <?= in_array('_DEAT_CHIL', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Death of a child') ?>
                    </label>
                </div>
                <div class="form-check">
                    <label for="_DEAT_SIBL">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_DEAT_SIBL" value="_DEAT_SIBL" <?= in_array('_DEAT_SIBL', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Death of a sibling') ?>
                    </label>
                </div>
                <div class="form-check">
                    <label for="_DEAT_PARE">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_DEAT_PARE" value="_DEAT_PARE" <?= in_array('_DEAT_PARE', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Death of a parent') ?>
                    </label>
                </div>
                <div class="form-check">
                    <label for="_DEAT_SPOU">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_DEAT_SPOU" value="_DEAT_SPOU" <?= in_array('_DEAT_SPOU', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Death of a spouse') ?>
                    </label>
                </div>
                <div class="form-check">
                    <label for="_DEAT_GPAR">
                        <input name="SHOW_RELATIVES_EVENTS[]" type="checkbox" id="_DEAT_GPAR" value="_DEAT_GPAR" <?= in_array('_DEAT_GPAR', $relatives_events, true) ? 'checked' : '' ?>>
                        <?= I18N::translate('Death of a grand-parent') ?>
                    </label>
                </div>
            </div>
        </div>
    </fieldset>

    <!-- SHOW_FACT_ICONS -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Fact icons') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'SHOW_FACT_ICONS', 'options' => [I18N::translate('hide'), I18N::translate('show')], 'selected' => (int) $tree->getPreference('SHOW_FACT_ICONS')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Fact icons” configuration setting */ I18N::translate('Some themes can display icons on the “Facts and events” tab.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <!-- EXPAND_NOTES -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Automatically expand notes') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'EXPAND_NOTES', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int) $tree->getPreference('EXPAND_NOTES')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Automatically expand notes” configuration setting */
                    I18N::translate('This option controls whether or not to automatically display content of a <i>Note</i> record on the Individual page.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <!-- EXPAND_SOURCES -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Automatically expand sources') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'EXPAND_SOURCES', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int) $tree->getPreference('EXPAND_SOURCES')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Automatically expand sources” configuration setting */
                    I18N::translate('This option controls whether or not to automatically display content of a <i>Source</i> record on the Individual page.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <h3><?= I18N::translate('Places') ?></h3>

    <!-- SHOW_PEDIGREE_PLACES -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Abbreviate place names') ?>
                <label class="sr-only" for="SHOW_PEDIGREE_PLACES_SUFFIX">
                    <?= /* I18N: A configuration setting */ I18N::translate('Abbreviate place names') ?>
                    <?= I18N::translate('first') ?> / <?= I18N::translate('last') ?>
                </label>
                <label class="sr-only" for="SHOW_PEDIGREE_PLACES">
                    <?= /* I18N: A configuration setting */ I18N::translate('Abbreviate place names') ?>
                </label>
            </legend>
            <div class="col-sm-9">
                <?= /* I18N: The placeholders are edit controls. Show the [first/last] [1/2/3/4/5] parts of a place name */ I18N::translate(
                    'Show the %1$s %2$s parts of a place name.',
                    view('components/select', ['name' => 'SHOW_PEDIGREE_PLACES_SUFFIX', 'selected' => $tree->getPreference('SHOW_PEDIGREE_PLACES_SUFFIX'), 'options' => ['0' => I18N::translateContext('Show the [first/last] [N] parts of a place name.', 'first'), '1' => I18N::translateContext('Show the [first/last] [N] parts of a place name.', 'last')]]),
                    view('components/select', ['name' => 'SHOW_PEDIGREE_PLACES', 'selected' => $tree->getPreference('SHOW_PEDIGREE_PLACES'), 'options' => FunctionsEdit::numericOptions(range(1, 9))])
                ) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Abbreviate place names” configuration setting */ I18N::translate('Place names are frequently too long to fit on charts, lists, etc. They can be abbreviated by showing just the first few parts of the name, such as <i>village, county</i>, or the last few part of it, such as <i>region, country</i>.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <h3><?= I18N::translate('Text') ?></h3>

    <!-- FORMAT_TEXT -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Format text and notes') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'FORMAT_TEXT', 'options' => $formats, 'selected' =>  $tree->getPreference('FORMAT_TEXT')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Format text and notes” configuration setting */ I18N::translate('To ensure compatibility with other genealogy applications, notes, text, and transcripts should be recorded in simple, unformatted text. However, formatting is often desirable to aid presentation, comprehension, etc.') ?>
                </p>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Format text and notes” configuration setting */ I18N::translate('Markdown is a simple system of formatting, used on websites such as Wikipedia. It uses unobtrusive punctuation characters to create headings and sub-headings, bold and italic text, lists, tables, etc.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <h3><?= I18N::translate('General') ?></h3>

    <!-- SHOW_GEDCOM_RECORD -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Allow users to see raw GEDCOM records') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'SHOW_GEDCOM_RECORD', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int) $tree->getPreference('SHOW_GEDCOM_RECORD')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Allow users to see raw GEDCOM records” configuration setting */ I18N::translate('Setting this to <b>Yes</b> will place links on individuals, sources, and families to let users bring up another window containing the raw data taken right out of the GEDCOM file.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <!-- HIDE_GEDCOM_ERRORS -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('GEDCOM errors') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'HIDE_GEDCOM_ERRORS', 'options' => [I18N::translate('hide'), I18N::translate('show')], 'selected' => (int) $tree->getPreference('HIDE_GEDCOM_ERRORS')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “GEDCOM errors” configuration setting */ I18N::translate('Many genealogy programs create GEDCOM files with custom tags, and webtrees understands most of them. When unrecognized tags are found, this option lets you choose whether to ignore them or display a warning message.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <!-- SHOW_COUNTER -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Hit counters') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'SHOW_COUNTER', 'options' => [I18N::translate('hide'), I18N::translate('show')], 'selected' => (int) $tree->getPreference('SHOW_COUNTER')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Hit counters” configuration setting */ I18N::translate('Some pages can display the number of times that they have been visited.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <h3><?= /* I18N: Options for editing */ I18N::translate('Edit preferences') ?></h3>

    <h3><?= I18N::translate('Facts for individual records') ?></h3>

    <!-- INDI_FACTS_ADD -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="INDI_FACTS_ADD">
            <?= I18N::translate('All individual facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'INDI_FACTS_ADD[]', 'id' => 'INDI_FACTS_ADD', 'selected' => explode(',', $tree->getPreference('INDI_FACTS_ADD')), 'options' => $all_indi_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “All individual facts” configuration setting */ I18N::translate('This is the list of GEDCOM facts that your users can add to individuals. You can modify this list by removing or adding fact names, even custom ones, as necessary. Fact names that appear in this list must not also appear in the “Unique individual facts” list.') ?>
            </p>
        </div>
    </div>

    <!-- INDI_FACTS_UNIQUE -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="INDI_FACTS_UNIQUE">
            <?= I18N::translate('Unique individual facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'INDI_FACTS_UNIQUE[]', 'id' => 'INDI_FACTS_UNIQUE', 'selected' => explode(',', $tree->getPreference('INDI_FACTS_UNIQUE')), 'options' => $all_indi_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Unique individual facts” configuration setting */ I18N::translate('This is the list of GEDCOM facts that your users can only add once to individuals. For example, if BIRT is in this list, users will not be able to add more than one BIRT record to an individual. Fact names that appear in this list must not also appear in the “All individual facts” list.') ?>
            </p>
        </div>
    </div>

    <!-- QUICK_REQUIRED_FACTS -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="QUICK_REQUIRED_FACTS">
            <?= I18N::translate('Facts for new individuals') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'QUICK_REQUIRED_FACTS[]', 'id' => 'QUICK_REQUIRED_FACTS', 'selected' => explode(',', $tree->getPreference('QUICK_REQUIRED_FACTS')), 'options' => $all_indi_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Facts for new individuals” configuration setting */ I18N::translate('This is a comma separated list of GEDCOM fact tags that will be shown when adding a new individual. For example, if BIRT is in the list, fields for birth date and birth place will be shown on the form.') ?>
            </p>
        </div>
    </div>

    <!-- INDI_FACTS_QUICK -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="INDI_FACTS_QUICK">
            <?= I18N::translate('Quick individual facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'INDI_FACTS_QUICK[]', 'id' => 'INDI_FACTS_QUICK', 'selected' => explode(',', $tree->getPreference('INDI_FACTS_QUICK')), 'options' => $all_indi_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Quick individual facts” configuration setting */ I18N::translate('The most common individual facts and events are listed separately, so that they can be added more easily.') ?>
            </p>
        </div>
    </div>

    <h3><?= I18N::translate('Facts for family records') ?></h3>

    <!-- FAM_FACTS_ADD -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="FAM_FACTS_ADD">
            <?= I18N::translate('All family facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'FAM_FACTS_ADD[]', 'id' => 'FAM_FACTS_ADD', 'selected' => explode(',', $tree->getPreference('FAM_FACTS_ADD')), 'options' => $all_fam_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “All family facts” configuration setting */ I18N::translate('This is the list of GEDCOM facts that your users can add to families. You can modify this list by removing or adding fact names, even custom ones, as necessary. Fact names that appear in this list must not also appear in the “Unique family facts” list.') ?>
            </p>
        </div>
    </div>

    <!-- FAM_FACTS_UNIQUE -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="FAM_FACTS_UNIQUE">
            <?= I18N::translate('Unique family facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'FAM_FACTS_UNIQUE[]', 'id' => 'FAM_FACTS_UNIQUE', 'selected' => explode(',', $tree->getPreference('FAM_FACTS_UNIQUE')), 'options' => $all_fam_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Unique family facts” configuration setting */ I18N::translate('This is the list of GEDCOM facts that your users can only add once to families. For example, if MARR is in this list, users will not be able to add more than one MARR record to a family. Fact names that appear in this list must not also appear in the “All family facts” list.') ?>
            </p>
        </div>
    </div>

    <!-- QUICK_REQUIRED_FAMFACTS -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="QUICK_REQUIRED_FAMFACTS">
            <?= I18N::translate('Facts for new families') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'QUICK_REQUIRED_FAMFACTS[]', 'id' => 'QUICK_REQUIRED_FAMFACTS', 'selected' => explode(',', $tree->getPreference('QUICK_REQUIRED_FAMFACTS')), 'options' => $all_fam_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Facts for new families” configuration setting */ I18N::translate('This is a comma separated list of GEDCOM fact tags that will be shown when adding a new family. For example, if MARR is in the list, then fields for marriage date and marriage place will be shown on the form.') ?>
            </p>
        </div>
    </div>

    <!-- FAM_FACTS_QUICK -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="FAM_FACTS_QUICK">
            <?= I18N::translate('Quick family facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'FAM_FACTS_QUICK[]', 'id' => 'FAM_FACTS_QUICK', 'selected' => explode(',', $tree->getPreference('FAM_FACTS_QUICK')), 'options' => $all_fam_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Quick family facts” configuration setting */ I18N::translate('The most common family facts and events are listed separately, so that they can be added more easily.') ?>
            </p>
        </div>
    </div>

    <h3><?= I18N::translate('Facts for source records') ?></h3>

    <!-- SOUR_FACTS_ADD -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="SOUR_FACTS_ADD">
            <?= I18N::translate('All source facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'SOUR_FACTS_ADD[]', 'id' => 'SOUR_FACTS_ADD', 'selected' => explode(',', $tree->getPreference('SOUR_FACTS_ADD')), 'options' => $all_sour_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “All source facts” configuration setting */ I18N::translate('This is the list of GEDCOM facts that your users can add to sources. You can modify this list by removing or adding fact names, even custom ones, as necessary. Fact names that appear in this list must not also appear in the “Unique source facts” list.') ?>
            </p>
        </div>
    </div>

    <!-- SOUR_FACTS_UNIQUE -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="SOUR_FACTS_UNIQUE">
            <?= I18N::translate('Unique source facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'SOUR_FACTS_UNIQUE[]', 'id' => 'SOUR_FACTS_UNIQUE', 'selected' => explode(',', $tree->getPreference('SOUR_FACTS_UNIQUE')), 'options' => $all_sour_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Unique source facts” configuration setting */ I18N::translate('This is the list of GEDCOM facts that your users can only add once to sources. For example, if TITL is in this list, users will not be able to add more than one TITL record to a source. Fact names that appear in this list must not also appear in the “All source facts” list.') ?>
            </p>
        </div>
    </div>

    <!-- SOUR_FACTS_QUICK -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="SOUR_FACTS_QUICK">
            <?= I18N::translate('Quick source facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'SOUR_FACTS_QUICK[]', 'id' => 'SOUR_FACTS_QUICK', 'selected' => explode(',', $tree->getPreference('SOUR_FACTS_QUICK')), 'options' => $all_sour_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Quick source facts” configuration setting */ I18N::translate('The most common source facts are listed separately, so that they can be added more easily.') ?>
            </p>
        </div>
    </div>

    <h3><?= I18N::translate('Facts for repository records') ?></h3>

    <!-- REPO_FACTS_ADD -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="REPO_FACTS_ADD">
            <?= I18N::translate('All repository facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'REPO_FACTS_ADD[]', 'id' => 'REPO_FACTS_ADD', 'selected' => explode(',', $tree->getPreference('REPO_FACTS_ADD')), 'options' => $all_repo_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “All repository facts” configuration setting */ I18N::translate('This is the list of GEDCOM facts that your users can add to repositories. You can modify this list by removing or adding fact names, even custom ones, as necessary. Fact names that appear in this list must not also appear in the “Unique repository facts” list.') ?>
            </p>
        </div>
    </div>

    <!-- REPO_FACTS_UNIQUE -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="REPO_FACTS_UNIQUE">
            <?= I18N::translate('Unique repository facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'REPO_FACTS_UNIQUE[]', 'id' => 'REPO_FACTS_UNIQUE', 'selected' => explode(',', $tree->getPreference('REPO_FACTS_UNIQUE')), 'options' => $all_repo_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Unique repository facts” configuration setting */ I18N::translate('This is the list of GEDCOM facts that your users can only add once to repositories. For example, if NAME is in this list, users will not be able to add more than one NAME record to a repository. Fact names that appear in this list must not also appear in the “All repository facts” list.') ?>
            </p>
        </div>
    </div>

    <!-- REPO_FACTS_QUICK -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="REPO_FACTS_QUICK">
            <?= I18N::translate('Quick repository facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'REPO_FACTS_QUICK[]', 'id' => 'REPO_FACTS_QUICK', 'selected' => explode(',', $tree->getPreference('REPO_FACTS_QUICK')), 'options' => $all_repo_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Quick repository facts” configuration setting */ I18N::translate('The most common repository facts are listed separately, so that they can be added more easily.') ?>
            </p>
        </div>
    </div>

    <h3><?= I18N::translate('Advanced fact preferences') ?></h3>

    <!-- ADVANCED_NAME_FACTS -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="ADVANCED_NAME_FACTS">
            <?= I18N::translate('Advanced name facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'ADVANCED_NAME_FACTS[]', 'id' => 'ADVANCED_NAME_FACTS', 'selected' => explode(',', $tree->getPreference('ADVANCED_NAME_FACTS')), 'options' => $all_name_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Advanced name facts” configuration setting */ I18N::translate('This is a comma separated list of GEDCOM fact tags that will be shown on the add/edit name form. If you use non-Latin alphabets such as Hebrew, Greek, Cyrillic, or Arabic, you may want to add tags such as _HEB, ROMN, FONE, etc. to allow you to store names in several different alphabets.') ?>
            </p>
        </div>
    </div>

    <!-- ADVANCED_PLAC_FACTS -->
    <div class="row form-group">
        <label class="col-sm-3 col-form-label" for="ADVANCED_PLAC_FACTS">
            <?= I18N::translate('Advanced place name facts') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select', ['name' => 'ADVANCED_PLAC_FACTS[]', 'id' => 'ADVANCED_PLAC_FACTS', 'selected' => explode(',', $tree->getPreference('ADVANCED_PLAC_FACTS')), 'options' => $all_plac_facts, 'class' => 'select2']) ?>
            <p class="small text-muted">
                <?= /* I18N: Help text for the “Advanced place name facts” configuration setting */ I18N::translate('This is a comma separated list of GEDCOM fact tags that will be shown when you add or edit place names. If you use non-Latin alphabets such as Hebrew, Greek, Cyrillic, or Arabic, you may want to add tags such as _HEB, ROMN, FONE, etc. to allow you to store place names in several different alphabets.') ?>
            </p>
        </div>
    </div>

    <h3><?= I18N::translate('Other preferences') ?></h3>

    <!-- SURNAME_TRADITION -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= I18N::translate('Surname tradition') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios', ['name' => 'SURNAME_TRADITION', 'options' => $all_surname_traditions, 'selected' => $tree->getPreference('SURNAME_TRADITION')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Surname tradition” configuration setting */ I18N::translate('When you add a new family member, a default surname can be provided. This surname will depend on the local tradition.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <!-- FULL_SOURCES -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Use full source citations') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'FULL_SOURCES', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int) $tree->getPreference('FULL_SOURCES')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Use full source citations” configuration setting */ I18N::translate('Source citations can include fields to record the quality of the data (primary, secondary, etc.) and the date the event was recorded in the source. If you don’t use these fields, you can disable them when creating new source citations.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <!-- PREFER_LEVEL2_SOURCES -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Source type') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'PREFER_LEVEL2_SOURCES', 'options' => $source_types, 'selected' => (int) $tree->getPreference('PREFER_LEVEL2_SOURCES')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Source type” configuration setting */ I18N::translate('When adding new close relatives, you can add source citations to the records (individual and family) or to the facts and events (birth, marriage, and death). This option controls whether records or facts will be selected by default.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <!-- NO_UPDATE_CHAN -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3">
                <?= /* I18N: A configuration setting */ I18N::translate('Keep the existing “last change” information') ?>
            </legend>
            <div class="col-sm-9">
                <?= view('components/radios-inline', ['name' => 'NO_UPDATE_CHAN', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int) $tree->getPreference('NO_UPDATE_CHAN')]) ?>
                <p class="small text-muted">
                    <?= /* I18N: Help text for the “Keep the existing ‘last change’ information” configuration setting */ I18N::translate('When a record is edited, the user and timestamp are recorded. Sometimes it is desirable to keep the existing “last change” information, for example when making minor corrections to someone else’s data. This option controls whether this feature is selected by default.') ?>
                </p>
            </div>
        </div>
    </fieldset>

    <div class="row form-group">
        <div class="offset-sm-3 col-sm-9">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= I18N::translate('save') ?>
            </button>
            <a class="btn btn-secondary" href="<?= e(route('manage-trees', ['tree' => $tree->name()])) ?>">
        <?= view('icons/cancel') ?>
                <?= I18N::translate('cancel') ?>
            </a>
            <!-- Coming soon
            <div class="form-check">
                <?php if ($tree_count > 1) : ?>
                <label>
                    <input type="checkbox" name="all_trees">
                    <?= /* I18N: Label for checkbox */ I18N::translate('Apply these preferences to all family trees') ?>
                </label>
                <?php endif ?>
            </div>
            <div class="form-check">
                <label>
                    <input type="checkbox" name="new_trees">
                    <?= /* I18N: Label for checkbox */ I18N::translate('Apply these preferences to new family trees') ?>
                </label>
            </div>
        </div>
        -->
        </div>
</form>
