<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ManageTrees;
use Fisharebest\Webtrees\Http\RequestHandlers\UnconnectedAction;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var string                            $title
 * @var bool                              $aliases
 * @var bool                              $associates
 * @var array<Collection<int,Individual>> $individual_groups
 * @var Individual                        $root
 * @var Tree                              $tree
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ManageTrees::class, ['tree' => $tree->name()]) => I18N::translate('Manage family trees'), $title]]) ?>

<h1><?= $title ?></h1>

<form method="post" action="<?= e(route(UnconnectedAction::class, ['tree' => $tree->name()])) ?>">
    <?= view('components/checkbox-inline', ['label' => I18N::translate('Include associates'), 'checked' => $associates, 'name' => 'associates']) ?>
    <?= view('components/checkbox-inline', ['label' => I18N::translate('Include aliases'), 'checked' => $aliases, 'name' => 'aliases']) ?>

    <button type="submit" class="btn btn-primary">
        <?= I18N::translate('update') ?>
    </button>

    <?= csrf_field() ?>
</form>

<p><?= I18N::translate('These groups of individuals are not related to %s.', $root->fullName()) ?></p>

<?php foreach ($individual_groups as $group) : ?>
    <h2><?= I18N::plural('%s individual', '%s individuals', count($group), I18N::number(count($group))) ?></h2>
    <ul>
        <?php foreach ($group as $individual) : ?>
            <li>
                <a href="<?= e($individual->url()) ?>"><?= $individual->fullName() ?></a>
            </li>
        <?php endforeach ?>
    </ul>
<?php endforeach ?>
