<?php

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ExportGedcomClient;
use Fisharebest\Webtrees\Http\RequestHandlers\ExportGedcomServer;
use Fisharebest\Webtrees\Http\RequestHandlers\ManageTrees;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var string $filename
 * @var string $title
 * @var Tree   $tree
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ManageTrees::class, ['tree' => $tree->name()]) => I18N::translate('Manage family trees'), $title]]) ?>

<h1><?= $title ?></h1>

<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
                <?= I18N::translate('A file on the server') ?>
            </div>
            <div class="card-body">
                <form method="post" action="<?= e(route(ExportGedcomServer::class, ['tree' => $tree->name()])) ?>" class="form form-horizontal">
                    <?= csrf_field() ?>


                    <div class="form-group mb-3">
                        <label for="filename"><?= I18N::translate('Filename') ?></label>
                        <input type="text" class="form-control" id="filename" name="filename" value="<?= e($filename) ?>">
                    </div>

                    <button type="submit" class="btn btn-primary">
                        <?= view('icons/save') ?>
                        <?= /* I18N: A button label. */
                        I18N::translate('continue') ?>
                    </button>
                </form>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
                <?= I18N::translate('A file on your computer') ?>
            </div>

            <div class="card-body">
                <form method="post" action="<?= e(route(ExportGedcomClient::class, ['tree' => $tree->name()])) ?>" class="form form-horizontal">
                    <?= csrf_field() ?>

                    <p class="card-title">
                        <?= I18N::translate('Export preferences') ?>
                    </p>

                    <?= view('admin/gedcom-export-options', ['tree' => $tree]) ?>

                    <?php if ($tree->getPreference('GEDCOM_MEDIA_PATH') !== '') : ?>
                        <div class="row mb-3">
                            <label class="col-sm-3" for="media-path">
                                <?= /* I18N: A media path (e.g. C:\aaa\bbb\ccc\) in a GEDCOM file */ I18N::translate('Add the GEDCOM media path to filenames') ?>
                            </label>

                            <div class="col-sm-9">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="media-path" name="media_path">
                                    <label class="form-check-label" for="media-path">
                                        <?= /* I18N: %s is the name of a folder. */ I18N::translate('Media filenames will be prefixed by %s.', '<code dir="ltr">' . e($tree->getPreference('GEDCOM_MEDIA_PATH')) . '</code>') ?>
                                    </label>
                                </div>
                            </div>
                        </div>
                    <?php endif ?>

                    <button type="submit" class="btn btn-primary">
                        <?= view('icons/download') ?>
                        <?= /* I18N: A button label. */
                        I18N::translate('continue') ?>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<?= view('modals/ajax') ?>
