<?php

declare(strict_types=1);

use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\Http\Controllers\ControlPanel;
use Fisharebest\Webtrees\Http\Controllers\ManageTrees;
use Fisharebest\Webtrees\Http\Controllers\MergeFacts;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var array<string,array<int,array<int,GedcomRecord>>> $duplicates
 * @var Tree                                             $tree
 * @var string                                           $title
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ManageTrees::class, ['tree' => $tree->name()]) => I18N::translate('Manage family trees'), $title]]) ?>

<h1><?= $title ?></h1>

<?php foreach ($duplicates as $category => $records) : ?>
    <h2><?= $category ?></h2>

    <?php if ($records !== []) : ?>
        <ol>
            <?php foreach ($records as $duplicate_group) : ?>
                <li>
                    <?= $duplicate_group[0]->fullName() ?>
                    <?php foreach ($duplicate_group as $record) : ?>
                        —
                        <a href="<?= e($record->url()) ?>">
                            <?= $record->xref() ?>
                        </a>
                    <?php endforeach ?>
                    <?php if (count($duplicate_group) === 2) : ?>
                        —
                        <a href="<?= e(route(MergeFacts::class, ['tree' => $tree->name(), 'xref1' => $duplicate_group[0]->xref(), 'xref2' => $duplicate_group[1]->xref()])) ?>">
                            <?= I18N::translate('Merge') ?>
                        </a>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
        </ol>
    <?php else : ?>
        <p><?= I18N::translate('No duplicates have been found.') ?></p>
    <?php endif ?>
<?php endforeach ?>
