<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Place;

/**
 * @var string $name
 * @var Place $place
 * @var string $tag
 * @var string $url
 * @var string $value
 * @var string $date
 */

?>

<div class="label">
    <?= $tag ?>
</div>

<div>
    <?= $date ?>
</div>

<?php if ($url !== '') : ?>
    <a href="<?= e($url) ?>">
        <?= $name ?>
    </a>
<?php endif ?>

<?php if ($value !== '') : ?>
    <span>
        <?= $value ?>
    </span>
<?php endif ?>

<?php if ($place->gedcomName() !== '') : ?>
    <div>
        <?= $place->fullName(true) ?>
    </div>
<?php endif ?>
