<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var array<mixed> $data
 * @var object       $leaflet_config
 */

?>

<div
    class="row gx-1 wt-places-tab-wrapper wt-fullscreen-container"
    data-wt-places-tab-map
    data-wt-leaflet-config="<?= e(json_encode($leaflet_config, JSON_THROW_ON_ERROR)) ?>"
    data-wt-map-data="<?= e(json_encode($data, JSON_THROW_ON_ERROR)) ?>"
    data-wt-nothing-to-show="<?= e(I18N::translate('Nothing to show')) ?>"
>
    <div class="col-sm-9">
        <div id="wt-map" class="wt-map" data-wt-map-canvas dir="ltr"><?= view('icons/spinner') ?></div>
    </div>
    <div class="col-sm-3">
        <ul class="wt-map-sidebar list-unstyled mb-0" data-wt-map-sidebar></ul>
    </div>
</div>

