<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

$chart_options = [
    'title' => '',
    'subtitle' => '',
    'height' => 400,
    'width'  => '100%',
    'legend' => [
        'position'  => 'none',
    ],
    'vAxis' => [
        'title' => I18N::translate('Total'),
    ],
    'hAxis' => [
        'title' => I18N::translate('Century'),
    ],
    'colors' => [
        '#84beff',
        '#ffd1dc',
    ],
    'isStacked' => true,
];

echo view('statistics/other/charts/column', [
    'data'          => $data,
    'chart_options' => $chart_options,
    'chart_title'   => $title,
    'language'      => I18N::languageTag(),
]);
