<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

?>

data-auto-width="false"
data-dom="<&quot;d-flex justify-content-between&quot;pf><t><&quot;d-flex justify-content-between&quot;irl>"
data-state-save="true"
data-length-menu="<?= e(json_encode([[10, 20, 50, 100, 500, 1000, -1], [I18N::number(10), I18N::number(20), I18N::number(50), I18N::number(100), I18N::number(500), I18N::number(1000), I18N::translate('All')]], JSON_THROW_ON_ERROR)) ?>"
data-language="<?= e(json_encode([
        'paginate'       => [
            /* I18N: A button label, first page */
            'first'    => I18N::translate('first'),
            /* I18N: A button label, last page */
            'last'     => I18N::translate('last'),
            /* I18N: A button label, next page */
            'next'     => I18N::translate('next'),
            /* I18N: A button label, previous page */
            'previous' => I18N::translate('previous'),
        ],
        'emptyTable'     => I18N::translate('No records to display'),
        /* I18N: %s are placeholders for numbers */
        'info'           => I18N::translate('Showing %1$s to %2$s of %3$s', '_START_', '_END_', '_TOTAL_'),
        'infoEmpty'      => I18N::translate('Showing %1$s to %2$s of %3$s', I18N::number(0), I18N::number(0), I18N::number(0)),
        /* I18N: %s is a number */
        'infoFiltered'   => I18N::translate('(filtered from %s total entries)', '_MAX_'),
        /* I18N: %s is a number of records per page */
        'lengthMenu'     => I18N::translate('Display %s', '_MENU_'),
        'loadingRecords' => I18N::translate('Loading…'),
        'processing'     => I18N::translate('Calculating…'),
        'search'         => I18N::translate('Filter'),
        'zeroRecords'    => I18N::translate('No records to display'),
    ], JSON_THROW_ON_ERROR)) ?>"
