<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Note;
use Fisharebest\Webtrees\Tree;
use Illuminate\Database\Capsule\Manager as DB;
use Illuminate\Database\Query\Expression;
use Illuminate\Database\Query\JoinClause;
use Illuminate\Support\Collection;

/**
 * @var string|null          $caption
 * @var Collection<int,Note> $notes
 * @var Tree                 $tree
 */

?>

<?php
// Count the number of linked records. These numbers include private records.
// It is not good to bypass privacy, but many servers do not have the resources
// to process privacy for every record in the tree
$count_individuals = DB::table('individuals')
    ->join('link', static function (JoinClause $join): void {
        $join->on('l_from', '=', 'i_id');
        $join->on('l_file', '=', 'i_file');
    })
    ->where('l_type', '=', 'NOTE')
    ->where('l_file', '=', $tree->id())
    ->groupBy(['l_to'])
    ->pluck(new Expression('COUNT(*)'), 'l_to')
    ->map(static fn (string $n): int => (int) $n)
    ->all();

$count_families = DB::table('families')
    ->join('link', static function (JoinClause $join): void {
        $join->on('l_from', '=', 'f_id');
        $join->on('l_file', '=', 'f_file');
    })
    ->where('l_type', '=', 'NOTE')
    ->where('l_file', '=', $tree->id())
    ->groupBy(['l_to'])
    ->pluck(new Expression('COUNT(*)'), 'l_to')
    ->map(static fn (string $n): int => (int) $n)
    ->all();

$count_media = DB::table('media')
    ->join('link', static function (JoinClause $join): void {
        $join->on('l_from', '=', 'm_id');
        $join->on('l_file', '=', 'm_file');
    })
    ->where('l_type', '=', 'NOTE')
    ->where('l_file', '=', $tree->id())
    ->groupBy(['l_to'])
    ->pluck(new Expression('COUNT(*)'), 'l_to')
    ->map(static fn (string $n): int => (int) $n)
    ->all();

$count_sources = DB::table('sources')
    ->join('link', static function (JoinClause $join): void {
        $join->on('l_from', '=', 's_id');
        $join->on('l_file', '=', 's_file');
    })
    ->where('l_type', '=', 'NOTE')
    ->where('l_file', '=', $tree->id())
    ->groupBy(['l_to'])
    ->pluck(new Expression('COUNT(*)'), 'l_to')
    ->map(static fn (string $n): int => (int) $n)
    ->all();
?>

<table
    class="table table-bordered table-sm wt-table-note datatables d-none"
    <?= view('lists/datatables-attributes') ?>
    data-columns="<?= e(json_encode([
        ['type' => 'html'],
        ['visible' => array_sum($count_individuals) > 0],
        ['visible' => array_sum($count_families) > 0],
        ['visible' => array_sum($count_media) > 0],
        ['visible' => array_sum($count_sources) > 0],
        ['visible' => (bool) $tree->getPreference('SHOW_LAST_CHANGE'), 'searchable' => false],
    ], JSON_THROW_ON_ERROR)) ?>"
>
    <caption class="visually-hidden">
        <?= $caption ?? I18N::translate('Sources') ?>
    </caption>

    <thead>
        <tr>
            <th><?= I18N::translate('Title') ?></th>
            <th><?= I18N::translate('Individuals') ?></th>
            <th><?= I18N::translate('Families') ?></th>
            <th><?= I18N::translate('Media objects') ?></th>
            <th><?= I18N::translate('Sources') ?></th>
            <th><?= I18N::translate('Last change') ?></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($notes as $note) : ?>
            <tr class="<?= $note->isPendingAddition() ? 'wt-new' : '' ?> <?= $note->isPendingDeletion() ? 'wt-old' : '' ?>">
                <!-- Title -->
                <td data-sort="<?= e($note->sortName()) ?>">
                    <a href="<?= e($note->url()) ?>">
                        <?= $note->fullName() ?>
                    </a>
                </td>

                <!-- Count of linked individuals -->
                <td class="text-center" data-sort="<?= $count_individuals[$note->xref()] ?? 0 ?>">
                    <?= I18N::number($count_individuals[$note->xref()] ?? 0) ?>
                </td>

                <!-- Count of linked families -->
                <td class="text-center" data-sort="<?= $count_families[$note->xref()] ?? 0 ?>">
                    <?= I18N::number($count_families[$note->xref()] ?? 0) ?>
                </td>

                <!-- Count of linked media objects -->
                <td class="text-center" data-sort="<?= $count_media[$note->xref()] ?? 0 ?>">
                    <?= I18N::number($count_media[$note->xref()] ?? 0) ?>
                </td>

                <!-- Count of sources -->
                <td class="text-center" data-sort="<?= $count_sources[$note->xref()] ?? 0 ?>">
                    <?= I18N::number($count_sources[$note->xref()] ?? 0) ?>
                </td>

                <!-- Last change -->
                <td data-sort="<?= sprintf('x%07d', $note->lastChangeTimestamp()->timestamp()) ?>">
                    <?= view('components/datetime', ['timestamp' => $note->lastChangeTimestamp()]) ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
