<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Submitter;
use Fisharebest\Webtrees\Tree;
use Illuminate\Database\Capsule\Manager as DB;
use Illuminate\Database\Query\Expression;
use Illuminate\Database\Query\JoinClause;
use Illuminate\Support\Collection;

/**
 * @var Collection<Submitter> $submitters
 * @var Tree                  $tree
 */

?>

<?php
// Count the number of linked records. These numbers include private records.
// It is not good to bypass privacy, but many servers do not have the resources
// to process privacy for every record in the tree
// Count the number of linked records. These numbers include private records.
// It is not good to bypass privacy, but many servers do not have the resources
// to process privacy for every record in the tree
$count_individuals = DB::table('individuals')
    ->join('link', static function (JoinClause $join): void {
        $join->on('l_from', '=', 'i_id');
        $join->on('l_file', '=', 'i_file');
    })
    ->where('l_type', '=', Submitter::RECORD_TYPE)
    ->where('l_file', '=', $tree->id())
    ->groupBy(['l_to'])
    ->select(['l_to', new Expression('COUNT(*) AS total')])
    ->pluck('total', 'l_to')
    ->all();

$count_families = DB::table('families')
    ->join('link', static function (JoinClause $join): void {
        $join->on('l_from', '=', 'f_id');
        $join->on('l_file', '=', 'f_file');
    })
    ->where('l_type', '=', Submitter::RECORD_TYPE)
    ->where('l_file', '=', $tree->id())
    ->groupBy(['l_to'])
    ->select(['l_to', new Expression('COUNT(*) AS total')])
    ->pluck('total', 'l_to')
    ->all();
?>

<table
    class="table table-bordered table-sm wt-table-submitter datatables d-none"
    <?= view('lists/datatables-attributes') ?>
    data-columns="<?= e(json_encode([
        ['type' => 'html'],
        ['visible' => array_sum($count_individuals) > 0],
        ['visible' => array_sum($count_families) > 0],
        ['visible' => (bool) $tree->getPreference('SHOW_LAST_CHANGE'), 'searchable' => false],
    ])) ?>"
    data-searchable="true"
>
    <caption class="sr-only">
        <?= $caption ?? I18N::translate('Submitters') ?>
    </caption>

    <thead>
        <tr>
            <th><?= I18N::translate('Submitter name') ?></th>
            <th><?= I18N::translate('Individuals') ?></th>
            <th><?= I18N::translate('Families') ?></th>
            <th><?= I18N::translate('Last change') ?></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($submitters as $submitter) : ?>
            <tr class="<?= $submitter->isPendingAddition() ? 'wt-new' : '' ?> <?= $submitter->isPendingDeletion() ? 'wt-old' : '' ?>">
                <td data-sort="<?= e($submitter->sortName()) ?>">
                    <a href="<?= e($submitter->url()) ?>">
                        <?= $submitter->fullName() ?>
                    </a>
                </td>

                <td class="text-center" data-sort="<?= $count_individuals[$submitter->xref()] ?? 0 ?>">
                    <?= I18N::number($count_individuals[$submitter->xref()] ?? 0) ?>
                </td>

                <td class="text-center" data-sort="<?= $count_families[$submitter->xref()] ?? 0 ?>">
                    <?= I18N::number($count_families[$submitter->xref()] ?? 0) ?>
                </td>

                <td data-sort="<?= $submitter->lastChangeTimestamp()->unix() ?>">
                    <?= view('components/datetime', ['timestamp' => $submitter->lastChangeTimestamp()]) ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
