<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Module\IndividualListModule;
use Fisharebest\Webtrees\Tree;

/**
 * @var bool                               $families
 * @var IndividualListModule|null          $module
 * @var array<array<mixed>>|null           $order
 * @var array<string,array<string,string>> $surnames
 * @var Tree                               $tree
 */

?>

<table
    class="table table-bordered table-sm wt-table-surname datatables d-none"
    <?= view('lists/datatables-attributes') ?>
    data-info="false"
    data-paging="false"
    data-searching="false"
    data-order="<?= e(json_encode($order ?? [[1, 'desc']])) ?>"
>
    <caption class="visually-hidden">
        <?= I18N::translate('Surnames') ?>
    </caption>
    <thead>
        <tr>
            <th>
                <?= I18N::translate('Surname') ?>
            </th>
            <th>
                <?php if ($families) :?>
                    <?= I18N::translate('Spouses') ?>
                <?php else : ?>
                    <?= I18N::translate('Individuals') ?>
                <?php endif ?>
            </th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($surnames as $surn => $surns) : ?>
            <tr>
                <td data-sort="<?= e($surn) ?>">
                    <!-- Multiple surname variants, e.g. von Groot, van Groot, van der Groot, etc. -->
                    <?php foreach ($surns as $spfxsurn => $indis) : ?>
                        <?php if ($module instanceof IndividualListModule) : ?>
                            <?php if ($spfxsurn) : ?>
                                <?php if ($surn !== '') : ?>
                                    <a href="<?= $module->listUrl($tree, ['surname' => $surn]) ?>" dir="auto">
                                        <?= e($spfxsurn) ?>
                                    </a>
                                <?php else : ?>
                                    <a href="<?= $module->listUrl($tree, ['alpha' => ',']) ?>" dir="auto">
                                        <?= e($spfxsurn) ?>
                                    </a>
                                <?php endif ?>
                            <?php else : ?>
                                <!-- No surname, but a value from "2 SURN"? A common workaround for toponyms, etc. -->
                                <a href="<?= $module->listUrl($tree, ['surname' => $surn]) ?>" dir="auto"><?= e($surn) ?></a>
                            <?php endif ?>
                        <?php else : ?>
                            <?php if ($spfxsurn) : ?>
                                <bdi><?= e($spfxsurn) ?></bdi>
                            <?php else : ?>
                                <!-- No surname, but a value from "2 SURN"? A common workaround for toponyms, etc. -->
                                <bdi><?= e($surn) ?></bdi>
                            <?php endif ?>    
                        <?php endif ?>
                        <br>
                    <?php endforeach ?>
                </td>

                <td class="text-center" data-sort="<?= array_sum($surns) ?>">
                    <?php foreach ($surns as $indis) : ?>
                        <?= I18N::number($indis) ?>
                        <br>
                    <?php endforeach ?>

                    <?php if (count($surns) > 1) : ?>
                        <?= I18N::number(array_sum($surns)) ?>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
