<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Submitter;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var Collection<int,Submitter> $submitters
 * @var string                    $title
 * @var Tree                      $tree
 */

?>
<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<div class="wt-page-content">
    <?= view('lists/submitters-table', ['submitters' => $submitters, 'tree' => $tree]) ?>
</div>
