<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;

/**
 * @var Individual $individual
 * @var string     $module
 * @var Tree       $tree
 */

?>

<div class="wt-chart wt-chart-interactive">
    <div class="tv_out" data-wt-interactive-tree data-wt-interactive-tree-details-url="<?= e(route('module', ['module' => $module, 'action' => 'Details', 'tree' => $tree->name()])) ?>" data-wt-interactive-tree-individuals-url="<?= e(route('module', ['module' => $module, 'action' => 'Individuals', 'tree' => $tree->name()])) ?>">
        <div class="tv_tools" data-wt-interactive-tree-tools>
            <ul>
                <li class="tv_button tvbCompact" title="<?= I18N::translate('Use compact layout') ?>" data-wt-interactive-tree-compact>
                </li>
                <li class="tv_button">
                    <a href="#" data-wt-fullscreen=".wt-chart-interactive">
                        <span title="<?= I18N::translate('Enter fullscreen') ?>"><?= view('icons/enter-fullscreen') ?></span>
                        <span title="<?= I18N::translate('Exit fullscreen') ?>"><?= view('icons/exit-fullscreen') ?></span>
                    </a>
                </li>
                <li class="tv_button" data-wt-interactive-tree-loading>
                    <i class="icon-loading-small"></i>
                </li>
            </ul>
        </div>
        <div class="tv_in" data-wt-interactive-tree-canvas dir="ltr">
            <?= $individual ?>
        </div>
    </div>
</div>
