<?php

use Fisharebest\Webtrees\I18N;

?>

<div id="<?= $name ?>_out" class="tv_out" data-url-details="<?= e(route('module', ['module' => $module, 'action' => 'Details', 'tree' => $tree->name(), 'dummy' => 'dummy'])) ?>" data-url-individuals="<?= e(route('module', ['module' => $module, 'action' => 'Individuals', 'tree' => $tree->name(), 'dummy' => 'dummy'])) ?>">
    <div id="tv_tools">
        <ul>
            <li id="tvbCompact" class="tv_button" title="<?= I18N::translate('Use compact layout') ?>">
            </li>
            <li class="tv_button" id="<?= $name ?>_loading">
                <i class="icon-loading-small"></i>
            </li>
        </ul>
    </div>
    <div id="<?= $name ?>_in" class="tv_in" dir="ltr">
        <?= $individual ?>
    </div>
</div>
