<?php

declare(strict_types=1);

use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\I18N;

/** @var GedcomRecord $record */

?>
<div class="input-group mb-3">
    <span class="input-group-text"><?= I18N::translate('URL') ?></span>

    <input type="text" class="form-control" aria-label="" value="<?= e($record->url()) ?>" readonly="readonly" id="share-url-input">

    <button
        class="btn btn-primary"
        type="button"
        id="share-url-button"
        data-wt-copy-button
        data-wt-copy-target="#share-url-input"
        data-wt-copy-message="<?= e(I18N::translate('The URL was copied to the clipboard')) ?>"
    >
        <?= view('icons/copy') ?>
        <?= I18N::translate('Copy') ?>
    </button>
</div>

