<?php use Fisharebest\Webtrees\GedcomTag; ?>
<?php use Fisharebest\Webtrees\I18N; ?>

<tr>
    <th scope="row">
        <label for="add-fact">
            <?= I18N::translate('Fact or event') ?>
        </label>
    </th>
    <td>
        <form method="get" action="<?= e(route('add-fact')) ?>" onsubmit="if ($('#add-fact').val() === null) {event.preventDefault();}">
            <input type="hidden" name="route" value="add-fact">
            <input type="hidden" name="xref" value="<?= e($record->xref()) ?>">
            <input type="hidden" name="ged" value="<?= e($record->tree()->name()) ?>">
            <div class="input-group">
                <select class="custom-select" id="add-fact" name="fact">
                    <option value="" disabled selected>
                        <?= I18N::translate('&lt;select&gt;') ?>
                    </option>
                    <?php foreach ($add_facts as $fact => $fact_name) : ?>
                        <option value="<?= $fact ?>"><?= $fact_name ?></option>
                    <?php endforeach ?>
                    <?php if ($record::RECORD_TYPE === 'INDI' || $record::RECORD_TYPE === 'FAM') : ?>
                        <option value="FACT">
                        <?= I18N::translate('Custom fact') ?>
                        </option>
                    <option value="EVEN">
                        <?= I18N::translate('Custom event') ?>
                    </option>
                    <?php endif ?>
                </select>
                <div class="input-group-append">
                    <button class="btn btn-light" type="submit">
                        <?= /* I18N: A button label. */ I18N::translate('add') ?>
                    </button>
                </div>
            </div>
        </form>

        <div class="wt-quick-facts">
            <?php foreach ($quick_facts as $fact) : ?>
                <a class="btn btn-link btn-sm wt-quick-fact" href="<?= e(route('add-fact', [
                    'fact' => $fact,
                    'xref' => $record->xref(),
                    'ged'  => $tree->name(),
                ])) ?>">
                    <?= GedcomTag::getLabel($fact) ?>
                </a>
            <?php endforeach ?>
        </div>
    </td>
</tr>
