<?php

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\GedcomTag;
use Fisharebest\Webtrees\Http\RequestHandlers\AddNewFact;
use Fisharebest\Webtrees\Http\RequestHandlers\SelectNewFact;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;

?>

<tr>
    <th scope="row">
        <label for="add-fact">
            <?= I18N::translate('Fact or event') ?>
        </label>
    </th>
    <td>
        <form method="post" action="<?= e(route(SelectNewFact::class, ['tree' => $record->tree()->name(), 'xref' => $record->xref()])) ?>" onsubmit="if ($('#add-fact').val() === null) {event.preventDefault();}">
            <?= csrf_field() ?>

            <div class="input-group">
                <select class="custom-select" id="add-fact" name="fact">
                    <option value="" disabled selected>
                        <?= I18N::translate('&lt;select&gt;') ?>
                    </option>
                    <?php foreach ($add_facts as $fact => $fact_name) : ?>
                        <option value="<?= $fact ?>"><?= $fact_name ?></option>
                    <?php endforeach ?>
                    <?php if ($record::RECORD_TYPE === Individual::RECORD_TYPE || $record::RECORD_TYPE === Family::RECORD_TYPE) : ?>
                        <option value="FACT">
                        <?= I18N::translate('Custom fact') ?>
                        </option>
                    <option value="EVEN">
                        <?= I18N::translate('Custom event') ?>
                    </option>
                    <?php endif ?>
                </select>
                <div class="input-group-append">
                    <button class="btn btn-light" type="submit">
                        <?= /* I18N: A button label. */ I18N::translate('add') ?>
                    </button>
                </div>
            </div>
        </form>

        <div class="wt-quick-facts">
            <?php foreach ($quick_facts as $fact) : ?>
                <a class="btn btn-link btn-sm wt-quick-fact" href="<?= e(route(AddNewFact::class, [
                    'fact' => $fact,
                    'xref' => $record->xref(),
                    'tree' => $tree->name(),
                ])) ?>">
                    <?= GedcomTag::getLabel($fact) ?>
                </a>
            <?php endforeach ?>
        </div>
    </td>
</tr>
