<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Enums\Sex;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Http\Controllers\ChangeFamilyMembers;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var Family $family
 * @var string $title
 * @var Tree   $tree
 */

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" action="<?= e(route(ChangeFamilyMembers::class, ['tree' => $tree->name()])) ?>" class="wt-page-content" name="changefamform">
    <input type="hidden" name="tree" value="<?= e($tree->name()) ?>">
    <input type="hidden" name="xref" value="<?= e($family->xref()) ?>">

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="HUSB">
            <?= match($family->husband()?->sex()) {
                Sex::Male => I18N::translate('Husband'),
                Sex::Female => I18N::translate('Wife'),
                default => I18N::translate('Spouse'),
            } ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select-individual', ['name' => 'HUSB', 'individual' => $family->husband(), 'tree' => $tree]) ?>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="WIFE">
            <?= match($family->wife()?->sex()) {
                Sex::Male => I18N::translate('Husband'),
                Sex::Female => I18N::translate('Wife'),
                default => I18N::translate('Spouse'),
            } ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select-individual', ['name' => 'WIFE', 'individual' => $family->wife(), 'tree' => $tree]) ?>
        </div>
    </div>

    <?php foreach ($family->children() as $n => $child) : ?>
        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="CHIL<?= $n ?>">
                <?= match($child->sex()) {
                    Sex::Male => I18N::translate('Son'),
                    Sex::Female => I18N::translate('Daughter'),
                    default => I18N::translate('Child'),
                } ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?= view('components/select-individual', ['name' => 'CHIL[]', 'id' => 'CHIL' . $n, 'individual' => $child, 'tree' => $tree]) ?>
            </div>
        </div>
    <?php endforeach ?>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="CHIL<?= count($family->children()) + 1 ?>">
            <?= I18N::translate('Child') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select-individual', ['name' => 'CHIL[]', 'id' => 'CHIL' . (count($family->children()) + 1), 'tree' => $tree]) ?>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-sm-3 wt-page-options-label">
        </div>
        <div class="col-sm-9 wt-page-options-value">
            <button class="btn btn-primary" type="submit">
                <?= view('icons/save') ?>
                <?= /* I18N: A button label. */
                I18N::translate('save') ?>
            </button>
            <a class="btn btn-secondary" href="<?= e($family->url()) ?>">
                <?= view('icons/cancel') ?>
                <?= /* I18N: A button label. */
                I18N::translate('cancel') ?>
            </a>
        </div>
    </div>

    <?= csrf_field() ?>
</form>
