<?php use Fisharebest\Webtrees\I18N; ?>

<a class="btn btn-link btn-sm" href="#" data-confirm="<?= I18N::translate('Are you sure you want to delete this fact?') ?>" onclick="return delete_fact(this.dataset.confirm, '<?= e($fact->record()->tree()->name()) ?>', '<?= e($fact->record()->xref()) ?>', '<?= e($fact->id()) ?>');" title="<?= I18N::translate('Delete') ?>">
    <?= view('icons/delete') ?>
    <span class="sr-only"><?= I18N::translate('Delete') ?></span>
</a>
