<?php

use Fisharebest\Webtrees\Http\RequestHandlers\EditFact;
use Fisharebest\Webtrees\I18N;

?>

<a class="btn btn-link btn-sm" href="<?= e(route(EditFact::class, ['xref' => $fact->record()->xref(), 'fact_id' => $fact->id(), 'tree' => $fact->record()->tree()->name()])) ?>" title="<?= I18N::translate('Edit') ?>">
    <?= view('icons/edit') ?>
    <span class="sr-only"><?= I18N::translate('Edit') ?></span>
</a>
