<?php

use Fisharebest\Webtrees\I18N;

?>
<?php use Fisharebest\Webtrees\View; ?>

<?php View::push('javascript') ?>
<script>
  webtrees.calLocalize(
        <?= json_encode(I18N::translateContext('NOMINATIVE', 'January'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translateContext('NOMINATIVE', 'February'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translateContext('NOMINATIVE', 'March'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translateContext('NOMINATIVE', 'April'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translateContext('NOMINATIVE', 'May'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translateContext('NOMINATIVE', 'June'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translateContext('NOMINATIVE', 'July'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translateContext('NOMINATIVE', 'August'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translateContext('NOMINATIVE', 'September'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translateContext('NOMINATIVE', 'October'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translateContext('NOMINATIVE', 'November'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translateContext('NOMINATIVE', 'December'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translate('Sun'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translate('Mon'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translate('Tue'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translate('Wed'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translate('Thu'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translate('Fri'), JSON_THROW_ON_ERROR) ?>,
        <?= json_encode(I18N::translate('Sat'), JSON_THROW_ON_ERROR) ?>,
        <?= I18N::locale()->territory()->firstDay() ?>
  );
</script>
<?php View::endpush() ?>
