<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var string $id
 */

?>

<span class="input-group-text">
    <a
        href="#"
        title="<?= I18N::translate('Select a date') ?>"
        data-wt-calendar-widget-button
        data-wt-calendar-div-id="caldiv<?= e($id) ?>"
        data-wt-calendar-input-id="<?= e($id) ?>"
    >
        <?= view('icons/calendar') ?>
        <span class="visually-hidden">
            <?= I18N::translate('Select a date') ?>
        </span>
    </a>
</span>
