<?php

use Fisharebest\Webtrees\I18N;

/**
 * @var string $id
 */

?>

<span class="input-group-text">
    <a data-bs-toggle="collapse" data-bs-target=".child_of_<?= e($id) ?>" href="#" title="<?= I18N::translate('Latitude') . ' / ' . I18N::translate('Longitude') ?>">
        <?= view('icons/coordinates') ?>
        <span class="visually-hidden">
            <?= I18N::translate('Latitude') . ' / ' . I18N::translate('Longitude') ?>
        </span>
    </a>
</span>
