<?php

use Fisharebest\Webtrees\I18N;

/**
 * @var string $id
 */

?>

<div class="input-group-append">
    <span class="input-group-text">
        <a class="wt-osk-trigger" data-id="<?= e($id) ?>" href="#" title="<?= I18N::translate('Find a special character') ?>">
            <?= view('icons/keyboard') ?>
            <span class="sr-only">
                <?= I18N::translate('Find a special character') ?>
            </span>
        </a>
    </span>
</div>
