<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var string $id
 */

?>

<span class="input-group-text">
    <a
        id="<?= e($id) ?>-edit"
        href="#"
        title="<?= I18N::translate('Edit the name') ?>"
        data-wt-edit-name-addon=""
        data-wt-name-input-id="<?= e($id) ?>"
    >
        <?= view('icons/edit') ?>
        <span class="visually-hidden">
            <?= I18N::translate('Edit the name') ?>
        </span>
    </a>
</span>

