<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var string $id
 */

?>

<span class="input-group-text">
    <a href="#" onclick="return webtrees.calendarWidget('caldiv<?= e($id) ?>', '<?= e($id) ?>');" title="<?= I18N::translate('Select a date') ?>">
        <?= view('icons/calendar') ?>
        <span class="visually-hidden">
            <?= I18N::translate('Select a date') ?>
        </span>
    </a>
</span>
