<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var array<string> $languages - Currently selected languages
 */

?>
<div style="columns: auto 12rem">
    <?php foreach (I18N::activeLanguages() as $language_tag => $endonym) : ?>
        <div class="form-check">
            <label title="<?= $language_tag ?>">
                <input type="checkbox" name="languages[]" value="<?= $language_tag ?>" <?= in_array($language_tag, $languages, true) ? 'checked' : '' ?>>
                <?= $endonym ?>
            </label>
        </div>
    <?php endforeach ?>
</div>
