<?php

use Fisharebest\Webtrees\Functions\FunctionsEdit;

?>
<?php use Fisharebest\Webtrees\I18N; ?>

<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" action="<?= e(route('link-spouse-to-individual-action', ['tree' => $tree->name(), 'xref' => $xref])) ?>" class="wt-page-content">
    <?= csrf_field() ?>

    <div class="form-group row">
        <label class="col-sm-3 col-form-label" for="spouse">
            <?= $label ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/select-individual', ['name' => 'spid', 'id' => 'spouse', 'tree' => $tree]) ?>
        </div>
    </div>

    <?= FunctionsEdit::addSimpleTag($tree, '0 MARR Y') ?>
    <?= FunctionsEdit::addSimpleTag($tree, '0 DATE', 'MARR') ?>
    <?= FunctionsEdit::addSimpleTag($tree, '0 PLAC', 'MARR') ?>

    <div class="row form-group">
        <div class="col-sm-9 offset-sm-3">
            <button class="btn btn-primary" type="submit">
                <?= view('icons/save') ?>
                <?= /* I18N: A button label. */
                I18N::translate('save') ?>
            </button>
            <a class="btn btn-secondary" href="<?= e($individual->url()) ?>">
                <?= view('icons/cancel') ?>
                <?= /* I18N: A button label. */
                I18N::translate('cancel') ?>
            </a>
        </div>
    </div>
</form>
