<?php use Fisharebest\Webtrees\I18N; ?>

<?php if (!empty($facts)) : ?>
<tr>
    <th scope="row">
        <label for="paste-fact">
            <?= I18N::translate('Add from clipboard') ?>
        </label>
    </th>
    <td>
        <form name="newFromClipboard" onsubmit="return false;">
            <div class="input-group">
                <select class="custom-select" id="paste-fact">
                    <?php foreach ($facts as $fact) : ?>
                    <option value="<?= e($fact->id()) ?>">
                        <?= $fact->label() ?>
                        <?php if ($fact->value() !== '') : ?>
                            – <?= e($fact->value()) ?>
                        <?php endif ?>
                        <?php if ($fact->date()->isOK()) : ?>
                            – <?= $fact->date()->minimumDate()->format('%Y') ?>
                        <?php endif ?>
                        <?php if (!$fact->place()->gedcomName() !== '') : ?>
                            – <?= $fact->place()->shortName() ?>
                        <?php endif ?>
                    </option>
                    <?php endforeach ?>
                </select>
                <div class="input-group-append">
                    <button class="btn btn-light" type="submit" onclick="return paste_fact('<?= e($tree->name()) ?>', '<?= e($record->xref()) ?>', '#paste-fact');">
                        <?= /* I18N: A button label. */ I18N::translate('add') ?>
                    </button>
                </div>
            </div>
        </form>
    </td>
</tr>
<?php endif ?>
