<?php

use Fisharebest\Webtrees\Http\RequestHandlers\PasteFact;
use Fisharebest\Webtrees\I18N;

?>

<?php if ($facts->isNotEmpty()) : ?>
<tr>
    <th scope="row">
        <label for="paste-fact">
            <?= I18N::translate('Add from clipboard') ?>
        </label>
    </th>
    <td>
        <form method="post" action="<?= route(PasteFact::class, ['tree' => $record->tree()->name(), 'xref' => $record->xref()]) ?>">
            <?= csrf_field() ?>

            <div class="input-group">
                <select class="custom-select" id="paste-fact" name="fact_id">
                    <?php foreach ($facts as $fact) : ?>
                    <option value="<?= e($fact->id()) ?>">
                        <?= $fact->label() ?>
                        <?php if ($fact->target() !== null) : ?>
                            – <?= strip_tags($fact->target()->fullName()) ?>
                        <?php elseif ($fact->value() !== '') : ?>
                            – <?= e($fact->value()) ?>
                        <?php endif ?>
                        <?php if ($fact->date()->isOK()) : ?>
                            – <?= $fact->date()->minimumDate()->format('%Y') ?>
                        <?php endif ?>
                        <?php if ($fact->place()->gedcomName() !== '') : ?>
                            – <?= $fact->place()->shortName() ?>
                        <?php endif ?>
                    </option>
                    <?php endforeach ?>
                </select>
                <div class="input-group-append">
                    <button class="btn btn-light" type="submit">
                        <?= /* I18N: A button label. */ I18N::translate('add') ?>
                    </button>
                </div>
            </div>
        </form>
    </td>
</tr>
<?php endif ?>
