<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ReorderMediaAction;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\View;

/**
 * @var Individual $individual
 * @var string     $title
 */

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" action="<?= e(route(ReorderMediaAction::class, ['tree' => $individual->tree()->name(), 'xref' => $individual->xref()])) ?>" class="wt-page-content">
    <div class="wt-sortable-list">
        <?php foreach ($individual->facts(['OBJE']) as $fact) : ?>
            <?php $media = $fact->target(); ?>
            <div class="card my-2 wt-sortable-item">
                <input type="hidden" name="order[]" value="<?= $fact->id() ?>">
                <div class="card-header">
                    <?= view('edit/reorder-card-header', ['title' => $media?->fullName() ?? '']) ?>
                </div>

                <div class="card-body">
                    <?= $media instanceof Media ? $media->displayImage(100, 100, 'contain', []) : '<div class="alert alert-danger">' . I18N::translate('%s does not exist.', e($fact->value())) . '</div>' ?>
                </div>
            </div>
        <?php endforeach ?>
    </div>

    <p>
        <button class="btn btn-primary" type="submit">
            <?= view('icons/save') ?>
            <?= /* I18N: A button label. */ I18N::translate('save') ?>
        </button>

        <a class="btn btn-secondary" href="<?= e($individual->url()) ?>">
            <?= view('icons/cancel') ?>
            <?= /* I18N: A button label. */ I18N::translate('cancel') ?>
        </a>
    </p>

    <?= csrf_field() ?>
</form>

<?php View::push('javascript') ?>
<script>
    new Sortable(document.querySelector(".wt-sortable-list"), {
        handle: ".card-header",
    });
</script>
<?php View::endpush() ?>
