<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Gedcom;
use Fisharebest\Webtrees\Http\RequestHandlers\ReorderFamiliesAction;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var Collection<int,Fact> $famc_facts
 * @var Collection<int,Fact> $fams_facts
 * @var Individual           $individual
 * @var string               $title
 * @var Tree                 $tree
 */

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" action="<?= e(route(ReorderFamiliesAction::class, ['tree' => $tree->name(), 'xref' => $individual->xref()])) ?>" class="wt-page-content">
    <?php if ($fams_facts->count() < 2) : ?>
        <?php foreach ($fams_facts as $fact) : ?>
            <input type="hidden" name="order[]" value="<?= e($fact->id()) ?>">
        <?php endforeach ?>
    <?php else : ?>
        <h3><?= I18N::translate('Spouses') ?></h3>

        <p>
            <?= I18N::translate('When an individual has more than one spouse, you should sort the families in date order.') ?>
        </p>

        <p>
            <button class="btn btn-secondary" type="button" data-wt-sort-by-date-button data-wt-sort-list=".wt-sortable-list-fams" data-wt-sort-key="wtSortByDate">
                <?= view('icons/sort') ?>
                <?= /* I18N: A button label. */ I18N::translate('sort by date of marriage') ?>
            </button>
        </p>

        <div class="wt-sortable-list wt-sortable-list-fams" data-wt-sortable-list>
            <?php foreach ($fams_facts as $fact) : ?>
                <?php $family = $fact->target(); ?>
                <?php if ($family instanceof Family) : ?>
                    <div class="card mb-2 wt-sortable-item" data-wt-sort-by-date="<?= $family->getMarriageDate()->julianDay() ?>">
                        <input type="hidden" name="order[]" value="<?= $fact->id() ?>">
                        <div class="card-header">
                            <?= view('edit/reorder-card-header', ['title' => $family->fullName()]) ?>
                        </div>

                        <div class="card-body">
                            <?= $family->formatFirstMajorFact(Gedcom::MARRIAGE_EVENTS, 2) ?>
                            <?= $family->formatFirstMajorFact(Gedcom::DIVORCE_EVENTS, 2) ?>
                        </div>
                    </div>
                <?php endif ?>
            <?php endforeach ?>
        </div>
    <?php endif ?>

    <?php if ($famc_facts->count() < 2) : ?>
            <?php foreach ($famc_facts as $fact) : ?>
                <input type="hidden" name="order[]" value="<?= e($fact->id()) ?>">
            <?php endforeach ?>
    <?php else : ?>
        <?php if ($fams_facts->count() >= 2) : ?>
        <hr>
        <?php endif ?>

        <h3><?= I18N::translate('Parents') ?></h3>

        <p>
            <?= I18N::translate('An individual can have more than one set of parents. For example, birth and adopted.') ?>
            <br>
            <?= I18N::translate('The first family in the list will be used in charts, lists, reports, etc.') ?>
        </p>

        <div class="wt-sortable-list wt-sortable-list-famc" data-wt-sortable-list>
            <?php foreach ($famc_facts as $fact) : ?>
                <?php $family = $fact->target(); ?>
                <?php if ($family instanceof Family) : ?>
                    <div class="card my-2 wt-sortable-item" data-sortbydate="<?= $family->getMarriageDate()->julianDay() ?>">
                        <input type="hidden" name="order[]" value="<?= $fact->id() ?>">
                        <div class="card-header">
                            <?= view('edit/reorder-card-header', ['title' => $family->fullName() . ($fact->attribute('PEDI') === '' ? '' : ' — ' . Registry::elementFactory()->make('INDI:FAMC:PEDI')->value($fact->attribute('PEDI'), $tree))]) ?>
                        </div>
                        <div class="card-body">
                            <?= $family->formatFirstMajorFact(Gedcom::MARRIAGE_EVENTS, 2) ?>
                            <?= $family->formatFirstMajorFact(Gedcom::DIVORCE_EVENTS, 2) ?>
                        </div>
                    </div>
                <?php endif ?>
            <?php endforeach ?>
        </div>
    <?php endif ?>

    <p>
        <button class="btn btn-primary" type="submit">
            <?= view('icons/save') ?>
            <?= /* I18N: A button label. */ I18N::translate('save') ?>
        </button>

        <a class="btn btn-secondary" href="<?= e($individual->url()) ?>">
            <?= view('icons/cancel') ?>
            <?= /* I18N: A button label. */ I18N::translate('cancel') ?>
        </a>
    </p>

    <?= csrf_field() ?>
</form>


