<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var string $title
 */

?>
<div class="d-flex">
    <button class="btn btn-outline-secondary btn-sm drag-handle">
        <?= view('icons/drag-handle') ?>
    </button>

    <div class="ms-2 me-auto">
        <?= $title ?>
    </div>

    <div class="btn-group">
        <button class="btn btn-outline-secondary btn-sm wt-btn-reorder wt-btn-reorder-first" type="button">
            <?= I18N::translate('first') ?>
        </button>

        <button class="btn btn-outline-secondary btn-sm wt-btn-reorder wt-btn-reorder-previous" type="button">
            <?= I18N::translate('up') ?>
        </button>

        <button class="btn btn-outline-secondary btn-sm wt-btn-reorder wt-btn-reorder-next" type="button">
            <?= I18N::translate('down') ?>
        </button>

        <button class="btn btn-outline-secondary btn-sm wt-btn-reorder wt-btn-reorder-last" type="button">
            <?= I18N::translate('last') ?>
        </button>
    </div>
</div>


