<?php use Fisharebest\Webtrees\Gedcom; ?>
<?php use Fisharebest\Webtrees\I18N; ?>
<?php use Fisharebest\Webtrees\View; ?>

<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" action="<?= e(route('reorder-spouses-action', ['tree' => $tree->name()])) ?>" class="wt-page-content">
    <?= csrf_field() ?>
    <input type="hidden" name="tree" value="<?= e($individual->tree()->name()) ?>">
    <input type="hidden" name="xref" value="<?= e($individual->xref()) ?>">

    <div class="wt-sortable-list">
        <?php foreach ($individual->facts(['FAMS']) as $fact) : ?>
            <div class="card mb-2 wt-sortable-item" data-sortbydate="<?= $fact->target()->getMarriageDate()->julianDay() ?>">
                <input type="hidden" name="order[]" value="<?= $fact->id() ?>">
                <h3 class="card-header">
                    <?= view('icons/drag-handle') ?>
                    <?= $fact->target()->fullName() ?>
                </h3>
                <div class="card-body">
                    <?= $fact->target()->formatFirstMajorFact(Gedcom::MARRIAGE_EVENTS, 2) ?>
                    <?= $fact->target()->formatFirstMajorFact(Gedcom::DIVORCE_EVENTS, 2) ?>
                </div>
            </div>
        <?php endforeach ?>
    </div>

    <p>
        <button class="btn btn-primary" type="submit">
            <?= view('icons/save') ?>
            <?= /* I18N: A button label. */ I18N::translate('save') ?>
        </button>

        <button class="btn btn-secondary" id="btn-default-order" type="button">
            <?= view('icons/sort') ?>
            <?= /* I18N: A button label. */ I18N::translate('sort by date of marriage') ?>
        </button>

        <a class="btn btn-secondary" href="<?= e($individual->url()) ?>">
            <?= view('icons/cancel') ?>
            <?= /* I18N: A button label. */ I18N::translate('cancel') ?>
        </a>
    </p>
</form>

<?php View::push('javascript') ?>
<script>
  new Sortable(document.querySelector(".wt-sortable-list"), {});

  $("#btn-default-order").on("click", function() {
    $(".wt-sortable-list .wt-sortable-item").sort(function(x, y) {
      return Math.sign(x.dataset.sortbydate - y.dataset.sortbydate);
    }).appendTo(".wt-sortable-list");
  });
</script>
<?php View::endpush() ?>
