<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Gedcom;
use Fisharebest\Webtrees\Http\RequestHandlers\ReorderChildrenAction;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;

/**
 * @var Family $family
 * @var string $title
 * @var string $url
 */

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" action="<?= e(route(ReorderChildrenAction::class, ['tree' => $family->tree()->name(), 'xref' => $family->xref()])) ?>" class="wt-page-content">
    <input type="hidden" name="url" value="<?= e($url) ?>">
    <div class="wt-sortable-list" data-wt-sortable-list>
        <?php foreach ($family->facts(['CHIL']) as $fact) : ?>
            <?php $child = $fact->target(); ?>
            <?php if ($child instanceof Individual) : ?>
                <div class="card my-2 wt-sortable-item" data-wt-sort-by-date="<?= $child->getBirthDate()->julianDay() ?>">
                    <input type="hidden" name="order[]" value="<?= $fact->id() ?>">
                    <div class="card-header">
                        <?= view('edit/reorder-card-header', ['title' => $child->fullName()]) ?>
                    </div>

                    <div class="card-body">
                        <?= $child->formatFirstMajorFact(Gedcom::BIRTH_EVENTS, 2) ?>
                        <?= $child->formatFirstMajorFact(Gedcom::DEATH_EVENTS, 2) ?>
                    </div>
                </div>
            <?php endif ?>
        <?php endforeach ?>
    </div>

    <p>
        <button class="btn btn-primary" type="submit">
            <?= view('icons/save') ?>
            <?= /* I18N: A button label. */ I18N::translate('save') ?>
        </button>

        <button class="btn btn-secondary" type="button" data-wt-sort-by-date-button data-wt-sort-list=".wt-sortable-list" data-wt-sort-key="wtSortByDate">
            <?= view('icons/sort') ?>
            <?= /* I18N: A button label. */ I18N::translate('sort by date of birth') ?>
        </button>

        <a class="btn btn-secondary" href="<?= e($url) ?>">
            <?= view('icons/cancel') ?>
            <?= /* I18N: A button label. */ I18N::translate('cancel') ?>
        </a>
    </p>

    <?= csrf_field() ?>
</form>


