<?php use Fisharebest\Webtrees\I18N; ?>
<?php use Fisharebest\Webtrees\View; ?>

<h2 class="wt-page-title"><?= $title ?></h2>

<form class="wt-page-content" method="post">
    <?= csrf_field() ?>
    <div class="wt-sortable-list">
        <?php foreach ($individual->facts(['OBJE']) as $fact) : ?>
            <div class="card mb-2 wt-sortable-item">
                <input type="hidden" name="order[]" value="<?= $fact->id() ?>">
                <h3 class="card-header">
                    <?= view('icons/drag-handle') ?>
                    <?= $fact->target()->fullName() ?>
                </h3>
                <div class="card-body">
                    <?= $fact->target()->displayImage(100, 100, 'contain') ?>
                </div>
            </div>
        <?php endforeach ?>
    </div>

    <p>
        <button class="btn btn-primary" type="submit">
            <?= view('icons/save') ?>
            <?= /* I18N: A button label. */ I18N::translate('save') ?>
        </button>

        <a class="btn btn-secondary" href="<?= e($individual->url()) ?>">
            <?= view('icons/cancel') ?>
            <?= /* I18N: A button label. */ I18N::translate('cancel') ?>
        </a>
    </p>
</form>

<?php View::push('javascript') ?>
<script>
  new Sortable(document.querySelector(".wt-sortable-list"), {});
</script>
<?php View::endpush() ?>
