<?php

use Fisharebest\Webtrees\I18N;

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" action="<?= e(route('edit-note-object-action', ['tree' => $tree->name(), 'xref' => $note->xref()])) ?>" class="wt-page-options">
    <?= csrf_field() ?>

    <div class="row form-group">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="NOTE">
            <?= I18N::translate('Shared note') ?>
        </label>

        <div class="col-sm-9 wt-page-options-value">
            <textarea class="form-control" name="NOTE" id="NOTE" rows="10" dir="auto"><?= e($note->getNote()) ?></textarea>

            <a class="wt-osk-trigger" data-id="NOTE" href="#" title="<?= I18N::translate('Find a special character') ?>">
                <?= view('icons/keyboard') ?>
                <span class="sr-only"><?= I18N::translate('Find a special character') ?></span>
            </a>
        </div>
    </div>

    <div class="row form-group">
        <div class="col-sm-9 offset-sm-3">
            <button class="btn btn-primary" type="submit">
                <?= view('icons/save') ?>
                <?= /* I18N: A button label. */
                I18N::translate('save') ?>
            </button>
            <a class="btn btn-secondary" href="<?= e($note->url()) ?>">
                <?= view('icons/cancel') ?>
                <?= /* I18N: A button label. */
                I18N::translate('cancel') ?>
            </a>
        </div>
    </div>
</form>
<?= view('modals/on-screen-keyboard') ?>
