<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Http\RequestHandlers\AddChildToIndividualPage;
use Fisharebest\Webtrees\Http\RequestHandlers\AddParentToIndividualPage;
use Fisharebest\Webtrees\Http\RequestHandlers\AddSpouseToIndividualPage;
use Fisharebest\Webtrees\Http\RequestHandlers\LinkChildToFamilyPage;
use Fisharebest\Webtrees\Http\RequestHandlers\LinkSpouseToIndividualPage;
use Fisharebest\Webtrees\Http\RequestHandlers\ReorderFamiliesPage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Illuminate\Support\Collection;

/**
 * @var bool                   $can_edit
 * @var int                    $fam_access_level
 * @var Individual             $individual
 * @var Collection<int,Family> $parent_families
 * @var Collection<int,Family> $spouse_families
 * @var Collection<int,Family> $step_child_families
 * @var Collection<int,Family> $step_parent_families
 */

?>
<?php
?>

<div class="container py-1">

    <div class="row wt-fact-content py-1 mb-2">
        <div class="col-sm-auto">
            <input id="show-date-differences" type="checkbox" class="form-check-input"
                data-bs-toggle="collapse"
                data-bs-target=".wt-date-difference"
                data-wt-persist="date-differences"
                autocomplete="off"
                <?= $parent_families ->isEmpty() &&
                    $spouse_families->isEmpty() &&
                    $step_child_families->isEmpty() &&
                    $step_parent_families->isEmpty() ?
                    'disabled="disabled"' : ''
                ?>
            >
            <label class="form-check-label" for="show-date-differences">
                <?= I18N::translate('Date differences') ?>
            </label>
        </div>
    </div>


<!-- Parents -->
<?php foreach ($parent_families as $family) : ?>
    <?= view('modules/relatives/family', [
        'individual'       => $individual,
        'family'           => $family,
        'type'             => 'FAMC',
        'label'            => $individual->getChildFamilyLabel($family),
        'fam_access_level' => $fam_access_level,
    ]) ?>
<?php endforeach ?>

<!-- step-parents -->
<?php foreach ($step_parent_families as $family) : ?>
    <?= view('modules/relatives/family', [
        'individual'       => $individual,
        'family'           => $family,
        'type'             => 'FAMC',
        'label'            => $individual->getStepFamilyLabel($family),
        'fam_access_level' => $fam_access_level,
    ]) ?>
<?php endforeach ?>

<!-- spouses -->
<?php foreach ($spouse_families as $family) : ?>
    <?= view('modules/relatives/family', [
        'individual'       => $individual,
        'family'           => $family,
        'type'             => 'FAMS',
        'label'            => $individual->getSpouseFamilyLabel($family),
        'fam_access_level' => $fam_access_level,
    ]) ?>
<?php endforeach ?>

<!-- step-children -->
<?php foreach ($step_child_families as $family) : ?>
    <?= view('modules/relatives/family', [
        'individual'       => $individual,
        'family'           => $family,
        'type'             => 'FAMS',
        'label'            => $family->fullName(),
        'fam_access_level' => $fam_access_level,
    ]) ?>
<?php endforeach ?>

<?php if ($can_edit) : ?>
            <?php if ($spouse_families->count() > 1) : ?>
                <div class="row mt-2">
                    <div class="col-sm-12 wt-fact-content py-1">
                        <a href="<?= e(route(ReorderFamiliesPage::class, ['tree' => $individual->tree()->name(), 'xref' => $individual->xref()])) ?>">
                            <?= view('icons/reorder') ?>
                            <?= I18N::translate('Re-order families') ?>
                        </a>
                    </div>
                </div>
            <?php endif ?>

            <?php if ($parent_families->isEmpty()) : ?>
                <div class="row mt-1">
                    <div class="col-sm-12 wt-fact-content py-1">
                        <a href="<?= e(route(AddParentToIndividualPage::class, ['tree' => $individual->tree()->name(), 'xref' => $individual->xref(), 'sex' => 'M', 'url' => $individual->url() . '#tab-relatives'])) ?>">
                            <?= I18N::translate('Add a father') ?>
                        </a>
                    </div>
                </div>
                <div class="row mt-1">
                    <div class="col-sm-12 wt-fact-content py-1">
                        <a href="<?= e(route(AddParentToIndividualPage::class, ['tree' => $individual->tree()->name(), 'xref' => $individual->xref(), 'sex' => 'F', 'url' => $individual->url() . '#tab-relatives'])) ?>">
                            <?= I18N::translate('Add a mother') ?>
                        </a>
                    </div>
                </div>
            <?php endif ?>

            <div class="row mt-1">
                    <div class="col-sm-12 wt-fact-content py-1">
                    <a href="<?= e(route(LinkChildToFamilyPage::class, ['tree' => $individual->tree()->name(), 'xref' => $individual->xref()])) ?>">
                        <?= I18N::translate('Link this individual to an existing family as a child') ?>
                    </a>
                    </div>
                </div>

            <div class="row mt-1">
                    <div class="col-sm-12 wt-fact-content py-1">
                    <a href="<?= e(route(AddSpouseToIndividualPage::class, ['tree' => $individual->tree()->name(), 'xref' => $individual->xref(), 'url' => $individual->url() . '#tab-relatives'])) ?>">
                        <?php if ($individual->sex() !== 'F') : ?>
                            <?= I18N::translate('Add a wife') ?>
                        <?php else : ?>
                            <?= I18N::translate('Add a husband') ?>
                        <?php endif ?>
                    </a>
                    </div>
                </div>

                <div class="row mt-1">
                    <div class="col-sm-12 wt-fact-content py-1">
                    <a href="<?= e(route(LinkSpouseToIndividualPage::class, ['tree' => $individual->tree()->name(), 'xref' => $individual->xref()])) ?>">
                        <?php if ($individual->sex() !== 'F') : ?>
                            <?= I18N::translate('Add a wife using an existing individual') ?>
                        <?php else : ?>
                            <?= I18N::translate('Add a husband using an existing individual') ?>
                        <?php endif ?>
                    </a>
                    </div>
                </div>

            <div class="row mt-1">
                    <div class="col-sm-12 wt-fact-content py-1">
                    <a href="<?= e(route(AddChildToIndividualPage::class, ['tree' => $individual->tree()->name(), 'xref' => $individual->xref(), 'sex' => 'U'])) ?>">
                        <?= I18N::translate('Add a child to create a one-parent family') ?>
                    </a>
                    </div>
                </div>

<?php endif ?>
</div>
