<?php

use Fisharebest\Webtrees\I18N;

?>

<div class="form-group row">
    <label class="col-sm-3 col-form-label" for="type">
        <?= I18N::translate('Chart type') ?>
    </label>
    <div class="col-sm-9">
        <?= view('components/select', ['name' => 'type', 'selected' => $type, 'options' => $charts]) ?>
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-3 col-form-label" for="xref">
        <label for="xref">
            <?= I18N::translate('Individual') ?>
        </label>
    </label>
    <div class="col-sm-9">
        <?= view('components/select-individual', ['name' => 'xref', 'individual' => $individual, 'tree' => $tree]) ?>
    </div>
</div>
