<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;

/**
 * @var array<string,string> $steps
 * @var string               $title
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<p>
    <?= I18N::translate('It can take several minutes to download and install the upgrade. Be patient.') ?>
</p>

<dl id="admin-upgrade-wizard-page">
    <?php foreach ($steps as $url => $text) : ?>
    <dt><?= $text ?></dt>
    <dd data-url="<?= e($url) ?>"></dd>
    <?php endforeach ?>
</dl>

