<?php

/**
 * webtrees: online genealogy
 * Copyright (C) 2021 webtrees development team
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace Fisharebest\Webtrees\Module;

use Illuminate\Support\Collection;

/**
 * Class HistoryRulersCzech
 */
class HistoryRulersCzech extends AbstractModule implements ModuleHistoricEventsInterface
{
    use ModuleHistoricEventsTrait;

    /**
     * How should this module be identified in the control panel, etc.?
     *
     * @return string
     */
    public function title(): string
    {
        return 'Seznam představitelů českého státu 🇨🇿';
    }

    /**
     * Should this module be enabled when it is first installed?
     *
     * @return bool
     */
    public function isEnabledByDefault(): bool
    {
        return false;
    }

    /**
     * All events provided by this module.
     *
     * @return Collection<string>
     */
    public function historicEventsAll(): Collection
    {
        return new Collection([
            "1 EVEN Sámo\n2 TYPE Král\n2 DATE FROM @#DJULIAN@ 623 TO @#DJULIAN@ 658\n2 NOTE Franský kupec, vládce slovanského kmenového svazu, tzv. Sámovy říše\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Sámova_říše_(623?-658/9))",
            "1 EVEN Interregnum\n2 TYPE mezivládí\n2 DATE FROM @#DJULIAN@ 659 TO @#DJULIAN@ 830",
            "1 EVEN Mojmír I.\n2 TYPE Kníže velkomoravský\n2 DATE FROM @#DJULIAN@ 830 TO @#DJULIAN@ 846\n2 NOTE První historicky známý moravský vládce, zakladatel dynastie Mojmírovců\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Velkomoravští_panovníci_(833-906):_Mojmírovci)",
            "1 EVEN Rostislav\n2 TYPE Kníže velkomoravský\n2 DATE FROM @#DJULIAN@ 846 TO @#DJULIAN@ 870\n2 NOTE Synovec Mojmíra I. V roce 846, pravděpodobně po Mojmírově smrti, byl na velkomoravský stolec dosazen Ludvíkem Němcem, panovníkem východofranské říše\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Velkomoravští_panovníci_(833-906):_Mojmírovci)",
            "1 EVEN Svatopluk I.\n2 TYPE Kníže velkomoravský\n2 DATE FROM @#DJULIAN@ 870 TO @#DJULIAN@ 871\n2 NOTE Synovec Rostislava. Třetí a nejvýznamnější panovník Velkomoravské říše (ve středověku označován za krále)\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Velkomoravští_panovníci_(833-906):_Mojmírovci)",
            "1 EVEN Wilhelm II. a Engelšalk\n2 TYPE Místodržící\n2 DATE FROM @#DJULIAN@ 871 TO @#DJULIAN@ 872\n2 NOTE Franští místodržící v době Svatopluka\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Velkomoravští_panovníci_(833-906):_Mojmírovci)",
            "1 EVEN Slavomír\n2 TYPE Kníže velkomoravský\n2 DATE FROM @#DJULIAN@ 872 TO @#DJULIAN@ 873\n2 NOTE Kněz, vůdce vzpoury proti franské nadvládě\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Velkomoravští_panovníci_(833-906):_Mojmírovci)",
            "1 EVEN Svatopluk I.\n2 TYPE Kníže velkomoravský\n2 DATE FROM @#DJULIAN@ 873 TO @#DJULIAN@ 894\n2 NOTE Znovu na trůně\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Velkomoravští_panovníci_(833-906):_Mojmírovci)",
            "1 EVEN Mojmír II.\n2 TYPE Kníže velkomoravský\n2 DATE FROM @#DJULIAN@ 894 TO @#DJULIAN@ 906\n2 NOTE Syn Svatopluka I. Po roce 906 o Mojmírovi II. historické prameny mlčí, předpokládá se tedy, že zemřel právě toho roku\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Velkomoravští_panovníci_(833-906):_Mojmírovci)",
            "1 EVEN Svatopluk II.\n2 TYPE Kníže velkomoravský\n2 DATE @#DJULIAN@ 906\n2 NOTE Údělník v Nitře. Na krátku dobu se stal spoluvládcem říše svého bratra\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Velkomoravští_panovníci_(833-906):_Mojmírovci)",
            "1 EVEN Bořivoj I.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 872 TO @#DJULIAN@ 883\n2 NOTE Zakladatel dynastie Přemyslovců, podle Kosmase syn bájného Hostivíta, jeho původ nelze spolehlivě prokázat. První historicky doložený Přemyslovec\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Velkomoravští_panovníci_(833-906):_Mojmírovci)",
            "1 EVEN Strojmír\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 883 TO @#DJULIAN@ 885\n2 NOTE Původ neznámý. Podle Kristiánovy legendy svrhl knížete Bořivoje, jenž uprchl na Moravu\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Velkomoravští_panovníci_(833-906):_Mojmírovci)",
            "1 EVEN Bořivoj I.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 885 TO @#DJULIAN@ 889\n2 NOTE Podruhé na trůně\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Velkomoravští_panovníci_(833-906):_Mojmírovci)",
            "1 EVEN Svatopluk I.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 890 TO @#DJULIAN@ 894\n2 NOTE Mojmírovec. Po smrti svého chráněnce Bořivoje I. na krátkou dobu opět převzal vládu (nárok na české území byl potvrzen Arnulfem Korutanským v roce 890)\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Velkomoravští_panovníci_(833-906):_Mojmírovci)",
            "1 EVEN Spytihněv I.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 894 TO @#DJULIAN@ 915\n2 NOTE Syn Bořivoje. Vlády se ujal poté, co se Čechy po smrti Svatopluka I. vymanily z vlivu Velké Moravy a přiklonily se k Bavorsku\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Vratislav I.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 915 TO @#DJULIAN@ 921\n2 NOTE Syn Bořivoje I., bratr Spytihněva I\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN svatý Václav\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 921 TO @#DJULIAN@ 935\n2 NOTE Syn Vratislava I., patron přemyslovské dynastie a české země, v některých seznamech bývá uveden jako kníže Václav I. Ve starší literatuře se často udává jako rok jeho smrti 929, většina soudobých vědců se ale již kloní k roku 935\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Boleslav I.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 935 TO @#DJULIAN@ 972\n2 NOTE Syn Vratislava I., bratr svatého Václava. Boleslav I. je někdy považován za zakladatele české státnosti: ražba mince, hradská soustava, územní expanze – severní část Moravy, Horní Slezsko, Krakovsko a Červené hrady (Halič) – a centralizace\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Boleslav II.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 972 TO @#DJULIAN@ 999\n2 NOTE Syn Boleslava I. Ještě rozšířil území zděděná po svém otci, ale ke sklonku vlády nedokázal zabránit jejich ztrátě ve prospěch Polska. Vyvražděni Slavníkovci, čímž dokončeno sjednocení Čech. Po jeho smrti přichází státní úpadek a boj o trůn mezi jeho třemi syny\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Boleslav III.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 999 TO @#DJULIAN@ 1002\n2 NOTE Syn Boleslava II. O trůn přišel povstáním předáků a družiníků\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Vladivoj\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1002 TO @#DJULIAN@ 1003\n2 NOTE Snad Piastovec, možná syn polského knížete Měška I. a Přemyslovny Doubravky. Na knížecí stolec dosazen polským knížetem Boleslavem Chrabrým\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Jaromír\n2 TYPE Kníže\n2 DATE @#DJULIAN@ 1003\n2 NOTE Syn Boleslava II. Po smrti Vladivoje byl díky vojenské pomoci Jindřicha II. krátce dosazen na český knížecí stolec \n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Boleslav III.\n2 TYPE Kníže\n2 DATE @#DJULIAN@ 1003\n2 NOTE Podruhé na trůně, roku 1003 Boleslavem Chrabrým znovu dosazen. Nařídil vraždění Vršovců; to vyvolalo povstání. Boleslav Chrabrý povolal svého chráněnce do Polska, oslepil jej a uvěznil\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Boleslav Chrabrý\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1003 TO @#DJULIAN@ 1004\n2 NOTE Piastovec, polský kníže. Syn polského knížete Měška I. a Přemyslovny Doubravky, dcery Boleslava I. Na jaře 1003 vpadl do Čech, které ovládal do podzimu 1004\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Jaromír\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1004 TO @#DJULIAN@ 1012\n2 NOTE Podruhé na trůně. Na podzim 1004 s podporou Jindřicha II. byli z Čech vypuzeni Poláci\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Oldřich\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1012 TO @#DJULIAN@ 1033\n2 NOTE Nejmladší syn Boleslava II. Na jaře 1012 se zmocnil vlády v Čechách, Jaromír uprchl. V letech 1019/1029 (datace je nejistá) postupně dobyl na Polácích Moravu, která od té doby byla trvalou součástí českého státu\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Jaromír\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1033 TO @#DJULIAN@ 1034\n2 NOTE Potřetí na trůně. Když Oldřicha roku 1033 obvinil císař Konrád II. z úkladů proti své osobě a sesadil jej, ustavilo říšské vojsko na podzim 1033 znovu Jaromíra českým knížetem\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Oldřich\n2 TYPE Kníže\n2 DATE @#DJULIAN@ 1034\n2 NOTE Podruhé na trůně. Na jaře 1034 Konrád II. Oldřicha propustil a vrátil mu vládu v knížectví. Jaromíra dal jeho bratr zajmout a oslepit\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Břetislav I.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1034 TO @#DJULIAN@ 1055\n2 NOTE Syn knížete Oldřicha. Roku 1054 vyřešil otázku nástupnictví prosazením seniorátu – knížetem měl být nejstarší mužský člen přemyslovské dynastie\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Spytihněv II.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1055 TO @#DJULIAN@ 1061\n2 NOTE Syn knížete Břetislava. Své bratry zbavil držav a podřídil tak Moravu své přímé vládě\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(872-1061):_Přemyslovci,_krátce_též_Mojmírovci_a_Piastovci)",
            "1 EVEN Vratislav II\n2 TYPE Kníže a král\n2 DATE FROM @#DJULIAN@ 1061 TO @#DJULIAN@ 1092\n2 NOTE Syn Břetislava I. Od roku 1085 byl prvním českým králem. Nedědičný titul ad personam mu propůjčil císař Jindřich IV. V letech 1085–1092 byl také titulárním polským králem\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Český_kníže_a_následně_král_(1061-1092):_Přemyslovci)",
            "1 EVEN Konrád I. Brněnský\n2 TYPE Kníže\n2 DATE @#DJULIAN@ 1092\n2 NOTE Syn Břetislava I. Na knížecí stolec usedl 20. ledna 1092. Stihl se pouze pokusit opět spojit pražské a olomoucké biskupství\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1092-1140):_Přemyslovci)",
            "1 EVEN Břetislav II.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1092 TO @#DJULIAN@ 1100\n2 NOTE Syn Vratislava II. Roku 1099 Břetislav II. vojensky obsadil Moravu a svěřil ji do správy svého bratra Bořivoje II., kterého rovněž určil jako svého nástupce\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1092-1140):_Přemyslovci)",
            "1 EVEN Bořivoj II.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1100 TO @#DJULIAN@ 1107\n2 NOTE Syn Vratislava II. Jeho nástup na trůn znamenal porušení zásad stařešinského řádu a počátek dlouhotrvajících rozbrojů mezi Přemyslovci\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1092-1140):_Přemyslovci)",
            "1 EVEN Svatopluk Olomoucký\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1107 TO @#DJULIAN@ 1109\n2 NOTE Syn Oty Olomouckého. V roce 1107 poslal k Bořivoji II. vyslance, který pomluvil u knížete jeho spojence, Bořivoj ztratil oporu své moci a byl nucen uprchnout do Německa. Svatopluk se tak stal knížetem\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1092-1140):_Přemyslovci)",
            "1 EVEN Vladislav I.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1109 TO @#DJULIAN@ 1117\n2 NOTE Syn Vratislava II. Jeho moc byla ohrožena ze strany příbuzných, císař Jindřich V. ho ovšem coby knížete potvrdil a Vladislav se tvrdě vypořádal se svými odpůrci\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1092-1140):_Přemyslovci)",
            "1 EVEN Bořivoj II.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1117 TO @#DJULIAN@ 1120\n2 NOTE Podruhé na trůně. Roku 1117 postoupil Vladislav I. svému bratru Bořivojovi II. vládu, ale již za tři roky se z nejasných příčin opět vystřídali\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1092-1140):_Přemyslovci)",
            "1 EVEN Vladislav I.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1120 TO @#DJULIAN@ 1125\n2 NOTE Podruhé na trůně\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1092-1140):_Přemyslovci)",
            "1 EVEN Soběslav I.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1125 TO @#DJULIAN@ 1140\n2 NOTE Syn Vratislava II. Vládu si nárokoval i Ota II. Olomoucký a získal si podporu německého krále Lothara III. Říšská vojenská výprava skončila porážkou v bitvě u Chlumce v únoru 1126\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1092-1140):_Přemyslovci)",
            "1 EVEN Vladislav II.\n2 TYPE Kníže a král\n2 DATE FROM @#DJULIAN@ 1140 TO @#DJULIAN@ 1172\n2 NOTE Syn Vladislava I. a druhý český král. Zřejmě nedědičný královský titul mu propůjčil císař Fridrich I. Barbarossa v roce 1158\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Český_kníže_a_následně_král_(1140-1172):_Přemyslovci)",
            "1 EVEN Bedřich\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1172 TO @#DJULIAN@ 1173\n2 NOTE Syn Vladislava II., který mu roku 1172 předal vládu podle principu primogenitury. Dosud ovšem platilo právo seniorátu. O knížecí hodnost se tak hlásili synové Soběslava I\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1172-1198):_Přemyslovcii)",
            "1 EVEN Soběslav II.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1173 TO @#DJULIAN@ 1178\n2 NOTE Syn Soběslava I. Získal podporu císaře Barbarossy, který za knížete určil Soběslavova bratra Oldřicha. Oldřich však neměl podporu české šlechty a brzy předal vládu Soběslavovi\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1172-1198):_Přemyslovcii)",
            "1 EVEN Bedřich\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1178 TO @#DJULIAN@ 1189\n2 NOTE Syn Vladislava II. V létě 1178 ztratil Soběslav II. podporu Fridricha Barbarossy, čehož využil Bedřich, uplatil císaře a obdržel od něj Čechy v léno\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1172-1198):_Přemyslovcii)",
            "1 EVEN Konrád II. Ota\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1189 TO @#DJULIAN@ 1191\n2 NOTE Syn Konráda II. Znojemského. Po smrti Bedřicha nastoupil na knížecí stolec, Čechy a Morava se tak spojily do jednoho státního celku, protože kníže rezignoval na titul markraběte moravského\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1172-1198):_Přemyslovcii)",
            "1 EVEN Václav (II.)\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1191 TO @#DJULIAN@ 1192\n2 NOTE Syn Soběslava I. Po smrti Konráda Oty se zmocnil Čech. Proti němu ale vystoupil biskup Jindřich Břetislav a vymohl u císaře Jindřicha VI., aby udělil Čechy v léno Přemyslu Otakarovi I. V některých seznamech je uváděn jako Václav II\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1172-1198):_Přemyslovcii)",
            "1 EVEN Přemysl Otakar I.\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1192 TO @#DJULIAN@ 1193\n2 NOTE Syn Vladislava II. Knížetem se s podporou biskupa Jindřicha Břetislava a císaře Jindřicha VI. stal roku 1192. O rok později ho šlechta na trůně vystřídala Jindřichem Břetislavem\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1172-1198):_Přemyslovcii)",
            "1 EVEN Jindřich Břetislav\n2 TYPE Kníže\n2 DATE FROM @#DJULIAN@ 1193 TO @#DJULIAN@ 1197\n2 NOTE Roku 1193 mu císař propůjčil hodnost českého knížete. Přemysl I. proti němu táhl s vojskem, v rozhodující chvíli se však od něho odvrátila šlechta\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1172-1198):_Přemyslovcii)",
            "1 EVEN Vladislav Jindřich\n2 TYPE Kníže\n2 DATE @#DJULIAN@ 1197\n2 NOTE Syn Vladislava II. Titul si nárokoval i jeho starší bratr Přemysl I. Aby zabránil vzestupu politické nestability, vzdal se titulu a dědických nároků ve prospěch svého bratra\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Česká_knížata_(1172-1198):_Přemyslovcii)",
            "1 EVEN Přemysl Otakar I.\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1198 TO @#DJULIAN@ 1230\n2 NOTE Podruhé na trůně, korunován 1203. Přemysl si postupně nechal potvrdit královskou hodnost od obou římských králů i od papeže. Dědičný titul zaručila Zlatá bula sicilská (1212)\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Přemyslovci_(1198-1306))",
            "1 EVEN Václav I.\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1230 TO @#DJULIAN@ 1253\n2 NOTE Syn Přemysla I., čtvrtý český král. Korunován byl už v roce 1228. Přispěl k odražení mongolského vpádu do Evropy a společně se synem Přemyslem získal Rakousko\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Přemyslovci_(1198-1306))",
            "1 EVEN Přemysl Otakar II.\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1253 TO @#DJULIAN@ 1278\n2 NOTE Syn Václava I., pátý český král (korunován 1261). Také vévoda rakouský, štýrský, korutanský a kraňský. Podcenil ale vývoj v římskoněmecké říši a politiku papežské kurie\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Přemyslovci_(1198-1306))",
            "1 EVEN Václav II.\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1278 TO @#DJULIAN@ 1305\n2 NOTE Syn Přemysla II., šestý český král (korunován 1297). Také polský král (korunován roku 1300). Pro syna získal i uherský trůn\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Přemyslovci_(1198-1306))",
            "1 EVEN Václav III.\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1305 TO @#DJULIAN@ 1306\n2 NOTE Syn Václava II, sedmý český král. V letech 1301–1304 byl uherským králem jako Ladislav V. Po smrti otce se snažil udržet unii s Polskem, byl však zavražděn. Skončilo tak více než 400 let vlády Přemyslovců v Čechách\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Přemyslovci_(1198-1306))",
            "1 EVEN Jindřich Korutanský\n2 TYPE Král český\n2 DATE @#DJULIAN@ 1306\n2 NOTE Menhardovec. Manžel Anny Přemyslovny. Měsíc po jeho volbě za krále se objevila vojska Rudolfa, syna římského krále Albrechta I., a Jindřich s Annou uprchli\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Nedynastičtí)",
            "1 EVEN Rudolf I. Habsburský\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1306 TO @#DJULIAN@ 1307\n2 NOTE Syn Albrechta I. Dokázal si získat podporu části panstva sliby (i úplatky), ale zemřel při obléhání hradu Bavora III. ze Strakonic\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Nedynastičtí)",
            "1 EVEN Jindřich Korutanský\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1307 TO @#DJULIAN@ 1310\n2 NOTE Podruhé na trůně. Jindřich nebyl schopný panovník a část panstva požádala o pomoc římského krále Jindřicha VII., jehož syn Jan Lucemburský se měl oženit s princeznou Eliškou Přemyslovnou\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Nedynastičtí)",
            "1 EVEN Jan Lucemburský\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1310 TO @#DJULIAN@ 1346\n2 NOTE Syn Jindřicha VII. V Janovi se protnuly tři nástupnické principy: Uznala ho česká šlechta. Císař mu udělil Čechy v léno. Oženil se s Eliškou Přemyslovnou\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Lucemburkové_(1310-1437))",
            "1 EVEN Karel IV.\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1346 TO @#DJULIAN@ 1378\n2 NOTE Syn Jana Lucemburského. Také římský císař. S jeho jménem je spojen největší politický i kulturní rozkvět českých zemí\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Lucemburkové_(1310-1437))",
            "1 EVEN Václav IV.\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1378 TO @#DJULIAN@ 1419\n2 NOTE Syn Karla IV. Také římský král. Českým králem byl korunován už ve dvou letech. Syna neměl, a tak byl jeho dědicem jeho bratr Zikmund\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Lucemburkové_(1310-1437))",
            "1 EVEN Zikmund\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1419 TO @#DJULIAN@ 1437\n2 NOTE Syn Karla IV. Také římský císař a uherský král. Roku 1421 ho český zemský sněm jako krále odmítl; plně respektovaným králem byl až poslední dva roky života\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Lucemburkové_(1310-1437))",
            "1 EVEN Albrecht II. Habsburský (Albrecht I.)\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1437 TO @#DJULIAN@ 1439\n2 NOTE Zikmundův zeť a dědic. Také římský a uherský král. Svých dědických práv se domáhal obtížně, české koruny dosáhl i přes odpor husitů\n2 SOUR [Wikipedia; Seznam představitelů českého státu]0(https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_a_období_interregna)",
            "1 EVEN Interregnum\n2 TYPE mezivládí\n2 DATE FROM @#DJULIAN@ 1439 TO @#DJULIAN@ 1453\n2 NOTE Po Albrechtově smrti byla koruna nabídnuta Albrechtu III. Bavorskému, který ji odmítl. Vznikly šlechtické spolky – sněmíky, landfrídy. Spolupráci landfrídů zajišťovaly zemské sněmy\n2 SOUR [Wikipedia; Seznam představitelů českého státu]0(https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_a_období_interregna)",
            "1 EVEN Ladislav Pohrobek\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1453 TO @#DJULIAN@ 1457\n2 NOTE Syn Albrechta II., narozen až po jeho smrti (= pohrobek). Také uherský král. V Čechách sídlil v letech 1453–1454 a potom už jen dva měsíce před svou smrtí\n2 SOUR [Wikipedia; Seznam představitelů českého státu]0(https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_a_období_interregna)",
            "1 EVEN Jiří z Poděbrad\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1458 TO @#DJULIAN@ 1471\n2 NOTE Zemský správce z doby Ladislava Pohrobka, po jehož smrti se stal králem. Ačkoliv měl potomky, korunu odkázal Jagelloncům\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Nedynastičtí_2)",
            "1 EVEN Matyáš Korvín\n2 TYPE Protikrál\n2 DATE FROM @#DJULIAN@ 1469 TO @#DJULIAN@ 1490\n2 NOTE Vládce Uher vojensky usiloval i o český trůn; v průběhu konfrontace se nechal opoziční českou šlechtou zvolit za krále, ačkoliv Jiřímu, který byl jeho tchánem, jen krátce předtím slíbil přátelství.\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Nedynastičtí_2)",
            "1 EVEN Vladislav Jagellonský (Vladislav II.)\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1471 TO @#DJULIAN@ 1516\n2 NOTE Syn Kazimíra IV. Zvolen českým králem byl podle přání Jiřího z Poděbrad, musel ale až do r. 1478 bojovat s Matyášem Korvínem – vládu v zemích Koruny si nakonec rozdělili. Od roku 1490 také král uherský. V roce 1500 vydal Vladislavské zřízení zemské\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Jagellonci_(1471-1526))",
            "1 EVEN Ludvík Jagellonský\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1516 TO @#DJULIAN@ 1526\n2 NOTE Syn Vladislava Jagellonského. Otec ho nechal korunovat již roku 1508 za uherského krále a o rok později za krále českého. Zemřel v bitvě u Moháče, čímž vymřela česko-uherská větev rodu\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Jagellonci_(1471-1526))",
            "1 EVEN Ferdinand I.\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1526 TO @#DJULIAN@ 1564\n2 NOTE Vnuk císaře Maxmiliána I., manžel Anny Jagellonské. Také římskoněmecký císař a uherský král\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Maxmilián I./II.\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1564 TO @#DJULIAN@ 1576\n2 NOTE Syn Ferdinanda I. Také římskoněmecký císař a uherský král\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Rudolf II.\n2 TYPE Král český\n2 DATE FROM @#DJULIAN@ 1576 TO 1611\n2 NOTE Syn Maxmiliána II. Zároveň král uherský a císař římský. Od r. 1608 vládl jen v Čechách a ve Slezsku. Císař do své smrti v roce 1612\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Matyáš II.\n2 TYPE Král český\n2 DATE FROM 1611 TO 1619\n2 NOTE Syn Maxmiliána II. Reálně vládl do r. 1618. Současně král uherský a císař římský od r. 1612. Jako král uherský Matyáš II\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Ferdinand II.\n2 TYPE Král český\n2 DATE 1619\n2 NOTE Matyášův bratranec. Jeho bratranec neměl potomky, a tak byl Ferdinand ještě za jeho života v roce 1617 korunován českým králem\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Fridrich Falcký\n2 TYPE Král český\n2 DATE FROM 1619 TO 1620\n2 NOTE Wittelsbach. Falcký kurfiřt, který projevoval sympatie k českým protestanstským stavům. Zvolen králem byl ale až v době, kdy bylo stavovské povstání v defenzivě\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Ferdinand II. štýrský\n2 TYPE Král český\n2 DATE FROM 1620 TO 1637\n2 NOTE Současně král uherský a císař římský. Reálně vládl od r. 1620. Potlačil české stavovské povstání\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Ferdinand III.\n2 TYPE Král český\n2 DATE FROM 1637 TO 1657\n2 NOTE Syn Ferdinanda II. Také císař římský a král uherský. Pokračoval v českých zemích v rekatolizaci a posilování absolutistické moci, ovšem už mírnějšími prostředky\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Ferdinand IV.\n2 TYPE Král český\n2 DATE FROM 1646 TO 1654\n2 NOTE spoluvladař Ferdinanda III., svého otce. Od r. 1647 také král uherský. Reálně nevládl, zemřel za života svého otce\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Leopold I.\n2 TYPE Král český\n2 DATE FROM 1657 TO 1705\n2 NOTE Syn Ferdinanda III. Také římskoněmecký císař a uherský král\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Josef I.\n2 TYPE Král\n2 DATE FROM 1705 TO 1711\n2 NOTE Syn Leopolda I. Již v dětských letech byl korunován uherským (v roce 1687) a římskoněmeckým králem (r. 1690). Českým králem Josef ovšem korunován nebyl\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Karel II./VI.\n2 TYPE Král český\n2 DATE FROM 1711 TO 1740\n2 NOTE Syn Leopolda I. Jako císař římský Karel VI. Současně král uherský. Snažil se pragmatickou sankcí zajistit dědictví nejstarší dceři Marii Terezii\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Marie Terezie\n2 TYPE Královna česká\n2 DATE FROM 1740 TO 1780\n2 NOTE Dcera Karla VI. Jediná vládnoucí česká královna. Také královna uherská. O dědictví musela bojovat s Karlem VII. (kurfiřtem bavorským), roku 1743 se nechala korunovat českou královnou. Ženská linie habsburské dynastie\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Karel Albrecht Bavorský / Karel III.\n2 TYPE Panovník\n2 DATE FROM 1741 TO 1743\n2 NOTE Protikrál, římský císař. Po smrti Karla VI. neuznal Pragmatickou sankci, 9. prosince 1741 se nechal provolat českými stavy králem jako Karel III\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsburkové_(1526-1780))",
            "1 EVEN Josef II.\n2 TYPE Král český\n2 DATE FROM 1780 TO 1790\n2 NOTE Syn Marie Terezie. Také římský císař a uherský král, reformátor\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsbursko-lotrinská_dynastie_(1780-1918))",
            "1 EVEN Leopold II.\n2 TYPE Král český\n2 DATE FROM 1790 TO 1792\n2 NOTE Syn Marie Terezie. Také římský císař a uherský král. Na rozdíl od bratra se nechal českým králem korunovat\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsbursko-lotrinská_dynastie_(1780-1918))",
            "1 EVEN František I. Rakouský\n2 TYPE Král český\n2 DATE FROM 1792 TO 1835\n2 NOTE Syn Leopolda II. Také uherský král, římský císař (do r. 1806), poté rakouský císař (od r. 1804)\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsbursko-lotrinská_dynastie_(1780-1918))",
            "1 EVEN Ferdinand I. Dobrotivý (Ferdinand V.)\n2 TYPE Král český\n2 DATE FROM 1835 TO 1848\n2 NOTE Syn Františka I. Také rakouský císař a uherský král. V roce 1848 byl odstaven od českého trůnu a abdikoval ve prospěch synovce Františka Josefa I. Poslední korunovaný český král\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsbursko-lotrinská_dynastie_(1780-1918))",
            "1 EVEN František Josef I.\n2 TYPE Král a císař\n2 DATE FROM 1848 TO 1916\n2 NOTE Synovec Ferdinanda V. Také rakouský císař a uherský král. Českým zemím vládl více jak 60 let, z vnitropolitických důvodů se však nedal korunovat českým králem. (Ztroskotaly i myšlenky na trialistickou monarchii)\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsbursko-lotrinská_dynastie_(1780-1918))",
            "1 EVEN Karel I. (Karel III.)\n2 TYPE Král český\n2 DATE FROM 1916 TO 1918\n2 NOTE Rakouský císař Karel I., král uherský jako Karel IV. a král český Karel III. (Z časových a politických důvodů nebyl korunován českým králem). Rakousko-Uhersko se mu už zachránit nepodařilo, ačkoliv nabídl federaci\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Habsbursko-lotrinská_dynastie_(1780-1918))",
            "1 EVEN Tomáš Garrigue Masaryk\n2 TYPE Prezident ČSR\n2 DATE FROM 14 NOV 1918 TO 14 DEC 1935\n2 NOTE První prezident Československa, o jehož vznik se zasloužil, do funkce byl zvolen celkem čtyřikrát\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezidenti_Československa_(1918-1948))",
            "1 EVEN Edvard Beneš\n2 TYPE Prezident ČSR\n2 DATE FROM 18 DEC 1935 TO 05 OCT 1938\n2 NOTE Po Mnichovské dohodě abdikoval, v době války vedl exilovou vládu\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezidenti_Československa_(1918-1948))",
            "1 EVEN Emil Hácha\n2 TYPE Státní prezident\n2 DATE FROM 30 NOV 1938 TO 09 MAY 1945\n2 NOTE Prezidentem druhé republiky (1938–1939) a státní prezident Protektorátu Čechy a Morava (1939–1945). Wikipedie [Emil Hácha](https://cs.wikipedia.org/wiki/Emil_Hácha)\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezident_Česko-Slovenska;_poté_státní_prezident_Protektorátu_Čechy_a_Morava_(1938-1945))",
            "1 EVEN Edvard Beneš\n2 TYPE Prezident ČSR\n2 DATE FROM 02 APR 1945 TO 07 JUN 1948\n2 NOTE Po Mnichovské dohodě abdikoval, v době války vedl exilovou vládu\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezidenti_Československa_(1948-1992))",
            "1 EVEN Klement Gottwald\n2 TYPE Prezident ČSR\n2 DATE FROM 14 JUN 1948 TO 14 MAR 1953\n2 NOTE Poválečný premiér, po komunistickém převratu v únoru 1948 se stal prezidentem. První dělnický prezident, jak říkali komunisti\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezidenti_Československa_(1948-1992))",
            "1 EVEN Antonín Zápotocký\n2 TYPE Prezident ČSR\n2 DATE FROM 21 MAR 1953 TO 13 NOV 1957\n2 NOTE Druhý komunistický prezident. Rezignoval na počáteční reformní snahy\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezidenti_Československa_(1948-1992))",
            "1 EVEN Antonín Novotný\n2 TYPE Prezident ČSR/ČSSR\n2 DATE FROM 19 NOV 1957 TO 28 MAR 1968\n2 NOTE V době jeho vlády došlo k jakémusi uvolnění a k částečné rehabilitaci některých nespravedlivě odsouzených v 50. letech\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezidenti_Československa_(1948-1992))",
            "1 EVEN Ludvík Svoboda\n2 TYPE Prezident ČSSR\n2 DATE FROM 30 MAR 1968 TO 28 MAY 1975\n2 NOTE Zvolen v březnu 1968. Po srpnové invazi odmítl kolaborantskou vládu, poté byl ale jedním z hlavních normalizátorů\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezidenti_Československa_(1948-1992))",
            "1 EVEN Gustáv Husák\n2 TYPE Prezident ČSSR\n2 DATE FROM 29 MAY 1975 TO 10 DEC 1989\n2 NOTE Na moskevských jednáních v srpnu roku 1968 Husák „změnil kurs“. V roce 1969 se dostal do čela KSČ\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezidenti_Československa_(1948-1992))",
            "1 EVEN Václav Havel\n2 TYPE Prezident ČSFR\n2 DATE FROM 29 DEC 1989 TO 20 JUL 1992\n2 NOTE Disident, mluvčí Charty 77 a jedna z vůdčích osobností Sametové revoluce\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezidenti_Československa_(1948-1992))",
            "1 EVEN Václav Havel\n2 TYPE Prezident ČR\n2 DATE FROM 02 FEB 1993 TO 02 FEB 2003\n2 NOTE Poslední československý prezident a první český prezident\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezidenti_České_republiky_(od_roku_1993))",
            "1 EVEN Václav Klaus\n2 TYPE Prezident ČR\n2 DATE FROM 07 MAR 2003 TO 4 MAR 2013\n2 NOTE Federální ministr financí, premiér a předseda Poslanecké sněmovny z 90. let\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezidenti_České_republiky_(od_roku_1993))",
            "1 EVEN Miloš Zeman\n2 TYPE Prezident ČR\n2 DATE FROM 08 MAR 2013\n2 NOTE Premiér a předseda Poslanecké sněmovny z 90. let, historicky první přímo zvolený prezident České republiky\n2 SOUR [Wikipedia; Seznam představitelů českého státu](https://cs.wikipedia.org/wiki/Seznam_představitelů_českého_státu#Prezidenti_České_republiky_(od_roku_1993))",
        ]);
    }
}
