<?php

use Fisharebest\Webtrees\Statistics;

/**
 * @var Statistics $stats
 */

?>

<div class="container pt-3">
    <?= $stats->embedTags(view('modules/statistics-chart/family-totals')) ?>
    <?= $stats->embedTags(view('modules/statistics-chart/marriage-length')) ?>
    <?= $stats->embedTags(view('modules/statistics-chart/marriage-age')) ?>
    <?= $stats->embedTags(view('modules/statistics-chart/birth-age')) ?>
    <?= $stats->embedTags(view('modules/statistics-chart/children')) ?>
    <?= $stats->embedTags(view('modules/statistics-chart/age-difference')) ?>
</div>
