<?php
/** @var \Fisharebest\Webtrees\Stats $stats */
?>

<script src="node_modules/chart.js/dist/Chart.js"></script>

<div class="container pt-3">
    <?= view('statistics/families/total-records', ['stats' => $stats]) ?>
    <?= view('statistics/families/marriage-length', ['stats' => $stats]) ?>
    <?= view('statistics/families/marriage-age', ['stats' => $stats]) ?>
    <?= view('statistics/families/birth-age', ['stats' => $stats]) ?>
    <?= view('statistics/families/children', ['stats' => $stats]) ?>
    <?= view('statistics/families/age-difference', ['stats' => $stats]) ?>
</div>
