<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

?>

<h4 class="border-bottom p-2 mb-4">
    <?= I18N::translate('Greatest age at death') ?>
</h4>

<div class="row row-cols-1 row-cols-md-2 mb-3 g-3">
    <div class="col">
        <div class="card">
            <h5 class="card-header">
                <?= I18N::translate('Males') ?>
            </h5>
            #topTenOldestMaleList#
        </div>
    </div>

    <div class="col">
        <div class="card">
            <h5 class="card-header">
                <?= I18N::translate('Females') ?>
            </h5>
            #topTenOldestFemaleList#
        </div>
    </div>
</div>