<?php

use Fisharebest\Webtrees\Statistics;

/**
 * @var Statistics $stats
 */

?>

<div class="container pt-3">
    <?= $stats->embedTags(view('modules/statistics-chart/total-individuals')) ?>
    <?= $stats->embedTags(view('modules/statistics-chart/total-events')) ?>
    <?= $stats->embedTags(view('modules/statistics-chart/lifespan')) ?>
    <?= $stats->embedTags(view('modules/statistics-chart/greatest-age')) ?>
    <?= $stats->embedTags(view('modules/statistics-chart/oldest-living')) ?>
    <?= $stats->embedTags(view('modules/statistics-chart/names')) ?>
</div>
