<?php

/** @var Statistics $stats */

use Fisharebest\Webtrees\Statistics;

?>

<div class="container pt-3">
    <?= view('statistics/individuals/total-records', ['stats' => $stats]) ?>
    <?= view('statistics/individuals/total-events', ['stats' => $stats]) ?>
    <?= view('statistics/individuals/lifespan', ['stats' => $stats]) ?>
    <?= view('statistics/individuals/greatest-age', ['stats' => $stats]) ?>
    <?= view('statistics/individuals/oldest-living', ['stats' => $stats]) ?>
    <?= view('statistics/individuals/names', ['stats' => $stats]) ?>
</div>
