<?php use Fisharebest\Webtrees\I18N; ?>

<?php
/** @var \Fisharebest\Webtrees\Stats $stats */
?>

<div class="container pt-3">
    <?= view('statistics/individuals/total-records', ['stats' => $stats]) ?>
    <?= view('statistics/individuals/total-events', ['stats' => $stats]) ?>
    <?= view('statistics/individuals/lifespan', ['stats' => $stats]) ?>
    <?= view('statistics/individuals/greatest-age', ['stats' => $stats]) ?>
    <?= view('statistics/individuals/oldest-living', ['stats' => $stats]) ?>
    <?= view('statistics/individuals/names', ['stats' => $stats]) ?>
</div>
