<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

?>

<h4 class="border-bottom p-2 mb-4">
    <?= I18N::translate('Total events') ?>
    <span class="badge bg-secondary rounded-pill float-end">#totalEvents#</span>
</h4>

<div class="row row-cols-1 row-cols-md-2 g-3 mb-3">
    <div class="col">
        <div class="card">
            <h5 class="card-header">
                <?= I18N::translate('First event') ?> — #firstEventType#
            </h5>
            <div class="card-body">
                #firstEvent#
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card">
            <h5 class="card-header">
                <?= I18N::translate('Last event') ?> — #lastEventType#
            </h5>
            <div class="card-body">
                #lastEvent#
            </div>
        </div>
    </div>
</div>
