<?php
/** @var \Fisharebest\Webtrees\Stats $stats */
?>

<script src="node_modules/chart.js/dist/Chart.js"></script>

<div class="container pt-3">
    <?= view('statistics/other/total-records', ['stats' => $stats]) ?>
    <?= view('statistics/other/total-events', ['stats' => $stats]) ?>
    <?= view('statistics/other/chart-objects', ['stats' => $stats]) ?>
    <?= view('statistics/other/places', ['stats' => $stats]) ?>
    <?= $stats->chartDistribution() ?>
</div>
