<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

?>

<h4 class="border-bottom p-2 mb-4">
    <?= I18N::translate('Places') ?>
    <span class="badge bg-secondary rounded-pill float-end">#totalPlaces#</span>
</h4>

<div class="row row-cols-1 row-cols-md-2 g-3 mb-3">
    <div class="col">
        <div class="card">
            <h5 class="card-header">
                <?= I18N::translate('Birth places') ?>
            </h5>
            #commonBirthPlacesList#
        </div>
    </div>

    <div class="col">
        <div class="card">
            <h5 class="card-header">
                <?= I18N::translate('Death places') ?>
            </h5>
            #commonDeathPlacesList#
        </div>
    </div>

    <div class="col">
        <div class="card">
            <h5 class="card-header">
                <?= I18N::translate('Marriage places') ?>
            </h5>
            #commonMarriagePlacesList#
        </div>
    </div>

    <div class="col">
        <div class="card">
            <h5 class="card-header">
                <?= I18N::translate('Events in countries') ?>
            </h5>
            #commonCountriesList#
        </div>
    </div>
</div>
