<?php

declare(strict_types=1);

/**
 * @var string $GOOGLE_ANALYTICS_ID
 */

use Fisharebest\Webtrees\I18N;

?>

<div class="row mb-3">
    <label for="GOOGLE_ANALYTICS_ID" class="col-sm-3 col-form-label">
        <?= /* I18N: A configuration setting */ I18N::translate('Site identification code') ?>
        <span class="visually-hidden">Google Analytics</span>
    </label>
    <div class="col-sm-9">
        <input type="text" class="form-control" id="GOOGLE_ANALYTICS_ID" name="GOOGLE_ANALYTICS_ID" value="<?= e($GOOGLE_ANALYTICS_ID) ?>" placeholder="UA-12345-6 / G-1A2B3C4D" maxlength="255" pattern="UA-[0-9]+-[0-9]+|G-[0-9A-Z]+">
    </div>
</div>
