<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Elements\SubmitterText;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Gedcom;
use Fisharebest\Webtrees\Http\RequestHandlers\AddNewFact;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Note;
use Fisharebest\Webtrees\Registry;
use Illuminate\Support\Collection;

/**
 * @var bool                 $can_edit
 * @var Collection<int,Fact> $clipboard_facts
 * @var Collection<int,Fact> $facts
 * @var Individual           $individual
 */

?>

<div class="container py-4 wt-facts-table">

    <div class="row wt-fact-content py-1">
        <div class="col-sm-auto">
            <input id="show-level-2-notes" class="form-check-input" type="checkbox"
                data-bs-toggle="collapse"
                data-bs-target=".wt-level-two-note"
                data-wt-persist="level-two-notes"
                autocomplete="off"
                <?= $facts->isEmpty() ? 'disabled="disabled"' : '' ?>
            >
            <label class="form-check-label" for="show-level-2-notes">
                <?= I18N::translate('Show all notes') ?>
            </label>
        </div>
    </div>

    <?php foreach ($facts as $fact) : ?>
        <?php if ($fact->tag() === 'INDI:NOTE' || $fact->tag() === 'FAM:NOTE') : ?>
            <?= view('fact', ['fact' => $fact, 'record' => $individual]) ?>
        <?php else : ?>
            <?php
            if ($fact->isPendingAddition()) {
                $styleadd = 'wt-new ';
            } elseif ($fact->isPendingDeletion()) {
                $styleadd = 'wt-old ';
            } else {
                $styleadd = '';
            }
            ?>

            <div class="row wt-level-two-note collapse mt-1">
                <div class="col-sm-2 pe-1 ps-0 <?= $styleadd ?>">
                    <div class="wt-fact-controls h-100 pt-1">
                        <?= $fact->label() ?>
                        <?= view('fact-edit-links', ['fact' => $fact, 'url' => $fact->record()->url() . '#tab-notes']) ?>
                    </div>
                </div>

                <div class="col-sm-10 wt-fact-content pt-1 <?= $styleadd ?>">
                    <?php preg_match_all("/\n[1-9] NOTE ?(.*(?:\n\d CONT.*)*)/", $fact->gedcom(), $matches, PREG_SET_ORDER) ?>
                    <?php foreach ($matches as $match) : ?>
                        <div class="mb-2">
                            <?php $text = preg_replace('/\n\d CONT ?/', "\n", $match[1]) ?>
                            <?php if (preg_match('/^@' . Gedcom::REGEX_XREF . '@$/', $text) === 1) : ?>
                                <?php $note = Registry::noteFactory()->make(trim($text, '@'), $individual->tree()) ?>
                                <?php if ($note instanceof Note) : ?>
                                    <?php if ($note->canShow()) : ?>
                                        <a href="<?= e($note->url()) ?>">
                                            <?= I18N::translate('Shared note') ?>
                                            <?= view('icons/note') ?>
                                        </a>
                                        <?= (new SubmitterText(''))->value($note->getNote(), $individual->tree()) ?>
                                    <?php endif ?>
                                <?php else : ?>
                                    <span class="error"><?= e($text) ?></span>
                                <?php endif ?>
                            <?php else : ?>
                                <?= (new SubmitterText(''))->value($text, $individual->tree()) ?>
                            <?php endif ?>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        <?php endif ?>
    <?php endforeach ?>

    <?php if ($facts->isEmpty()) : ?>
        <div class="row wt-fact-content my-3">
            <div class="col-sm-auto py-2">
                <?= I18N::translate('There are no notes for this individual.') ?>
            </div>
        </div>
    <?php endif ?>

    <?php if ($can_edit) : ?>
        <div class="row my-3">
            <div class="col-sm-2 py-2 wt-fact-controls">
                <?= I18N::translate('Note') ?>
            </div>
            <div class="col-sm-10 wt-fact-content py-2">
                <a href="<?= e(route(AddNewFact::class, ['tree' => $individual->tree()->name(), 'xref' => $individual->xref(), 'fact' => 'NOTE'])) ?>">
                    <?= I18N::translate('Add a note') ?>
                </a>
            </div>
        </div>
    <?php endif ?>

</div>
