<?php

use Fisharebest\Webtrees\Census\CensusPlaceInterface;
use Fisharebest\Webtrees\Date;
use Fisharebest\Webtrees\I18N;

/**
 * @var array<CensusPlaceInterface> $census_places
 */

?>

<select class="form-control census-selector" aria-label="<?= I18N::translate('Census date and place') ?>">
    <option value="" disabled selected hidden><?= I18N::translate('Census date') ?></option>

    <?php foreach ($census_places as $census_place) : ?>
        <optgroup label="<?= $census_place->censusPlace() ?>">
          <?php foreach ($census_place->allCensusDates() as $census) : ?>
              <option data-date="<?= $census->censusDate() ?>" data-place="<?= $census->censusPlace() ?>" data-census="<?= get_class($census) ?>">
                  <?= (new Date($census->censusDate()))->minimumDate()->format('%Y') ?>
                  —
                  <?= $census->censusPlace() ?>
              </option>
          <?php endforeach ?>
        </optgroup>
    <?php endforeach ?>
</select>

<script>
  document.querySelectorAll('.census-selector').forEach(function (el) {
    el.addEventListener('change', function (el) {
      const select = el.target;
      const option = select.options[select.selectedIndex];
      const form = select.closest('form');

      form.querySelector('[id$=CENS\\3a DATE]').value = option.dataset.date;
      form.querySelector('[id$=CENS\\3a PLAC]').value = option.dataset.place;
    });
  });
</script>
