<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Census\CensusPlaceInterface;
use Fisharebest\Webtrees\Date;
use Fisharebest\Webtrees\I18N;

/**
 * @var array<CensusPlaceInterface> $census_places
 */

?>

<select class="form-select census-selector" aria-label="<?= I18N::translate('Census date and place') ?>" autocomplete="off" data-wt-census-selector="" data-wt-census-date-target="input[id$=CENS-DATE]">
    <option value="" disabled="disabled" selected="selected" hidden="hidden"><?= I18N::translate('Census date') ?></option>

    <?php foreach ($census_places as $census_place) : ?>
        <optgroup label="<?= $census_place->censusPlace() ?>">
          <?php foreach ($census_place->allCensusDates() as $census) : ?>
              <option data-wt-date="<?= $census->censusDate() ?>" data-wt-place="<?= $census->censusPlace() ?>" data-wt-census="<?= get_class($census) ?>">
                  <?= (new Date($census->censusDate()))->yearOnly()->display() ?>
                  —
                  <?= $census->censusPlace() ?>
              </option>
          <?php endforeach ?>
        </optgroup>
    <?php endforeach ?>
</select>


