<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ModulesAllPage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var Collection<int,Tree> $all_trees
 * @var string               $sitemap_url
 * @var array<string,string> $submit_urls
 * @var string               $title
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ModulesAllPage::class) => I18N::translate('Modules'), $title]]) ?>

<h1><?= $title ?></h1>

<p>
    <?= /* I18N: The www.sitemaps.org site is translated into many languages (e.g. https://www.sitemaps.org/fr/) - choose an appropriate URL. */ I18N::translate('Sitemaps are a way for webmasters to tell search engines about the pages on a website that are available for crawling. All major search engines support sitemaps. For more information, see <a href="https://www.sitemaps.org/">www.sitemaps.org</a>.') ?>
</p>

<p>
    <?= /* I18N: Label for a configuration option */ I18N::translate('Which family trees should be included in the sitemaps') ?>
</p>

<form method="post" action="<?= e(route('module', ['module' => 'sitemap', 'action' => 'Admin'])) ?>">
    <?php foreach ($all_trees as $tree) : ?>
        <?= view('components/checkbox', ['label' => e($tree->title()), 'name' => 'sitemap' . $tree->id(), 'checked' => (bool) $tree->getPreference('include_in_sitemap')]) ?>
    <?php endforeach ?>

    <button type="submit" class="btn btn-primary">
        <?= I18N::translate('save') ?>
    </button>

    <?= csrf_field() ?>
</form>

<hr>

<p>
    <?= I18N::translate('URL') ?> — <a href="<?= e($sitemap_url) ?>"><?= e($sitemap_url) ?></a>
</p>

<p>
    <?= I18N::translate('To tell search engines that sitemaps are available, you can use the following links.') ?>
</p>

<ul>
    <?php foreach ($submit_urls as $search_engine => $url) : ?>
    <li>
        <a href="<?= e($url) ?>">
            <?= e($search_engine) ?>
        </a>
    </li>
    <?php endforeach ?>
</ul>
