<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\TreePage;

?>
<<?php /* Beware short open tags in PHP <8.0 */ ?>?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
    <?php foreach ($records as $record) : ?>
        <url>
            <loc><?= e($record->url()) ?></loc>
            <?php if ($record->facts(['CHAN'])->isNotEmpty()) : ?>
                <lastmod><?= $record->facts(['CHAN'])->first()->date()->minimumDate()->Format('%Y-%m-%d') ?></lastmod>
            <?php endif ?>
        </url>
    <?php endforeach ?>

    <?php if ($records->isNotEmpty()) : ?>
        <url>
            <loc><?= e(route(TreePage::class, ['tree' => $tree->name()])) ?></loc>
        </url>
    <?php endif ?>
</urlset>


