<?php

use Fisharebest\Webtrees\Repository;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var Collection<int,Repository> $repositories
 * @var string                     $title
 * @var Tree                       $tree
 */

?>
<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<div class="wt-page-content">
    <?= view('lists/repositories-table', ['repositories' => $repositories, 'tree' => $tree]) ?>
</div>
