<?php

declare(strict_types=1);

/**
 * @var string $baseurl
 * @var string $dbca
 * @var string $dbcert
 * @var string $dbhost
 * @var string $dbkey
 * @var string $dbname
 * @var string $dbuser
 * @var string $dbpass
 * @var string $dbport
 * @var string $dbtype
 * @var string $dbverify
 * @var string $tblpfx
 */

?>
; <<?= '?php' ?> return; ?> DO NOT DELETE THIS LINE
dbtype="<?= addcslashes($dbtype, '"') ?>"
dbhost="<?= addcslashes($dbhost, '"') ?>"
dbport="<?= addcslashes($dbport, '"') ?>"
dbuser="<?= addcslashes($dbuser, '"') ?>"
dbpass="<?= addcslashes($dbpass, '"') ?>"
dbname="<?= addcslashes($dbname, '"') ?>"
tblpfx="<?= addcslashes($tblpfx, '"') ?>"
dbkey="<?= addcslashes($dbkey, '"') ?>"
dbcert="<?= addcslashes($dbcert, '"') ?>"
dbca="<?= addcslashes($dbca, '"') ?>"
dbverify="<?= addcslashes($dbverify, '"') ?>"
base_url="<?= addcslashes($baseurl, '"') ?>"
rewrite_urls="0"
