<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var Throwable $exception
 */

?>

<p>
    <?= I18N::translate('An unexpected database error occurred.') ?>
</p>

<pre><?= $exception->getMessage() ?></pre>

<pre><?= $exception->getTraceAsString() ?></pre>

<p>
    <?= I18N::translate('The webtrees developers would be very interested to learn about this error. If you contact them, they will help you resolve the problem.') ?>
</p>
