<?php

/**
 * webtrees: online genealogy
 * Copyright (C) 2026 webtrees development team
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace Fisharebest\Webtrees\Report;

use Fisharebest\Webtrees\TestCase;
use PHPUnit\Framework\Attributes\CoversClass;

#[CoversClass(ReportConfig::class)]
class ReportConfigTest extends TestCase
{
    public function testConstructorAssignsProperties(): void
    {
        $config = new ReportConfig(
            page_width:      612.0,
            page_height:     792.0,
            left_margin:     36.0,
            right_margin:    36.0,
            top_margin:      36.0,
            bottom_margin:   36.0,
            header_margin:   9.0,
            footer_margin:   9.0,
            orientation:     PageOrientation::Portrait,
            page_size:       PageSize::USLetter,
            show_generated_by: true,
            rtl:             false,
            generated_by:    'Generated by webtrees',
            author:          'Test Author',
            title:           'Test Report',
            description:     'A test report',
            align_rtl:       'right',
            entity_rtl:      'rlm',
            font:            'dejavusans',
        );

        self::assertSame(612.0, $config->page_width);
        self::assertSame(792.0, $config->page_height);
        self::assertSame(36.0, $config->left_margin);
        self::assertSame(36.0, $config->right_margin);
        self::assertSame(36.0, $config->top_margin);
        self::assertSame(36.0, $config->bottom_margin);
        self::assertSame(9.0, $config->header_margin);
        self::assertSame(9.0, $config->footer_margin);
        self::assertSame(PageOrientation::Portrait, $config->orientation);
        self::assertSame(PageSize::USLetter, $config->page_size);
        self::assertTrue($config->show_generated_by);
        self::assertFalse($config->rtl);
        self::assertSame('Generated by webtrees', $config->generated_by);
        self::assertSame('Test Author', $config->author);
        self::assertSame('Test Report', $config->title);
        self::assertSame('A test report', $config->description);
        self::assertSame('right', $config->align_rtl);
        self::assertSame('rlm', $config->entity_rtl);
        self::assertSame('dejavusans', $config->font);
    }
}
