<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var Tree $tree
 * @var bool $uses_analytics
 */

?>

<div class="wt-footer wt-footer-privacy-policy text-center my-2">
    <a href="<?= e(route('module', ['module' => 'privacy-policy', 'action' => 'Page', 'tree' => $tree->name()])) ?>">
        <?= I18N::translate('Privacy policy') ?>
    </a>

    <?php if ($uses_analytics) : ?>
        <div class="alert alert-info alert-dismissible fade collapse mb-0" id="privacy-warning" data-wt-cookie-warning data-wt-cookie-warning-key="cookie-warning">
            <?= I18N::translate('This website uses cookies to learn about visitor behavior.') ?>

            <button type="button" id="privacy-warning-button" class="btn-close" data-wt-cookie-warning-dismiss data-bs-dismiss="alert" aria-label="<?= I18N::translate('close') ?>">
            </button>
        </div>
    <?php endif ?>
</div>


