<?php

use Fisharebest\Webtrees\Functions\FunctionsEdit;
use Fisharebest\Webtrees\I18N;

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" class="wt-page-options wt-page-options-pedigreemap-chart d-print-none">
    <?= csrf_field() ?>

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="xref">
            <?= I18N::translate('Individual') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select-individual', ['name' => 'xref', 'individual' => $individual, 'tree' => $tree, 'required' => true]) ?>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="generations">
            <?= I18N::translate('Generations') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select', ['name' => 'generations', 'selected' => $generations, 'options' => FunctionsEdit::numericOptions(range(2, $maxgenerations))]) ?>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-3 wt-page-options-label"></div>
        <div class="col-sm-9 wt-page-options-value">
            <input class="btn btn-primary" type="submit" value="<?= /* I18N: A button label. */
            I18N::translate('view')
            ?>">
        </div>
    </div>
</form>


<div class="wt-ajax-load wt-page-content">
    <?= $map ?>
</div>

