<?php use Fisharebest\Webtrees\I18N; ?>
<?php use Fisharebest\Webtrees\View; ?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<form class="wt-page-options wt-page-options-relationships-chart d-print-none">
    <input type="hidden" name="route" value="module">
    <input type="hidden" name="module" value="<?= e($module_name) ?>">
    <input type="hidden" name="action" value="Chart">
    <input type="hidden" name="ged" value="<?= e($tree->name()) ?>">

    <div class="row form-group">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="xref">
            <?= I18N::translate('Individual 1') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select-individual', ['name' => 'xref', 'individual' => $individual1, 'tree' => $tree]) ?>
            <button class="btn btn-link small" id="btn-swap-individuals" type="button">
                <?= /* I18N: Reverse the order of two individuals */
                I18N::translate('Swap individuals') ?>
            </button>
        </div>
    </div>

    <div class="row form-group">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="xref2">
            <?= I18N::translate('Individual 2') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select-individual', ['name' => 'xref2', 'individual' => $individual2, 'tree' => $tree]) ?>
        </div>
    </div>

    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3 wt-page-options-label">
            </legend>
            <div class="col-sm-9 wt-page-options-value">
                <?php if ($ancestors_only) : ?>
                    <input type="hidden" name="ancestors" value="1">
                    <?= I18N::translate('Find relationships via ancestors') ?>
                <?php else : ?>
                    <?= view('components/radios', ['name' => 'ancestors', 'options' => $ancestors_options, 'selected' => $ancestors]) ?>
                <?php endif ?>
            </div>
        </div>
    </fieldset>

    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-3 wt-page-options-label">
            </legend>
            <div class="col-sm-9 wt-page-options-value">
                <?php if ($max_recursion === 0) : ?>
                    <?= I18N::translate('Find the closest relationships') ?>
                    <input type="hidden" name="recursion" value="0">
                <?php else : ?>
                    <?= view('components/radios', ['name' => 'recursion', 'options' => $recursion_options, 'selected' => $recursion]) ?>
                <?php endif ?>
            </div>
        </div>
    </fieldset>

    <div class="row form-group">
        <div class="col-form-label col-sm-3 wt-page-options-label"></div>
        <div class="col-sm-9 wt-page-options-value">
            <input class="btn btn-primary" type="submit" value="<?= /* I18N: A button label. */
            I18N::translate('view') ?>">
        </div>
    </div>
</form>

<?php if ($individual1 !== null && $individual2 !== null) : ?>
    <div class="wt-ajax-load wt-page-content wt-chart wt-chart-relationships" data-ajax-url="<?= e($ajax_url) ?>"></div>
<?php endif ?>

<?php View::push('javascript') ?>
<script>
  $('#btn-swap-individuals').click(function () {
    // Swap the (hidden) options of the select
    var select1       = document.querySelector('#xref');
    var select2       = document.querySelector('#xref2');
    var tmp_html      = select1.innerHTML;
    select1.innerHTML = select2.innerHTML;
    select2.innerHTML = tmp_html;

    // Also swap the select2 element
    var span1       = document.querySelector('#xref + span');
    var span2       = document.querySelector('#xref2 + span');
    var tmp_html    = span1.innerHTML;
    span1.innerHTML = span2.innerHTML.replace('xref2', 'xref');
    span2.innerHTML = tmp_html.replace('xref', 'xref2');
  });
</script>
<?php View::endpush() ?>
