<?php

use Fisharebest\Webtrees\Http\RequestHandlers\AddMediaFileAction;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Tree;

/**
 * @var string               $max_upload_size
 * @var Media                $media
 * @var Tree                 $tree
 * @var array<string,string> $unused_files
 */

?>

<form method="post" action="<?= e(route(AddMediaFileAction::class, ['xref' => $media->xref(), 'tree' => $media->tree()->name()])) ?>" enctype="multipart/form-data">
    <?= csrf_field() ?>

    <?= view('modals/header', ['title' => I18N::translate('Add a media file')]) ?>

    <div class="modal-body">
        <?= view('modals/media-file-fields', ['max_upload_size' => $max_upload_size, 'unused_files' => $unused_files, 'media_file' => null, 'tree' => $tree]) ?>
    </div>

    <?= view('modals/footer-save-cancel') ?>
</form>
