<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\Controllers\CreateNote;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var Tree $tree
 */

?>

<form method="post" action="<?= e(route(CreateNote::class, ['tree' => $tree->name()])) ?>" id="wt-modal-form" data-wt-modal-submit>
    <?= view('modals/header', ['title' => I18N::translate('Create a shared note')]) ?>

    <div class="modal-body">
        <?= view('modals/note-object-fields') ?>
    </div>

    <?= view('modals/footer-save-cancel') ?>

    <?= csrf_field() ?>
</form>
