<?php use Fisharebest\Webtrees\I18N; ?>

<form method="post" action="<?= e(route('link-media-to-record')) ?>" id="wt-modal-form">
    <?= csrf_field() ?>
    <input type="hidden" name="ged" value="<?= e($tree->name()) ?>">
    <input type="hidden" name="xref" value="<?= e($media->xref()) ?>">

    <?= view('modals/header', ['title' => I18N::translate('Link this media object to a source')]) ?>

    <div class="modal-body">
        <div class="form-group">
            <label class="col-form-label" for="link">
                <?= I18N::translate('Source') ?>
            </label>
            <?= view('components/select-source', ['name' => 'link', 'tree' => $tree]) ?>
        </div>
    </div>

    <?= view('modals/footer-save-cancel') ?>
</form>

