<?php

use Fisharebest\Webtrees\I18N;

?>

<div class="row form-group">
    <label class="col-form-label col-sm-2" for="restriction">
        <?= /* I18N: a restriction on viewing data */ I18N::translate('Restriction') ?>
    </label>
    <div class="col-sm-10">
        <select class="form-control" id="restriction" name="restriction">
            <option value="">&nbsp;</option>
            <option value="none">
                <?= I18N::translate('Show to visitors') ?>
            </option>
            <option value="privacy">
                <?= I18N::translate('Show to members') ?>
            </option>
            <option value="confidential">
                <?= I18N::translate('Show to managers') ?>
            </option>
            <option value="locked">
                <?= I18N::translate('Only managers can edit') ?>
            </option>
        </select>
    </div>
</div>
