<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

?>

<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="restriction">
        <?= /* I18N: a restriction on viewing data */ I18N::translate('Restriction') ?>
    </label>
    <div class="col-sm-10">
        <select class="form-select" id="restriction" name="restriction">
            <option value="">&nbsp;</option>
            <option value="NONE">
                <?= I18N::translate('Show to visitors') ?>
            </option>
            <option value="PRIVACY">
                <?= I18N::translate('Show to members') ?>
            </option>
            <option value="CONFIDENTIAL">
                <?= I18N::translate('Show to managers') ?>
            </option>
            <option value="LOCKED">
                <?= I18N::translate('Only managers can edit') ?>
            </option>
        </select>
    </div>
</div>
