<?php

use Illuminate\Support\Collection;

/**
 * @var Collection<int,string> $shares
 * @var string                 $title
 */

?>
<div class="modal fade" id="wt-shares-modal" tabindex="-1" role="dialog" aria-label="<?= e($title) ?>" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <?= view('modals/header', ['title' => $title]) ?>

            <div class="modal-body">
                <div class="wt-share-list">
                    <?php foreach ($shares as $share) : ?>
                        <div class="wt-share-item">
                            <?= $share ?>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>

            <?= view('modals/footer-close') ?>
        </div>
    </div>
</div>
