<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var Tree $tree
 */

?>

<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="title">
        <?= I18N::translate('Title') ?>
    </label>
    <div class="col-sm-10">
        <input class="form-control" type="text" id="title" name="title" required="required">
    </div>
</div>
<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="abbreviation">
        <?= I18N::translate('Abbreviation') ?>
    </label>
    <div class="col-sm-10">
        <input class="form-control" type="text" id="abbreviation" name="abbreviation">
    </div>
</div>
<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="author">
        <?= I18N::translate('Author') ?>
    </label>
    <div class="col-sm-4">
        <input class="form-control" type="text" id="author" name="author">
    </div>
    <label class="col-form-label col-sm-2" for="publication">
        <?= I18N::translate('Publication') ?>
    </label>
    <div class="col-sm-4">
        <input class="form-control" type="text" id="publication" name="publication">
    </div>
</div>
<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="repository">
        <?= I18N::translate('Repository') ?>
    </label>
    <div class="col-sm-4">
        <?= view('components/select-repository', ['name' => 'repository', 'tree' => $tree]) ?>
    </div>
    <label class="col-form-label col-sm-2" for="call_number">
        <?= I18N::translate('Call number') ?>
    </label>
    <div class="col-sm-4">
        <input class="form-control" type="text" id="call_number" name="call_number">
    </div>
</div>
<div class="row mb-3">
    <label class="col-form-label col-sm-2" for="text">
        <?= I18N::translate('Text') ?>
    </label>
    <div class="col-sm-10">
        <textarea class="form-control" id="text" name="text" rows="5"></textarea>
    </div>
</div>

<?= view('modals/restriction-fields') ?>
