<?php
declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

$id = 'google-chart-' . bin2hex(random_bytes(8));
?>

<?php if (count($data) === 1): ?>
    <?= I18N::translate('This information is not available.'); ?>
<?php else: ?>
    <?= view('statistics/other/chart-setup') ?>

    <div id="<?= $id ?>" title="<?= $chart_title ?>"></div>

    <script>

    var callbackComboChart = function () {
        var options = {
            title: '<?= $chart_title ?? '' ?>',
            subtitle: '<?= $chart_sub_title ?? '' ?>',
            vAxis: {
                title: '<?= $vAxis_title ?? '' ?>'
            },
            hAxis: {
                title: '<?= $hAxis_title ?? '' ?>'
            },
            colors: <?= json_encode($colors) ?>
        };

        google.charts.setOnLoadCallback(function () {
            drawComboChart(
                '<?= $id ?>',
                <?= json_encode($data) ?>,
                options
            );
        });

        $(window).resize(function () {
            drawComboChart(
                '<?= $id ?>',
                <?= json_encode($data) ?>,
                options
            );
        });
    };

    if (
        document.readyState === "complete" ||
        (document.readyState !== "loading" && !document.documentElement.doScroll)
    ) {
        callbackComboChart();
    } else {
        document.addEventListener("DOMContentLoaded", callbackComboChart);
    }

    </script>
<?php endif; ?>
