<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Charts\BarChartData;
use Fisharebest\Webtrees\I18N;

/**
 * @var BarChartData         $chart_data
 * @var array<string,mixed>  $chart_options
 * @var string               $chart_title
 * @var string               $language
 */

?>

<?php if (!$chart_data->hasData()) : ?>
    <?= I18N::translate('This information is not available.') ?>
<?php else : ?>
    <div class="d-grid mb-3">
        <div class="card">
            <div class="card-header">
                <?= $chart_title ?>
            </div>
            <div class="card-body">
                <?= view('statistics/other/charts/column', [
                    'chart_data'    => $chart_data,
                    'chart_options' => $chart_options,
                    'chart_title'   => '',
                    'language'      => $language,
                ]) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
