<?php use Fisharebest\Webtrees\I18N; ?>
<?php use Fisharebest\Webtrees\Site; ?>

<?= view('components/breadcrumbs', ['links' => [route('admin-control-panel') => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<p>
    <?= I18N::translate('If you use one of the following tracking and analytics services, webtrees can add the tracking codes automatically.') ?>
</p>

<p>
    <?= I18N::translate('Tracking and analytics are not added to the control panel.') ?>
</p>

<p>
    <?= I18N::translate('Site verification codes do not work when webtrees is installed in a subfolder.') ?>
</p>

<?php foreach ($modules as $module) : ?>
    <h2>
        <?= e($module->title()) ?>
    </h2>

    <p>
        <a class="btn btn-link" href="<?= e(route('analytics-edit', ['module' => $module->name()])) ?>">
            <?= view('icons/preferences') ?>
            <?= I18N::translate('Preferences') ?>
        </a>

        <a class="btn btn-link" href="<?= e($module->analyticsHomePageUrl()) ?>">
            <?= view('icons/information') ?>
            <?= e($module->analyticsHomePageUrl()) ?>
        </a>
    </p>
<?php endforeach ?>
