<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Statistics;

/** @var Statistics $stats */
?>

<h4 class="border-bottom p-2 mb-4">
    <?= I18N::translate('Sources') ?>
</h4>

<div class="row row-cols-1 row-cols-lg-2 g-3 mb-3">
    <div class="col">
        <div class="card">
            <h5 class="card-header">
                <?= I18N::translate('Individuals with sources') ?>
                <span class="badge bg-secondary rounded-pill float-end"><?= $stats->totalIndisWithSources() ?></span>
            </h5>
            <div class="card-body">
                <?= $stats->chartIndisWithSources() ?>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card">
            <h5 class="card-header">
                <?= I18N::translate('Families with sources') ?>
                <span class="badge bg-secondary rounded-pill float-end"><?= $stats->totalFamsWithSources() ?></span>
            </h5>
            <div class="card-body">
                <?= $stats->chartFamsWithSources() ?>
            </div>
        </div>
    </div>
</div>
