<?php
declare(strict_types=1);

use Fisharebest\Webtrees\View;
?>

<?php View::push('javascript') ?>
<script src="https://www.gstatic.com/charts/loader.js"></script>
<script>

google.charts.load(
    'current',
    {
        'packages': [
            'corechart',
            'geochart',
            'bar'
        ],
        // Note: you will need to get a mapsApiKey for your project.
        // See: https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings
        'mapsApiKey': ''
    }
);

</script>
<?php View::endpush() ?>
