<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Statistics;

/** @var Statistics $stats */
?>

<h4 class="border-bottom p-2 mb-4">
    <?= I18N::translate('Sources') ?>
</h4>

<div class="mb-3">
    <div class="card-deck">
        <div class="col-12 col-lg-6 mb-3">
            <div class="card m-0">
                <h5 class="card-header">
                    <?= I18N::translate('Individuals with sources') ?>
                    <span class="badge badge-secondary badge-pill float-right"><?= $stats->totalIndisWithSources() ?></span>
                </h5>
                <div class="card-body">
                    <?= $stats->chartIndisWithSources() ?>
                </div>
            </div>
        </div>

        <div class="col-12 col-lg-6 mb-3">
            <div class="card m-0">
                <h5 class="card-header">
                    <?= I18N::translate('Families with sources') ?>
                    <span class="badge badge-secondary badge-pill float-right"><?= $stats->totalFamsWithSources() ?></span>
                </h5>
                <div class="card-body">
                    <?= $stats->chartFamsWithSources() ?>
                </div>
            </div>
        </div>
    </div>
</div>
