<?php
declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Place;

/** @var \Fisharebest\Webtrees\Stats $stats */
?>

<h4 class="border-bottom p-2 mb-4">
    <?= I18N::translate('Places') ?>
    <span class="badge badge-secondary badge-pill float-right"><?= $stats->totalPlaces() ?></span>
</h4>

<div class="card-deck mb-3">
    <div class="col-lg-6 col-md-6 mb-3">
        <div class="card m-0">
            <h5 class="card-header">
                <?= I18N::translate('Birth places') ?>
            </h5>
            <ul class="list-group list-group-flush">
                <?php $places = $stats->commonBirthPlacesList(); ?>
                <?php foreach ($places as $entry): ?>
                    <?php
                        /* @var Place $place */
                        $place = $entry['place'];
                    ?>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="<?= e($place->url()) ?>"><?= $place->getFullName() ?></a>
                        <span class="badge badge-secondary badge-pill ml-3"><?= I18N::number($entry['count']) ?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <div class="col-lg-6 col-md-6 mb-3">
        <div class="card m-0">
            <h5 class="card-header">
                <?= I18N::translate('Death places') ?>
            </h5>
            <ul class="list-group list-group-flush">
                <?php $places = $stats->commonDeathPlacesList(); ?>
                <?php foreach ($places as $entry): ?>
                    <?php
                    /* @var Place $place */
                    $place = $entry['place'];
                    ?>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="<?= e($place->url()) ?>"><?= $place->getFullName() ?></a>
                        <span class="badge badge-secondary badge-pill ml-3"><?= I18N::number($entry['count']) ?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <div class="col-lg-6 col-md-6 mb-3">
        <div class="card m-0">
            <h5 class="card-header">
                <?= I18N::translate('Marriage places') ?>
            </h5>
            <ul class="list-group list-group-flush">
                <?php $places = $stats->commonMarriagePlacesList(); ?>
                <?php foreach ($places as $entry): ?>
                    <?php
                    /* @var Place $place */
                    $place = $entry['place'];
                    ?>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="<?= e($place->url()) ?>"><?= $place->getFullName() ?></a>
                        <span class="badge badge-secondary badge-pill ml-3"><?= I18N::number($entry['count']) ?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <div class="col-lg-6 col-md-6 mb-3">
        <div class="card m-0">
            <h5 class="card-header">
                <?= I18N::translate('Events in countries') ?>
            </h5>
            <ul class="list-group list-group-flush">
                <?php $places = $stats->commonCountriesList(); ?>
                <?php foreach ($places as $entry): ?>
                    <?php
                    /* @var Place $place */
                    $place = $entry['place'];
                    ?>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="<?= e($place->url()) ?>"><?= $entry['name'] ?></a>
                        <span class="badge badge-secondary badge-pill ml-3"><?= I18N::number($entry['count']) ?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
