<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Place;

/**
 * @var array<array{count:int,place:Place}> $records
 */
?>

<?php if ($records !== []) : ?>
    <ul class="list-group list-group-flush">
        <?php foreach ($records as $record) : ?>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <?= $record['place']->fullName(true) ?>
                <span class="badge bg-secondary rounded-pill ms-3"><?= I18N::number($record['count']) ?></span>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else : ?>
    <div class="card-body">
        <?= I18N::translate('This information is not available.') ?>
    </div>
<?php endif; ?>
