<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Statistics;

/** @var Statistics $stats */
?>

<h4 class="border-bottom p-2 mb-4">
    <?= I18N::translate('Records') ?>
    <span class="badge bg-secondary rounded-pill float-end"><?= $stats->totalRecords() ?></span>
</h4>

<div class="row row-cols-1 row-cols-lg-2 g-3 mb-3">
    <div class="col">
        <div class="card">
            <h5 class="card-header border-bottom-0">
                <?= I18N::translate('Media objects') ?>
                <span class="badge bg-secondary rounded-pill float-end"><?= $stats->totalMedia() ?></span>
            </h5>
        </div>
    </div>

    <div class="col">
        <div class="card">
            <h5 class="card-header border-bottom-0">
                <?= I18N::translate('Sources') ?>
                <span class="badge bg-secondary rounded-pill float-end"><?= $stats->totalSources() ?></span>
            </h5>
        </div>
    </div>

    <div class="col">
        <div class="card">
            <h5 class="card-header border-bottom-0">
                <?= I18N::translate('Notes') ?>
                <span class="badge bg-secondary rounded-pill float-end"><?= $stats->totalNotes() ?></span>
            </h5>
        </div>
    </div>

    <div class="col">
        <div class="card">
            <h5 class="card-header border-bottom-0">
                <?= I18N::translate('Repositories') ?>
                <span class="badge bg-secondary rounded-pill float-end"><?= $stats->totalRepositories() ?></span>
            </h5>
        </div>
    </div>
</div>
