<?php
use Fisharebest\Webtrees\Http\RequestHandlers\Logout;
use Fisharebest\Webtrees\I18N;
?>

<p>
<?= I18N::translate('You are signed in as %s.', e($user->userName())) ?>
</p>

<form method="post" action="<?= e(route(Logout::class)) ?>">
    <?= csrf_field() ?>

    <button type="submit" class="btn btn-primary">
        <?= /* I18N: A button label. */ I18N::translate('sign out') ?>
    </button>
</form>
