<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Illuminate\Support\Collection;

/**
 * @var bool                 $can_edit
 * @var Collection<int,Fact> $clipboard_facts
 * @var Collection<int,Fact> $facts
 * @var bool                 $has_associate_facts
 * @var bool                 $has_historic_facts
 * @var bool                 $has_relative_facts
 * @var Individual           $individual
 */

?>

<div class="container py-4">
    <?php if ($has_associate_facts || $has_relative_facts || $has_historic_facts) : ?>
        <div class="row wt-fact-content py-1">
            <?php if ($has_associate_facts) : ?>
                <div class="col-sm-auto">
                    <label>
                        <input id="show-associate-facts" type="checkbox" data-bs-toggle="collapse" data-bs-target=".wt-associate-fact" data-wt-persist="associates" autocomplete="off">
                        <?= I18N::translate('Associated events') ?>
                    </label>
                </div>
            <?php endif ?>

            <?php if ($has_relative_facts) : ?>
                <div class="col-sm-auto">
                    <label>
                        <input id="show-relatives-facts" type="checkbox" data-bs-toggle="collapse" data-bs-target=".wt-relation-fact" data-wt-persist="relatives" autocomplete="off">
                        <?= I18N::translate('Events of close relatives') ?>
                    </label>
                </div>
            <?php endif ?>

            <?php if ($has_historic_facts) : ?>
                <div class="col-sm-auto">
                    <label>
                        <input id="show-historical-facts" type="checkbox" data-bs-toggle="collapse" data-bs-target=".wt-historic-fact" data-wt-persist="historic-facts" autocomplete="off">
                        <?= I18N::translate('Historic events') ?>
                    </label>
                </div>
            <?php endif ?>
        </div>
    <?php endif ?>

    <?php foreach ($facts as $fact) : ?>
        <?= view('fact', ['fact' => $fact, 'record' => $individual]) ?>
    <?php endforeach ?>

    <?php if (!$has_individual_facts) : ?>
        <div class="row wt-fact-content my-3">
            <div class="col-sm-auto py-2">
                <?= I18N::translate('There are no facts for this individual.') ?>
            </div>
        </div>
    <?php endif ?>

    <?php if ($individual->canEdit()) : ?>
        <?= view('fact-add-new', ['record' => $individual]) ?>
    <?php endif ?>
</div>
