<?php

use Fisharebest\Webtrees\Location;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var Collection<Location> $locations
 * @var string               $title
 * @var Tree                 $tree
 */

?>
<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<div class="wt-page-content">
    <?= view('lists/locations-table', ['locations' => $locations, 'tree' => $tree]) ?>
</div>
