<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\I18N;

/**
 * @var string        $base_url
 * @var UserInterface $user
 */

?>
<?= I18N::translate('Hello %s…', $user->realName()) ?>

<?= I18N::translate('The administrator at the webtrees site %s has approved your application for an account. You may now sign in by accessing the following link: %s', $base_url, $base_url) ?>
