<?php

use Fisharebest\Webtrees\I18N;

?>
<?= I18N::translate('Hello %s…', $recipient->realName()) ?>

<?= /* I18N: %s is a person's name */ I18N::translate('%s sent you the following message.', $sender->realName()) ?>

------------------------------------------------------------
<?= $message ?>

------------------------------------------------------------

<?php if ($url !== '') : ?>
    <?= I18N::translate('This message was sent while viewing the following URL: ') ?>
    <?= $url ?>
<?php endif ?>
