<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\I18N;

/**
 * @var string        $message
 * @var UserInterface $recipient
 * @var UserInterface $sender
 * @var string        $url
 */

?>
<?= I18N::translate('Hello %s…', $recipient->realName()) ?>

<?= /* I18N: %s is a person's name */ I18N::translate('%s sent you the following message.', I18N::translate('%1$s (%2$s)', $sender->realName(), $sender->email())) ?>

------------------------------------------------------------
<?= $message ?>

------------------------------------------------------------

<?php if ($url !== '') : ?>
    <?= I18N::translate('This message was sent while viewing the following URL: ') ?>
    <?= $url ?>
<?php endif ?>
