<?php

use Fisharebest\Webtrees\I18N;

?>
<?= I18N::translate('Hello %s…', $sender->realName()) ?>

<?= I18N::translate('You sent the following message to a webtrees user:') ?><?= $recipient->realName() ?>

------------------------------------------------------------
<?= $message ?>
------------------------------------------------------------

<?php if ($url !== '') : ?>
    <?= I18N::translate('This message was sent while viewing the following URL: ') ?>
    <?= $url ?>
<?php endif ?>
