<?php

use Fisharebest\Webtrees\I18N;

?>
<div dir="<?= I18N::locale()->direction() ?>" lang="<?= I18N::locale()->languageTag() ?>">
    <p>
        <?= I18N::translate('Hello %s…', '<span dir="auto">' . e($recipient->realName()) . '</span>') ?>
    </p>

    <p>
        <?= /* I18N: %s is a person's name */
        I18N::translate('%1$s (%2$s) sent you the following message.', e($sender->realName()), e($sender->email())) ?>
    </p>

    <hr>

    <p>
        <?= nl2br(e($message), false) ?>
    </p>

    <hr>

    <?php if ($url !== '') : ?>
        <p>
            <?= I18N::translate('This message was sent while viewing the following URL: ') ?>
            <?= e($url) ?>
        </p>
    <?php endif ?>
</div>
