<?php

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\I18N;

/**
 * @var string        $message
 * @var UserInterface $recipient
 * @var UserInterface $sender
 * @var string        $url
 */

?>
<?= I18N::translate('Hello %s…', $recipient->realName()) ?>

<?= /* I18N: %1$s is a person's name, %2$s an email address */ I18N::translate('%1$s (%2$s) sent you the following message.', $sender->realName(), $sender->email()) ?>

------------------------------------------------------------
<?= $message ?>

------------------------------------------------------------

<?php if ($url !== '') : ?>
    <?= I18N::translate('This message was sent while viewing the following URL: ') ?>
    <?= $url ?>
<?php endif ?>
