<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\I18N;

/**
 * @var string        $message
 * @var UserInterface $recipient
 * @var UserInterface $sender
 * @var string        $url
 */

?>
<?= I18N::translate('Hello %s…', $sender->realName()) ?>

<?= I18N::translate('You sent the following message to a webtrees user:') ?><?= $recipient->realName() ?>

------------------------------------------------------------
<?= $message ?>
------------------------------------------------------------

<?php if ($url !== '') : ?>
    <?= I18N::translate('This message was sent while viewing the following URL: ') ?>
    <?= $url ?>
<?php endif ?>
