<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\I18N;

/**
 * @var string        $latest_version
 * @var UserInterface $recipient
 * @var string        $url
 */

?>

<div dir="<?= I18N::locale()->direction() ?>" lang="<?= I18N::locale()->languageTag() ?>">
    <p>
        <?= I18N::translate('Hello %s…', '<bdi>' . e($recipient->realName()) . '</bdi>') ?>
    </p>

    <p>
        <?= I18N::translate('A new version of webtrees is available.') ?>  <?= e($latest_version) ?>
    </p>

    <p>
        <?= I18N::translate('See %s for more information.', '<a href="https://webtrees.net">webtrees.net</a>') ?>
    </p>

    <p>
        <?= $url ?>
    </p>
</div>
