<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\I18N;

/**
 * @var string        $url
 * @var UserInterface $user
 * @var string        $base_url
 */

?>
<?= I18N::translate('Hello %s…', e($user->realName())) ?>

<?= I18N::translate('To set a new password, follow this link.') ?>

<a href="<?= e($url) ?>"><?= e($url) ?></a>

<?= I18N::translate('If you did not request a new password, please ignore this message.') ?>

<?= I18N::translate('If you received this message in error, you can stop any further emails here:') ?>

<?= $base_url ?>
