<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\I18N;

/**
 * @var string        $url
 * @var UserInterface $user
 */

?>
<div dir="<?= I18N::textDirection()->value ?>" lang="<?= I18N::languageTag() ?>">
    <p>
        <?= I18N::translate('Hello %s…', '<bdi>' . e($user->realName()) . '</bdi>') ?>
    </p>

    <p>
        <?= I18N::translate('To set a new password, follow this link.') ?>
    </p>

    <p>
        <a href="<?= e($url) ?>"><?= e($url) ?></a>
    </p>

    <p>
        <?= I18N::translate('If you did not request a new password, please ignore this message.') ?>
    </p>
</div>
