<?php

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\I18N;

/**
 * @var string        $url
 * @var UserInterface $user
 */

?>
<div dir="<?= I18N::locale()->direction() ?>" lang="<?= I18N::locale()->languageTag() ?>">
    <p>
        <?= I18N::translate('Hello %s…', '<span dir="auto">' . e($user->realName()) . '</span>') ?>
    </p>

    <p>
        <?= I18N::translate('To set a new password, follow this link.') ?>
    </p>

    <p>
        <a href="<?= e($url) ?>"><?= e($url) ?></a>
    </p>

    <p>
        <?= I18N::translate('If you did not request a new password, please ignore this message.') ?>
    </p>
</div>
