<?php

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\Http\RequestHandlers\PendingChanges;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var Tree $tree
 * @var UserInterface $user
 */

?>
<div dir="<?= I18N::locale()->direction() ?>" lang="<?= I18N::locale()->languageTag() ?>">
    <p>
        <?= I18N::translate('Hello %s…', '<bdi>' . e($user->realName()) . '</bdi>') ?>
    </p>

    <p>
        <?= I18N::translate('There are pending changes for you to moderate.') ?>
    </p>

    <ul>
        <li>
            <a href="<?= e(route(PendingChanges::class, ['tree' => $tree->name()])) ?>">
                <?= e($tree->title()) ?>
            </a>
        </li>
    </ul>
</div>
