<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\Http\RequestHandlers\PendingChanges;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var Tree $tree
 * @var UserInterface $user
*/

?>

<?= I18N::translate('Hello %s…', $user->realName()) ?>

<?= I18N::translate('There are pending changes for you to moderate.') ?>

<?= $tree->title() ?> - <?= route(PendingChanges::class, ['tree' => $tree->name()]) ?>
