<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var string        $base_url
 * @var string        $comments
 * @var Tree|null     $tree
 * @var UserInterface $user
 */

?>
<?= I18N::translate('Hello administrator…') ?>

<?= /* I18N: %s is a server name/URL */
I18N::translate('A prospective user has registered with webtrees at %s.', $base_url) ?>

<?= I18N::translate('Username') ?> - <?= e($user->userName()) ?>

<?= I18N::translate('Real name') ?> - <?= e($user->realName()) ?>

<?= I18N::translate('Email address') ?> - <?= e($user->email()) ?>

<?= I18N::translate('Comments') ?> - <?= e($comments) ?>

<?= I18N::translate('Tree') ?> - <?= e($tree instanceof Tree ? $tree->name() : '') ?>

<?= I18N::translate('The user has been sent an email with the information necessary to confirm the access request.') ?>

<?= I18N::translate('You will be informed by email when this prospective user has confirmed the request. You can then complete the process by activating the username. The new user will not be able to sign in until you activate the account.') ?>
