<?php

use Fisharebest\Webtrees\Http\RequestHandlers\VerifyEmail;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\User;

?>
<div dir="<?= I18N::locale()->direction() ?>" lang="<?= I18N::locale()->languageTag() ?>">
    <p>
        <?= I18N::translate('Hello %s…', e($user->realName())) ?>
    </p>

    <p>
        <?= /* I18N: %1$s is the site URL and %2$s is an email address */
        I18N::translate('You (or someone claiming to be you) has requested an account at %1$s using the email address %2$s.', e($base_url), e($user->email())) ?>
    </p>

    <p>
        <?= I18N::translate('Follow this link to verify your email address.') ?>
    </p>

    <p>
        <a href="<?= e(route(VerifyEmail::class, ['username' => $user->userName(), 'token' => $user->getPreference(User::PREF_VERIFICATION_TOKEN), 'tree' => $tree instanceof Tree ? $tree->name() : null])) ?>">
            <?= e(route(VerifyEmail::class, ['username' => $user->userName(), 'token' => $user->getPreference(User::PREF_VERIFICATION_TOKEN), 'tree' => $tree instanceof Tree ? $tree->name() : null])) ?>
        </a>
    </p>

    <p>
        <?= I18N::translate('If you didn’t request an account, you can just delete this message.') ?>
    </p>
</div>
