<?php

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\I18N;

/**
 * @var string        $base_url
 * @var UserInterface $user
 * @var string        $verify_url
 */

?>

<?= I18N::translate('Hello %s…', $user->realName()) ?>

<?= /* I18N: %1$s is the site URL and %2$s is an email address */I18N::translate('You (or someone claiming to be you) has requested an account at %1$s using the email address %2$s.', $base_url, $user->email()) ?>

<?= I18N::translate('Follow this link to verify your email address.') ?>

<?= $verify_url ?>

<?= I18N::translate('If you didn’t request an account, you can just delete this message.');
