<?php

use Fisharebest\Webtrees\I18N;

?>
<div dir="<?= I18N::locale()->direction() ?>" lang="<?= I18N::locale()->languageTag() ?>">
    <p>
        <?= I18N::translate('Hello %s…', e($user->realName())) ?>
    </p>

    <p>
        <?= /* I18N: %1$s is the site URL and %2$s is an email address */
        I18N::translate('You (or someone claiming to be you) has requested an account at %1$s using the email address %2$s.', e($base_url), e($user->email())) ?>
    </p>

    <p>
        <?= I18N::translate('Follow this link to verify your email address.') ?>
    </p>

    <p>
        <a href="<?= e($verify_url) ?>">
            <?= e($verify_url) ?>
        </a>
    </p>

    <p>
        <?= I18N::translate('If you didn’t request an account, you can just delete this message.') ?>
    </p>
</div>
