<?php
/**
 * Application configuration data.  Data here has no GUI to edit it,
 * although most of it can be altered to customise local installations.
 *
 * NOTE: The one-item-per-line and extra-comma-after-last-item approach
 * is used to allow SVN to reliably merge changes for users that have
 * customised their local copy of this file.
 *
 * webtrees: Web based Family History software
 * Copyright (C) 2010 webtrees development team.
 *
 * Derived from PhpGedView
 * Copyright (C) 2010 PGV Development Team.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @version $Id$
 */

if (!defined('WT_WEBTREES')) {
	header('HTTP/1.0 403 Forbidden');
	exit;
}

define('WT_CONFIG_DATA_PHP', '');

// Unknown surname in various scripts
// TODO: This is extremely poor I18N - there is not a 1:1 correlation between script and language
$UNKNOWN_NN=array(
	'hebrew'    =>'(לא-ידוע)',
	'arabic'    =>'(غير معروف)',
	'greek'     =>'(άγνωστος/η)',
	'russian'   =>'(неопределено)',
	'cyrillic'  =>'(неопределено)',
	'han'       =>'(未知)',
	'latin'     =>WT_I18N::translate_c('surname', '(unknown)'),
	'common'    =>WT_I18N::translate_c('surname', '(unknown)'),
);

// Unknown givne name in various scripts
// TODO: This is extremely poor I18N - there is not a 1:1 correlation between script and language
$UNKNOWN_PN=array(
	'hebrew'    =>'(לא-ידוע)',
	'arabic'    =>'(غير معروف)',
	'greek'     =>'(άγνωστος/η)',
	'russian'   =>'(неопределено)',
	'cyrillic'   =>'(неопределено)',
	'han'       =>'(未知)',
	'latin'     =>WT_I18N::translate_c('given name', '(unknown)'),
	'common'    =>WT_I18N::translate_c('given name', '(unknown)'),
);

// Type attribute of a media object
$MEDIA_TYPES=array(
	'audio'      =>WT_I18N::translate('Audio'),
	'book'       =>WT_I18N::translate('Book'),
	'card'       =>WT_I18N::translate('Card'),
	'certificate'=>WT_I18N::translate('Certificate'),
	'coat'       =>WT_I18N::translate('Coat of Arms'),
	'document'   =>WT_I18N::translate('Document'),
	'electronic' =>WT_I18N::translate('Electronic'),
	'fiche'      =>WT_I18N::translate('Microfiche'),
	'film'       =>WT_I18N::translate('Microfilm'),
	'magazine'   =>WT_I18N::translate('Magazine'),
	'manuscript' =>WT_I18N::translate('Manuscript'),
	'map'        =>WT_I18N::translate('Map'),
	'newspaper'  =>WT_I18N::translate('Newspaper'),
	'photo'      =>WT_I18N::translate('Photo'),
	'tombstone'  =>WT_I18N::translate('Tombstone'),
	'video'      =>WT_I18N::translate('Video'),
	'painting'   =>WT_I18N::translate('Painting'),
	'other'      =>WT_I18N::translate('Other'),
);

// GEDCOM ADOP codes
$ADOP_CODES=array(
	'BOTH'=>WT_I18N::translate('Adopted by both parents'),
	'HUSB'=>WT_I18N::translate('Adopted by father'),
	'WIFE'=>WT_I18N::translate('Adopted by mother'),
);

// GEDCOM ADOP Female codes
$ADOP_CODES_F=array(
	'BOTH'=>WT_I18N::translate_c('FEMALE', 'Adopted by both parents'),
	'HUSB'=>WT_I18N::translate_c('FEMALE', 'Adopted by father'),
	'WIFE'=>WT_I18N::translate_c('FEMALE', 'Adopted by mother'),
);

// GEDCOM ADOP Male codes
$ADOP_CODES_M=array(
	'BOTH'=>WT_I18N::translate_c('MALE', 'Adopted by both parents'),
	'HUSB'=>WT_I18N::translate_c('MALE', 'Adopted by father'),
	'WIFE'=>WT_I18N::translate_c('MALE', 'Adopted by mother'),
);

// GEDCOM PEDI codes
$PEDI_CODES=array(
	'birth'  =>WT_I18N::translate_c('Pedigree', 'Birth'),
	'adopted'=>WT_I18N::translate_c('Pedigree', 'Adopted'),
	'foster' =>WT_I18N::translate_c('Pedigree', 'Foster'),
	'sealing'=>WT_I18N::translate_c('Pedigree', 'Sealing'),
);

// GEDCOM PEDI Female codes
$PEDI_CODES_F=array(
	'birth'  =>WT_I18N::translate_c('Female pedigree', 'Birth'),
	'adopted'=>WT_I18N::translate_c('Female pedigree', 'Adopted'),
	'foster' =>WT_I18N::translate_c('Female pedigree', 'Foster'),
	'sealing'=>WT_I18N::translate_c('Female pedigree', 'Sealing'),
);

// GEDCOM PEDI Male codes
$PEDI_CODES_M=array(
	'birth'  =>WT_I18N::translate_c('Male pedigree', 'Birth'),
	'adopted'=>WT_I18N::translate_c('Male pedigree', 'Adopted'),
	'foster' =>WT_I18N::translate_c('Male pedigree', 'Foster'),
	'sealing'=>WT_I18N::translate_c('Male pedigree', 'Sealing'),
);

// GEDCOM RELA codes for non-genealogical relationships.
// These aren't part of the standard, but we list the common ones here so we can translate them.
$RELA_CODES=array(
	'attendant'       =>WT_I18N::translate('Attendant'),
	'attending'       =>WT_I18N::translate('Attending'),
	'best_man'        =>WT_I18N::translate('Best Man'),
	'bridesmaid'      =>WT_I18N::translate('Bridesmaid'),
	'buyer'           =>WT_I18N::translate('Buyer'),
	'circumciser'     =>WT_I18N::translate('Circumciser'),
	'civil_registrar' =>WT_I18N::translate('Civil Registrar'),
	'employee'        =>WT_I18N::translate('Employee'),
	'employer'        =>WT_I18N::translate('Employer'),
	'foster_child'    =>WT_I18N::translate('Foster Child'),
	'foster_father'   =>WT_I18N::translate('Foster Father'),
	'foster_mother'   =>WT_I18N::translate('Foster Mother'),
	'friend'          =>WT_I18N::translate('Friend'),
	'godfather'       =>WT_I18N::translate('Godfather'),
	'godmother'       =>WT_I18N::translate('Godmother'),
	'godparent'       =>WT_I18N::translate('Godparent'),
	'godson'          =>WT_I18N::translate('Godson'),
	'goddaughter'     =>WT_I18N::translate('Goddaughter'),
	'godchild'        =>WT_I18N::translate('Godchild'),
	'guardian'        =>WT_I18N::translate('Guardian'),
	'informant'       =>WT_I18N::translate('Informant'),
	'lodger'          =>WT_I18N::translate('Lodger'),
	'nanny'           =>WT_I18N::translate('Nanny'),
	'nurse'           =>WT_I18N::translate('Nurse'),
	'owner'           =>WT_I18N::translate('Owner'),
	'priest'          =>WT_I18N::translate('Priest'),
	'rabbi'           =>WT_I18N::translate('Rabbi'),
	'registry_officer'=>WT_I18N::translate('Registry Officer'),
	'seller'          =>WT_I18N::translate('Seller'),
	'servant'         =>WT_I18N::translate('Servant'),
	'slave'           =>WT_I18N::translate('Slave'),
	'ward'            =>WT_I18N::translate('Ward'),
	'witness'         =>WT_I18N::translate('Witness'),
);

// GEDCOM RELA codes for non-genealogical relationships.
// These aren't part of the standard, but we list the common ones here so we can translate them.
$RELA_CODES_F=array(
	'attendant'       =>WT_I18N::translate_c('FEMALE', 'Attendant'),
	'attending'       =>WT_I18N::translate_c('FEMALE', 'Attending'),
	'buyer'           =>WT_I18N::translate_c('FEMALE', 'Buyer'),
	'civil_registrar' =>WT_I18N::translate_c('FEMALE', 'Civil Registrar'),
	'employee'        =>WT_I18N::translate_c('FEMALE', 'Employee'),
	'employer'        =>WT_I18N::translate_c('FEMALE', 'Employer'),
	'friend'          =>WT_I18N::translate_c('FEMALE', 'Friend'),
	'guardian'        =>WT_I18N::translate_c('FEMALE', 'Guardian'),
	'informant'       =>WT_I18N::translate_c('FEMALE', 'Informant'),
	'lodger'          =>WT_I18N::translate_c('FEMALE', 'Lodger'),
	'nurse'           =>WT_I18N::translate_c('FEMALE', 'Nurse'),
	'owner'           =>WT_I18N::translate_c('FEMALE', 'Owner'),
	'registry_officer'=>WT_I18N::translate_c('FEMALE', 'Registry Officer'),
	'seller'          =>WT_I18N::translate_c('FEMALE', 'Seller'),
	'servant'         =>WT_I18N::translate_c('FEMALE', 'Servant'),
	'slave'           =>WT_I18N::translate_c('FEMALE', 'Slave'),
	'ward'            =>WT_I18N::translate_c('FEMALE', 'Ward'),
);

// GEDCOM RELA codes for non-genealogical relationships.
// These aren't part of the standard, but we list the common ones here so we can translate them.
$RELA_CODES_M=array(
	'attendant'       =>WT_I18N::translate_c('MALE', 'Attendant'),
	'attending'       =>WT_I18N::translate_c('MALE', 'Attending'),
	'buyer'           =>WT_I18N::translate_c('MALE', 'Buyer'),
	'civil_registrar' =>WT_I18N::translate_c('MALE', 'Civil Registrar'),
	'employee'        =>WT_I18N::translate_c('MALE', 'Employee'),
	'employer'        =>WT_I18N::translate_c('MALE', 'Employer'),
	'friend'          =>WT_I18N::translate_c('MALE', 'Friend'),
	'guardian'        =>WT_I18N::translate_c('MALE', 'Guardian'),
	'informant'       =>WT_I18N::translate_c('MALE', 'Informant'),
	'lodger'          =>WT_I18N::translate_c('MALE', 'Lodger'),
	'nurse'           =>WT_I18N::translate_c('MALE', 'Nurse'),
	'owner'           =>WT_I18N::translate_c('MALE', 'Owner'),
	'registry_officer'=>WT_I18N::translate_c('MALE', 'Registry Officer'),
	'seller'          =>WT_I18N::translate_c('MALE', 'Seller'),
	'servant'         =>WT_I18N::translate_c('MALE', 'Servant'),
	'slave'           =>WT_I18N::translate_c('MALE', 'Slave'),
	'ward'            =>WT_I18N::translate_c('MALE', 'Ward'),
);

// NPFX tags - name prefixes
$NPFX_accept=array(
	'Adm',
	'Amb',
	'Brig',
	'Can',
	'Capt',
	'Chan',
	'Chapln',
	'Cmdr',
	'Col',
	'Cpl',
	'Cpt',
	'Dr',
	'Gen',
	'Gov',
	'Hon',
	'Lady',
	'Lt',
	'Mr',
	'Mrs',
	'Ms',
	'Msgr',
	'Pfc',
	'Pres',
	'Prof',
	'Pvt',
	'Rabbi',
	'Rep',
	'Rev',
	'Sen',
	'Sgt',
	'Sir',
	'Sr',
	'Sra',
	'Srta',
	'Ven',
);

// SPFX tags - surname prefixes
$SPFX_accept=array(
	'al',
	'da',
	'de',
	'dem',
	'den',
	'der',
	'di',
	'du',
	'el',
	'la',
	'van',
	'von',
);

// NSFX tags - name suffixes
$NSFX_accept=array(
	'I',
	'II',
	'III',
	'IV',
	'Jr',
	'Junior',
	'MD',
	'PhD',
	'Senior',
	'Sr',
	'V',
	'VI',
);

// FILE:FORM tags - file formats
$FILE_FORM_accept=array(
	'avi',
	'bmp',
	'gif',
	'jpeg',
	'mp3',
	'ole',
	'pcx',
	'png',
	'tiff',
	'wav',
);

// Fact tags (as opposed to event tags), that don't normally have a value
$emptyfacts=array(
	'ADOP',
	'ANUL',
	'BAPL',
	'BAPM',
	'BARM',
	'BASM',
	'BIRT',
	'BLES',
	'BURI',
	'CENS',
	'CHAN',
	'CHR',
	'CHRA',
	'CONF',
	'CONL',
	'CREM',
	'DATA',
	'DEAT',
	'DIV',
	'DIVF',
	'EMIG',
	'ENDL',
	'ENGA',
	'FCOM',
	'GRAD',
	'HUSB',
	'IMMI',
	'MAP',
	'MARB',
	'MARC',
	'MARL',
	'MARR',
	'MARS',
	'NATU',
	'ORDN',
	'PROB',
	'RESI',
	'RETI',
	'SLGC',
	'SLGS',
	'WIFE',
	'WILL',
	'_HOL',
	'_NMR',
	'_SEPR',
);

// Tags that don't require a PLAC subtag
$nonplacfacts=array(
	'ENDL',
	'NCHI',
	'SLGC',
	'SLGS',
);

// Tags that don't require a DATE subtag
$nondatefacts=array(
	'ABBR',
	'ADDR',
	'AFN',
	'AUTH',
	'CHIL',
	'EMAIL',
	'FAX',
	'HUSB',
	'NAME',
	'NCHI',
	'NOTE',
	'OBJE',
	'PHON',
	'PUBL',
	'REFN',
	'REPO',
	'RESN',
	'SEX',
	'SOUR',
	'SSN',
	'TEXT',
	'TITL',
	'WIFE',
	'WWW',
	'_EMAIL',
);

// Tags that require a TYPE subtag
$typefacts=array(
);

// Tags that require a DATE:TIME as well as a DATE
$date_and_time=array(
	'BIRT',
	'DEAT',
);

// Level 2 tags that apply to specific Level 1 tags
// Tags are applied in the order they appear here.
$level2_tags=array(
	'_HEB'=>array(
		'NAME',
		'TITL',
	),
	'ROMN'=>array(
		'NAME',
		'TITL',
	),
	'TYPE'=>array(
		'EVEN',
		'FACT',
		'GRAD',
		'IDNO',
		'MARR',
		'ORDN',
		'SSN',
	),
	'AGNC'=>array(
		'EDUC',
		'GRAD',
		'OCCU',
		'ORDN',
		'RETI',
	),
	'CAUS'=>array(
		'DEAT',
	),
	'CALN'=>array(
		'REPO',
	),
	'CEME'=>array( // CEME is NOT a valid 5.5.1 tag
		'BURI',
	),
	'RELA'=>array(
		'ASSO',
	),
	'DATE'=>array(
		'ADOP',
		'ANUL',
		'BAPL',
		'BAPM',
		'BARM',
		'BASM',
		'BIRT',
		'BLES',
		'BURI',
		'CENS',
		'CENS',
		'CHR',
		'CHRA',
		'CONF',
		'CONL',
		'CREM',
		'DEAT',
		'DIV',
		'DIVF',
		'EDUC',
		'EMIG',
		'ENDL',
		'ENGA',
		'EVEN',
		'EVEN',
		'FCOM',
		'GRAD',
		'IMMI',
		'MARB',
		'MARC',
		'MARL',
		'MARR',
		'MARS',
		'NATU',
		'OCCU',
		'ORDN',
		'PROB',
		'PROP',
		'RELI',
		'RESI',
		'RESI',
		'RETI',
		'SLGC',
		'SLGS',
		'WILL',
		'_TODO',
	),
	'TEMP'=>array(
		'BAPL',
		'CONL',
		'ENDL',
		'SLGC',
		'SLGS',
	),
	'PLAC'=>array(
		'ADOP',
		'ANUL',
		'BAPL',
		'BAPM',
		'BARM',
		'BASM',
		'BIRT',
		'BLES',
		'BURI',
		'CENS',
		'CENS',
		'CHR',
		'CHRA',
		'CONF',
		'CONL',
		'CREM',
		'DEAT',
		'DIV',
		'DIVF',
		'EDUC',
		'EMIG',
		'ENDL',
		'ENGA',
		'EVEN',
		'EVEN',
		'FCOM',
		'GRAD',
		'IMMI',
		'MARB',
		'MARC',
		'MARL',
		'MARR',
		'MARS',
		'NATU',
		'OCCU',
		'ORDN',
		'PROB',
		'PROP',
		'RELI',
		'RESI',
		'RESI',
		'RETI',
		'SLGC',
		'SLGS',
		'SSN',
		'WILL',
	),
	'STAT'=>array(
		'BAPL',
		'CONL',
		'ENDL',
		'SLGC',
		'SLGS',
	),
	'ADDR'=>array(
		'BIRT',
		'BURI',
		'CENS',
		'CHR',
		'CHRA',
		'CREM',
		'DEAT',
		'EDUC',
		'EVEN',
		'GRAD',
		'MARR',
		'OCCU',
		'ORDN',
		'PROP',
		'RESI',
	),
	'PHON'=>array(
		'OCCU',
		'RESI',
	),
	'FAX'=>array(
		'OCCU',
		'RESI',
	),
	'URL'=>array(
		'OCCU',
		'RESI',
	),
	'EMAIL'=>array(
		'OCCU',
		'RESI',
	),
	'AGE'=>array(
		'CENS',
		'DEAT',
	),
	'HUSB'=>array(
		'MARR',
	),
	'WIFE'=>array(
		'MARR',
	),
	'FAMC'=>array(
		'ADOP',
		'SLGC',
	),
	'FILE'=>array(
		'OBJE',
	),
	'_PRIM'=>array(
		'OBJE',
	),
	'EVEN'=>array(
		'DATA',
	),
	'_WT_USER'=>array(
		'_TODO',
	),
);

// The order of name parts, when generating names
$STANDARD_NAME_FACTS=array('NAME', 'NPFX', 'GIVN', 'SPFX', 'SURN', 'NSFX');
$REVERSED_NAME_FACTS=array('NAME', 'NPFX', 'SPFX', 'SURN', 'GIVN', 'NSFX');

$FACTS=array(
	'ABBR'=> /* I18N: gedcom tag ABBR */     WT_I18N::translate('Abbreviation'),
	'ADDR'=> /* I18N: gedcom tag ADDR */     WT_I18N::translate('Address'),
	'ADR1'=>                                 WT_I18N::translate('Address line 1'),
	'ADR2'=>                                 WT_I18N::translate('Address line 2'),
	'ADOP'=> /* I18N: gedcom tag ADOP */     WT_I18N::translate('Adoption'),
	'ADOP:DATE'=>                            WT_I18N::translate('Date of Adoption'),
	'ADOP:PLAC'=>                            WT_I18N::translate('Place of Adoption'),
	'ADOP:SOUR'=>                            WT_I18N::translate('Source for Adoption'),
	'AFN'=> /* I18N: gedcom tag AFN */       WT_I18N::translate('Ancestral File Number'),
	'AGE'=> /* I18N: gedcom tag AGE */       WT_I18N::translate('Age'),
	'AGNC'=> /* I18N: gedcom tag AGNC */     WT_I18N::translate('Agency'),
	'ALIA'=> /* I18N: gedcom tag ALIA */     WT_I18N::translate('Alias'),
	'ANCE'=> /* I18N: gedcom tag ANCE */     WT_I18N::translate('Generations of ancestors'),
	'ANCI'=> /* I18N: gedcom tag ANCI */     WT_I18N::translate('Ancestors interest'),
	'ANUL'=> /* I18N: gedcom tag ANUL */     WT_I18N::translate('Annulment'),
	'ASSO'=> /* I18N: gedcom tag ASSO */     WT_I18N::translate('Associate'),
	'AUTH'=> /* I18N: gedcom tag AUTH */     WT_I18N::translate('Author'),
	'BAPL'=> /* I18N: gedcom tag BAPL */     WT_I18N::translate('LDS baptism'),
	'BAPL:DATE'=>                            WT_I18N::translate('Date of LDS Baptism'),
	'BAPL:PLAC'=>                            WT_I18N::translate('Place of LDS Baptism'),
	'BAPM'=> /* I18N: gedcom tag BAPM */     WT_I18N::translate('Baptism'),
	'BAPM:DATE'=>                            WT_I18N::translate('Date of baptism'),
	'BAPM:PLAC'=>                            WT_I18N::translate('Place of baptism'),
	'BAPM:SOUR'=>                            WT_I18N::translate('Source for baptism'),
	'BARM'=> /* I18N: gedcom tag BARM */     WT_I18N::translate('Bar mitzvah'),
	'BARM:DATE'=>                            WT_I18N::translate('Date of bar mitzvah'),
	'BARM:PLAC'=>                            WT_I18N::translate('Place of bar mitzvah'),
	'BARM:SOUR'=>                            WT_I18N::translate('Source for bar mitzvah'),
	'BASM'=> /* I18N: gedcom tag BASM */     WT_I18N::translate('Bat mitzvah'),
	'BASM:DATE'=>                            WT_I18N::translate('Date of bat mitzvah'),
	'BASM:PLAC'=>                            WT_I18N::translate('Place of bat mitzvah'),
	'BASM:SOUR'=>                            WT_I18N::translate('Source for bat mitzvah'),
	'BIRT'=> /* I18N: gedcom tag BIRT */     WT_I18N::translate('Birth'),
	'BIRT:DATE'=>                            WT_I18N::translate('Date of birth'),
	'BIRT:PLAC'=>                            WT_I18N::translate('Place of birth'),
	'BIRT:SOUR'=>                            WT_I18N::translate('Source for birth'),
	'BLES'=> /* I18N: gedcom tag BLES */     WT_I18N::translate('Blessing'),
	'BLES:DATE'=>                            WT_I18N::translate('Date of Blessing'),
	'BLES:PLAC'=>                            WT_I18N::translate('Place of Blessing'),
	'BLES:SOUR'=>                            WT_I18N::translate('Source for Blessing'),
	'BLOB'=> /* I18N: gedcom tag BLOB */     WT_I18N::translate('Binary Data Object'),
	'BURI'=> /* I18N: gedcom tag BURI */     WT_I18N::translate('Burial'),
	'BURI:DATE'=>                            WT_I18N::translate('Date of burial'),
	'BURI:PLAC'=>                            WT_I18N::translate('Place of burial'),
	'BURI:SOUR'=>                            WT_I18N::translate('Source for burial'),
	'CALN'=> /* I18N: gedcom tag CALN */     WT_I18N::translate('Call number'),
	'CAST'=> /* I18N: gedcom tag CAST */     WT_I18N::translate('Caste'),
	'CAUS'=> /* I18N: gedcom tag CAUS */     WT_I18N::translate('Cause'),
	'CEME'=> /* I18N: gedcom tag CEME */     WT_I18N::translate('Cemetery'),
	'CENS'=> /* I18N: gedcom tag CENS */     WT_I18N::translate('Census'),
	'CENS:DATE'=>                            WT_I18N::translate('Census date'),
	'CENS:PLAC'=>                            WT_I18N::translate('Census place'),
	'CHAN'=> /* I18N: gedcom tag CHAN */     WT_I18N::translate('Last change'),
	'CHAR'=> /* I18N: gedcom tag CHAR */     WT_I18N::translate('Character set'),
	'CHIL'=> /* I18N: gedcom tag CHIL */     WT_I18N::translate('Child'),
	'CHR'=> /* I18N: gedcom tag CHR */       WT_I18N::translate('Christening'),
	'CHR:DATE'=>                             WT_I18N::translate('Date of christening'),
	'CHR:PLAC'=>                             WT_I18N::translate('Place of christening'),
	'CHR:SOUR'=>                             WT_I18N::translate('Source for christening'),
	'CHRA'=> /* I18N: gedcom tag CHRA */     WT_I18N::translate('Adult christening'),
	'CITN'=> /* I18N: gedcom tag CITN */     WT_I18N::translate('Citizenship'),
	'CITY'=> /* I18N: gedcom tag CITY */     WT_I18N::translate('City'),
	'COMM'=> /* I18N: gedcom tag COMM */     WT_I18N::translate('Comment'),
	'CONC'=> /* I18N: gedcom tag CONC */     WT_I18N::translate('Concatenation'),
	'CONT'=> /* I18N: gedcom tag CONT */     WT_I18N::translate('Continued'),
	'CONF'=> /* I18N: gedcom tag CONF */     WT_I18N::translate('Confirmation'),
	'CONF:DATE'=>                            WT_I18N::translate('Date of confirmation'),
	'CONF:PLAC'=>                            WT_I18N::translate('Place of confirmation'),
	'CONF:SOUR'=>                            WT_I18N::translate('Source for confirmation'),
	'CONL'=> /* I18N: gedcom tag CONL */     WT_I18N::translate('LDS confirmation'),
	'COPR'=> /* I18N: gedcom tag COPR */     WT_I18N::translate('Copyright'),
	'CORP'=> /* I18N: gedcom tag CORP */     WT_I18N::translate('Corporation'),
	'CREM'=> /* I18N: gedcom tag CREM */     WT_I18N::translate('Cremation'),
	'CREM:DATE'=>                            WT_I18N::translate('Date of Cremation'),
	'CREM:PLAC'=>                            WT_I18N::translate('Place of Cremation'),
	'CREM:SOUR'=>                            WT_I18N::translate('Source for Cremation'),
	'CTRY'=> /* I18N: gedcom tag CTRY */     WT_I18N::translate('Country'),
	'DATA'=> /* I18N: gedcom tag DATA */     WT_I18N::translate('Data'),
	'DATA:DATE'=>                            WT_I18N::translate('Date of entry in original source'),
	'DATE'=> /* I18N: gedcom tag DATE */     WT_I18N::translate('Date'),
	'DEAT'=> /* I18N: gedcom tag DEAT */     WT_I18N::translate('Death'),
	'DEAT:CAUS'=>                            WT_I18N::translate('Cause of death'),
	'DEAT:DATE'=>                            WT_I18N::translate('Date of death'),
	'DEAT:PLAC'=>                            WT_I18N::translate('Place of death'),
	'DEAT:SOUR'=>                            WT_I18N::translate('Source for death'),
	'DESC'=> /* I18N: gedcom tag DESC */     WT_I18N::translate('Descendants'),
	'DESI'=> /* I18N: gedcom tag DESI */     WT_I18N::translate('Descendants interest'),
	'DEST'=> /* I18N: gedcom tag DEST */     WT_I18N::translate('Destination'),
	'DIV'=> /* I18N: gedcom tag DIV */       WT_I18N::translate('Divorce'),
	'DIVF'=> /* I18N: gedcom tag DIVF */     WT_I18N::translate('Divorce filed'),
	'DSCR'=> /* I18N: gedcom tag DSCR */     WT_I18N::translate('Description'),
	'EDUC'=> /* I18N: gedcom tag EDUC */     WT_I18N::translate('Education'),
	'EDUC:AGNC'=>                            WT_I18N::translate('School or college'),
	'EMAI'=> /* I18N: gedcom tag EMAI */     WT_I18N::translate('Email address'),
	'EMAIL'=> /* I18N: gedcom tag EMAIL */   WT_I18N::translate('Email address'),
	'EMAL'=> /* I18N: gedcom tag EMAL */     WT_I18N::translate('Email address'),
	'EMIG'=> /* I18N: gedcom tag EMIG */     WT_I18N::translate('Emigration'),
	'EMIG:DATE'=>                            WT_I18N::translate('Date of Emigration'),
	'EMIG:PLAC'=>                            WT_I18N::translate('Place of Emigration'),
	'ENDL'=> /* I18N: gedcom tag ENDL */     WT_I18N::translate('LDS endowment'),
	'ENDL:DATE'=>                            WT_I18N::translate('Date of LDS Endowment'),
	'ENDL:PLAC'=>                            WT_I18N::translate('Place of LDS Endowment'),
	'ENGA'=> /* I18N: gedcom tag ENGA */     WT_I18N::translate('Engagement'),
	'ENGA:DATE'=>                            WT_I18N::translate('Date of engagement'),
	'ENGA:PLAC'=>                            WT_I18N::translate('Place of engagement'),
	'ENGA:SOUR'=>                            WT_I18N::translate('Source for engagement'),
	'EVEN'=> /* I18N: gedcom tag EVEN */     WT_I18N::translate('Event'),
	'EVEN:DATE'=>                            WT_I18N::translate('Date of Event'),
	'EVEN:PLAC'=>                            WT_I18N::translate('Place of Event'),
	'FACT'=> /* I18N: gedcom tag FACT */     WT_I18N::translate('Fact'),
	'FAM'=> /* I18N: gedcom tag FAM */       WT_I18N::translate('Family'),
	'FAMC'=> /* I18N: gedcom tag FAMC */     WT_I18N::translate('Family as a child'),
	'FAMC:HUSB:BIRT:PLAC'=>                  WT_I18N::translate('Father\'s birthplace'),
	'FAMC:HUSB:FAMC:HUSB:GIVN'=>             WT_I18N::translate('Paternal grandfather\'s given name'),
	'FAMC:HUSB:FAMC:WIFE:GIVN'=>             WT_I18N::translate('Paternal grandmother\'s given name'),
	'FAMC:HUSB:GIVN'=>                       WT_I18N::translate('Father\'s given name'),
	'FAMC:HUSB:OCCU'=>                       WT_I18N::translate('Father\'s occupation'),
	'FAMC:HUSB:SURN'=>                       WT_I18N::translate('Father\'s surname'),
	'FAMC:MARR:PLAC'=>                       WT_I18N::translate('Parents\' marriage place'),
	'FAMC:WIFE:BIRT:PLAC'=>                  WT_I18N::translate('Mother\'s birthplace'),
	'FAMC:WIFE:FAMC:HUSB:GIVN'=>             WT_I18N::translate('Maternal grandfather\'s given name'),
	'FAMC:WIFE:FAMC:WIFE:GIVN'=>             WT_I18N::translate('Maternal grandmother\'s Given Name'),
	'FAMC:WIFE:GIVN'=>                       WT_I18N::translate('Mother\'s given name'),
	'FAMC:WIFE:SURN'=>                       WT_I18N::translate('Mother\'s surname'),
	'FAMF'=> /* I18N: gedcom tag FAMF */     WT_I18N::translate('Family file'),
	'FAMS'=> /* I18N: gedcom tag FAMS */     WT_I18N::translate('Family as a spouse'),
	'FAMS:CENS:DATE'=>                       WT_I18N::translate('Spouse census date'),
	'FAMS:CENS:PLAC'=>                       WT_I18N::translate('Spouse census place'),
	'FAMS:CHIL:BIRT:PLAC'=>                  WT_I18N::translate('Child\'s birth place'),
	'FAMS:DIV:DATE'=>                        WT_I18N::translate('Spouse divorce date'),
	'FAMS:DIV:PLAC'=>                        WT_I18N::translate('Spouse divorce place'),
	'FAMS:MARR:DAT'=>                        WT_I18N::translate('Date of marriage'),
	'FAMS:MARR:PLAC'=>                       WT_I18N::translate('Place of marriage'),
	'FAMS:NOTE'=>                            WT_I18N::translate('Spouse note'),
	'FAMS:SLGS:DATE'=>                       WT_I18N::translate('LDS spouse sealing date'),
	'FAMS:SLGS:PLAC'=>                       WT_I18N::translate('LDS spouse sealing place'),
	'FAMS:SLGS:TEMP'=>                       WT_I18N::translate('LDS spouse sealing temple'),
	'FAMS:SPOUSE:BIRT:PLAC'=>                WT_I18N::translate('Spouse\'s birth place'),
	'FAMS:SPOUSE:DEAT:PLAC'=>                WT_I18N::translate('Spouse\'s death place'),
	'FAX'=> /* I18N: gedcom tag FAX */       WT_I18N::translate('Fax'),
	'FCOM'=> /* I18N: gedcom tag FCOM */     WT_I18N::translate('First communion'),
	'FCOM:DATE'=>                            WT_I18N::translate('Date of first communion'),
	'FCOM:PLAC'=>                            WT_I18N::translate('Place of first communion'),
	'FCOM:SOUR'=>                            WT_I18N::translate('Source for first communion'),
	'FILE'=> /* I18N: gedcom tag FILE */     WT_I18N::translate('Filename'),
	'FONE'=> /* I18N: gedcom tag FONE */     WT_I18N::translate('Phonetic'),
	'FORM'=> /* I18N: gedcom tag FORM */     WT_I18N::translate('Format'),
	'GEDC'=> /* I18N: gedcom tag GEDC */     WT_I18N::translate('Gedcom'),
	'GIVN'=> /* I18N: gedcom tag GIVN */     WT_I18N::translate('Given names'),
	'GRAD'=> /* I18N: gedcom tag GRAD */     WT_I18N::translate('Graduation'),
	'HEAD'=> /* I18N: gedcom tag HEAD */     WT_I18N::translate('Header'),
	'HUSB'=> /* I18N: gedcom tag HUSB */     WT_I18N::translate('Husband'),
	'IDNO'=> /* I18N: gedcom tag IDNO */     WT_I18N::translate('Identification number'),
	'IMMI'=> /* I18N: gedcom tag IMMI */     WT_I18N::translate('Immigration'),
	'IMMI:DATE'=>                            WT_I18N::translate('Date of Immigration'),
	'IMMI:PLAC'=>                            WT_I18N::translate('Place of Immigration'),
	'INDI'=> /* I18N: gedcom tag INDI */     WT_I18N::translate('Individual'),
	'INFL'=> /* I18N: gedcom tag INFL */     WT_I18N::translate('Infant'),
	'LANG'=> /* I18N: gedcom tag LANG */     WT_I18N::translate('Language'),
	'LATI'=> /* I18N: gedcom tag LATI */     WT_I18N::translate('Latitude'),
	'LEGA'=> /* I18N: gedcom tag LEGA */     WT_I18N::translate('Legatee'),
	'LONG'=> /* I18N: gedcom tag LONG */     WT_I18N::translate('Longitude'),
	'MAP'=> /* I18N: gedcom tag MAP */       WT_I18N::translate('Map'),
	'MARB'=> /* I18N: gedcom tag MARB */     WT_I18N::translate('Marriage banns'),
	'MARB:DATE'=>                            WT_I18N::translate('Date of marriage banns'),
	'MARB:PLAC'=>                            WT_I18N::translate('Place of marriage banns'),
	'MARB:SOUR'=>                            WT_I18N::translate('Source for marriage banns'),
	'MARC'=> /* I18N: gedcom tag MARC */     WT_I18N::translate('Marriage contract'),
	'MARL'=> /* I18N: gedcom tag MARL */     WT_I18N::translate('Marriage licence'),
	'MARR'=> /* I18N: gedcom tag MARR */     WT_I18N::translate('Marriage'),
	'MARR:DATE'=>                            WT_I18N::translate('Date of marriage'),
	'MARR:PLAC'=>                            WT_I18N::translate('Place of marriage'),
	'MARR:SOUR'=>                            WT_I18N::translate('Source for marriage'),
	'MARR_CIVIL'=>                           WT_I18N::translate('Civil marriage'),
	'MARR_PARTNERS'=>                        WT_I18N::translate('Registered partnership'),
	'MARR_RELIGIOUS'=>                       WT_I18N::translate('Religious marriage'),
	'MARR_UNKNOWN'=>                         WT_I18N::translate('Marriage type unknown'),
	'MARS'=> /* I18N: gedcom tag MARS */     WT_I18N::translate('Marriage settlement'),
	'MEDI'=> /* I18N: gedcom tag MEDI */     WT_I18N::translate('Media type'),
	'NAME'=> /* I18N: gedcom tag NAME */     WT_I18N::translate('Name'),
	'NAME:FONE'=>                            WT_I18N::translate('Phonetic name'),
	'NAME:_HEB'=>                            WT_I18N::translate('Name in Hebrew'),
	'NATI'=> /* I18N: gedcom tag NATI */     WT_I18N::translate('Nationality'),
	'NATU'=> /* I18N: gedcom tag NATU */     WT_I18N::translate('Naturalization'),
	'NATU:DATE'=>                            WT_I18N::translate('Date of Naturalization'),
	'NATU:PLAC'=>                            WT_I18N::translate('Place of Naturalization'),
	'NCHI'=> /* I18N: gedcom tag NCHI */     WT_I18N::translate('Number of children'),
	'NICK'=> /* I18N: gedcom tag NICK */     WT_I18N::translate('Nickname'),
	'NMR'=> /* I18N: gedcom tag NMR */       WT_I18N::translate('Number of marriages'),
	'NOTE'=> /* I18N: gedcom tag NOTE */     WT_I18N::translate('Note'),
	'NPFX'=> /* I18N: gedcom tag NPFX */     WT_I18N::translate('Name prefix'),
	'NSFX'=> /* I18N: gedcom tag NSFX */     WT_I18N::translate('Name suffix'),
	'OBJE'=> /* I18N: gedcom tag OBJE */     WT_I18N::translate('Multimedia object'),
	'OCCU'=> /* I18N: gedcom tag OCCU */     WT_I18N::translate('Occupation'),
	'OCCU:AGNC'=>                            WT_I18N::translate('Employer'),
	'ORDI'=> /* I18N: gedcom tag ORDI */     WT_I18N::translate('Ordinance'),
	'ORDN'=> /* I18N: gedcom tag ORDN */     WT_I18N::translate('Ordination'),
	'ORDN:AGNC'=>                            WT_I18N::translate('Religious Institution'),
	'ORDN:DATE'=>                            WT_I18N::translate('Date of Ordination'),
	'ORDN:PLAC'=>                            WT_I18N::translate('Place of Ordination'),
	'PAGE'=> /* I18N: gedcom tag PAGE */     WT_I18N::translate('Citation details'),
	'PEDI'=> /* I18N: gedcom tag PEDI */     WT_I18N::translate('Pedigree'),
	'PHON'=> /* I18N: gedcom tag PHON */     WT_I18N::translate('Phone'),
	'PLAC'=> /* I18N: gedcom tag PLAC */     WT_I18N::translate('Place'),
	'PLAC:FONE'=>                            WT_I18N::translate('Phonetic place'),
	'PLAC:ROMN'=>                            WT_I18N::translate('Romanized place'),
	'PLAC:_HEB'=>                            WT_I18N::translate('Place in Hebrew'),
	'POST'=> /* I18N: gedcom tag POST */     WT_I18N::translate('Postal code'),
	'PROB'=> /* I18N: gedcom tag PROB */     WT_I18N::translate('Probate'),
	'PROP'=> /* I18N: gedcom tag PROP */     WT_I18N::translate('Property'),
	'PUBL'=> /* I18N: gedcom tag PUBL */     WT_I18N::translate('Publication'),
	'QUAY'=> /* I18N: gedcom tag QUAY */     WT_I18N::translate('Quality of data'),
	'REFN'=> /* I18N: gedcom tag REFN */     WT_I18N::translate('Reference number'),
	'RELA'=> /* I18N: gedcom tag RELA */     WT_I18N::translate('Relationship'),
	'RELI'=> /* I18N: gedcom tag RELI */     WT_I18N::translate('Religion'),
	'REPO'=> /* I18N: gedcom tag REPO */     WT_I18N::translate('Repository'),
	'RESI'=> /* I18N: gedcom tag RESI */     WT_I18N::translate('Residence'),
	'RESI:DATE'=>                            WT_I18N::translate('Date of Residence'),
	'RESI:PLAC'=>                            WT_I18N::translate('Place of Residence'),
	'RESN'=> /* I18N: gedcom tag RESN */     WT_I18N::translate('Restriction'),
	'RETI'=> /* I18N: gedcom tag RETI */     WT_I18N::translate('Retirement'),
	'RETI:AGNC'=>                            WT_I18N::translate('Employer'),
	'RFN'=> /* I18N: gedcom tag RFN */       WT_I18N::translate('Record file number'),
	'RIN'=> /* I18N: gedcom tag RIN */       WT_I18N::translate('Record ID number'),
	'ROLE'=> /* I18N: gedcom tag ROLE */     WT_I18N::translate('Role'),
	'ROMN'=> /* I18N: gedcom tag ROMN */     WT_I18N::translate('Romanized'),
	'SERV'=> /* I18N: gedcom tag SERV */     WT_I18N::translate('Remote server'),
	'SEX'=> /* I18N: gedcom tag SEX */       WT_I18N::translate('Gender'),
	'SHARED_NOTE'=>                          WT_I18N::translate('Shared note'),
	'SLGC'=> /* I18N: gedcom tag SLGC */     WT_I18N::translate('LDS child sealing'),
	'SLGC:DATE'=>                            WT_I18N::translate('Date of LDS Child Sealing'),
	'SLGC:PLAC'=>                            WT_I18N::translate('Place of LDS Child Sealing'),
	'SLGS'=> /* I18N: gedcom tag SLGS */     WT_I18N::translate('LDS spouse sealing'),
	'SLGS:DATE'=>                            WT_I18N::translate('Date of LDS Spouse Sealing'),
	'SLGS:PLAC'=>                            WT_I18N::translate('Place of LDS Spouse Sealing'),
	'SOUR'=> /* I18N: gedcom tag SOUR */     WT_I18N::translate('Source'),
	'SPFX'=> /* I18N: gedcom tag SPFX */     WT_I18N::translate('Surname prefix'),
	'SSN'=> /* I18N: gedcom tag SSN */       WT_I18N::translate('Social Security Number'),
	'STAE'=> /* I18N: gedcom tag STAE */     WT_I18N::translate('State'),
	'STAT'=> /* I18N: gedcom tag STAT */     WT_I18N::translate('Status'),
	'STAT:DATE'=>                            WT_I18N::translate('Status change date'),
	'SUBM'=> /* I18N: gedcom tag SUBM */     WT_I18N::translate('Submitter'),
	'SUBN'=> /* I18N: gedcom tag SUBN */     WT_I18N::translate('Submission'),
	'SURN'=> /* I18N: gedcom tag SURN */     WT_I18N::translate('Surname'),
	'TEMP'=> /* I18N: gedcom tag TEMP */     WT_I18N::translate('Temple'),
	'TEXT'=> /* I18N: gedcom tag TEXT */     WT_I18N::translate('Text'),
	'TIME'=> /* I18N: gedcom tag TIME */     WT_I18N::translate('Time'),
	'TITL'=> /* I18N: gedcom tag TITL */     WT_I18N::translate('Title'),
	'TITL:FONE'=>                            WT_I18N::translate('Phonetic title'),
	'TITL:ROMN'=>                            WT_I18N::translate('Romanized title'),
	'TITL:_HEB'=>                            WT_I18N::translate('Title in Hebrew'),
	'TRLR'=> /* I18N: gedcom tag TRLR */     WT_I18N::translate('Trailer'),
	'TYPE'=> /* I18N: gedcom tag TYPE */     WT_I18N::translate('Type'),
	'URL'=> /* I18N: gedcom tag URL */       WT_I18N::translate('Web URL'),
	'VERS'=> /* I18N: gedcom tag VERS */     WT_I18N::translate('Version'),
	'WIFE'=> /* I18N: gedcom tag WIFE */     WT_I18N::translate('Wife'),
	'WILL'=> /* I18N: gedcom tag WILL */     WT_I18N::translate('Will'),
	'WWW'=> /* I18N: gedcom tag WWW */       WT_I18N::translate('Web home page'),
	'_ADOP_CHIL'=>                           WT_I18N::translate('Adoption of a child'),
	'_ADOP_GCHI'=>                           WT_I18N::translate('Adoption of a grandchild'),
	'_ADOP_GCH1'=>                           WT_I18N::translate('Adoption of a grandchild'),
	'_ADOP_GCH2'=>                           WT_I18N::translate('Adoption of a grandchild'),
	'_ADOP_HSIB'=>                           WT_I18N::translate('Adoption of a half-sibling'),
	'_ADOP_SIBL'=>                           WT_I18N::translate('Adoption of a sibling'),
	'_ADPF'=> /* I18N: gedcom tag _ADPF */   WT_I18N::translate('Adopted by father'),
	'_ADPM'=> /* I18N: gedcom tag _ADPM */   WT_I18N::translate('Adopted by mother'),
	'_AKA'=> /* I18N: gedcom tag _AKA */     WT_I18N::translate('Also known as'),
	'_AKAN'=> /* I18N: gedcom tag _AKAN */   WT_I18N::translate('Also known as'),
	'_BAPM_CHIL'=>                           WT_I18N::translate('Baptism of a child'),
	'_BAPM_GCHI'=>                           WT_I18N::translate('Baptism of a grandchild'),
	'_BAPM_GCH1'=>                           WT_I18N::translate('Baptism of a grandchild'),
	'_BAPM_GCH2'=>                           WT_I18N::translate('Baptism of a grandchild'),
	'_BAPM_HSIB'=>                           WT_I18N::translate('Baptism of a half-sibling'),
	'_BAPM_SIBL'=>                           WT_I18N::translate('Baptism of a sibling'),
	'_BIBL'=> /* I18N: gedcom tag _BIBL */   WT_I18N::translate('Bibliography'),
	'_BIRT_CHIL'=>                           WT_I18N::translate('Birth of a child'),
	'_BIRT_GCHI'=>                           WT_I18N::translate('Birth of a grandchild'),
	'_BIRT_GCH1'=>                           WT_I18N::translate('Birth of a grandchild'),
	'_BIRT_GCH2'=>                           WT_I18N::translate('Birth of a grandchild'),
	'_BIRT_HSIB'=>                           WT_I18N::translate('Birth of a half-sibling'),
	'_BIRT_SIBL'=>                           WT_I18N::translate('Birth of a sibling'),
	'_BRTM'=> /* I18N: gedcom tag _BRTM */   WT_I18N::translate('Brit milah'),
	'_BRTM:DATE'=>                           WT_I18N::translate('Date of brit milah'),
	'_BRTM:PLAC'=>                           WT_I18N::translate('Place of brit milah'),
	'_BRTM:SOUR'=>                           WT_I18N::translate('Source for brit milah'),
	'_BURI_CHIL'=>                           WT_I18N::translate('Burial of a child'),
	'_BURI_GCHI'=>                           WT_I18N::translate('Burial of a grandchild'),
	'_BURI_GCH1'=>                           WT_I18N::translate('Burial of a grandchild'),
	'_BURI_GCH2'=>                           WT_I18N::translate('Burial of a grandchild'),
	'_BURI_GPAR'=>                           WT_I18N::translate('Burial of a grand-parent'),
	'_BURI_HSIB'=>                           WT_I18N::translate('Burial of a half-sibling'),
	'_BURI_SIBL'=>                           WT_I18N::translate('Burial of a sibling'),
	'_BURI_SPOU'=>                           WT_I18N::translate('Burial of a spouse'),
	'_CHR_CHIL'=>                            WT_I18N::translate('Christening of a child'),
	'_CHR_GCHI'=>                            WT_I18N::translate('Christening of a grandchild'),
	'_CHR_GCH1'=>                            WT_I18N::translate('Christening of a grandchild'),
	'_CHR_GCH2'=>                            WT_I18N::translate('Christening of a grandchild'),
	'_CHR_HSIB'=>                            WT_I18N::translate('Christening of a half-sibling'),
	'_CHR_SIBL'=>                            WT_I18N::translate('Christening of a sibling'),
	'_COML'=> /* I18N: gedcom tag _COML */   WT_I18N::translate('Common Law Marriage'),
	'_CREM_CHIL'=>                           WT_I18N::translate('Cremation of a child'),
	'_CREM_GCHI'=>                           WT_I18N::translate('Cremation of a grandchild'),
	'_CREM_GCH1'=>                           WT_I18N::translate('Cremation of a grandchild'),
	'_CREM_GCH2'=>                           WT_I18N::translate('Cremation of a grandchild'),
	'_CREM_GPAR'=>                           WT_I18N::translate('Cremation of a grand-parent'),
	'_CREM_HSIB'=>                           WT_I18N::translate('Cremation of a half-sibling'),
	'_CREM_SIBL'=>                           WT_I18N::translate('Cremation of a sibling'),
	'_CREM_SPOU'=>                           WT_I18N::translate('Cremation of a spouse'),
	'_DBID'=> /* I18N: gedcom tag _DBID */   WT_I18N::translate('Linked database ID'),
	'_DEAT_CHIL'=>                           WT_I18N::translate('Death of a child'),
	'_DEAT_GCHI'=>                           WT_I18N::translate('Death of a grandchild'),
	'_DEAT_GCH1'=>                           WT_I18N::translate('Death of a grandchild'),
	'_DEAT_GCH2'=>                           WT_I18N::translate('Death of a grandchild'),
	'_DEAT_GPAR'=>                           WT_I18N::translate('Death of a grand-parent'),
	'_DEAT_HSIB'=>                           WT_I18N::translate('Death of a half-sibling'),
	'_DEAT_PARE'=>                           WT_I18N::translate('Death of a parent'),
	'_DEAT_SIBL'=>                           WT_I18N::translate('Death of a sibling'),
	'_DEAT_SPOU'=>                           WT_I18N::translate('Death of a spouse'),
	'_DEG'=> /* I18N: gedcom tag _DEG */     WT_I18N::translate('Degree'),
	'_DETS'=> /* I18N: gedcom tag _DETS */   WT_I18N::translate('Death of one spouse'),
	'_EMAIL'=> /* I18N: gedcom tag _EMAIL */ WT_I18N::translate('Email address'),
	'_EYEC'=> /* I18N: gedcom tag _EYEC */   WT_I18N::translate('Eye color'),
	'_FA1'=>                                 WT_I18N::translate('Fact 1'),
	'_FA2'=>                                 WT_I18N::translate('Fact 2'),
	'_FA3'=>                                 WT_I18N::translate('Fact 3'),
	'_FA4'=>                                 WT_I18N::translate('Fact 4'),
	'_FA5'=>                                 WT_I18N::translate('Fact 5'),
	'_FA6'=>                                 WT_I18N::translate('Fact 6'),
	'_FA7'=>                                 WT_I18N::translate('Fact 7'),
	'_FA8'=>                                 WT_I18N::translate('Fact 8'),
	'_FA9'=>                                 WT_I18N::translate('Fact 9'),
	'_FA10'=>                                WT_I18N::translate('Fact 10'),
	'_FA11'=>                                WT_I18N::translate('Fact 11'),
	'_FA12'=>                                WT_I18N::translate('Fact 12'),
	'_FA13'=>                                WT_I18N::translate('Fact 13'),
	'_FNRL'=> /* I18N: gedcom tag _FNRL */   WT_I18N::translate('Funeral'),
	'_FREL'=> /* I18N: gedcom tag _FREL */   WT_I18N::translate('Relationship to father'),
	'_GEDF'=> /* I18N: gedcom tag _GEDF */   WT_I18N::translate('GEDCOM file'),
	'_HAIR'=> /* I18N: gedcom tag _HAIR */   WT_I18N::translate('Hair color'),
	'_HEB'=> /* I18N: gedcom tag _HEB */     WT_I18N::translate('Hebrew'),
	'_HEIG'=> /* I18N: gedcom tag _HEIG */   WT_I18N::translate('Height'),
	'_HNM'=> /* I18N: gedcom tag _HNM */     WT_I18N::translate('Hebrew name'),
	'_HOL'=> /* I18N: gedcom tag _HOL */     WT_I18N::translate('Holocaust'),
	'_INTE'=> /* I18N: gedcom tag _INTE */   WT_I18N::translate('Interred'),
	'_MARB_CHIL'=>                           WT_I18N::translate('Marriage Banns of a child'),
	'_MARB_FAMC'=>                           WT_I18N::translate('Marriage banns of parents'),
	'_MARB_GCHI'=>                           WT_I18N::translate('Marriage Banns of a grandchild'),
	'_MARB_GCH1'=>                           WT_I18N::translate('Marriage Banns of a grandchild'),
	'_MARB_GCH2'=>                           WT_I18N::translate('Marriage Banns of a grandchild'),
	'_MARB_HSIB'=>                           WT_I18N::translate('Marriage banns of a half-sibling'),
	'_MARB_PARE'=>                           WT_I18N::translate('Marriage banns of a parent'),
	'_MARB_SIBL'=>                           WT_I18N::translate('Marriage banns of a sibling'),
	'_MARI'=> /* I18N: gedcom tag _MARI */   WT_I18N::translate('Marriage Intention'),
	'_MARNM'=> /* I18N: gedcom tag _MARNM */ WT_I18N::translate('Married Name'),
	'_PRIM'=> /* I18N: gedcom tag _PRIM */   WT_I18N::translate('Highlighted image'),
	'_MARNM_SURN'=>                          WT_I18N::translate('Married Surname'),
	'_MARR_CHIL'=>                           WT_I18N::translate('Marriage of a child'),
	'_MARR_FAMC'=>                           WT_I18N::translate('Marriage of parents'),
	'_MARR_GCHI'=>                           WT_I18N::translate('Marriage of a grandchild'),
	'_MARR_GCH1'=>                           WT_I18N::translate('Marriage of a grandchild'),
	'_MARR_GCH2'=>                           WT_I18N::translate('Marriage of a grandchild'),
	'_MARR_HSIB'=>                           WT_I18N::translate('Marriage of a half-sibling'),
	'_MARR_PARE'=>                           WT_I18N::translate('Marriage of a parent'),
	'_MARR_SIBL'=>                           WT_I18N::translate('Marriage of a sibling'),
	'_MBON'=> /* I18N: gedcom tag _MBON */   WT_I18N::translate('Marriage bond'),
	'_MDCL'=> /* I18N: gedcom tag _MDCL */   WT_I18N::translate('Medical'),
	'_MEDC'=> /* I18N: gedcom tag _MEDC */   WT_I18N::translate('Medical condition'),
	'_MEND'=> /* I18N: gedcom tag _MEND */   WT_I18N::translate('Marriage ending status'),
	'_MILI'=> /* I18N: gedcom tag _MILI */   WT_I18N::translate('Military'),
	'_MILT'=> /* I18N: gedcom tag _MILT */   WT_I18N::translate('Military service'),
	'_MREL'=> /* I18N: gedcom tag _MREL */   WT_I18N::translate('Relationship to mother'),
	'_MSTAT'=> /* I18N: gedcom tag _MSTAT */ WT_I18N::translate('Marriage beginning status'),
	'_NAME'=> /* I18N: gedcom tag _NAME */   WT_I18N::translate('Mailing name'),
	'_NAMS'=> /* I18N: gedcom tag _NAMS */   WT_I18N::translate('Namesake'),
	'_NLIV'=> /* I18N: gedcom tag _NLIV */   WT_I18N::translate('Not living'),
	'_NMAR'=> /* I18N: gedcom tag _NMAR */   WT_I18N::translate('Never married'),
	'_NMR'=> /* I18N: gedcom tag _NMR */     WT_I18N::translate('Not married'),
	'_WT_USER'=>                             WT_I18N::translate('by'),
	'_PRMN'=> /* I18N: gedcom tag _PRMN */   WT_I18N::translate('Permanent number'),
	'_SCBK'=> /* I18N: gedcom tag _SCBK */   WT_I18N::translate('Scrapbook'),
	'_SEPR'=> /* I18N: gedcom tag _SEPR */   WT_I18N::translate('Separated'),
	'_SSHOW'=> /* I18N: gedcom tag _SSHOW */ WT_I18N::translate('Slide show'),
	'_STAT'=> /* I18N: gedcom tag _STAT */   WT_I18N::translate('Marriage status'),
	'_SUBQ'=> /* I18N: gedcom tag _SUBQ */   WT_I18N::translate('Short version'),
	'_THUM'=> /* I18N: gedcom tag _THUM */   WT_I18N::translate('Always use main image?'),
	'_TODO'=> /* I18N: gedcom tag _TODO */   WT_I18N::translate('To-do item'),
	'_TYPE'=> /* I18N: gedcom tag _TYPE */   WT_I18N::translate('Media type'),
	'_UID'=> /* I18N: gedcom tag _UID */     WT_I18N::translate('Globally unique identifier'),
	'_URL'=> /* I18N: gedcom tag _URL */     WT_I18N::translate('Web URL'),
	'_WEIG'=> /* I18N: gedcom tag _WEIG */   WT_I18N::translate('Weight'),
	'_YART'=> /* I18N: gedcom tag _YART */   WT_I18N::translate('Yahrzeit'),
	'__BRTM_CHIL'=>WT_I18N::translate  (                     'Brit milah of a son'), // Brit milah applies only to males
	'__BRTM_GCHI'=>WT_I18N::translate  (                     'Brit milah of a grandson'),
	'__BRTM_GCH1'=>WT_I18N::translate_c('daughter\'s son',   'Brit milah of a grandson'),
	'__BRTM_GCH2'=>WT_I18N::translate_c('son\'s son',        'Brit milah of a grandson'),
	'__BRTM_HSIB'=>WT_I18N::translate  (                     'Brit milah of a half-brother'),
	'__BRTM_SIBL'=>WT_I18N::translate  (                     'Brit milah of a brother'),
);

// Facts, as applied to Males.
// Use the context-sensitive translations when the word is the same in English
$FACTS_M=array(
	// close relatives facts
	'_ADOP_CHIL'=>WT_I18N::translate  (        'Adoption of a son'),
	'_ADOP_GCHI'=>WT_I18N::translate  (        'Adoption of a grandson'),
	'_ADOP_GCH1'=>WT_I18N::translate_c('daughter\'s son', 'Adoption of a grandson'),
	'_ADOP_GCH2'=>WT_I18N::translate_c('son\'s son',      'Adoption of a grandson'),
	'_ADOP_HSIB'=>WT_I18N::translate  (        'Adoption of a half-brother'),
	'_ADOP_SIBL'=>WT_I18N::translate  (        'Adoption of a brother'),
	'_BAPM_CHIL'=>WT_I18N::translate  (        'Baptism of a son'),
	'_BAPM_GCHI'=>WT_I18N::translate  (        'Baptism of a grandson'),
	'_BAPM_GCH1'=>WT_I18N::translate_c('daughter\'s son', 'Baptism of a grandson'),
	'_BAPM_GCH2'=>WT_I18N::translate_c('son\'s son',      'Baptism of a grandson'),
	'_BAPM_HSIB'=>WT_I18N::translate  (        'Baptism of a half-brother'),
	'_BAPM_SIBL'=>WT_I18N::translate  (        'Baptism of a brother'),
	'_BIRT_CHIL'=>WT_I18N::translate  (        'Birth of a son'),
	'_BIRT_GCHI'=>WT_I18N::translate  (        'Birth of a grandson'),
	'_BIRT_GCH1'=>WT_I18N::translate_c('daughter\'s son', 'Birth of a grandson'),
	'_BIRT_GCH2'=>WT_I18N::translate_c('son\'s son',      'Birth of a grandson'),
	'_BIRT_HSIB'=>WT_I18N::translate  (        'Birth of a half-brother'),
	'_BIRT_SIBL'=>WT_I18N::translate  (        'Birth of a brother'),
	'_BURI_CHIL'=>WT_I18N::translate  (        'Burial of a son'),
	'_BURI_GCHI'=>WT_I18N::translate  (        'Burial of a grandson'),
	'_BURI_GCH1'=>WT_I18N::translate_c('daughter\'s son', 'Burial of a grandson'),
	'_BURI_GCH2'=>WT_I18N::translate_c('son\'s son',      'Burial of a grandson'),
	'_BURI_GPAR'=>WT_I18N::translate  (        'Burial of a grandfather'),
	'_BURI_GPA1'=>WT_I18N::translate  (        'Burial of a paternal grandfather'),
	'_BURI_GPA2'=>WT_I18N::translate  (        'Burial of a maternal grandfather'),
	'_BURI_HSIB'=>WT_I18N::translate  (        'Burial of a half-brother'),
	'_BURI_PARE'=>WT_I18N::translate  (        'Burial of a father'),
	'_BURI_SIBL'=>WT_I18N::translate  (        'Burial of a brother'),
	'_BURI_SPOU'=>WT_I18N::translate  (        'Burial of a husband'),
	'_CHR_CHIL'=>WT_I18N::translate   (        'Christening of a son'),
	'_CHR_GCHI'=>WT_I18N::translate   (        'Christening of a grandson'),
	'_CHR_GCH1'=>WT_I18N::translate_c ('daughter\'s son', 'Christening of a grandson'),
	'_CHR_GCH2'=>WT_I18N::translate_c ('son\'s son',      'Christening of a grandson'),
	'_CHR_HSIB'=>WT_I18N::translate   (        'Christening of a half-brother'),
	'_CHR_SIBL'=>WT_I18N::translate   (        'Christening of a brother'),
	'_CREM_CHIL'=>WT_I18N::translate  (        'Cremation of a son'),
	'_CREM_GCHI'=>WT_I18N::translate  (        'Cremation of a grandson'),
	'_CREM_GCH1'=>WT_I18N::translate_c('daughter\'s son', 'Cremation of a grandson'),
	'_CREM_GCH2'=>WT_I18N::translate_c('son\'s son',      'Cremation of a grandson'),
	'_CREM_GPAR'=>WT_I18N::translate  (        'Cremation of a grandfather'),
	'_CREM_GPA1'=>WT_I18N::translate  (        'Cremation of a paternal grandfather'),
	'_CREM_GPA2'=>WT_I18N::translate  (        'Cremation of a maternal grandfather'),
	'_CREM_HSIB'=>WT_I18N::translate  (        'Cremation of a half-brother'),
	'_CREM_PARE'=>WT_I18N::translate  (        'Cremation of a father'),
	'_CREM_SIBL'=>WT_I18N::translate  (        'Cremation of a brother'),
	'_CREM_SPOU'=>WT_I18N::translate  (        'Cremation of a husband'),
	'_DEAT_CHIL'=>WT_I18N::translate  (        'Death of a son'),
	'_DEAT_GCHI'=>WT_I18N::translate  (        'Death of a grandson'),
	'_DEAT_GCH1'=>WT_I18N::translate_c('daughter\'s son', 'Death of a grandson'),
	'_DEAT_GCH2'=>WT_I18N::translate_c('son\'s son',      'Death of a grandson'),
	'_DEAT_GPAR'=>WT_I18N::translate  (        'Death of a grandfather'),
	'_DEAT_GPA1'=>WT_I18N::translate  (        'Death of a paternal grandfather'),
	'_DEAT_GPA2'=>WT_I18N::translate  (        'Death of a maternal grandfather'),
	'_DEAT_HSIB'=>WT_I18N::translate  (        'Death of a half-brother'),
	'_DEAT_PARE'=>WT_I18N::translate  (        'Death of a father'),
	'_DEAT_SIBL'=>WT_I18N::translate  (        'Death of a brother'),
	'_DEAT_SPOU'=>WT_I18N::translate  (        'Death of a husband'),
	'_MARB_CHIL'=>WT_I18N::translate  (        'Marriage Banns of a son'),
	'_MARB_GCHI'=>WT_I18N::translate  (        'Marriage Banns of a grandson'),
	'_MARB_GCH1'=>WT_I18N::translate_c('daughter\'s son', 'Marriage banns of a grandson'),
	'_MARB_GCH2'=>WT_I18N::translate_c('son\'s son',      'Marriage banns of a grandson'),
	'_MARB_PARE'=>WT_I18N::translate  (        'Marriage banns of a father'),
	'_MARB_HSIB'=>WT_I18N::translate  (        'Marriage Banns of a half-brother'),
	'_MARB_SIBL'=>WT_I18N::translate  (        'Marriage Banns of a brother'),
	'_MARR_CHIL'=>WT_I18N::translate  (        'Marriage of a son'),
	'_MARR_GCHI'=>WT_I18N::translate  (        'Marriage of a grandson'),
	'_MARR_GCH1'=>WT_I18N::translate_c('daughter\'s son', 'Marriage of a grandson'),
	'_MARR_GCH2'=>WT_I18N::translate_c('son\'s son',      'Marriage of a grandson'),
	'_MARR_HSIB'=>WT_I18N::translate  (        'Marriage of a half-brother'),
	'_MARR_PARE'=>WT_I18N::translate  (        'Marriage of a father'),
	'_MARR_SIBL'=>WT_I18N::translate  (        'Marriage of a brother'),
	// this person facts
	'_ADPF'     =>WT_I18N::translate_c('MALE', 'Adopted by father'),
	'_ADPM'     =>WT_I18N::translate_c('MALE', 'Adopted by mother'),
	'_AKA'      =>WT_I18N::translate_c('MALE', 'Also known as'),
	'_AKAN'     =>WT_I18N::translate_c('MALE', 'Also known as'),
	'_INTE'     =>WT_I18N::translate_c('MALE', 'Interred'),
	// one of spouse facts
	'_NMAR'     =>WT_I18N::translate_c('MALE', 'Never married'),
	'_NMR'      =>WT_I18N::translate_c('MALE', 'Not married'),
);

// Facts, as applied to Females
$FACTS_F=array(
	// close relatives facts
	'_ADOP_CHIL'=>WT_I18N::translate  (          'Adoption of a daughter'),
	'_ADOP_GCHI'=>WT_I18N::translate  (          'Adoption of a granddaughter'),
	'_ADOP_GCH1'=>WT_I18N::translate_c('daughter\'s daughter','Adoption of a granddaughter'),
	'_ADOP_GCH2'=>WT_I18N::translate_c('son\'s daughter',     'Adoption of a granddaughter'),
	'_ADOP_HSIB'=>WT_I18N::translate  (          'Adoption of a half-sister'),
	'_ADOP_SIBL'=>WT_I18N::translate  (          'Adoption of a sister'),
	'_BAPM_CHIL'=>WT_I18N::translate  (          'Baptism of a daughter'),
	'_BAPM_GCHI'=>WT_I18N::translate  (          'Baptism of a granddaughter'),
	'_BAPM_GCH1'=>WT_I18N::translate_c('daughter\'s daughter','Baptism of a granddaughter'),
	'_BAPM_GCH2'=>WT_I18N::translate_c('son\'s daughter',     'Baptism of a granddaughter'),
	'_BAPM_HSIB'=>WT_I18N::translate  (          'Baptism of a half-sister'),
	'_BAPM_SIBL'=>WT_I18N::translate  (          'Baptism of a sister'),
	'_BIRT_CHIL'=>WT_I18N::translate  (          'Birth of a daughter'),
	'_BIRT_GCHI'=>WT_I18N::translate  (          'Birth of a granddaughter'),
	'_BIRT_GCH1'=>WT_I18N::translate_c('daughter\'s daughter','Birth of a granddaughter'),
	'_BIRT_GCH2'=>WT_I18N::translate_c('son\'s daughter',     'Birth of a granddaughter'),
	'_BIRT_HSIB'=>WT_I18N::translate  (          'Birth of a half-sister'),
	'_BIRT_SIBL'=>WT_I18N::translate  (          'Birth of a sister'),
	'_BURI_CHIL'=>WT_I18N::translate  (          'Burial of a daughter'),
	'_BURI_GCHI'=>WT_I18N::translate  (          'Burial of a granddaughter'),
	'_BURI_GCH1'=>WT_I18N::translate_c('daughter\'s daughter','Burial of a granddaughter'),
	'_BURI_GCH2'=>WT_I18N::translate_c('son\'s daughter',     'Burial of a granddaughter'),
	'_BURI_GPAR'=>WT_I18N::translate  (          'Burial of a grandmother'),
	'_BURI_GPA1'=>WT_I18N::translate  (          'Burial of a paternal grandmother'),
	'_BURI_GPA2'=>WT_I18N::translate  (          'Burial of a maternal grandmother'),
	'_BURI_HSIB'=>WT_I18N::translate  (          'Burial of a half-sister'),
	'_BURI_PARE'=>WT_I18N::translate  (          'Burial of a mother'),
	'_BURI_SIBL'=>WT_I18N::translate  (          'Burial of a sister'),
	'_BURI_SPOU'=>WT_I18N::translate  (          'Burial of a wife'),
	'_CHR_CHIL'=>WT_I18N::translate   (          'Christening of a daughter'),
	'_CHR_GCHI'=>WT_I18N::translate   (          'Christening of a granddaughter'),
	'_CHR_GCH1'=>WT_I18N::translate_c ('daughter\'s daughter','Christening of a granddaughter'),
	'_CHR_GCH2'=>WT_I18N::translate_c ('son\'s daughter',     'Christening of a granddaughter'),
	'_CHR_HSIB'=>WT_I18N::translate   (          'Christening of a half-sister'),
	'_CHR_SIBL'=>WT_I18N::translate   (          'Christening of a sister'),
	'_CREM_CHIL'=>WT_I18N::translate  (          'Cremation of a daughter'),
	'_CREM_GCHI'=>WT_I18N::translate  (          'Cremation of a granddaughter'),
	'_CREM_GCH1'=>WT_I18N::translate_c('daughter\'s daughter','Cremation of a granddaughter'),
	'_CREM_GCH2'=>WT_I18N::translate_c('son\'s daughter',     'Cremation of a granddaughter'),
	'_CREM_GPAR'=>WT_I18N::translate  (          'Cremation of a grandmother'),
	'_CREM_GPA1'=>WT_I18N::translate  (          'Cremation of a paternal grandmother'),
	'_CREM_GPA2'=>WT_I18N::translate  (          'Cremation of a maternal grandmother'),
	'_CREM_HSIB'=>WT_I18N::translate  (          'Cremation of a half-sister'),
	'_CREM_PARE'=>WT_I18N::translate  (          'Cremation of a mother'),
	'_CREM_SIBL'=>WT_I18N::translate  (          'Cremation of a sister'),
	'_CREM_SPOU'=>WT_I18N::translate  (          'Cremation of a wife'),
	'_DEAT_CHIL'=>WT_I18N::translate  (          'Death of a daughter'),
	'_DEAT_PARE'=>WT_I18N::translate  (          'Death of a mother'),
	'_DEAT_GCHI'=>WT_I18N::translate  (          'Death of a granddaughter'),
	'_DEAT_GCH1'=>WT_I18N::translate_c('daughter\'s daughter','Death of a granddaughter'),
	'_DEAT_GCH2'=>WT_I18N::translate_c('son\'s daughter',     'Death of a granddaughter'),
	'_DEAT_GPAR'=>WT_I18N::translate  (          'Death of a grandmother'),
	'_DEAT_GPA1'=>WT_I18N::translate  (          'Death of a paternal grandmother'),
	'_DEAT_GPA2'=>WT_I18N::translate  (          'Death of a maternal grandmother'),
	'_DEAT_HSIB'=>WT_I18N::translate  (          'Death of a half-sister'),
	'_DEAT_SIBL'=>WT_I18N::translate  (          'Death of a sister'),
	'_DEAT_SPOU'=>WT_I18N::translate  (          'Death of a wife'),
	'_MARB_CHIL'=>WT_I18N::translate  (          'Marriage Banns of a daughter'),
	'_MARB_GCHI'=>WT_I18N::translate  (          'Marriage Banns of a granddaughter'),
	'_MARB_GCH1'=>WT_I18N::translate_c('daughter\'s daughter','Marriage banns of a granddaughter'),
	'_MARB_GCH2'=>WT_I18N::translate_c('son\'s daughter',     'Marriage banns of a granddaughter'),
	'_MARB_HSIB'=>WT_I18N::translate  (          'Marriage banns of a half-sister'),
	'_MARB_PARE'=>WT_I18N::translate  (          'Marriage banns of a mother'),
	'_MARB_SIBL'=>WT_I18N::translate  (          'Marriage banns of a sister'),
	'_MARR_CHIL'=>WT_I18N::translate  (          'Marriage of a daughter'),
	'_MARR_GCHI'=>WT_I18N::translate  (          'Marriage of a granddaughter'),
	'_MARR_GCH1'=>WT_I18N::translate_c('daughter\'s daughter','Marriage of a granddaughter'),
	'_MARR_GCH2'=>WT_I18N::translate_c('son\'s daughter',     'Marriage of a granddaughter'),
	'_MARR_HSIB'=>WT_I18N::translate  (          'Marriage of a half-sister'),
	'_MARR_PARE'=>WT_I18N::translate  (          'Marriage of a mother'),
	'_MARR_SIBL'=>WT_I18N::translate  (          'Marriage of a sister'),
	// this person facts
	'_ADPF'     =>WT_I18N::translate_c('FEMALE', 'Adopted by father'),
	'_ADPM'     =>WT_I18N::translate_c('FEMALE', 'Adopted by mother'),
	'_AKA'      =>WT_I18N::translate_c('FEMALE', 'Also known as'),
	'_AKAN'     =>WT_I18N::translate_c('FEMALE', 'Also known as'),
	'_INTE'     =>WT_I18N::translate_c('FEMALE', 'Interred'),
	// one of spouse facts
	'_NMAR'     =>WT_I18N::translate_c('FEMALE', 'Never married'),
	'_NMR'      =>WT_I18N::translate_c('FEMALE', 'Not married'),
);

// Facts, as applied to Repositories
$FACTS_REPO=array(
	'NAME'      =>WT_I18N::translate_c('Repository', 'Name')
);

// Create a label for a fact type.
function translate_fact($fact, $person=null) {
	global $FACTS, $FACTS_M, $FACTS_F, $FACTS_REPO;

	if ($person instanceof WT_Person && $person->getSex()=='M' && array_key_exists($fact, $FACTS_M)) {
		return $FACTS_M[$fact];
	}
	if ($person instanceof WT_Person && $person->getSex()=='F' && array_key_exists($fact, $FACTS_F)) {
		return $FACTS_F[$fact];
	}
	if ($person instanceof WT_Repository && array_key_exists($fact, $FACTS_REPO)) {
		return $FACTS_REPO[$fact];
	}
	if (array_key_exists($fact, $FACTS)) {
		return $FACTS[$fact];
	}
	// If no specialisation exists (e.g. DEAT:CAUS), then look for the general (CAUS)
	if (strpos($fact, ':')) {
		list(, $fact)=explode(':', $fact, 2);
		return translate_fact($fact, $person);
	}
	// Still no translation? Highlight this as an error
	return '<span class="error" title="'.WT_I18N::translate('Unrecognized GEDCOM Code').'">'.$fact.'</span>';
}

function abbreviate_fact($fact) {
	switch ($fact) {
	case 'BIRT':  return WT_I18N::translate_c('Abbreviation for birth',            'b.');
	case 'MARR':  return WT_I18N::translate_c('Abbreviation for marriage',         'm.');
	case 'DEAT':  return WT_I18N::translate_c('Abbreviation for death',            'd.');
	case 'PHON':  return WT_I18N::translate_c('Abbreviation for telephone number', 't.');
	case 'FAX':   return WT_I18N::translate_c('Abbreviation for fax number',       'f.');
	case 'EMAIL': return WT_I18N::translate_c('Abbreviation for email address',    'e.');
	default:      return utf8_substr(translate_fact($fact), 0, 1).'.'; // Just use the first letter of the full fact
	}
}

// Create a label for a relationship type.
function translate_rela($rela, $sex='') {
	global $RELA_CODES, $RELA_CODES_M, $RELA_CODES_F;

	if ($sex=='M' && array_key_exists($rela, $RELA_CODES_M)) {
		return $RELA_CODES_M[$rela];
	}
	if ($sex=='F' && array_key_exists($rela, $RELA_CODES_F)) {
		return $RELA_CODES_F[$rela];
	}
	if (array_key_exists($rela, $RELA_CODES)) {
		return $RELA_CODES[$rela];
	}
	// Still no translation? Return original relationship name
	return $rela;
}
