<?php
declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\AppleTouchIconPng;
use Fisharebest\Webtrees\Http\RequestHandlers\BrowserconfigXml;
?>

<!--iOS-->
<link rel="apple-touch-icon" sizes="180x180" href="<?= e(route(AppleTouchIconPng::class)) ?>">
<!--Generic favicons-->
<link rel="icon" sizes="32x32" href="<?= e(asset('favicon-32.png')) ?>">
<link rel="icon" sizes="192x192" href="<?= e(asset('favicon-192.png')) ?>">
<!--IE11/Edge-->
<meta name="msapplication-config" content="<?= e(route(BrowserconfigXml::class)) ?>">
