<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var string $content
 */

?>
<!DOCTYPE html>
<html dir="<?= I18N::locale()->direction() ?>" lang="<?= I18N::locale()->languageTag() ?>">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title><?= I18N::translate('Setup wizard for webtrees') ?></title>

        <!-- Until we set base_url, can't fetch resources with HTTP. -->
        <link rel="icon" href="data:image/x-icon;base64,<?= base64_encode((string) file_get_contents(__DIR__ . '/../../../public/favicon.ico')) ?>" type="image/x-icon">
        <style>
            <?= file_get_contents(__DIR__ . '/../../../public/css/vendor.min.css') ?>
        </style>
    </head>

    <body class="container">
        <h1 class="text-info">
            <?= I18N::translate('Setup wizard for webtrees') ?>
        </h1>

        <?= $content ?>
    </body>
</html>
