<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var string $individual_list
 * @var Tree   $tree
 */

?>

<form method="post" action="<?= e(route('module', ['module' => 'descendancy', 'action' => 'Descendants', 'tree' => $tree->name()])) ?>" data-wt-descendancy-sidebar data-wt-descendancy-search-url="<?= e(route('module', ['module' => 'descendancy', 'action' => 'Search', 'tree' => $tree->name(), 'search' => ''])) ?>" data-wt-descendancy-placeholder="<?= e(I18N::translate('Search')) ?>">
    <input type="search" name="sb_desc_name" id="sb_desc_name" placeholder="<?= I18N::translate('Search') ?>">

    <?= csrf_field() ?>
</form>

<div id="sb_desc_content">
    <ul>
        <?= $individual_list ?>
    </ul>
</div>


