<div class="wt-footer wt-footer-custom text-center py-2">
    &copy;2005-
    <?php echo date("Y") ?>
     Frank Warius, J&uuml;rgen Musyal, Wolfgang Meuthien u.a. Alle Rechte vorbehalten. 
     Alle Informationen werden "as is" bereitgestellt, unter Ausschluss jeglicher Haftung.
    <br/>   
    &copy;2005-
    <?php echo date("Y") ?>
    Frank Warius, Juergen Musyal, Wolfgang Meuthien et al. 
    All rights reserved. All information are provided "as is", without warrenty of any kind.
    <br/>
   <!--  Click <a href="<?=e($url)?>">here</a> for more information. -->
</div>

