<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;

/**
 * @var Individual $individual
 */

?>

<div class="census-assistant-link" hidden>
    <a href="#">
        <?= I18N::translate('Create a shared note using the census assistant') ?>
    </a>
</div>

<div
    id="census-assistant"
    hidden
    data-wt-census-header-url="<?= e(route('module', ['module' => 'GEDFact_assistant', 'action' => 'CensusHeader', 'tree' => $individual->tree()->name()])) ?>"
    data-wt-census-individual-url="<?= e(route('module', ['module' => 'GEDFact_assistant', 'action' => 'CensusIndividual', 'tree' => $individual->tree()->name()])) ?>"
    data-wt-census-transcript-label="<?= e(I18N::translate('Census transcript')) ?>"
    data-wt-census-household-label="<?= e(I18N::translate('Household')) ?>"
    data-wt-census-individual-name="<?= e(strip_tags($individual->fullName())) ?>"
>
    <input type="hidden" name="ca_census" class="census-assistant-class">
    <div class="mb-3">
        <div class="input-group">
            <label class="input-group-text" for="census-assistant-title">
                <?= I18N::translate('Title') ?>
            </label>

            <input class="form-control" id="census-assistant-title" name="ca_title" value="">
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-sm-6">
            <div class="input-group">
                <label class="input-group-text" for="census-assistant-citation">
                    <?= I18N::translate('Citation') ?>
                </label>

                <input class="form-control" id="census-assistant-citation" name="ca_citation">
            </div>
        </div>

        <div class="col-sm-6">
            <div class="input-group">
                <label class="input-group-text" for="census-assistant-place">
                    <?= I18N::translate('Place') ?>
                </label>

                <input class="form-control" id="census-assistant-place" name="ca_place">
            </div>
        </div>
    </div>

    <div class="mb-3">
        <div class="input-group">
            <span class="input-group-text">
                <?= I18N::translate('Individuals') ?>
            </span>

            <?= view('components/select-individual', ['name' => 'census-assistant-individual', 'individual' => $individual, 'tree' => $individual->tree()]) ?>

            <button type="button" class="btn btn-primary census-assistant-add" title="<?= I18N::translate('add') ?>">
                <?= view('icons/add') ?>
            </button>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-sm table-borderless small wt-census-assistant-table" id="census-assistant-table">
            <thead class="wt-census-assistant-header"></thead>
            <tbody class="wt-census-assistant-body"></tbody>
        </table>
    </div>

    <div class="mb-3">
        <div class="input-group">
            <label class="input-group-text" for="census-assistant-notes">
                <?= I18N::translate('Comments') ?>
            </label>

            <textarea class="form-control" id="census-assistant-notes" name="ca_notes" rows="3"></textarea>
        </div>
    </div>
</div>


