<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Contracts\UserInterface;

/**
 * @var string        $MATOMO_SITE_ID
 * @var string        $MATOMO_URL
 * @var UserInterface $user
 */

?>
<script>
  var _paq = window._paq = window._paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u=<?= json_encode($MATOMO_URL, JSON_THROW_ON_ERROR) ?>;
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', <?= (int) $MATOMO_SITE_ID ?>]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
