<?php

use Fisharebest\Webtrees\I18N;

?>

<div class="form-group row">
    <label class="col-sm-3 col-form-label" for="num">
        <?= /* I18N: ... to show in a list */ I18N::translate('Number of surnames') ?>
    </label>
    <div class="col-sm-9">
        <input class="form-control" id="num" name="num" type="number" min="1" value="<?= e($num) ?>" required>
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-3 col-form-label" for="infoStyle">
        <?= I18N::translate('Presentation style') ?>
    </label>
    <div class="col-sm-9">
        <?= view('components/select', ['name' => 'infoStyle', 'selected' => $infoStyle, 'options' => $info_styles]) ?>
    </div>
</div>
