<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Location;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Note;
use Fisharebest\Webtrees\Repository;
use Fisharebest\Webtrees\Source;
use Fisharebest\Webtrees\Submitter;

/**
 * @var GedcomRecord $record
 */

echo match ($record->tag()) {
    Individual::RECORD_TYPE => view('icons/individual'),
    Family::RECORD_TYPE     => view('icons/family'),
    Source::RECORD_TYPE     => view('icons/source'),
    Repository::RECORD_TYPE => view('icons/repository'),
    Note::RECORD_TYPE       => view('icons/note'),
    Media::RECORD_TYPE      => view('icons/media'),
    Submitter::RECORD_TYPE  => view('icons/submitter'),
    Location::RECORD_TYPE   => view('icons/location'),
    default                 => '',
};
