<?php

declare(strict_types=1);

/**
 * @var string $sex
 */

if ($sex === 'F') : ?>
<span class="wt-icon-sex wt-icon-sex-f" aria-hidden="true"><i class="fa-solid fa-venus"></i></span>
<?php elseif ($sex === 'M') : ?>
<span class="wt-icon-sex wt-icon-sex-m" aria-hidden="true"><i class="fa-solid fa-mars"></i></span>
<?php elseif ($sex === 'X') : ?>
<span class="wt-icon-sex wt-icon-sex-x" aria-hidden="true"><i class="fa-solid fa-transgender"></i></span>
<?php elseif ($sex === 'U') : ?>
<span class="wt-icon-sex wt-icon-sex-u" aria-hidden="true"><i class="fa-solid fa-genderless"></i></span>
<?php endif ?>
