<?php

declare(strict_types=1);

/**
 * @var string $sex
 */

if ($sex === 'F') : ?>
<span class="wt-icon-sex wt-icon-sex-f"><i class="fa-solid fa-venus fa-fw" aria-hidden="true"></i></span>
<?php elseif ($sex === 'M') : ?>
<span class="wt-icon-sex wt-icon-sex-m"><i class="fa-solid fa-mars fa-fw" aria-hidden="true"></i></span>
<?php elseif ($sex === 'X') : ?>
<span class="wt-icon-sex wt-icon-sex-x"><i class="fa-solid fa-transgender fa-fw" aria-hidden="true"></i></span>
<?php elseif ($sex === 'U') : ?>
<span class="wt-icon-sex wt-icon-sex-u"><i class="fa-solid fa-genderless fa-fw" aria-hidden="true"></i></span>
<?php endif ?>
