<?php

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<form method="post">
    <?= csrf_field() ?>
    <div class="row form-group">
        <label for="head" class="col-sm-3 col-form-label">
            <?= I18N::translate('Add content to the end of the <code>&lt;head&gt;</code> element.') ?>
        </label>
        <div class="col-sm-9">
            <textarea id="head" name="head" class="form-control text-monospace" dir="ltr" rows="5"><?= e($head) ?></textarea>
            <p class="text-muted">
                <?= I18N::translate('Include the <code>&lt;style&gt;&lt;/style&gt;</code> tags.') ?>
            </p>
        </div>
    </div>

    <div class="row form-group">
        <label for="body" class="col-sm-3 col-form-label">
            <?= I18N::translate('Add content to the end of the <code>&lt;body&gt;</code> element.') ?>
        </label>
        <div class="col-sm-9">
            <textarea id="body" name="body" class="form-control text-monospace" dir="ltr" rows="5"><?= e($body) ?></textarea>
            <p class="text-muted">
                <?= I18N::translate('Include the <code>&lt;script&gt;&lt;/script&gt;</code> tags.') ?>
            </p>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">
        <?= view('icons/save') ?>
        <?= I18N::translate('save') ?>
    </button>

    <a href="<?= route(ControlPanel::class) ?>" class="btn btn-secondary">
        <?= view('icons/cancel') ?>
        <?= I18N::translate('cancel') ?>
    </a>
</form>
