<?php

use Fisharebest\Webtrees\Functions\FunctionsEdit;
use Fisharebest\Webtrees\I18N;

?>

<div class="card mb-4">
    <a class="card-header" href="#" data-toggle="collapse" data-target="#add-associate-<?= e($id) ?>" aria-expanded="false" aria-controls="add-associate">
        <?= I18N::translate('Associate') ?>
    </a>

    <div class="card-body collapse" id="add-associate-<?= e($id) ?>">
        <?= FunctionsEdit::addSimpleTag($tree, $level . ' _ASSO') ?>
        <?= FunctionsEdit::addSimpleTag($tree, ($level + 1) . ' RELA') ?>
        <?= FunctionsEdit::addSimpleTag($tree, ($level + 1) . ' NOTE') ?>
        <?= FunctionsEdit::addSimpleTag($tree, ($level + 1) . ' SHARED_NOTE') ?>
    </div>
</div>
