<?php

use Fisharebest\Webtrees\Functions\FunctionsEdit;
use Fisharebest\Webtrees\GedcomTag;

?>

<div class="card mb-4">
    <a class="card-header" href="#" data-toggle="collapse" data-target="#add-fact-<?= $tag ?>" aria-expanded="false" aria-controls="add-fact-<?= $tag ?>">
        <?= GedcomTag::getLabel($tag) ?>
    </a>

    <div class="card-body collapse" id="add-fact-<?= $tag ?>">
        <?php FunctionsEdit::addSimpleTags($tree, $tag) ?>
    </div>
</div>
