<?php

use Fisharebest\Webtrees\Functions\FunctionsEdit;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var int  $level
 * @var Tree $tree
 */

?>

<div class="card mb-4">
    <a class="card-header" href="#" data-toggle="collapse" data-target="#add-note-object" aria-expanded="false" aria-controls="add-note-object">
        <?= I18N::translate('Shared note') ?>
    </a>

    <div class="card-body collapse" id="add-note-object">
        <?= FunctionsEdit::addSimpleTag($tree, $level . ' SHARED_NOTE') ?>
    </div>
</div>
