<?php

use Fisharebest\Webtrees\Functions\FunctionsEdit;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var int  $level
 * @var Tree $tree
 */

?>

<div class="card mb-4">
    <a class="card-header" href="#" data-toggle="collapse" data-target="#add-media-object" aria-expanded="false" aria-controls="add-media-object">
        <?= I18N::translate('Add a media object') ?>
    </a>

    <div class="card-body collapse" id="add-media-object">
        <?= FunctionsEdit::addSimpleTag($tree, $level . ' OBJE') ?>
    </div>
</div>
