<?php

use Fisharebest\Webtrees\Functions\FunctionsEdit;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var int  $level
 * @var Tree $tree
 */

?>

<div class="card mb-4">
    <a class="card-header" href="#" data-toggle="collapse" data-target="#add-restriction" aria-expanded="false" aria-controls="add-restriction">
        <?= I18N::translate('Restriction') ?>
    </a>

    <div class="card-body collapse" id="add-restriction">
        <?= FunctionsEdit::addSimpleTag($tree, $level . ' RESN') ?>
    </div>
</div>
