<?php

use Fisharebest\Webtrees\I18N;

?>

<div class="row form-group">
    <label for="BING_WEBMASTER_ID" class="col-sm-3 col-form-label">
        <?= I18N::translate('Site verification code') ?>
    </label>

    <div class="col-sm-9">
        <input type="text" class="form-control" id="BING_WEBMASTER_ID" name="BING_WEBMASTER_ID" value="<?= e($BING_WEBMASTER_ID ?? '') ?>" maxlength="255" pattern="[0-9a-zA-Z+=/_:.!-]*">
    </div>
</div>

<p>
    <?= I18N::translate('Site verification codes do not work when webtrees is installed in a subfolder.') ?>
</p>
