name: Code style

on: [push, pull_request]

# Change default permissions from all to none.
permissions: {}

# Cancel previous runs of the same workflow for the same pull request or branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    if: ${{ !startsWith(github.event.head_commit.message, 'Translation:') }}
    runs-on: ${{ matrix.operating-system }}
    name: PHP/PHTML

    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-version: ['8.3', '8.4', '8.5', '8.6']
      fail-fast: false

    steps:
      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-file: 'development'

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false # Don't leave GITHUB_TOKEN in .git/config

      - run: composer validate

      - run: composer install --no-progress

      - run: composer webtrees:phpcs
